composer.lock, src/SavedSearchesControllerProvider.php, src/SavedSearchesServiceProvider.php, web/index.php
The UiTID repository has been swapped out for a combined one that includes fixed searches.
=> III-286: Update and register saved search service provider

bootstrap.php, composer.json, composer.lock, src/Event/EventControllerProvider.php, src/Search/SearchServiceProvider.php
Event iri generator has been renamed.
=> III-910: Add Offer locator to domain-event repos

src/Role/RoleControllerProvider.php
Seems PATCH does still work if it's removed
=> III-1138: Removed bind, GET /role/:id doesn't work otherwise

composer.json, composer.lock, src/Event/DeprecatedEventControllerProvider.php, src/Offer/OfferControllerProvider.php, src/Place/PlaceControllerProvider.php
=> III-2181: Update description by language

bootstrap.php, src/Migrations/Version20180711095920.php, src/Organizer/OrganizerControllerProvider.php, src/Organizer/OrganizerPermissionServiceProvider.php, src/Resque/ResqueCommandBusServiceProvider.php, src/Security/GeneralSecurityServiceProvider.php, src/Security/OrganizerSecurityServiceProvider.php, web/index.php
=> III-2273: Reconfigure silex app for fine grained permissions on organizers

composer.lock
- Update package to get https://github.com/cultuurnet/udb3-php/pull/405
=> Update cultuurnet/udb3 package

bin/udb3.php, bootstrap.php, src/Console/ImportEventCdbXmlCommand.php
- Added console command to import event cdbxml, for testing purposes.
- [internal] Moved system user id from various places to a global constant
- [internal] Simplified FQNs for console commands
=> Add console command to import event cdbxml

bin/udb3.php, src/Console/ValidatePlaceJsonLdCommand.php
- [internal] Added a console command to validate Place JSON-LD for easier debugging.
=> Add console command to validate place json-ld

composer.json, composer.lock, lib/udb3-export/composer.json, lib/udb3-export/tests/CalendarSummary/HttpCalendarSummaryRepositoryTest.php, lib/udb3-export/tests/Command/ExportEventsAsPDFJSONDeserializerTest.php, lib/udb3-export/tests/Command/ExportEventsAsPDFTest.php, lib/udb3-export/tests/Command/ExportEventsJSONDeserializerTest.php, lib/udb3-export/tests/EventExportCommandHandlerTest.php, lib/udb3-export/tests/EventExportServiceCollectionTest.php, lib/udb3-export/tests/EventExportServiceTest.php, lib/udb3-export/tests/Format/HTML/HTMLEventFormatterTest.php, lib/udb3-export/tests/Format/HTML/HTMLFileWriterTest.php, lib/udb3-export/tests/Format/HTML/Properties/TitleTest.php, lib/udb3-export/tests/Format/HTML/TransformingIteratorIteratorTest.php, lib/udb3-export/tests/Format/HTML/Uitpas/DistributionKey/KansentariefDiscountSpecificationTest.php, lib/udb3-export/tests/Format/HTML/Uitpas/DistributionKey/KansentariefForCurrentCardSystemSpecificationTest.php, lib/udb3-export/tests/Format/HTML/Uitpas/DistributionKey/KansentariefForOtherCardSystemsSpecificationTest.php, lib/udb3-export/tests/Format/HTML/Uitpas/Event/PointCollectingSpecificationTest.php, lib/udb3-export/tests/Format/HTML/Uitpas/EventInfo/CultureFeedEventInfoServiceTest.php, lib/udb3-export/tests/Format/HTML/Uitpas/Promotion/EventOrganizerPromotionQueryFactoryTest.php, lib/udb3-export/tests/Format/HTML/Zipped/ZippedWebArchiveFileWriterTest.php, lib/udb3-export/tests/Format/JSONLD/JSONLDEventFormatterTest.php, lib/udb3-export/tests/Format/TabularData/TabularDataEventFormatterTest.php, lib/udb3-export/tests/Notification/DefaultHTMLBodyFactoryTest.php, lib/udb3-export/tests/Notification/DefaultPlainTextBodyFactoryTest.php, lib/udb3-export/tests/PriceFormatterTest.php
- `phpunit/phpunit` dev dependency (`^7.5`)
- upgraded the `phpunit/phpunit` dev dependency in the `udb3-export` lib to `7.5`
=> Upgrade phpunit

build.xml
- Overall build will now fail if the udb3-export build fails
=> Check udb3-export phing build return code

web/index.php
- Incorrect namespaces after refactor
=> Fix incorrect namespaces that were still using Symfony

composer.lock
- `mathiasverraes/money` dependency is now properly removed from `composer.lock` file
=> Clean up composer.lock file

app/Curators/CuratorsServiceProvider.php, config.yml.dist, src/Curators/Events/NewsArticleAboutEventAdded.php, src/Curators/Events/NewsArticleAboutEventAddedJSONDeserializer.php, src/Curators/LabelFactory.php, src/Curators/NewsArticleProcessManager.php, src/Curators/Publisher.php, src/Curators/PublisherName.php, tests/Curators/Events/NewsArticleAboutEventAddedJSONDeserializerTest.php, tests/Curators/LabelFactoryTest.php, tests/Curators/NewsArticleProcessManagerTest.php, tests/Curators/PublisherTest.php
- We now only add preconfigured labels for known publishers
---
Ticket: https://jira.uitdatabank.be/browse/III-3037
=> III-3037 - Add correct curator labels for known publishers

app/Place/PlaceJSONLDServiceProvider.php, config.yml.dist, src/Place/DummyPlaceProjectionEnricher.php, tests/Place/DummyPlaceProjectionEnricherTest.php
- Enricher for event read model to add `isDummyPlaceForEducationEvents` when the place is a dummy place
---
Ticket: https://jira.uitdatabank.be/browse/III-3049
=> III-3049 - Add bookable offer property to place read model

src/Place/DummyPlaceProjectionEnricher.php, tests/Place/DummyPlaceProjectionEnricherTest.php
- Place read model should now be correctly enriched fur dummy places
=> [HOTFIX] Read model enricher used incorrect json structure

src/UDB2/Event/EventImporter.php
- Imported and updated events from UDB2 will now be relocated to their canonical places
---
Ticket: https://jira.uitdatabank.be/browse/III-3048
=> Dispatch UpdateLocation after importing and updating from UDB2

app/UDB2IncomingEventServicesProvider.php, src/Place/DummyPlaceProjectionEnricher.php, src/UDB2/Event/EventImporter.php
- Fixed multiple bugs in the event cdbxml importer
---
Ticket: https://jira.uitdatabank.be/browse/III-3069
Note: This will require a `composer up cultuurnet/udb3` after https://github.com/cultuurnet/udb3-php/pull/423 is merged.
=> Fix cdbxml imports

composer.lock
- Fixed last cdbxml import error by updating `cultuurnet/udb3`
=> Update cultuurnet/udb3 dependency to version that fixes cdbxml imports

app/Console/ImportPlaceCdbXmlCommand.php, bin/udb3.php
- Added a CLI command to import places from cdbxml for testing and debugging.
=> Add a CLI command to import places from cdbxml for debugging / testing

composer.lock
- Updated cultuurnet/udb3 dependency to fix audiencetype issue
=> Update cultuurnet/udb3 dependency to fix audiencetype issue

app/Event/EventEditingServiceProvider.php, composer.json, composer.lock
- Updated LocationMarkedAsDuplicateProcessManager bootstrapping
---
Ticket: https://jira.uitdatabank.be/browse/III-3070
=> III-3070 Update LocationMarkedAsDuplicateProcessManager bootstrapping

composer.lock
- Updated the `cultuurnet/udb3` package so we use `location.mainId` to find the related events of a location when it's marked as duplicate.
---
Ticket: https://jira.uitdatabank.be/browse/III-3080
=> III-3080 Update udb3-php

composer.json, composer.lock
- Fixed the same issue as in https://github.com/cultuurnet/udb3-php/pull/437
---
⚠️ After merging this we should merge it into all open branches of this repo as well.
=> Fix composer 2 deprecation warning

composer.json, composer.lock
- Updated cultuurnet/udb3 dependency so we can deploy III-3055
---
Ticket: https://jira.uitdatabank.be/browse/III-3055
=> III-3055 Update udb3-php dependency

composer.json
- Update cultuurnet/udb3 dependency
---
[Jira](https://jira.uitdatabank.be/browse/III-3105)
=> Update cultuurnet/udb3 dependency

app/Event/EventControllerProvider.php, src/Http/Management/User/CultureFeedUserIdentification.php, web/index.php
Forgot to push these commits for #395
=> Extra commits for #395

app/ApiName.php, app/CommandHandling/ContextDecoratedCommandBus.php, app/CommandHandling/ContextFactory.php, app/Curators/CuratorsServiceProvider.php, app/Import/ImportControllerProvider.php, app/Metadata/MetadataServiceProvider.php, app/UDB2IncomingEventServicesProvider.php, app/UiTPAS/UiTPASIncomingEventServicesProvider.php, bin/udb3.php, bootstrap.php, composer.json, composer.lock, src/EventSourcing/LazyCallbackMetadataEnricher.php, web/index.php
- Added api name to context and event metadata
---
Ticket: https://jira.uitdatabank.be/browse/III-3114
---
Not mentioned in the ticket were the UiTPAS and Curators AMQP listeners that can automatically add/remove labels based on messages from those services. I've added those as well.
=> [WIP] III-3114 Add api name to metadata

app/ApiName.php, bin/udb3.php, bootstrap.php
- Fixed undefined `api_name` service
=> Fix undefined api name

composer.lock, tests/Event/EventEditingServiceTest.php
- Fixed broken uitpas consumer by updating cultuurnet/udb3 package
=> Fix broken uitpas consumer by updating cultuurnet/udb3 package

composer.json, composer.lock
- upgraded cultuurnet/udb3 dependency
---
Ticket:
[Jira](https://jira.uitdatabank.be/browse/III-3146)
=> Feature: III-3146

src/EventExport/EventExportService.php
- Added a log for the actual amount of yielded events in the export service
---
Ticket: https://jira.uitdatabank.be/browse/III-3153
=> III-3135 Log the actual amount of events yielded

composer.json, composer.lock
- Bumped cultuurnet/udb3 dependency
---
Ticket:
[Jira](https://jira.uitdatabank.be/browse/III-3154)
=> Feature: III-3154

composer.json, composer.lock
- Fixed udb3 dependency version
---
Ticket: https://jira.uitdatabank.be/browse/III-3153
=> III-3153 Update udb3 dependency to correct version

composer.lock
- Updated udb3 dependency to latest version
---
Ticket: https://jira.uitdatabank.be/browse/III-3190
=> III-3190 Update udb3 to latest version

src/EventExport/Format/HTML/Properties/TaalicoonDescription.php, tests/EventExport/Format/HTML/HTMLFileWriterTest.php, tests/EventExport/Format/HTML/results/export_event_with_age_range.html, tests/EventExport/Format/HTML/results/export_event_with_custom_logo.html, tests/EventExport/Format/HTML/results/export_event_with_four_taaliconen.html, tests/EventExport/Format/HTML/results/export_event_with_taaliconen.html, tests/EventExport/Format/HTML/results/export_event_with_uitpas_brand.html, tests/EventExport/Format/HTML/results/export_event_with_uitpas_info.html, tests/EventExport/Format/HTML/results/export_event_with_uitpas_info_paspartoe_branded.html
- changed descriptive text of language icons in export
---
Ticket: [https://jira.uitdatabank.be/browse/III-3237](https://jira.uitdatabank.be/browse/III-3237)
=> III-3237 - change descriptive text of language icons

app/Organizer/OrganizerControllerProvider.php, composer.lock, src/Http/Organizer/EditOrganizerRestController.php, src/Organizer/Commands/RemoveAddress.php, src/Organizer/DefaultOrganizerEditingService.php, src/Organizer/OrganizerCommandHandler.php, src/Organizer/OrganizerEditingServiceInterface.php, src/Organizer/OrganizerLDProjector.php, tests/Http/Organizer/EditOrganizerRestControllerTest.php, tests/Organizer/DefaultOrganizerEditingServiceTest.php, tests/Organizer/OrganizerCommandHandlerTest.php, tests/Organizer/OrganizerLDProjectorTest.php, tests/Organizer/Samples/organizer_with_deleted_address.json
- AddressRemoved handling to OrganizerLDProjector
- RemoveAddress command/handler
- bumped udb3-php dependencyBump udb3-php dependency
---
Ticket:
[Jira](https://jira.uitdatabank.be/browse/III-3227)
=> Feature: III-3227

composer.lock
- updated cultuurnet/broadway-tools dependency
---
Ticket:
[Jira](https://jira.uitdatabank.be/browse/III-3252)
=> Bug: III-3252

composer.lock
- Updated dependency on `udb3/php` to get the fix in https://github.com/cultuurnet/udb3-php/pull/456
---
Ticket: https://jira.uitdatabank.be/browse/III-3132
=> Update udb3 dependency to latest version

app/Labels/LabelsControllerProvider.php, features.yml.dist
- Already rolled out feature flag: `label-management`
---
Overview: https://docs.google.com/spreadsheets/d/1CKZEbIRsh7rAP5H1SEAwxR7T1XR6VLDu_F6GZLQGrUw/edit#gid=0
=> Clean up rolled out label-management feature flag

app/UDB2IncomingEventServicesProvider.php, features.yml.dist
- Already rolled out feature flag: `import-validate-xml`
---
Overview: https://docs.google.com/spreadsheets/d/1CKZEbIRsh7rAP5H1SEAwxR7T1XR6VLDu_F6GZLQGrUw/edit#gid=0
=> Clean up rolled out import-validate-xml feature flag

app/CommandHandling/CommandBusServiceProvider.php, features.yml.dist
- Already rolled out feature flag: `facility-permission`
---
Overview: https://docs.google.com/spreadsheets/d/1CKZEbIRsh7rAP5H1SEAwxR7T1XR6VLDu_F6GZLQGrUw/edit#gid=0
=> Clean up rolled out facility-permission feature flag

app/Organizer/OrganizerGeoCoordinatesServiceProvider.php, features.yml.dist
- Already rolled out feature flag: `organizer-geocordinates-replay-filtering-event`
---
Overview: https://docs.google.com/spreadsheets/d/1CKZEbIRsh7rAP5H1SEAwxR7T1XR6VLDu_F6GZLQGrUw/edit#gid=0
=> Clean up rolled out organizer-geocordinates-replay-filtering-event feature flag

composer.json, composer.lock, src/Search/CountingSearchServiceInterface.php, src/Search/Results.php, src/Search/ResultsGenerator.php, src/Search/ResultsGeneratorInterface.php, src/Search/Sapi3CountingSearchService.php, src/Search/Sapi3SearchService.php, src/Search/SearchServiceInterface.php, tests/Search/ResultsGeneratorTest.php, tests/Search/ResultsTest.php, tests/Search/Sapi3CountingSearchServiceTest.php, tests/Search/Sapi3SearchServiceTest.php, tests/Search/samples/search-response.json, tests/Search/samples/search-results-leuven.xml
- Search related code from udb3-php
---
Related PR: https://github.com/cultuurnet/udb3-php/pull/463
=> Internalize search related code from udb3 php

app/CultureFeed/CultureFeedServiceProvider.php, app/User/UserServiceProvider.php, composer.json, composer.lock, features.yml.dist
- `auth0-user-management` feature flag
- Unused `cultuurnet/uitid-credentials-fetcher` dependency
---
Ticket: https://jira.uitdatabank.be/browse/III-3321
=> III-3321 Remove auth0 feature flag and old uitid code

app/Migrations/Version20200602134547.php, bootstrap.php, src/Event/Productions/GroupEventsAsProduction.php, src/Event/Productions/Production.php, src/Event/Productions/ProductionCommandHandler.php, src/Event/Productions/ProductionId.php, src/Event/Productions/ProductionRepository.php, tests/Event/Productions/Doctrine/SchemaConfigurator.php, tests/Event/Productions/ProductionCommandHandlerTest.php, tests/Event/Productions/ProductionIdTest.php, tests/Event/Productions/ProductionRepositoryTest.php, tests/Event/Productions/ProductionTest.php
- Productions entity and table
- Command to group multiple events as a new production
---
Ticket:
=> Productions - Part 1

src/Event/Productions/AddEventToProduction.php, src/Event/Productions/EventCannotBeAddedToProduction.php, src/Event/Productions/Production.php, src/Event/Productions/ProductionCommandHandler.php, src/Event/Productions/ProductionRepository.php, src/Event/Productions/RemoveEventFromProduction.php, tests/Event/Productions/ProductionCommandHandlerTest.php, tests/Event/Productions/ProductionRepositoryTest.php, tests/Event/Productions/ProductionTest.php
- Command to add event to an existing production
- Command to remove event from an existing production
---
Ticket: https://jira.uitdatabank.be/browse/III-3324
=> Add and remove events from productions

src/Event/Productions/MergeProductions.php, src/Event/Productions/ProductionCommandHandler.php, src/Event/Productions/ProductionRepository.php, tests/Event/Productions/ProductionCommandHandlerTest.php, tests/Event/Productions/ProductionRepositoryTest.php
- Functionality to merge productions
---
~Merge https://github.com/cultuurnet/udb3-silex/pull/464 first and change base to `master`~
=> Merge productions

app/Event/ProductionControllerProvider.php, src/Http/Productions/CreateProductionValidator.php, src/Http/Productions/ProductionsWriteController.php, tests/Http/Productions/CreateProductionValidatorTest.php, tests/Http/Productions/ProductionsWriteControllerTest.php, web/index.php
- `/productions/` endpoint to group multiple events as a new production
---
=> Productions write api

app/Event/ProductionControllerProvider.php, src/Http/Productions/ProductionsWriteController.php, tests/Http/Productions/ProductionsWriteControllerTest.php
- API endpoint to add events to an existing production
---
Merge https://github.com/cultuurnet/udb3-silex/pull/466 first and change base to `master`
=> Add event to existing production

app/Event/ProductionControllerProvider.php, src/Event/Productions/GroupEventsAsProduction.php, src/Http/Productions/ProductionsWriteController.php, tests/Event/Productions/ProductionCommandHandlerTest.php, tests/Http/Productions/ProductionsWriteControllerTest.php
- Endpoint to merge existing productions: `/productions/{toProductionId}/merge/{fromProductionId}`
---
~Merge https://github.com/cultuurnet/udb3-silex/pull/468 first and change base to `master`~
=> Endpoint to merge existing productions

app/Event/ProductionControllerProvider.php
- Fixed a fatal error in the `ProductionsControllerProvider`
=> Fix fatal error in ProductionsControllerProvider

app/Event/ProductionControllerProvider.php, app/Migrations/Version20200618120205.php, src/Event/Productions/ProductionRepository.php, src/Http/Productions/ProductionsSearchController.php, tests/Http/Productions/ProductionsSearchControllerTest.php
- Endpoint to search productions by keyword
- Fulltext index on `name` field of productions
=> Full text search productions

app/Event/EventJSONLDServiceProvider.php, app/Event/ProductionControllerProvider.php, app/Event/ProductionServiceProvider.php, bootstrap.php, src/Event/Productions/SimilaritiesClient.php, src/Event/Productions/Suggestion.php, src/Event/Productions/SuggestionsNotFound.php, src/Http/Productions/ProductionSuggestionController.php
- endpoint for productions suggestions
---
Ticket:
[Jira](https://jira.uitdatabank.be/browse/III-3324)
=> Feature:III-3324

app/Authentication/UitidApiKeyServiceProvider.php, app/Security/GeneralSecurityServiceProvider.php, bootstrap.php
- Fixed `bypass_api_key_check` option not working
- Removed unused `role_constraints_mode`
---
Ticket: https://jira.uitdatabank.be/browse/III-3385
=> III-3385 Fix api key check bypass not working

src/Event/Productions/AddEventToProduction.php, src/Event/Productions/MergeProductions.php, src/Event/Productions/RejectSuggestedEventPair.php, src/Event/Productions/RemoveEventFromProduction.php
- Permissions on certain production commands were incorrectly configured
---
Ticket: https://jira.uitdatabank.be/browse/III-3324
=> III-3324 - Fix production endpoints

src/Event/Productions/SimilaritiesClient.php, src/Event/Productions/Suggestion.php, src/Http/Productions/ProductionSuggestionController.php
- Included similarity score in the `GET /productions/suggestion` endpoint
---
Ticket: https://jira.uitdatabank.be/browse/III-3452
Swagger docs PR: https://github.com/cultuurnet/udb3-swagger/pull/60
---
=> Include similarity score in /productions/suggestion

composer.lock, tests/OfferLDProjectorTestBase.php
- Updated `cultuurnet/udb3` and `cultuurnet/udb3-models`
---
Ticket: https://jira.uitdatabank.be/browse/III-3399
Related PRs:
- https://github.com/cultuurnet/udb3-models/pull/9
- https://github.com/cultuurnet/udb3-models/pull/10
- https://github.com/cultuurnet/udb3-php/pull/470
=> Update cultuurnet/udb3 and cultuurnet/udb3-models

app/Migrations/Version20200909121744.php
- Added migration to create `similar_events` table
---
Ticket: https://jira.uitdatabank.be/browse/III-3485
=> Create similar_events table

config.yml.dist
- Removed unused config from dist file
---
Ticket: https://jira.uitdatabank.be/browse/III-3484
=> Remove event_similarities_api example config

.github/workflows/ci.yml, app/Console/ImportEventCdbXmlCommand.php, app/Console/ImportPlaceCdbXmlCommand.php, app/Labels/LabelServiceProvider.php, app/Offer/OfferControllerProvider.php, app/Proxy/ProxyServiceProvider.php, bin/udb3.php, bootstrap.php, phpstan.neon, src/EventExport/Format/TabularData/TabularDataEventFormatter.php, src/Http/Label/CommandType.php, src/Http/Label/EditRestController.php, src/Media/Serialization/MediaObjectSerializer.php, src/User/UserIdentityDetails.php, tests/CommandHandling/ResqueCommandBusTest.php, tests/DescriptionJSONDeserializerTest.php, tests/Event/Commands/UpdateContactPointTest.php, tests/EventExport/samples/event_with_price.json, tests/Http/Label/CommandTypeTest.php, tests/LabelJSONDeserializerTest.php, tests/Media/MediaManagerTest.php, tests/Offer/Commands/AddLabelToMultipleJSONDeserializerTest.php, tests/Offer/Commands/AddLabelToQueryJSONDeserializerTest.php, tests/Offer/IriOfferIdentifierJSONDeserializerTest.php, tests/Offer/LocalOfferReadingServiceTest.php, tests/Offer/OfferTest.php, tests/Organizer/Commands/DeleteOrganizerTest.php, tests/Place/PlaceTest.php, tests/Security/Permission/UserPermissionVoterTest.php
- Increased phpstan level to 1
=> Increase required PHPStan level to 1

.github/workflows/ci.yml, composer.lock
- Fix unknown class constant ATOM
---
Ticket: https://jira.uitdatabank.be/browse/III-3498
=> [III-3498] Fix undefined class constant atom

composer.lock, src/Event/Commands/UpdateMajorInfo.php, src/Event/Event.php, src/Event/EventEditingService.php, src/Event/EventEditingServiceInterface.php, src/Event/ReadModel/JSONLD/EventLDProjector.php, src/Offer/AvailableTo.php, src/Place/Commands/UpdateMajorInfo.php, src/Place/DefaultPlaceEditingService.php, src/Place/Place.php, src/Place/PlaceEditingServiceInterface.php, tests/Offer/AvailableToTest.php
- Updated dependency on `cultuurnet/udb3` to latest version
- Removed all usages of unnecessary `CalendarInterface`
=> Update udb php

src/Event/EventThemeResolver.php, src/Event/EventTypeResolver.php
- Event type `0.3.1.0.1` - `Course with open sessions` with the same themes as event `0.3.1.0.0`
---
Ticket: https://jira.uitdatabank.be/browse/III-3240
=> III-3240 Add new event type for course with open session

app/ErrorHandlerProvider.php, app/SentryErrorHandler.php, app/SentryServiceProvider.php, bin/udb3.php, web/index.php
- Capture user information (ID, sub, uid, uitidv1id)
- Capture runtime information (api_key, api_name)
---
Ticket: https://jira.uitdatabank.be/browse/III-3528
=> III-3528 Capture user info and runtime info

app/SentryErrorHandler.php
- Allow nullable api name
---
Ticket: https://jira.uitdatabank.be/browse/III-3528
=> III-3528 Fix nullable api name

app/Event/EventJSONLDServiceProvider.php, src/Event/ReadModel/JSONLD/EventLDProjector.php, tests/Event/ReadModel/JSONLD/EventLDProjectorTest.php, tests/Offer/AvailableToTest.php
- We now correctly use the EventType to determine what calendar date to use for AvailableTo
---
Ticket: https://jira.uitdatabank.be/browse/III-3242
=> Pass EventType to AvailableTo factory method where needed

app/ErrorHandlerProvider.php, app/SentryErrorHandler.php, bin/udb3.php, web/index.php
- Capture all exceptions to Sentry but discard HTTP not found exceptions [404]
---
Ticket: https://jira.uitdatabank.be/browse/III-3530
=> III-3530 Capture "all" exceptions

app/Migrations/Version20201022154706.php
- Added migration to create the offer popularity table
---
Ticket: https://jira.uitdatabank.be/browse/III-3501
=> III-3501 Create the offer popularity table

src/Offer/Popularity/DBALPopularityRepository.php, src/Offer/Popularity/Popularity.php, src/Offer/Popularity/PopularityRepository.php, src/Offer/Popularity/PopularitySchemaConfigurator.php, tests/Offer/Popularity/DBALPopularityRepositoryTest.php, tests/Offer/Popularity/PopularityTest.php
- Add Popularity value object
- Add PopularityRepository
---
Ticket: https://jira.uitdatabank.be/browse/III-3583
=> III-3583 Add Popularity repository

app/Media/MediaServiceProvider.php, app/SentryPsrLoggerDecorator.php, app/UiTPAS/UiTPASIncomingEventServicesProvider.php, bootstrap.php, web/index.php
- Added Sentry decorator to PSR loggers, similar to https://github.com/cultuurnet/udb3-search-service/pull/79 but a bit simpler because the bootstrapping required less changes
---
Ticket: https://jira.uitdatabank.be/browse/III-3585
=> III-3585 Log amqp errors to sentry

app/Console/SQL/get_events_with_missing_or_outdated_coordinates.sql, app/Console/SQL/get_places_with_missing_or_outdated_coordinates.sql
- Move semicolon to last line
---
Ticket: https://jira.uitdatabank.be/browse/III-3634
=> Fix typo in geo-coordinate queries

app/Event/EventGeoCoordinatesServiceProvider.php, app/Place/PlaceGeoCoordinatesServiceProvider.php, src/Offer/AbstractGeoCoordinatesCommandHandler.php
- Added debug logging for geocoding results
---
Ticket: https://jira.uitdatabank.be/browse/III-3634
=> III-3634 Add debug logging for geocoding results

app/Console/ReindexOffersWithPopularityScore.php, app/Console/ReplayCommand.php, app/Event/EventJSONLDServiceProvider.php, bin/udb3.php
- Add a new CLI command to reindex offers with a popularity score in SAPI3.
---
https://jira.uitdatabank.be/browse/III-3634
=> III-3643 Add CLI to reindex offers with popularity

.github/workflows/ci.yml
- Added the php.ini for xdebug 3 and setting `xdebug.mode=coverage`
=> Fix for switch to xdebug 3 by setting xdebug mode to coverage

.github/workflows/ci.yml, composer.json, composer.lock, src/Offer/ReadModel/JSONLD/StatusUpdatedProjector.php, src/ReadModel/Context.php, src/ReadModel/OfferDocumentRepository.php, tests/Event/ReadModel/JSONLD/EventLDProjectorTest.php, tests/Event/ReadModel/JSONLD/copied_event.json, tests/Event/ReadModel/JSONLD/copied_event_without_working_hours.json, tests/Offer/ReadModel/JSONLD/OfferUpdateTest.php, tests/Offer/ReadModel/JSONLD/StatusUpdatedProjectorTest.php, tests/Place/ReadModel/JSONLD/PlaceLDProjectorTest.php, tests/ReadModel/OfferDocumentRepositoryTest.php
- Added a StatusUpdatedProjector to handle the StatusUpdated event on either an event or place.
---
Ticket: https://jira.uitdatabank.be/browse/III-3656
=> Handle the StatusUpdated event.

src/Offer/ReadModel/JSONLD/NewPropertyPolyfillOfferRepository.php, tests/Offer/ReadModel/JSONLD/NewPropertyPolyfillOfferRepositoryTest.php
- Fix for modified status on parent event.
---
Ticket: https://jira.uitdatabank.be/browse/III-3658
=> Fix for modified status on parent event.

app/Event/EventControllerProvider.php, app/Place/PlaceControllerProvider.php, src/Http/Event/UpdateStatusRequestHandler.php, src/Http/Offer/UpdateStatusValidator.php, src/Http/Place/UpdateStatusRequestHandler.php, tests/Http/Offer/UpdateStatusValidatorTest.php
- `/events/{id}/status` endpoint to update status of an event
- `/places/{id}/status` endpoint to update status of a place
---
Ticket: https://jira.uitdatabank.be/browse/III-3659
=> Add endpoints to update event status

composer.lock, src/Offer/CommandHandlers/UpdateStatusHandler.php, src/Offer/Offer.php
- After the change in `udb3-php` to make `withStatus()` only update the top status, `Offer::updateStatus()` had to be updated to also call `withStatusOnTimestamps()`
---
Ticket: https://jira.uitdatabank.be/browse/III-3679
=> III-3679 Change Offer::updateStatus() to set statuses on timestamps as well

composer.json, composer.lock
Updated dependencies for all udb3-... libraries that were changed in The Great PHP Update Of 2021
---
Ticket: https://jira.uitdatabank.be/browse/III-3551
=> Update all changed dependencies to latest version

app/Offer/OfferControllerProvider.php, src/Http/Offer/UpdateStatusRequestHandler.php
- Fix registration of UpdateStatusRequestHandler
=> Fix registration of UpdateStatusRequestHandler

.github/pull_request_template.md, composer.lock, src/Http/Deserializer/Calendar/CalendarJSONParser.php, tests/Http/Deserializer/Calendar/CalendarJSONParserTest.php, tests/Http/Deserializer/Calendar/samples/calendar_all_fields.json
- Apply the top-level status to sub-events without a status
---
Ticket: https://jira.uitdatabank.be/browse/III-3747
=> III-3747 Apply top-level status to sub-events

app/UiTPAS/UiTPASControllerProvider.php, web/index.php
- Added `/uitpas/labels` endpoint
---
Ticket: https://jira.uitdatabank.be/browse/III-3735
Note: This is branched from #549 !
=> III-3735 Add uitpas labels endpoint

app/CommandHandling/CommandBusServiceProvider.php, app/Console/AbstractFireProjectedToJSONLDCommand.php, app/Console/ReindexOffersWithPopularityScore.php, app/Console/ReplayCommand.php, app/Event/EventEditingServiceProvider.php, app/Event/EventGeoCoordinatesServiceProvider.php, app/Organizer/OrganizerGeoCoordinatesServiceProvider.php, app/Place/PlaceGeoCoordinatesServiceProvider.php, app/UiTPAS/UiTPASCommandValidatorServiceProvider.php, bootstrap.php, composer.json, composer.lock, src/Broadway/CommandHandling/Validation/CommandValidatorInterface.php, src/Broadway/CommandHandling/Validation/CompositeCommandValidator.php, src/Broadway/CommandHandling/Validation/ValidatingCommandBusDecorator.php, src/Broadway/Domain/DomainMessageIsNot.php, src/Broadway/Domain/DomainMessageIsReplayed.php, src/Broadway/Domain/DomainMessageSpecificationInterface.php, src/Broadway/Domain/ReplayDetectorTrait.php, src/Broadway/EventHandling/FilteringEventListener.php, src/Broadway/EventHandling/ReplayFilteringEventListener.php, src/Broadway/EventHandling/ReplayFlaggingEventBus.php, src/Broadway/EventHandling/ReplayModeEventBusInterface.php, src/EventSourcing/DomainMessageBuilder.php, src/UiTPAS/Event/CommandHandling/Validation/EventHasTicketSalesCommandValidator.php, tests/Broadway/CommandHandling/Validation/CompositeCommandValidatorTest.php, tests/Broadway/CommandHandling/Validation/ValidatingCommandBusDecoratorTest.php, tests/Broadway/EventHandling/ReplayFilteringEventListenerTest.php, tests/Broadway/EventHandling/ReplayFlaggingEventBusTest.php
- Internalize `broadway-tools` inside `udb3-silex`
---
Ticket: https://jira.uitdatabank.be/browse/III-3715
=> III-3715 Internalize broadway tools

bootstrap.php, composer.json, composer.lock, src/Clock/Clock.php, src/Clock/FrozenClock.php, src/Clock/SystemClock.php, src/EventExport/Format/HTML/Uitpas/Promotion/EventOrganizerPromotionQueryFactory.php, src/Jwt/JwtEncoderService.php, tests/EventExport/Format/HTML/Uitpas/Promotion/EventOrganizerPromotionQueryFactoryTest.php, tests/Jwt/JwtEncoderServiceTest.php
- Merge the package cultuurnet/clock inside udb3-silex
---
Ticket: https://jira.uitdatabank.be/browse/III-3717
Note: started from PR https://github.com/cultuurnet/udb3-silex/pull/559
=> III-3717 Internalize the clock package

app/FeatureToggles/FeatureTogglesControllerProvider.php, app/FeatureToggles/FeatureTogglesProvider.php, bootstrap.php, composer.json, composer.lock, web/index.php
- Internalize silex feature toggles provider
---
Ticket: https://jira.uitdatabank.be/browse/III-3718
=> III-3718 Internalize silex feature toggles provider

composer.lock
- Issue with extra small multiple calendar not properly rendering the status when the events were on the same day
---
Ticket: https://jira.uitdatabank.be/browse/III-3804
=> III-3804 Update calendar-summary-v3 to latest version

src/Event/Event.php, src/Place/Place.php, tests/Event/CommandHandlers/UpdateSubEventStatusHandlerTest.php
- Fixed status not being applied correctly or reverting changes made after a MajorInfoUpdated
---
Ticket: https://jira.uitdatabank.be/browse/III-3809
=> III-3809 Set calendar property on aggregate after MajorInfoUpdated

composer.json, composer.lock
- Unused dependencies on `cultuurnet/entry` and `cultuurnet/calendar-summary`
=> Remove unused dependencies

app/Migrations/Version20210222150300.php, composer.json
- Added migration to add `labels_import` table
---
Ticket: https://jira.uitdatabank.be/browse/III-3607
=> III-3607 Add labels import table

app/Console/UpdateUniqueOrganizers.php
- Change the namespace to Ramsey\Uuid\Uuid
=> Hotfix namespace to Ramsey\Uuid\Uuid

config/cli-config.php
- Replace deprecated `DialogHelper` with `QuestionHelper`
=> Hotfix replace deprecated DialogHelper

src/Event/Productions/SimilarEventsRepository.php
- Improve similarity query by using a subquery on the skipped events instead of a join
---
Ticket: https://jira.uitdatabank.be/browse/III-3696
=> III-3696 Improve similarity query

tests/Organizer/CommandHandler/AddLabelHandlerTest.php, tests/Organizer/CommandHandler/ImportLabelsHandlerTest.php, tests/Organizer/CommandHandler/RemoveLabelHandlerTest.php
- Coding standards were violated due to an unlucky merge order
=> Fix code styles that were accidentally merged

src/Http/Place/ReadPlaceRestController.php
- Convert `includeMetadata` to boolean
---
Ticket: https://jira.uitdatabank.be/browse/III-3821
=> III-3821 Convert `includeMetadata` to boolean

app/Search/Sapi3SearchServiceProvider.php
- The results generator now uses an offer search service instead of an event search service.
---
Ticket: https://jira.uitdatabank.be/browse/III-3833
=> III-3833 Fix bulk label

tests/EventExport/Format/JSONLD/JSONLDEventFormatterTest.php, tests/EventExport/samples/event_with_status.json
- Test scenario to verify we can already export event status in jsonld format 
---
Ticket: https://jira.uitdatabank.be/browse/III-3860
=> Add test to verify we can export the status of an event in jsonld format

composer.json, composer.lock, tests/Http/Event/ReadEventRestControllerTest.php, tests/Http/Place/ReadPlaceRestControllerTest.php
- Update cultuurnet/calendar-summary-v3 to v3.1
---
Ticket: https://jira.uitdatabank.be/browse/III-3862
=> III-3862 Update cultuurnet/calendar-summary-v3 to v3.1

src/EventSourcing/CopyAwareEventStoreDecorator.php
- Add typecast to int to prevent crash
---
Ticket: https://jira.uitdatabank.be/browse/III-3868
=> III-3868 Add typecast to int to prevent crash

composer.json, composer.lock
- https://github.com/cultuurnet/calendar-summary-v3/releases/tag/v3.2
---
Ticket: https://jira.uitdatabank.be/browse/III-3872
=> Update calendar summary to latest version

src/Event/Commands/CreateEvent.php, src/Event/EventCommandHandler.php, tests/Event/Commands/CreateEventTest.php, tests/Event/EventCommandHandlerTest.php
- https://jira.uitdatabank.be/browse/III-3526?focusedCommentId=104620&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-104620
---
Ticket: https://jira.uitdatabank.be/browse/III-3526
=> III-3526 - Comment by bert

phpunit.xml.dist, src/Calendar.php, tests/CalendarTest.php
- Fix for top level end date which is before start date
---
Ticket: https://jira.uitdatabank.be/browse/III-3511
=> III-3511 Fix for top level end date which is before start date

src/Http/OfferRestBaseController.php, tests/Http/OfferRestBaseControllerTest.php
- Fixed CopyRightHolder TypeError
---
Ticket: https://jira.uitdatabank.be/browse/III-3886
=> III-3886 Fix Copyrightholder TypeError

src/Http/Event/ReadEventRestController.php
- Fixed TypeError about hidePast argument
---
Ticket: https://jira.uitdatabank.be/browse/III-3887
=> III-3887 Convert hidePast parameter value to boolean

app/Error/CliErrorHandlerProvider.php, app/Error/WebErrorHandlerProvider.php, bin/udb3.php, readme.md, web/index.php
- Added `cli.log`
- Renamed `error.log` to `web.log`
- Fixed missing `ErrorLogger` service in `bin/udb3.php`
---
Ticket: https://jira.uitdatabank.be/browse/III-3816
=> III-3816 Different web and cli logs

src/Http/Event/ReadEventRestController.php
- Fixed `hidePast=false` getting converted to `true` 🤦  (Thanks for the tip @LucWollants!)
---
Ticket: https://jira.uitdatabank.be/browse/III-3887
=> III-3887 Use getBoolean() instead of casting to bool

src/Event/Productions/ProductionRepository.php
- Fixed productions returned when searching with a `limit`. When the `GROUP_CONCAT` was removed, the `limit` was applied to rows per event instead of rows per production
---
Ticket: https://jira.uitdatabank.be/browse/III-3892
=> III-3892 Limit productions results in a join that groups rows by production_id

app/Error/WebErrorHandlerProvider.php
- Same as https://github.com/cultuurnet/udb3-search-service/pull/135
---
Ticket: https://jira.uitdatabank.be/browse/III-3816
=> III-3816 Don't log exceptions that are child classes or implementations of bad request exceptions

app/CommandHandling/CommandBusServiceProvider.php, app/Curators/CuratorsServiceProvider.php, app/Error/CliErrorHandlerProvider.php, app/Error/LoggerName.php, app/Error/WebErrorHandlerProvider.php, app/Event/EventGeoCoordinatesServiceProvider.php, app/Event/EventImportServiceProvider.php, app/Export/ExportServiceProvider.php, app/GeocodingServiceProvider.php, app/Import/ImportConsumerServiceProvider.php, app/Labels/LabelServiceProvider.php, app/Media/MediaServiceProvider.php, app/Offer/BulkLabelOfferServiceProvider.php, app/Organizer/OrganizerGeoCoordinatesServiceProvider.php, app/Place/PlaceGeoCoordinatesServiceProvider.php, app/Search/Sapi3SearchServiceProvider.php, app/UDB2IncomingEventServicesProvider.php, app/UiTPAS/UiTPASCommandValidatorServiceProvider.php, app/UiTPAS/UiTPASIncomingEventServicesProvider.php, app/User/UserServiceProvider.php, bootstrap.php, readme.md, worker_bootstrap.php
- Renamed log files for more consistency and predictability
---
Ticket: https://jira.uitdatabank.be/browse/III-3881
=> III-3881 Consistent logger names

app/Console/UpdateUniqueOrganizers.php
- Remove uuid constraint on organizers when updating unique table
---
Ticket: https://jira.uitdatabank.be/browse/III-3653
=> III-3653 Remove uuid constraint on organizers when updating unique table

app/User/UserControllerProvider.php, src/Http/User/UserIdentityController.php
- Endpoints that were temporarily added for testing purposes
=> Remove obsolete endpoints

bootstrap.php, composer.json, composer.lock
- Dependency on https://github.com/mbutkereit/psr-7-service-provider
- Controllers can now use PSR-7 request/response objects
---
Ticket: https://jira.uitdatabank.be/browse/III-3835
=> Allow PSR-7 Request and Response in controllers

app/Place/DeprecatedPlaceControllerProvider.php
=> Remove unnecessary (and faulty) service provisioning

app/Console/UpdateUniqueOrganizers.php
- Fixed integrity constraint violations when repopulating the `organizer_unique_websites` table and another organizer than the one currently being handled already has the same website (caused by the table being empty and the unique check thus not working, causing organizers to have duplicate websites)
=> III-3653 Handle duplicate organizer websites

app/Labels/LabelServiceProvider.php, bootstrap.php, src/EventSourcing/DBAL/UniqueConstraintService.php, src/EventSourcing/DBAL/UniqueConstraintServiceInterface.php, src/EventSourcing/DBAL/UniqueDBALEventStoreDecorator.php, src/Label/Events/LabelNameUniqueConstraintService.php, src/Organizer/Events/WebsiteUniqueConstraintService.php, tests/EventSourcing/DBAL/UniqueDBALEventStoreDecoratorTest.php, tests/Organizer/DBALWebsiteLookupServiceTest.php, tests/Organizer/Events/WebsiteUniqueConstraintServiceTest.php
- Expanded the check on the unique website url for organizers
---
Ticket: https://jira.uitdatabank.be/browse/III-3970
=> III-3970 Expand the check on the unique website url for organizers

src/Http/Organizer/EditOrganizerRestController.php
- Correctly set the validation message
---
Ticket: https://jira.uitdatabank.be/browse/III-3992
=> III-3992 Correctly set the validation message

config.yml.dist, src/Jwt/FallbackJwtDecoder.php, src/Jwt/JwtDecoderService.php, src/Jwt/JwtDecoderServiceInterface.php, src/Jwt/Silex/JwtServiceProvider.php, src/Jwt/Symfony/Authentication/JwtAuthenticationProvider.php, tests/Jwt/FallbackJwtDecoderTest.php, tests/Jwt/JwtDecoderServiceTest.php, tests/Jwt/Symfony/Authentication/JwtAuthenticationProviderTest.php, tests/Jwt/WithFallbackJwtDecoderTest.php, web/index.php
- Changed how `iss` claim is validated, so we can validate multiple issuers
---
Ticket: https://jira.uitdatabank.be/browse/III-4071
Todo: Update config in appconfig and udb3-vagrant
=> III-4071 Accept multiple issuers

app/User/UserControllerProvider.php, src/Http/User/UserIdentityController.php, tests/Http/User/UserIdentityControllerTest.php, web/index.php
- Move current user endpoint from `index.php` to `UserControllerProvider`
---
Ticket: https://jira.uitdatabank.be/browse/III-4062
=> III-4062 Move current user endpoint to UserController

app/Console/UpdateUniqueOrganizers.php, src/EventSourcing/DBAL/UniqueDBALEventStoreDecorator.php, tests/EventSourcing/DBAL/UniqueDBALEventStoreDecoratorTest.php
- Changed unique website check from partial match to full match
---
Ticket: https://jira.uitdatabank.be/browse/III-4078
=> III-4078 Fix partial match for unique website

src/Http/Productions/CreateProductionValidator.php, tests/Http/Productions/CreateProductionValidatorTest.php, tests/Http/Productions/ProductionsWriteControllerTest.php
- Support productions with a single event
---
Ticket: https://jira.uitdatabank.be/browse/III-4093
=> III-4093 Support productions with a single event

src/Role/ValueObjects/Permission.php, tests/Http/Role/ReadRoleRestControllerTest.php, tests/Role/ValueObjects/PermissionTest.php
- new permission for filminvoer
---
Ticket: https://jira.uitdatabank.be/browse/III-4097
=> III-4097 - Add permissions filminvoer

src/SavedSearches/Sapi3FixedSavedSearchRepository.php, tests/CultuurNet/UDB3/SavedSearches/Sapi3FixedSavedSearchRepositoryTest.php
- Add tests for Sapi3FixedSavedSearchRepository
---
Ticket: https://jira.uitdatabank.be/browse/III-4063
=> III-4063 Add test for query mode uuid

app/Event/ProductionControllerProvider.php, src/Event/Productions/BroadcastingProductionRepository.php, src/Event/Productions/DBALProductionRepository.php, src/Event/Productions/ProductionCommandHandler.php, src/Event/Productions/ProductionRepository.php, src/Event/Productions/RenameProduction.php, src/Http/Productions/ProductionsWriteController.php, src/Http/Productions/RenameProductionValidator.php, tests/Event/Productions/BroadcastingProductionRepositoryTest.php, tests/Event/Productions/DBALProductionRepositoryTest.php, tests/Event/Productions/ProductionCommandHandlerTest.php, tests/Http/Productions/ProductionsWriteControllerTest.php, tests/Http/Productions/RenameProductionValidatorTest.php
- Add new endpoint to rename production
Note: an urldecode is not needed that is already done by Silex
---
Ticket: https://jira.uitdatabank.be/browse/III-3494
=> III-3494 Add new endpoint to rename production

src/Security/CommandAuthorizationException.php
- Tweak status code to 403 (Forbidden) instead of 401 (Unauthorized)
---
Ticket: https://jira.uitdatabank.be/browse/III-4141
=> Tweak status code to 403 (Forbidden) instead of 401 (Unauthorized)

app/Error/WebErrorHandlerProvider.php, src/Http/ApiProblem/ApiProblem.php
- Fixed "Trying to clone an uncloneable object of class CultuurNet\UDB3\Http\ApiProblem\ApiProblem"
=> Fix "Trying to clone an uncloneable object of class CultuurNet\UDB3\Http\ApiProblem\ApiProblem"

src/EventExport/Format/TabularData/TabularDataEventFormatter.php, tests/EventExport/Format/JSONLD/JSONLDEventFormatterTest.php, tests/EventExport/Format/TabularData/TabularDataEventFormatterTest.php, tests/EventExport/samples/event_with_booking_availability.json
- Added exporting of booking availability on table and json format
---
Ticket: https://jira.uitdatabank.be/browse/III-4119
=> III-4119 Export booking availability

src/Http/Event/UpdateSubEventsRequestHandler.php, src/Http/Offer/UpdateBookingAvailabilityRequestHandler.php, src/Offer/ValueObjects/BookingAvailability.php, src/Offer/ValueObjects/BookingAvailabilityType.php, tests/CalendarTest.php, tests/Offer/ValueObjects/BookingAvailabilityTest.php, tests/TimestampTest.php
- Consistent use of BookingAvailability and BookingAvailabilityType
=> Consistent use of BookingAvailability and BookingAvailabilityType

tests/Http/Request/Body/AssociativeArrayRequestBodyParserTest.php
- Tests for `AssociativeArrayRequestBodyParser`
=> Add tests for AssociativeArrayRequestBodyParser

composer.json, composer.lock, src/Model/Serializer/ValueObject/Calendar/StatusDenormalizer.php, tests/Http/Offer/UpdateStatusRequestHandlerTest.php
- Allow empty status reason
---
Ticket: https://jira.uitdatabank.be/browse/III-4192
=> III-4192 Allow empty status reason

composer.json, composer.lock
- Depend on `dev-booking-availability` for `publiq/stoplight-docs-uitdatabank`
=> Depend on dev-booking-availability for publiq/stoplight-docs-uitdatabank

composer.json, composer.lock
- Updated `cultuurnet/calendar-summary-v3` to v3.3
---
Ticket: https://jira.uitdatabank.be/browse/III-4190
=> III-4190 Update cultuurnet/calendar-summary-v3 to v3.3

src/Event/Event.php, src/Http/Event/DateRangeValidatingRequestBodyParser.php, src/Http/Event/UpdateSubEventsRequestHandler.php, src/Http/Offer/DateRangeValidator.php, src/Http/Offer/UpdateCalendarValidationRequestBodyParser.php, src/Model/Serializer/ValueObject/Calendar/SubEventUpdateDenormalizer.php, src/Model/ValueObject/Calendar/SubEventUpdate.php, tests/Event/CommandHandlers/UpdateSubEventsHandlerTest.php, tests/Http/Event/UpdateSubEventsRequestHandlerTest.php
- Implemented updating the start and or end date of sub events
---
Ticket: https://jira.uitdatabank.be/browse/III-4162
=> III-4162 Make it possible update start and end date of a sub event

src/Calendar.php, tests/CalendarTest.php
- Fix edge case for status reason on sub event of single calendar
---
Ticket: https://jira.uitdatabank.be/browse/III-4045
=> III-4045 Fix edge case reason single calendar

composer.json, composer.lock, tests/Http/Event/ReadEventRestControllerTest.php, tests/Http/Place/ReadPlaceRestControllerTest.php
- Upgrade cultuurnet/calendar-summary-v3 to version 3.4
=> Upgrade cultuurnet/calendar-summary-v3 to version 3.4

app/Console/UpdateBookingAvailabilityCommand.php, app/Impersonator.php, bin/udb3.php
- Added new CLI command to update the booking availability of events based on custom query and with calendar type single or multiple
---
Ticket: https://jira.uitdatabank.be/browse/III-4220
=> III-4220 Add CLI command to update booking availability

app/Role/RoleControllerProvider.php
- Add constraints endpoint without SapiVersion
---
Ticket: https://jira.uitdatabank.be/browse/III-4225
=> III-4225 Add constraints endpoint without SapiVersion

src/Http/ApiProblem/ApiProblem.php, src/Http/Import/ImportRestController.php, tests/Http/Import/ImportRestControllerTest.php
- Handle the unique constraint violation when importing a new resource with an already existing resource id
---
Ticket: https://jira.uitdatabank.be/browse/III-4142
=> III-4142 Handle importing a new resource with an already existing resource id

app/Console/UpdateBookingAvailabilityCommand.php
- Add extra brackets around booking availability CLI query
---
Ticket: https://jira.uitdatabank.be/browse/III-4228
=> III-4228 Add extra brackets around query

src/Role/ReadModel/Detail/Projector.php, tests/Role/ReadModel/Detail/ProjectorTest.php
- Added a top level constraint to the role projection
---
See for more details: https://jira.uitdatabank.be/browse/III-4226?focusedCommentId=113607&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-113607
Ticket: https://jira.uitdatabank.be/browse/III-4226
=> III-4226 Remove SapiVersion from the Roles projection/endpoint (Step 1)

app/Media/MediaServiceProvider.php
- update content url for switch to new service
---
Ticket: https://jira.uitdatabank.be/browse/III-4231
=> III-4231 update content url

app/Role/RoleControllerProvider.php
- Removed constraints endpoints with SapiVersion
---
Ticket: https://jira.uitdatabank.be/browse/III-4225
=> III-4225 Removed constraints endpoints with SapiVersion

app/Event/EventControllerProvider.php, app/Offer/OfferControllerProvider.php, app/Organizer/OrganizerControllerProvider.php, app/Place/PlaceControllerProvider.php, app/UiTPASService/UiTPASServiceEventControllerProvider.php, app/UiTPASService/UiTPASServiceOrganizerControllerProvider.php, web/index.php
- All URLs now use `kebab-casing`
- Existing routes with `camelCasing` automatically get rewritten to `kebab-casing` internally for backward compatibility
---
Ticket: https://jira.uitdatabank.be/browse/III-4178
This builds upon the work in #746 so that PR as well as its related Stoplight docs PR (https://github.com/cultuurnet/stoplight-docs-uitdatabank/pull/24) should be merged first
=> III-4178 Use kebab-casing in URLs and automatically transform known camelCase operations/resources

app/Organizer/OrganizerControllerProvider.php, src/Http/Organizer/AddLabelRequestHandler.php, src/Http/Organizer/EditOrganizerRestController.php, src/Http/Request/RouteParameters.php, src/Model/ValueObject/Taxonomy/Label/LabelName.php, tests/Http/Organizer/AddLabelRequestHandlerTest.php, tests/Http/Organizer/EditOrganizerRestControllerTest.php, tests/Http/Request/RouteParametersTest.php, tests/Model/ValueObject/Taxonomy/Label/LabelNameTest.php
- Added new request handler for add label
---
Ticket: https://jira.uitdatabank.be/browse/III-4288
=> III-4288 Refactor add label to organizer endpoint

app/Organizer/OrganizerControllerProvider.php, src/Http/Organizer/DeleteLabelRequestHandler.php, src/Http/Organizer/EditOrganizerRestController.php, src/Http/Request/RouteParameters.php, src/Model/ValueObject/Taxonomy/Label/LabelName.php, tests/Http/Organizer/AddLabelRequestHandlerTest.php, tests/Http/Organizer/DeleteLabelRequestHandlerTest.php, tests/Http/Organizer/EditOrganizerRestControllerTest.php, tests/Http/Request/RouteParametersTest.php, tests/Model/ValueObject/Taxonomy/Label/LabelNameTest.php
- Added new request handler for the delete label from organizer endpoint
- Removed obsolete code from `EditOrganizerRestController`
---
Ticket: https://jira.uitdatabank.be/browse/III-4289
=> III-4289 Refactor deleting label from organizer

src/Http/Organizer/AddLabelRequestHandler.php, src/Http/Organizer/DeleteLabelRequestHandler.php, src/Organizer/CommandHandler/AddLabelHandler.php, src/Organizer/CommandHandler/ImportLabelsHandler.php, src/Organizer/CommandHandler/RemoveLabelHandler.php, src/Organizer/CommandHandler/UpdateGeoCoordinatesFromAddressCommandHandler.php, src/Organizer/Commands/AbstractLabelCommand.php, tests/Http/Organizer/AddLabelRequestHandlerTest.php, tests/Http/Organizer/DeleteLabelRequestHandlerTest.php, tests/Organizer/CommandHandler/AddLabelHandlerTest.php, tests/Organizer/CommandHandler/RemoveLabelHandlerTest.php, tests/Organizer/Commands/AbstractLabelCommandTest.php, tests/Organizer/Commands/AddLabelTest.php, tests/Organizer/Commands/RemoveLabelTest.php
- Refactor organizer label commands to work with Label from Model namespace
---
Ticket: https://jira.uitdatabank.be/browse/III-4289
=> III-4289 Refactor organizer label commands to work with Label from Model namespace

app/Organizer/OrganizerCommandHandlerProvider.php, app/Organizer/OrganizerControllerProvider.php, bootstrap.php, src/Http/Organizer/DeleteAddressRequestHandler.php, src/Http/Organizer/EditOrganizerRestController.php, src/Organizer/CommandHandler/RemoveAddressHandler.php, src/Organizer/DefaultOrganizerEditingService.php, src/Organizer/Organizer.php, src/Organizer/OrganizerCommandHandler.php, src/Organizer/OrganizerEditingServiceInterface.php, tests/Http/Organizer/DeleteAddressRequestHandlerTest.php, tests/Http/Organizer/EditOrganizerRestControllerTest.php, tests/Organizer/CommandHandler/RemoveAddressHandlerTest.php, tests/Organizer/DefaultOrganizerEditingServiceTest.php, tests/Organizer/OrganizerCommandHandlerTest.php
- Added new `DeleteAddressRequestHandler`
- Added new `RemoveAddressHandler`
- Removed obsolete code to handle address deletion
---
Ticket: https://jira.uitdatabank.be/browse/III-4294
=> III-4294 Refactor deleting address from organizer to PSR-7

app/Console/ReindexEventsWithRecommendations.php, bin/udb3.php
- Added script to reindex events that are a recommendation for other events
---
Ticket: https://jira.uitdatabank.be/browse/III-4372
=> III-4372 Add script to reindex events that are a recommendation for other events

src/Event/ReadModel/JSONLD/EventLDProjector.php, src/EventExport/Format/TabularData/TabularDataEventFormatter.php, src/Offer/ReadModel/JSONLD/OfferLDProjector.php, src/Organizer/OrganizerLDProjector.php, src/Place/ReadModel/JSONLD/PlaceLDProjector.php, tests/Event/ReadModel/JSONLD/EventLDProjectorTest.php, tests/EventSourcing/DBAL/UniqueDBALEventStoreDecoratorTest.php, tests/Offer/Item/ReadModel/JSONLD/ItemLDProjector.php, tests/Offer/ReadModel/JSONLD/CdbXmlContactInfoImporterTest.php, tests/Offer/ReadModel/JSONLD/OfferLDProjectorTest.php, tests/OfferLDProjectorTestBase.php, tests/Place/ReadModel/JSONLD/PlaceLDProjectorTest.php
- Improved type hinting on `OfferLDProjector`, `EventLDProjector` and `PlaceLDProjector`
- Improved type hinting on `OfferLDProjectorTest`, `EventLDProjectorTest` and `PlaceLDProjectorTest`
- Used `Json::encode` which throws by default
---
Ticket: https://jira.uitdatabank.be/browse/III-4227
=> III-4227 Boy scouting

app/Event/EventCommandHandlerProvider.php, app/Event/EventControllerProvider.php, bootstrap.php, src/Event/CommandHandlers/RemoveThemeHandler.php, src/Event/Commands/RemoveTheme.php, src/Event/Event.php, src/Event/Events/ThemeRemoved.php, src/Event/ReadModel/JSONLD/EventLDProjector.php, src/Http/Event/DeleteThemeRequestHandler.php, tests/Event/CommandHandlers/RemoveThemeHandlerTest.php, tests/Event/ReadModel/JSONLD/EventLDProjectorTest.php, tests/Http/Event/DeleteThemeRequestHandlerTest.php
- Added the `RemoveTheme` command
- Added the `ThemeRemoved` event
- Added the `RemoveThemeHandler` command handler
- Added the `DeleteThemeRequestHandler` request handler
- Consistent subscribe of command handlers
---
Ticket: https://jira.uitdatabank.be/browse/III-4378
=> III-4378 Implement new endpoint to remove theme from an event

src/Offer/ReadModel/JSONLD/MediaUrlOfferRepositoryDecorator.php, tests/Offer/ReadModel/JSONLD/MediaUrlOfferRepositoryDecoratorTest.php
- Map media urls of embedded location
---
Ticket: https://jira.uitdatabank.be/browse/III-4396
=> III-4396 Also map media embedded location

src/Organizer/Events/WebsiteUpdated.php, src/Organizer/Organizer.php, tests/Organizer/CommandHandler/UpdateWebsiteHandlerTest.php, tests/Organizer/Events/WebsiteUniqueConstraintServiceTest.php, tests/Organizer/Events/WebsiteUpdatedTest.php, tests/Organizer/OrganizerLDProjectorTest.php, tests/Organizer/OrganizerTest.php
-  Refactoring of `WebsiteUpdated` to use primitive types
---
Ticket: https://jira.uitdatabank.be/browse/III-4394
=> III-4394 websiteUpdated refactoring

src/Organizer/Events/OrganizerCreatedWithUniqueWebsite.php, src/Organizer/Organizer.php, tests/DomainMessage/CompositeDomainMessageEnricherTest.php, tests/Organizer/CommandHandler/DeleteOrganizerHandlerTest.php, tests/Organizer/CommandHandler/RemoveAddressHandlerTest.php, tests/Organizer/CommandHandler/UpdateContactPointHandlerTest.php, tests/Organizer/CommandHandler/UpdateWebsiteHandlerTest.php, tests/Organizer/DefaultOrganizerEditingServiceTest.php, tests/Organizer/Events/OrganizerCreatedWithUniqueWebsiteTest.php, tests/Organizer/Events/WebsiteUniqueConstraintServiceTest.php, tests/Organizer/OrganizerLDProjectorTest.php, tests/Organizer/OrganizerTest.php
- refactor `OrganizerCreatedWithUniqueWebsite` with primitive types
---
Ticket: https://jira.uitdatabank.be/browse/III-4399
=> III-4399 refactor OrganizerCreatedWithUniqueWebsite with primitive types

src/Organizer/Events/AbstractLabelEvent.php, src/Organizer/Organizer.php, tests/Label/LabelEventRelationTypeResolverTest.php, tests/Label/ReadModels/Relations/ProjectorTest.php, tests/Label/Specifications/LabelEventIsOfOrganizerTypeTest.php, tests/Organizer/CommandHandler/AddLabelHandlerTest.php, tests/Organizer/CommandHandler/ImportLabelsHandlerTest.php, tests/Organizer/CommandHandler/RemoveLabelHandlerTest.php, tests/Organizer/Events/AbstractLabelEventTest.php, tests/Organizer/Events/LabelAddedTest.php, tests/Organizer/Events/LabelRemovedTest.php, tests/Organizer/OrganizerLDProjectorTest.php, tests/Organizer/OrganizerTest.php
- Refactor `AbstractLabelEvent` to use primitive types
---
Ticket: https://jira.uitdatabank.be/browse/III-4388
=> III-4388 refactor abstract label event

src/Organizer/Events/AddressTranslated.php, src/Organizer/Organizer.php, tests/Organizer/CommandHandler/UpdateAddressHandlerTest.php, tests/Organizer/Events/AddressTranslatedTest.php, tests/Organizer/OrganizerLDProjectorTest.php, tests/Organizer/OrganizerTest.php, tests/Organizer/ProcessManager/GeoCoordinatesProcessManagerTest.php
- refactor `AddressTranslated ` to use primitive types
- 
---
Ticket: https://jira.uitdatabank.be/browse/III-4389
=> III-4389 refactor address translated

app/Migrations/Version20211201160612.php, src/Curators/DBALNewsArticleRepository.php, src/Curators/NewsArticle.php, src/Curators/NewsArticleNotFound.php, src/Curators/NewsArticleNotFoundException.php, src/Curators/NewsArticleRepository.php, src/Curators/NewsArticleSchemaConfigurator.php, src/Curators/NewsArticles.php, tests/Curators/DBALNewsArticleRepositoryTest.php
- Added value object for `NewsArticle` and a simple `NewsArticles` collection
- Added repository `NewsArticleRepository` and a concrete DBAL implementation `DBALNewsArticleRepository`
---
=> III-4410 Create repository for news article table

src/Organizer/Events/OrganizerCreated.php, tests/DomainMessage/CompositeDomainMessageEnricherTest.php, tests/Organizer/CommandHandler/AddLabelHandlerTest.php, tests/Organizer/CommandHandler/ImportLabelsHandlerTest.php, tests/Organizer/CommandHandler/RemoveLabelHandlerTest.php, tests/Organizer/CommandHandler/UpdateAddressHandlerTest.php, tests/Organizer/CommandHandler/UpdateGeoCoordinatesCommandHandlerTest.php, tests/Organizer/CommandHandler/UpdateTitleHandlerTest.php, tests/Organizer/Events/OrganizerCreatedTest.php, tests/Organizer/Events/WebsiteUniqueConstraintServiceTest.php, tests/Organizer/OrganizerLDProjectorTest.php, tests/Organizer/OrganizerTest.php
- refactor `OrganizerCreated` to use primitives for Title
---
Ticket: https://jira.uitdatabank.be/browse/III-4391
=> III-4391 refactor OrganizerCreated Title

src/Organizer/Events/OrganizerCreated.php, tests/DomainMessage/CompositeDomainMessageEnricherTest.php, tests/Organizer/CommandHandler/AddLabelHandlerTest.php, tests/Organizer/CommandHandler/ImportLabelsHandlerTest.php, tests/Organizer/CommandHandler/RemoveLabelHandlerTest.php, tests/Organizer/CommandHandler/UpdateAddressHandlerTest.php, tests/Organizer/CommandHandler/UpdateGeoCoordinatesCommandHandlerTest.php, tests/Organizer/CommandHandler/UpdateTitleHandlerTest.php, tests/Organizer/Events/OrganizerCreatedTest.php, tests/Organizer/Events/WebsiteUniqueConstraintServiceTest.php, tests/Organizer/OrganizerLDProjectorTest.php, tests/Organizer/OrganizerTest.php
- Changed the `Address` parameter of `OrganizerCreated` to primitive types
---
Ticket: https://jira.uitdatabank.be/browse/III-4391
=> III-4391 refactor OrganizerCreated address

app/Curators/CuratorsControllerProvider.php, app/Curators/CuratorsServiceProvider.php, bootstrap.php, src/Curators/Serializer/NewsArticleNormalizer.php, src/Http/ApiProblem/ApiProblem.php, src/Http/Curators/GetNewsArticleRequestHandler.php, src/Http/Curators/GetNewsArticlesRequestHandler.php, tests/Curators/DBALNewsArticleRepositoryTest.php, tests/Http/Curators/GetNewsArticleRequestHandlerTest.php, tests/Http/Curators/GetNewsArticlesRequestHandlerTest.php, tests/Http/Organizer/GetOrganizerRequestHandlerTest.php, web/index.php
- Added ApiProblem for not found news article
- Added `NewsArticleNormalizer` to normalize a `NewsArticle` to an array
- Added `GetNewsArticleRequestHandler` to get an article by id
- Added `GetNewsArticlesRequestHandler` to get all articles
---
=> III-4410 Implement the news article get requests

app/Curators/CuratorsControllerProvider.php, src/Http/Curators/DeleteNewsArticleRequestHandler.php, tests/Curators/DBALNewsArticleRepositoryTest.php, tests/Http/Curators/DeleteNewsArticleRequestHandlerTest.php, web/index.php
- Added request handler for deleting a news article
---
=> III-4410 Add request handler for deleting a news article

src/Organizer/Events/AddressTranslated.php, src/Organizer/Organizer.php, src/Organizer/OrganizerLDProjector.php
- refactored the getter of AddressTranslated to return primitive types
---
=> III-4414 refactor organizer getters AddressTranslated

src/Organizer/Events/AddressTranslated.php, src/Organizer/Events/AddressUpdated.php, src/Organizer/Organizer.php, src/Organizer/OrganizerLDProjector.php, src/Organizer/ProcessManager/GeoCoordinatesProcessManager.php
- Refactor Getters for `AddressUpdated` and fixing type hinting
---
=> III-4144 refactor organizer getters AddressUpdated

src/Organizer/Events/AddressTranslated.php, src/Organizer/Events/AddressUpdated.php, src/Organizer/Events/ContactPointUpdated.php, src/Organizer/Organizer.php, src/Organizer/OrganizerLDProjector.php, src/Organizer/ProcessManager/GeoCoordinatesProcessManager.php
- Refactored Getters to return primitive types
---
=> III-4144 refactor organizer getters ContactPointUpdated

src/Organizer/Events/AddressTranslated.php, src/Organizer/Events/AddressUpdated.php, src/Organizer/Events/ContactPointUpdated.php, src/Organizer/Events/GeoCoordinatesUpdated.php, src/Organizer/Organizer.php, src/Organizer/OrganizerLDProjector.php, src/Organizer/ProcessManager/GeoCoordinatesProcessManager.php
- Refactor `GeoCoordinatesUpdated` Getters to return primitive types
---
=> III-4144 refactor organizer getters GeoCoordinatesUpdated

src/Organizer/Events/TitleUpdated.php, src/Organizer/Organizer.php, src/Organizer/OrganizerLDProjector.php
- Refactor Getter of `TitleUpdated`
---
Ticket: https://jira.uitdatabank.be/browse/4414
=> III-4414 refactor organizer getters TitleUpdated

src/Organizer/Events/OrganizerCreatedWithUniqueWebsite.php, src/Organizer/Organizer.php, src/Organizer/OrganizerLDProjector.php, tests/Organizer/OrganizerTest.php
- Refactor getters OrganizerCreatedWithUniqueWebsite
---
=> III-4414 Refactor getters OrganizerCreatedWithUniqueWebsite

src/Organizer/Events/OrganizerCreated.php, src/Organizer/Organizer.php, src/Organizer/OrganizerLDProjector.php
- Refactored getters for OrganizerCreated
---
=> III-4414 Refactor getters OrganizerCreated

src/Label/ReadModels/JSON/Projector.php, src/Label/ReadModels/Relations/Projector.php, src/LabelEventInterface.php, src/Offer/Events/AbstractLabelEvent.php, src/Offer/Offer.php, src/Offer/ReadModel/History/OfferHistoryProjectorTrait.php, src/Offer/ReadModel/JSONLD/OfferLDProjector.php, src/Organizer/Events/AbstractLabelEvent.php, src/Organizer/Organizer.php, src/Organizer/OrganizerLDProjector.php, tests/BackwardsCompatiblePayloadSerializerFactoryTest.php, tests/Label/ReadModels/JSON/ProjectorTest.php, tests/Offer/Events/AbstractLabelEventTest.php, tests/Organizer/Events/AbstractLabelEventTest.php, tests/Place/ReadModel/History/HistoryProjectorTest.php
- Added method `LabelEventInterface::getLabelName`
- Added method `LabelEventInterface::isLabelVisible`
- Changed return type to `LabelEventInterface::getItemId`
- Removed `LabelEventInterface::getLabel`
---
=> III-4414 Refactor LabelEventInterface

app/Curators/CuratorsControllerProvider.php, composer.json, composer.lock, src/Curators/Serializer/NewsArticleDenormalizer.php, src/Curators/Serializer/NewsArticleNormalizer.php, src/Http/Curators/CreateNewsArticleRequestHandler.php, src/Http/Request/Body/JsonSchemaLocator.php, tests/Http/Curators/CreateNewsArticleRequestHandlerTest.php, tests/Http/Curators/GetNewsArticleRequestHandlerTest.php, tests/Http/Curators/GetNewsArticlesRequestHandlerTest.php, web/index.php
- Added a denormalizer `NewsArticleDenormalizer`
- Added a request handler `CreateNewsArticleRequestHandler`
- Fixed typo in the JSON body of an article, it should be headline instead of heading
---
=> III-4410 Add news article post request

src/Http/Organizer/CreateOrganizerRequestHandler.php, src/Model/Import/Organizer/OrganizerDocumentImporter.php, src/Model/ValueObject/Collection/Behaviour/IsStringArray.php, src/Model/ValueObject/Contact/ContactPoint.php, src/Model/ValueObject/Contact/TelephoneNumbers.php, src/Model/ValueObject/Geography/Address.php, src/Model/ValueObject/Web/EmailAddresses.php, src/Model/ValueObject/Web/Urls.php, src/Organizer/CommandHandler/UpdateContactPointHandler.php, src/Organizer/Organizer.php, src/Organizer/OrganizerLDProjector.php, src/Organizer/WorkflowStatus.php, tests/Model/Import/Organizer/OrganizerDocumentImporterTest.php, tests/Model/ValueObject/Contact/ContactPointTest.php, tests/Model/ValueObject/Geography/AddressTest.php, tests/Organizer/OrganizerTest.php
- new trait `IsStringArray`
- new method `sameAs` for ContactPoint & Address
- update type hinting
- Replace deprecated ValueObjects of Organizer 
---
=> III-4414 Refactor organizer to use Model value objects

src/Curators/DBALNewsArticleRepository.php, src/Curators/NewsArticleRepository.php, src/Curators/NewsArticleSearch.php, src/Http/Curators/GetNewsArticlesRequestHandler.php, tests/Curators/DBALNewsArticleRepositoryTest.php, tests/Http/Curators/GetNewsArticlesRequestHandlerTest.php
- Added search query parameters for publisher, about and url
---
=> III-4410 Make it possible to search on publisher, about and url

app/Event/EventJSONLDServiceProvider.php, src/Offer/ReadModel/JSONLD/CuratorEnrichedOfferRepository.php, tests/Offer/ReadModel/JSONLD/CuratorEnrichedOfferRepositoryTest.php
- Added `CuratorEnrichedOfferRepository` to enrich offers with curators labels based on the linked news articles.
---
=> III-4410 Add class to apply curator labels on the fly

composer.json, composer.lock, src/Curators/Serializer/NewsArticleNormalizer.php, tests/Http/Curators/CreateNewsArticleRequestHandlerTest.php, tests/Http/Curators/GetNewsArticleRequestHandlerTest.php, tests/Http/Curators/GetNewsArticlesRequestHandlerTest.php, tests/Http/Curators/UpdateNewsArticleRequestHandlerTest.php
- Added extra tests for invalid news article bodies
- Added extra tests for missing properties in news article bodies
- Added JSON-LD properties on news articles
---
=> III-4410 Finetune news article properties

src/Curators/DBALNewsArticleRepository.php, src/Curators/NewsArticleRepository.php, src/Curators/NewsArticleSearch.php, src/Http/Curators/GetNewsArticlesRequestHandler.php, tests/Curators/DBALNewsArticleRepositoryTest.php, tests/Http/Curators/GetNewsArticlesRequestHandlerTest.php
- Added basic pagination with `page` query parameter
- Wrapped result inside `hydra:member` to mimic old API
---
=> III-4410 Add pagination

tests/Organizer/OrganizerTest.php
- Removed LegacyCode from `OrganizerTest`
---
=> III-4414 overlooked legacy code OrganizerTest

src/Event/Event.php, src/LabelAwareAggregateRoot.php, src/Offer/CommandHandlers/AddLabelHandler.php, src/Offer/CommandHandlers/RemoveLabelHandler.php, src/Offer/Offer.php, src/Organizer/CommandHandler/AddLabelHandler.php, src/Organizer/CommandHandler/RemoveLabelHandler.php, src/Organizer/Organizer.php, src/Place/Place.php, src/UDB2/Label/RelatedUDB3LabelApplier.php, tests/Event/EventTest.php, tests/Offer/Item/Item.php, tests/Offer/OfferTest.php, tests/Organizer/OrganizerTest.php, tests/Place/PlaceTest.php, tests/UDB2/Label/RelatedUDB3LabelApplierTest.php
- Refactored `LabelAwareAggregateRoot` to replace deprecated Label VO and its implementing classes
---
Ticket: https://jira.uitdatabank.be/browse/III-4419
=> III-4419 refactor LabelAwareAggregateRoot

app/AggregateType.php, app/Console/ReplayCommand.php, app/Labels/LabelServiceProvider.php, app/Media/MediaServiceProvider.php, bootstrap.php, src/EventSourcing/DBAL/AggregateAwareDBALEventStore.php, tests/EventSourcing/DBAL/AggregateAwareDBALEventStoreTest.php, tests/EventSourcing/DBAL/EventStreamTest.php, tests/EventSourcing/DBAL/UniqueDBALEventStoreDecoratorTest.php
- Refactor enum `AggregateType` to use `Enum` from Model namespace
---
=> III-4187 Refactor enum AggregateType

src/EventExport/CalendarSummary/Format.php, src/EventExport/CalendarSummary/HttpCalendarSummaryRepository.php, src/EventExport/Format/HTML/HTMLEventFormatter.php, src/EventExport/Format/TabularData/TabularDataEventFormatter.php, tests/EventExport/CalendarSummary/HttpCalendarSummaryRepositoryTest.php, tests/EventExport/Format/HTML/HTMLEventFormatterTest.php, tests/EventExport/Format/TabularData/TabularDataEventFormatterTest.php
-  Changed `Format` to use new `Enum` class instead of deprecated one.
---
=> III-4187 refactor enum Format

src/EventExport/CalendarSummary/ContentType.php, src/EventExport/CalendarSummary/HttpCalendarSummaryRepository.php, src/EventExport/Format/HTML/HTMLEventFormatter.php, src/EventExport/Format/TabularData/TabularDataEventFormatter.php, src/Model/ValueObject/String/Enum.php, tests/EventExport/CalendarSummary/HttpCalendarSummaryRepositoryTest.php, tests/EventExport/Format/HTML/HTMLEventFormatterTest.php, tests/EventExport/Format/TabularData/TabularDataEventFormatterTest.php, tests/Model/ValueObject/String/EnumTest.php
- Refactor enum `ContentType` to derive from Enum from Model namespace
- Boy scouting on `Enum` class
---
=> III-4187 Refactor enum ContentType

src/EventExport/Format/HTML/HTMLEventFormatter.php, src/EventExport/Format/HTML/Properties/TaalicoonDescription.php, tests/EventExport/Format/HTML/HTMLEventFormatterTest.php
- Change `Enum` of `TaalicoonDescription`
---
=> III-4187 refactor enum TaalicoonDescription

src/Http/Jobs/JobStatus.php, src/Http/Jobs/JobsStatusFactoryInterface.php, src/Http/Jobs/ReadRestController.php, src/Http/Jobs/ResqueJobStatusFactory.php, tests/Http/Jobs/JobStatusTest.php, tests/Http/Jobs/ReadRestControllerTest.php
- Changed LegacyEnum for `JobStatus`
---
Ticket: https://jira.uitdatabank.be/browse/IIII-4187
=> IIII-4187 refactor enum JobStatus

src/Http/JSONLD/ContextController.php, src/Http/JSONLD/EntityType.php
- Refactored `EntityType` to stop using deprecated Enum
---
=> III-4187 refactor enum EntityType

src/Label/LabelEventRelationTypeResolver.php, src/Label/ReadModels/Relations/Projector.php, src/Label/ReadModels/Relations/Repository/Doctrine/DBALWriteRepository.php, src/Label/ReadModels/Relations/Repository/LabelRelation.php, src/Label/ReadModels/Relations/Repository/WriteRepositoryInterface.php, src/Label/ValueObjects/RelationType.php, tests/Label/LabelEventRelationTypeResolverTest.php, tests/Label/ReadModels/JSON/ItemVisibilityProjectorTest.php, tests/Label/ReadModels/JSON/Repository/Doctrine/DBALWriteRepositoryTest.php, tests/Label/ReadModels/Relations/ProjectorTest.php, tests/Label/ReadModels/Relations/Repository/Doctrine/BaseDBALRepositoryTest.php, tests/Label/ReadModels/Relations/Repository/Doctrine/DBALReadRepositoryTest.php, tests/Label/ReadModels/Relations/Repository/Doctrine/DBALWriteRepositoryTest.php, tests/Label/ReadModels/Relations/Repository/OfferLabelRelationTest.php, tests/Label/ValueObjects/RelationTypeTest.php, tests/Model/Import/PreProcessing/LabelPreProcessingDocumentImporterTest.php, tests/Model/Import/Taxonomy/Label/RelationshipModelLockedLabelRepositoryTest.php, tests/Model/Import/Validation/Taxonomy/Label/LabelPermissionRuleTest.php, tests/UDB2/Label/RelatedUDB3LabelApplierTest.php
- Refactored `RelationType` to replace deprecated Enum
---
=> III-4187 refactor enum RelationType

src/EventExport/Command/ExportEventsAsPDF.php, src/EventExport/Command/ExportEventsAsPDFJSONDeserializer.php, src/EventExport/FileFormatInterface.php, src/EventExport/Format/HTML/PDF/PDFWebArchiveFileFormat.php, src/EventExport/Format/HTML/WebArchive/WebArchiveFileFormat.php, src/EventExport/Format/HTML/WebArchive/WebArchiveTemplate.php, src/EventExport/Format/JSONLD/JSONLDFileFormat.php, src/EventExport/Format/TabularData/OOXML/OOXMLFileFormat.php, tests/EventExport/Command/ExportEventsAsPDFJSONDeserializerTest.php, tests/EventExport/Command/ExportEventsAsPDFTest.php, tests/EventExport/EventExportCommandHandlerTest.php
- Refactor `WebArchiveTemplate` for deprecated enum
---
=> III-4187 refactor enum WebArchiveTemplate

tests/Model/ValueObject/Identity/ItemIdentifierFactoryTest.php
- Made url pattern for item identifier less strict
---
Ticket: https://jira.uitdatabank.be/browse/III-4438
=> III-4438 Make url pattern for item identifier less strict

src/EventExport/Command/ExportEventsAsPDF.php, src/EventExport/EventExportCommandHandler.php
- Fixed broken PDF export cause by nullable properties
=> Hotfix for broken PDF export because of nullable properties

src/EventExport/Command/ExportEvents.php, src/EventExport/Command/ExportEventsAsJsonLDJSONDeserializer.php, src/EventExport/Command/ExportEventsAsOOXMLJSONDeserializer.php, src/EventExport/Command/ExportEventsAsPDF.php, src/EventExport/Command/ExportEventsAsPDFJSONDeserializer.php, src/EventExport/Command/ExportEventsInterface.php, src/EventExport/Command/ExportEventsJSONDeserializer.php, src/EventExport/EventExportService.php, src/EventExport/EventExportServiceInterface.php, src/EventExport/Notification/NotificationMailerInterface.php, src/EventExport/Notification/Swift/DefaultMessageFactory.php, src/EventExport/Notification/Swift/MessageFactoryInterface.php, src/EventExport/Notification/Swift/NotificationMailer.php, src/Http/User/UserIdentityController.php, src/UiTID/CdbXmlCreatedByToUserIdResolver.php, src/User/Auth0UserIdentityResolver.php, src/User/UserIdentityResolver.php, tests/EventExport/Command/ExportEventsAsPDFJSONDeserializerTest.php, tests/EventExport/Command/ExportEventsAsPDFTest.php, tests/EventExport/Command/ExportEventsJSONDeserializerTest.php, tests/EventExport/EventExportCommandHandlerTest.php, tests/EventExport/EventExportServiceTest.php, tests/Http/User/UserIdentityControllerTest.php, tests/UiTID/CdbXmlCreatedByToUserIdResolverTest.php, tests/User/Auth0UserIdentityResolverTest.php
- Replaced legacy `EmailAddress` with the one from `Model` namespace
---
=> III-4539 Replace legacy email address

src/Calendar/OpeningTime.php, tests/Calendar/CalendarConverterTest.php, tests/Calendar/OpeningHourTest.php, tests/Calendar/OpeningTimeTest.php, tests/CalendarFactoryTest.php, tests/CalendarTest.php, tests/Event/ReadModel/JSONLD/EventLDProjectorTest.php, tests/Http/Deserializer/Calendar/CalendarJSONDeserializerTest.php, tests/Http/Deserializer/Calendar/CalendarJSONParserTest.php, tests/Http/Offer/UpdateCalendarRequestHandlerTest.php
- Changed deprecated VO `Hour` to new VO
---
=> III-4539 remove VO hour

src/Calendar/OpeningTime.php, tests/Calendar/CalendarConverterTest.php, tests/Calendar/OpeningHourTest.php, tests/Calendar/OpeningTimeTest.php, tests/CalendarFactoryTest.php, tests/CalendarTest.php, tests/Event/ReadModel/JSONLD/EventLDProjectorTest.php, tests/Http/Deserializer/Calendar/CalendarJSONDeserializerTest.php, tests/Http/Deserializer/Calendar/CalendarJSONParserTest.php, tests/Http/Offer/UpdateCalendarRequestHandlerTest.php
- Removed deprecated VO `Minute`
---
=> III-4539 remove VO Minute

src/Event/Event.php, src/Offer/AgeRange.php, tests/Event/EventTest.php, tests/Event/Events/TypicalAgeRangeUpdatedTest.php, tests/Model/Import/Event/EventDocumentImporterTest.php, tests/Model/Import/Offer/Udb3ModelToLegacyOfferAdapterTest.php, tests/Model/Import/Place/PlaceDocumentImporterTest.php, tests/Offer/AgeRangeTest.php, tests/Offer/Events/AbstractTypicalAgeRangeUpdatedTest.php, tests/Offer/OfferTest.php, tests/OfferCommandHandlerTestTrait.php, tests/OfferLDProjectorTestBase.php, tests/Place/PlaceRepositoryTest.php, tests/Place/PlaceTest.php
- Replaced deprecated VO `Age`.
---
=> III-4539 remove VO Age

composer.json, composer.lock, tests/Http/Organizer/UpdateUrlRequestHandlerTest.php
- Fixed failing test after update of URL properties validation in JSON schema
---
Ticket: https://jira.uitdatabank.be/browse/III-4544
=> III-4544 URL properties

app/Import/ImportControllerProvider.php, app/Organizer/OrganizerControllerProvider.php
- Added `PUT /organizers/{organizerId}` route
---
Ticket: https://jira.uitdatabank.be/browse/III-4404
=> III-4404 PUT /organizers/{organizerId}

src/Model/ValueObject/Web/Url.php, tests/Model/ValueObject/Web/UrlTest.php
- Fixed allow urls with special characters
=> Fix: allow urls with special characters

src/Event/ReadModel/JSONLD/RelatedEventLDProjector.php, src/Offer/BulkLabelCommandHandler.php, src/Offer/IriOfferIdentifier.php, src/Offer/IriOfferIdentifierFactory.php, src/Offer/IriOfferIdentifierFactoryInterface.php, src/Offer/IriOfferIdentifierJSONDeserializer.php, tests/Event/LocationMarkedAsDuplicateProcessManagerTest.php, tests/Event/ReadModel/JSONLD/RelatedEventLDProjectorTest.php, tests/Offer/BulkLabelCommandHandlerTest.php, tests/Offer/Commands/AddLabelToMultipleJSONDeserializerTest.php, tests/Offer/Commands/AddLabelToMultipleTest.php, tests/Offer/IriOfferIdentifierFactoryTest.php, tests/Offer/IriOfferIdentifierJSONDeserializerTest.php, tests/Offer/IriOfferIdentifierTest.php, tests/Offer/OfferIdentifierCollectionTest.php
- Replace deprecated `Url` in `Offer`
---
=> III-4539 remove Vo Url in Offer

src/UDB2/Actor/ActorEventCdbXmlEnricher.php, src/UDB2/Actor/Events/ActorCreatedEnrichedWithCdbXml.php, src/UDB2/Actor/Events/ActorUpdatedEnrichedWithCdbXml.php, src/UDB2/DomainEvents/AbstractActorEvent.php, src/UDB2/DomainEvents/AbstractEventEvent.php, src/UDB2/DomainEvents/HasUrlTrait.php, src/UDB2/Event/EventCdbXmlEnricher.php, src/UDB2/Event/Events/EventCreatedEnrichedWithCdbXml.php, src/UDB2/Event/Events/EventUpdatedEnrichedWithCdbXml.php, tests/UDB2/Actor/ActorEventCdbXmlEnricherTest.php, tests/UDB2/Actor/Events/ActorCreatedEnrichedWithCdbXmlTest.php, tests/UDB2/Actor/Events/ActorUpdatedEnrichedWithCdbXmlTest.php, tests/UDB2/DomainEvents/ActorCreatedJSONDeserializerTest.php, tests/UDB2/DomainEvents/ActorCreatedTest.php, tests/UDB2/DomainEvents/ActorUpdatedJSONDeserializerTest.php, tests/UDB2/DomainEvents/ActorUpdatedTest.php, tests/UDB2/DomainEvents/EventCreatedJSONDeserializerTest.php, tests/UDB2/DomainEvents/EventCreatedTest.php, tests/UDB2/DomainEvents/EventUpdatedJSONDeserializerTest.php, tests/UDB2/DomainEvents/EventUpdatedTest.php, tests/UDB2/Event/EventCdbXmlEnricherTest.php
- Replace deprecated Url in events related stuff
---
=> III-4539 remove vo url events

src/Http/Role/EditRoleRestController.php, src/Label/ValueObjects/LabelName.php, src/Media/Properties/MIMEType.php, src/PriceInfo/Price.php, tests/Label/ValueObjects/LabelNameTest.php, tests/PriceInfo/PriceTest.php
- Removed dependency on `InvalidNativeArgumentException`
---
=> III-4539 Remove invalid InvalidNativeArgumentException

composer.json, composer.lock, tests/Http/Organizer/AddImageRequestHandlerTest.php, tests/Http/Organizer/ImportOrganizerRequestHandlerTest.php, tests/Http/Organizer/UpdateAddressRequestHandlerTest.php, tests/Http/Organizer/UpdateContactPointRequestHandlerTest.php, tests/Http/Organizer/UpdateDescriptionRequestHandlerTest.php, tests/Http/Organizer/UpdateImagesRequestHandlerTest.php, tests/Http/Organizer/UpdateTitleRequestHandlerTest.php
- Added extra tests for non-whitespace characters in organizer string properties
- Updated JSON schemas
---
Ticket: https://jira.uitdatabank.be/browse/III-4580
=> III-4580 Whitespace validation organizers

app/UDB2IncomingEventServicesProvider.php, app/UiTPAS/UiTPASIncomingEventServicesProvider.php, bootstrap.php, src/Broadway/AMQP/EventBusForwardingConsumerFactory.php, src/Http/Label/Query/QueryFactory.php, src/Http/Label/ReadRestController.php, src/Label/ReadModels/JSON/Repository/Doctrine/DBALReadRepository.php, src/Label/ReadModels/JSON/Repository/Entity.php, src/Label/ReadModels/JSON/Repository/GodUserReadRepositoryDecorator.php, src/Label/ReadModels/JSON/Repository/Query.php, src/Label/ReadModels/JSON/Repository/ReadRepositoryInterface.php, src/Label/Services/ReadService.php, src/Label/Services/ReadServiceInterface.php, src/Media/ImageUploaderService.php, tests/Http/Label/Query/QueryFactoryTest.php, tests/Http/Label/ReadRestControllerTest.php, tests/Label/ReadModels/JSON/Repository/Doctrine/BaseDBALRepositoryTest.php, tests/Label/ReadModels/JSON/Repository/Doctrine/DBALReadRepositoryTest.php, tests/Label/ReadModels/JSON/Repository/Doctrine/DBALWriteRepositoryTest.php, tests/Label/ReadModels/JSON/Repository/EntityTest.php, tests/Label/ReadModels/JSON/Repository/GodUserReadRepositoryDecoratorTest.php, tests/Label/ReadModels/JSON/Repository/QueryTest.php, tests/Label/Services/ReadServiceTest.php, tests/Media/ImageUploaderServiceTest.php
- Refactored `ImageUploaderService` to work with `int`
- Refactored `EventBusForwardingConsumerFactory` to work with `int`
- Refactored `ReadServiceInterface` to work with `int`
- Refactored `ReadRepositoryInterface` to work with `int`
- Refactored `Query` to work with `int`
- Refactored `Entity` to work with `int`
Note: the class `Price` is not modified.
---
=> III-4539 Remove value object Natural

app/UDB2IncomingEventServicesProvider.php, app/UiTPAS/UiTPASIncomingEventServicesProvider.php, src/Broadway/AMQP/EventBusForwardingConsumerFactory.php, src/Http/Label/Query/QueryFactory.php, src/Http/Label/Query/QueryFactoryInterface.php, src/Http/Label/ReadRestController.php, src/Label/ReadModels/JSON/Repository/Doctrine/DBALReadRepository.php, src/Label/ReadModels/JSON/Repository/GodUserReadRepositoryDecorator.php, src/Label/ReadModels/JSON/Repository/Query.php, src/Label/ReadModels/JSON/Repository/ReadRepositoryInterface.php, src/Label/Services/ReadService.php, src/Label/Services/ReadServiceInterface.php, tests/Http/Label/Query/QueryFactoryTest.php, tests/Http/Label/ReadRestControllerTest.php, tests/Label/ReadModels/JSON/Repository/Doctrine/DBALReadRepositoryTest.php, tests/Label/ReadModels/JSON/Repository/GodUserReadRepositoryDecoratorTest.php, tests/Label/ReadModels/JSON/Repository/QueryTest.php, tests/Label/Services/ReadServiceTest.php
- Boy scouting on the files modified for the Natural removal
---
=> III-4539 Boy scouting on the files modified for the Natural removal

src/Calendar.php, src/CalendarType.php, src/Event/ReadModel/JSONLD/EventLDProjector.php, src/EventExport/Format/HTML/HTMLEventFormatter.php, src/Offer/AvailableTo.php, src/Offer/CalendarTypeNotSupported.php
- Refactor `CalendarType` to extend internal `Enum`
---
=> III-4539 Refactor CalendarType

src/Http/Label/EditRestController.php, src/Label/Commands/Create.php, src/Label/Events/CopyCreated.php, src/Label/Events/Created.php, src/Label/Label.php, src/Label/ReadModels/JSON/Repository/Doctrine/DBALReadRepository.php, src/Label/ReadModels/JSON/Repository/Doctrine/DBALWriteRepository.php, src/Label/ReadModels/JSON/Repository/Entity.php, src/Label/ValueObjects/Privacy.php, src/Offer/CalendarTypeNotSupported.php, tests/Http/Label/EditRestControllerTest.php, tests/Http/Label/ReadRestControllerTest.php, tests/Label/Events/CreatedTest.php, tests/Label/ReadModels/JSON/Repository/BroadcastingWriteRepositoryDecoratorTest.php, tests/Label/ReadModels/JSON/Repository/Doctrine/BaseDBALRepositoryTest.php, tests/Label/ReadModels/JSON/Repository/EntityTest.php, tests/Label/ReadModels/JSON/Repository/GodUserReadRepositoryDecoratorTest.php, tests/Label/ValueObjects/PrivacyTest.php, tests/Role/ReadModel/Labels/LabelRolesProjectorTest.php, tests/Role/ReadModel/Labels/RoleLabelsProjectorTest.php
- Refactor privacy to derive from internal Enum class
---
=> III-4539 Refactor privacy

src/BackwardsCompatiblePayloadSerializerFactory.php, src/Http/Import/ImportLabelVisibilityRequestBodyParser.php, src/Http/Label/EditRestController.php, src/Label/Commands/Create.php, src/Label/Events/CopyCreated.php, src/Label/Events/Created.php, src/Label/Label.php, src/Label/ReadModels/JSON/Repository/Doctrine/DBALWriteRepository.php, src/Label/ReadModels/JSON/Repository/Entity.php, src/Label/ValueObjects/Visibility.php, src/Model/Import/PreProcessing/LabelPreProcessingDocumentImporter.php, src/Offer/CommandHandlers/AddLabelHandler.php, src/Organizer/CommandHandler/AddLabelHandler.php, src/Organizer/CommandHandler/ImportLabelsHandler.php, src/Organizer/CommandHandler/RemoveLabelHandler.php, src/UDB2/Label/RelatedUDB3LabelApplier.php, tests/Http/Label/EditRestControllerTest.php, tests/Http/Label/ReadRestControllerTest.php, tests/Label/Events/CreatedTest.php, tests/Label/ReadModels/JSON/Repository/BroadcastingWriteRepositoryDecoratorTest.php, tests/Label/ReadModels/JSON/Repository/Doctrine/BaseDBALRepositoryTest.php, tests/Label/ReadModels/JSON/Repository/EntityTest.php, tests/Label/ValueObjects/VisibilityTest.php, tests/Role/ReadModel/Labels/LabelRolesProjectorTest.php, tests/Role/ReadModel/Labels/RoleLabelsProjectorTest.php
- Refactor Visibility to use embedded Enum class
---
=> III-4539 Refactor visibility

src/Calendar/CalendarConverter.php, src/Calendar/DayOfWeek.php, src/Calendar/DayOfWeekCollection.php, src/CalendarFactory.php, tests/Calendar/DayOfWeekTest.php, tests/Calendar/OpeningHourTest.php
- Refactor DayOfWeek to use internal Enum class
---
=> III-4539 Refactor DayOfWeek

src/Media/ImageStorage.php, tests/Media/ImageStorageTest.php
- test local save if upload fails
- Only make a local copy if upload fails
---
Ticket: https://jira.uitdatabank.be/browse/III-4433
=> III-4433 prevent local copy

app/Console/ReplaceNewsArticlePublisher.php, bin/udb3.php
- Added script to replace the publisher of news articles
---
Ticket: https://jira.uitdatabank.be/browse/III-4523
=> III-4523 Add script  to replace publisher

app/Migrations/Version20220308071939.php
- Add table for storage of clusters of duplicate places
---
Ticket: https://jira.uitdatabank.be/browse/III-4600
=> III-4600 Add table for duplicate places

app/Event/EventControllerProvider.php, composer.json, composer.lock
- Bound new `PUT` event endpoint to `ImportEventRequestHandler`
---
Ticket: https://jira.uitdatabank.be/browse/III-4368
=> III-4368 Bind PUT event endpoint to ImportEventRequestHandler

composer.json, composer.lock, tests/Http/Event/ImportEventRequestHandlerTest.php, tests/Http/Organizer/ImportOrganizerRequestHandlerTest.php, tests/Http/Place/ImportPlaceRequestHandlerTest.php
- Allowed event, place and organizer to have contact point with optional fields
---
Ticket: https://jira.uitdatabank.be/browse/III-4633
=> III-4633 Allow event and place to have contact point with optional fields

app/Event/EventControllerProvider.php, app/Place/PlaceControllerProvider.php, src/Http/Event/ImportEventRequestHandler.php, src/Http/Place/ImportPlaceRequestHandler.php, tests/Http/Event/ImportEventRequestHandlerTest.php, tests/Http/Place/ImportPlaceRequestHandlerTest.php
- Removed approve logic from import of events and places
---
Ticket: https://jira.uitdatabank.be/browse/III-4636
=> III-4636 Remove approve logic from import of events and places

src/Http/Event/ImportEventRequestHandler.php, tests/Http/Event/ImportEventRequestHandlerTest.php
- Implemented deleting an event that has workflow status deleted
---
Ticket: https://jira.uitdatabank.be/browse/III-4622
=> III-4622 Delete an event with workflow status deleted

src/Http/Import/ImportTermRequestBodyParser.php, tests/Http/Event/ImportEventRequestHandlerTest.php, tests/Http/Import/ImportTermRequestBodyParserTest.php, tests/Http/Place/ImportPlaceRequestHandlerTest.php
- Improved unsupported terms error
---
Ticket: https://jira.uitdatabank.be/browse/III-4639
=> III-4639 Improve unsupported terms error

src/Model/Place/PlaceReference.php, src/Model/Serializer/Event/EventDenormalizer.php, src/Model/Serializer/Place/PlaceReferenceDenormalizer.php, tests/Model/Event/ImmutableEventTest.php, tests/Model/Import/Event/Udb3ModelToLegacyEventAdapterTest.php, tests/Model/Place/PlaceReferenceTest.php, tests/Model/Serializer/Place/PlaceReferenceDenormalizerTest.php
- Prevented parsing embedded places when parsing events.
---
Ticket: https://jira.uitdatabank.be/browse/III-4643
=> III-4643 Prevent place parsing when parsing event

src/Http/Event/ImportEventRequestHandler.php, tests/Http/Event/ImportEventRequestHandlerTest.php
- Allowed creating legacy event with address
---
Ticket: https://jira.uitdatabank.be/browse/III-4644
=> III-4644 Allow creating legacy event with address

src/Label/LabelImportPreProcessor.php
- Take into account provided visibility for new labels
Note: no unit tests were added, it is covered by new acceptance tests https://github.com/cultuurnet/udb3-acceptance-tests/pull/98
---
Ticket: https://jira.uitdatabank.be/browse/III-4652
=> III-4652 Take into account provided visibility for new labels

src/Event/ReadModel/JSONLD/EventLDProjector.php, tests/Event/ReadModel/JSONLD/EventLDProjectorTest.php, tests/Event/ReadModel/JSONLD/copied_event_with_place_type.json
- allow a fallback for events with a `placeType` instead of an `eventType`
---
Ticket: https://jira.uitdatabank.be/browse/III-3926
=> III-3926 events with placetypes

src/Organizer/OrganizerLDProjector.php, tests/Organizer/OrganizerLDProjectorTest.php, tests/Organizer/Samples/organizer_with_one_image_with_different_urls.json, tests/Organizer/Samples/organizer_with_two_images_with_different_urls.json
- Take into account images with urls different from id when removing
---
Ticket: https://jira.uitdatabank.be/browse/III-4659
=> III-4659 images different urls

src/Http/Event/ImportEventRequestHandler.php, src/Http/Organizer/ImportOrganizerRequestHandler.php, src/Http/Place/ImportPlaceRequestHandler.php, tests/Http/Event/ImportEventRequestHandlerTest.php, tests/Http/Organizer/ImportOrganizerRequestHandlerTest.php, tests/Http/Place/ImportPlaceRequestHandlerTest.php
- `POST /imports/events`, `POST /imports/places` and `POST /imports/organizers` now return `200` instead of `201`
---
Ticket: https://jira.uitdatabank.be/browse/III-4671
=> III-4671 Fix imports status code

src/Http/Offer/LegacyCalendarRequestBodyParser.php, tests/Http/Event/ImportEventRequestHandlerTest.php
- Added support for single calendar with missing subEvent
---
Ticket: https://jira.uitdatabank.be/browse/III-4672
=> III-4672 Support single calendar with missing subEvent

app/Security/OfferSecurityServiceProvider.php, app/Security/OrganizerSecurityServiceProvider.php, src/Security/Permission/ResourceOwnerVoter.php, tests/Security/PermissionVoterCommandBusSecurityTest.php
- Made it possible to cache the resource owner
---
Ticket: https://jira.uitdatabank.be/browse/III-4653
=> III-4653 Cache resource owner

src/Http/Event/ImportEventRequestHandler.php, src/Http/Place/ImportPlaceRequestHandler.php, src/Offer/NotAllowedToPublish.php, src/Offer/Offer.php, tests/Offer/OfferTest.php
- Catched publish exceptions
---
Ticket: https://jira.uitdatabank.be/browse/III-4665
=> III-4665 Catch publish exceptions

app/Migrations/Version20220414133757.php
- Added indexes on relations tables.
---
Ticket: https://jira.uitdatabank.be/browse/III-4653
=> III-4653 Add indexes on relations tables

src/Offer/ReadModel/JSONLD/NewPropertyPolyfillOfferRepository.php, tests/Offer/ReadModel/JSONLD/NewPropertyPolyfillOfferRepositoryTest.php
- Added simple polyfill for `attendanceMode` with `offline` as default value
---
Ticket: https://jira.uitdatabank.be/browse/III-4667
=> III-4667 Added simple polyfill for attendanceMode with offline as default

src/Event/Event.php, src/Event/Events/EventCreated.php, src/Event/Events/LocationUpdated.php, src/Event/Events/MajorInfoUpdated.php, src/Event/Location/LocationNotFound.php, src/Event/ReadModel/History/HistoryProjector.php, src/Event/ReadModel/JSONLD/EventLDProjector.php, src/Event/ReadModel/Relations/Projector.php, src/Event/RelocateEventToCanonicalPlace.php, src/Event/ValueObjects/LocationId.php, src/Http/Event/AttendanceModeValidatingRequestBodyParser.php, src/Http/Event/CopyEventRequestHandler.php, src/Http/Event/ImportEventRequestHandler.php, src/Http/Offer/BookingInfoValidatingRequestBodyParser.php, src/Http/Offer/CalendarValidatingRequestBodyParser.php, src/Http/Offer/UpdateCalendarRequestHandler.php, src/Http/Offer/UpdateCalendarValidatingRequestBodyParser.php, src/Http/Place/ImportPlaceRequestHandler.php, tests/Event/EventTest.php, tests/Event/RelocateEventToCanonicalPlaceTest.php, tests/Event/ValueObjects/LocationIdTest.php, tests/Http/Event/ImportEventRequestHandlerTest.php
- Added validation for virtual locations
- Online event requires a virtual location
- Offline event requires a real location
- Mixed event requires a real location
---
Ticket: https://jira.uitdatabank.be/browse/III-4667
=> III-4667 Add validation for virtual locations

src/Place/PlaceTypeResolver.php
- Added a new `PlaceType`: Playground
---
Ticket: https://jira.uitdatabank.be/browse/III-4587
=> III-4587 add playground

app/Event/EventControllerProvider.php, src/Event/ValueObjects/LocationId.php, src/Http/Event/VirtualLocationPolyfillRequestBodyParser.php, tests/Http/Event/ImportEventRequestHandlerTest.php
- Added polyfill of virtual location for online attendance mode
---
Ticket: https://jira.uitdatabank.be/browse/III-4667
=> III-4667 Polyfill virtual location for online attendance mode

src/Http/Event/UpdateAttendanceModeRequestHandler.php, tests/Http/Event/UpdateAttendanceModeRequestHandlerTest.php
- Improved json pointer in error message
---
Ticket: https://jira.uitdatabank.be/browse/III-4677
=> III-4677 Improve json pointer in error message

app/Event/EventControllerProvider.php, src/Event/Event.php, src/Event/UpdateLocationNotSupported.php, src/Http/ApiProblem/ApiProblem.php, src/Http/Docs/Stoplight.php, src/Http/Event/ImportEventRequestHandler.php, src/Http/Event/UpdateLocationRequestHandler.php, tests/Event/EventTest.php, tests/Http/Event/ImportEventRequestHandlerTest.php, tests/Http/Event/UpdateLocationRequestHandlerTest.php
- Update attendance mode when setting real location on online event
- Prevent using virtual location on the location endpoint
---
Ticket: https://jira.uitdatabank.be/browse/III-4678
=> III-4678 Update attendance mode when setting location

app/Event/EventControllerProvider.php, src/Event/Serializer/UpdateOnlineUrlDenormalizer.php, src/Http/Event/UpdateOnlineUrlRequestHandler.php, src/Http/Request/Body/JsonSchemaLocator.php, tests/Http/Event/UpdateOnlineUrlRequestHandlerTest.php
- Added denormalizer `UpdateOnlineUrlDenormalizer` for `UpdateOnlineUrl` command
- Added `UpdateOnlineUrlRequestHandler` to handle the requests from the `PUT online-url` endpoint
---
Ticket: https://jira.uitdatabank.be/browse/III-4456
=> III-4456 update online url endpoint

src/Event/Event.php, tests/Event/CommandHandlers/UpdateAttendanceModeHandlerTest.php, tests/Event/EventCommandHandlerTest.php
- Fixed location updates and attendance mode updates crashing on events imported from XML
---
Ticket: https://jira.uitdatabank.be/browse/III-4702
=> III-4702 Uninitialized attendance mode property

src/Event/Event.php, src/Event/UpdateOnlineUrlNotSupported.php, src/Http/Event/ImportEventRequestHandler.php, src/Http/Event/UpdateOnlineUrlRequestHandler.php, tests/Event/CommandHandlers/UpdateOnlineUrlHandlerTest.php, tests/Event/EventTest.php, tests/Http/Event/ImportEventRequestHandlerTest.php
- Prevent importing offline event with onlineUrl
- Prevent updating the onlineUrl of an offline event
---
Ticket: https://jira.uitdatabank.be/browse/III-4456
=> III-4456 Prevent combination of offline event and onlineUrl

app/Error/WebErrorHandlerProvider.php, src/Http/ApiProblem/ApiProblem.php, src/Http/ApiProblem/ConvertsToApiProblem.php, src/Http/Event/ImportEventRequestHandler.php, src/Http/Place/ImportPlaceRequestHandler.php, src/Offer/InvalidWorkflowStatusTransition.php, src/Offer/Offer.php, tests/Offer/OfferTest.php
- When trying to publish an offer that is already approved, no error gets returned. Only for rejected or deleted.
---
Ticket: https://jira.uitdatabank.be/browse/III-4689
=> III-4689 Cannot publish approved offer

src/Offer/ReadModel/JSONLD/PropertyPolyfillOfferRepository.php, src/Organizer/ReadModel/JSONLD/PropertyPolyfillRepository.php, tests/Offer/ReadModel/JSONLD/PropertyPolyfillOfferRepositoryTest.php, tests/Organizer/ReadModel/JSONLD/PropertyPolyfillRepositoryTest.php
- Fixed duplicate labels polyfill code crashing on null labels by filtering those out first
---
Ticket: https://jira.uitdatabank.be/browse/III-4708
=> III-4708 Fix crash on null value in labels polyfill code

src/EventExport/Format/TabularData/TabularDataEventFormatter.php, tests/EventExport/Format/TabularData/TabularDataEventFormatterTest.php, tests/EventExport/samples/event_with_organizer_with_different_mainLanguage.json
- Fixed undefined index `nl` (and other languages) in organizer name in tabular data formatter for exports
- Fixed undefined property `typicalAgeRange` in tabular data formatter for exports
---
Ticket: https://jira.uitdatabank.be/browse/III-3921
=> III-3921 Undefined index/property in tabular data formatter

src/EventExport/Format/JSONLD/JSONLDEventFormatter.php, src/EventExport/Format/TabularData/TabularDataEventFormatter.php, tests/EventExport/Format/JSONLD/JSONLDEventFormatterTest.php, tests/EventExport/Format/TabularData/TabularDataEventFormatterTest.php, tests/EventExport/samples/event_with_attendance_mode.json
- Add attendance as exportable property with both the mode and url
---
Ticket: https://jira.uitdatabank.be/browse/III-4463
=> III-4463 Make it possible to export attendance (mode + url)

src/Event/ReadModel/History/HistoryProjector.php, tests/Event/ReadModel/History/HistoryProjectorTest.php
- Logged `AttendanceModeUpdated` inside the history of an event
- Logged `OnlineUrlUpdated ` inside the history of an event
- Logged `OnlineUrlDeleted ` inside the history of an event
---
Ticket: https://jira.uitdatabank.be/browse/III-4666
=> III-4666 Expand history with attendance

src/Http/Event/ImportEventRequestHandler.php, src/Http/Offer/OfferValidatingRequestBodyParser.php, src/Http/Place/ImportPlaceRequestHandler.php
- Put common `RequestBodyParser` in an `OfferValidatingRequestBodyParser`
---
Ticket: https://jira.uitdatabank.be/browse/III-4722
=> III-4722 create offer validating request body parser

src/Event/Commands/Moderation/Publish.php, src/Place/Commands/Moderation/Publish.php, tests/Event/CommandHandlers/UpdateAttendanceModeHandlerTest.php, tests/Event/Commands/Moderation/PublishTest.php, tests/Event/EventCommandHandlerTest.php, tests/EventExport/Format/TabularData/TabularDataEventFormatterTest.php, tests/Http/Event/ImportEventRequestHandlerTest.php, tests/Offer/Item/Commands/Moderation/Publish.php, tests/Offer/ReadModel/JSONLD/PropertyPolyfillOfferRepositoryTest.php, tests/Organizer/ReadModel/JSONLD/PropertyPolyfillRepositoryTest.php, tests/Place/Commands/Moderation/PublishTest.php
- Changed `Publish` command permission to `aanbodBewerken`
---
Ticket: https://jira.uitdatabank.be/browse/III-4700
=> III-4700 Change Publish command permission to aanbodBewerken

app/Event/EventJSONLDServiceProvider.php, src/Event/Event.php, src/Event/ReadModel/JSONLD/EventLDProjector.php, src/Event/RelocateEventToCanonicalPlace.php, src/Event/Serializer/AttendanceModeWithLocationDenormalizer.php, src/Event/ValueObjects/LocationId.php, src/Http/Event/AttendanceModeValidatingRequestBodyParser.php, src/Http/Event/ImportEventRequestHandler.php, src/Http/Event/OnlineLocationPolyfillRequestBodyParser.php, src/Http/Event/UpdateAttendanceModeRequestHandler.php, src/Http/Event/UpdateLocationRequestHandler.php, src/Model/Place/ImmutablePlace.php, src/Model/Place/Place.php, src/Model/Serializer/Place/DummyLocationNormalizer.php, src/Model/Serializer/Place/NilLocationNormalizer.php, tests/Event/ReadModel/JSONLD/EventLDProjectorTest.php, tests/Event/ValueObjects/LocationIdTest.php, tests/Http/Event/ImportEventRequestHandlerTest.php, tests/Http/Event/UpdateAttendanceModeRequestHandlerTest.php, tests/Http/Event/UpdateLocationRequestHandlerTest.php, tests/Model/Place/ImmutablePlaceTest.php
- Project `Nil location` with extra properties like address and terms
- Renamed `Online location` to `Nil location`
---
Ticket: https://jira.uitdatabank.be/browse/III-4724
=> III-4724 Project the nil location with extra properties

app/Console/UpdateEventsAttendanceMode.php, bin/udb3.php
- Added CLI command to update attendance mode of events
---
Ticket: https://jira.uitdatabank.be/browse/III-4727
=> III-4727 Add CLI command to update attendance mode of events

app/Place/PlaceJSONLDServiceProvider.php, src/Place/NilLocationEnrichedPlaceRepository.php, tests/Place/NilLocationEnrichedPlaceRepositoryTest.php
- Provided a default projection of the nil location on the places GET endpoint
---
Ticket: https://jira.uitdatabank.be/browse/III-4725
=> III-4725 Provide nil location projection

app/Console/GeocodeEventCommand.php, app/Console/GeocodeOrganizerCommand.php, app/Console/GeocodePlaceCommand.php
- Log the dispatch before the actual command to make sure the UUID gets logged
=> Log the dispatch before the actual command to make sure the UUID gets logged

app/Console/GeocodeEventCommand.php, app/Console/GeocodeOrganizerCommand.php, app/Console/GeocodePlaceCommand.php
- Refactored fallback to use the address in the first language if the main language is missing
---
Ticket: https://jira.uitdatabank.be/browse/III-4747
=> III-4747 Improved address fallback for geocoding

app/Console/GeocodeEventCommand.php, app/Console/GeocodeOrganizerCommand.php, app/Console/GeocodePlaceCommand.php
- Excluded organizers, places and events that don't have an address from the geocode CLI command
---
Ticket: https://jira.uitdatabank.be/browse/III-4746
=> III-4746 Improve geocode command

src/Label/ReadModels/JSON/Repository/Doctrine/DBALReadRepository.php, tests/Label/ReadModels/JSON/Repository/Doctrine/DBALReadRepositoryTest.php
- Used SQL REGEXP to filter labels with special characters
---
Ticket: https://jira.uitdatabank.be/browse/III-4734
=> III-4734 Use SQL REGEXP to filter labels with special characters

src/Model/ValueObject/Taxonomy/Label/LabelName.php, tests/Model/ValueObject/Taxonomy/Label/LabelNameTest.php
- Changed the regex from `LabelName` to accept newlines in labels.
---
Ticket: https://jira.uitdatabank.be/browse/III-4783
=> III-4783 refactor regex labelname

src/Place/Place.php, tests/Place/PlaceTest.php
- Reset facilities to null on UDB2 import
---
Ticket: https://jira.uitdatabank.be/browse/III-4613
=> III-4613 Reset facilities to null on UDB2 import

src/EventExport/Format/HTML/HTMLEventFormatter.php, tests/EventExport/Format/HTML/HTMLEventFormatterTest.php, tests/EventExport/samples/event_with_nil_location.json
- Handle `nil` location as dummy place during export
---
Ticket: https://jira.uitdatabank.be/browse/III-4460
=> III-4460 Handle nil location as dummy place during export

app/Console/AbstractRemoveLabel.php, app/Console/RemoveLabelOffer.php, app/Console/RemoveLabelOrganizer.php, bin/udb3.php, composer.json
- Added a CLI Command to remove invalid labels that cannot be done through the GUI because of special chars. 
---
Ticket: https://jira.uitdatabank.be/browse/III-4787
=> III-4787 cleanup newline labels

app/Event/EventControllerProvider.php, app/Event/EventEditingServiceProvider.php, app/Offer/OfferControllerProvider.php, app/Place/PlaceControllerProvider.php, app/Place/PlaceEditingServiceProvider.php, src/Event/EventEditingServiceInterface.php, src/Http/Offer/UpdateOrganizerRequestHandler.php, src/Http/OfferRestBaseController.php, src/Offer/DefaultOfferEditingService.php, src/Offer/OfferEditingServiceInterface.php, src/Place/PlaceEditingServiceInterface.php, tests/Event/EventEditingServiceTest.php, tests/Http/Offer/UpdateOrganizerRequestHandlerTest.php, tests/Http/OfferRestBaseControllerTest.php, tests/Offer/DefaultOfferEditingServiceTest.php, tests/Place/DefaultPlaceEditingServiceTest.php
- Added an `UpdateOrganizerRequestHandler`
- Legacy Paths for `UpdateOrganizer`
- Test for LegacyPath `UpdateOrganizer`
---
Ticket: https://jira.uitdatabank.be/browse/III-4828
=> III-4828 improve Organizer Id Validation

app/AMQP/AMQPPublisherServiceProvider.php, bootstrap.php
- Used config for AMQP CLI routing
---
Ticket: https://jira.uitdatabank.be/browse/III-4819
=> III-4819 Use config for AMQP CLI routing

app/EventBus/EventBusServiceProvider.php
- Fixed anonymous requests being broken, for example `OPTIONS` requests, due to the EventBus service being instantiated for every requests in the `after()` middleware, which in turn instantiated the command bus (due to some process managers requiring the command bus), which in turn requires a user id.
---
Ticket: https://jira.uitdatabank.be/browse/III-4821
=> III-4821 Fix anonymous requests being broken

web/index.php
- Make trailing slash accepted as a public route
---
Ticket: https://jira.uitdatabank.be/browse/III-4844
=> III-4844 Allow trailing slash as public route

src/Event/ReadModel/Relations/Doctrine/DBALEventRelationsRepository.php
- Fixed TypeError introduced in III-4822
---
Ticket: https://jira.uitdatabank.be/browse/III-4853
=> III-4853 Fix type error introduced in III-4822

composer.lock, src/Model/Serializer/ValueObject/Price/PriceInfoDenormalizer.php, src/Offer/Offer.php, tests/Event/EventTest.php
- tests for update PriceInfo with UiTPAS
- Ignore UiTPAS Prices in `PriceInfoDenormalizer`
- Include check onUiTPAS Prices in updatePriceInfo of Aggregate
---
Ticket: https://jira.uitdatabank.be/browse/III-4815
=> III-4815 ignore prices with category uitpas

src/Http/Offer/PatchOfferRequestHandler.php, tests/Http/Offer/PatchOfferRequestHandlerTest.php
- Fixed crashing tests because body content was empty
=> Fix empty body stream

app/Place/PlaceControllerProvider.php
- Use placeId instead of cdbid
---
Ticket: https://jira.uitdatabank.be/browse/III-4866
=> Fix/use placeId instead of cdbid

web/index.php
- Removed obsolete route to server swagger file.
---
Ticket: https://jira.uitdatabank.be/browse/III-4887
=> III-4887 Remove obsolete route to server swagger file.

app/UiTPASService/UiTPASServiceEventControllerProvider.php, app/UiTPASService/UiTPASServiceLabelsControllerProvider.php, app/UiTPASService/UiTPASServiceOrganizerControllerProvider.php, src/UiTPASService/Controller/GetUiTPASLabelsRequestHandler.php
- Add new GetUiTPASLabelsRequestHandler
- Make the UiTPAS providers also implement `ServiceProviderInterface`
---
Ticket: https://jira.uitdatabank.be/browse/III-4908
=> III-4908 Refactor UiTPAS service labels controller provider

app/Authentication/AuthServiceProvider.php
- Fixed `calsum` endpoint by making it public again
---
Note: I tested this manually but will also add some acceptance tests for this if possible.
=> Fix calsum endpoint

bootstrap.php
- Fixed bootstrapping `UiTPASServiceEventControllerProvider`
=> Fix bootstrapping `UiTPASServiceEventControllerProvider`

src/Http/Media/UploadMediaRequestHandler.php, src/Media/ImageUploaderInterface.php, src/Media/ImageUploaderService.php, tests/Http/Media/UploadMediaRequestHandlerTest.php, tests/Media/ImageUploaderServiceTest.php
- Fixed merge issue
---
Ticket: https://jira.uitdatabank.be/browse/III-4891
=> III-4891 Fixed merge issue

bootstrap.php
- Registered `UiTPASServiceOrganizerControllerProvider`
---
Ticket: https://jira.uitdatabank.be/browse/III-4934
=> III-4934 Register `UiTPASServiceOrganizerControllerProvider`

app/UiTPASService/UiTPASServiceOrganizerControllerProvider.php
- Registered `GetCardSystemsFromOrganizerRequestHandler`
---
Ticket: https://jira.uitdatabank.be/browse/III-4934
=> III-4934 Register `GetCardSystemsFromOrganizerRequestHandler`

src/UiTPASService/Controller/GetCardSystemsFromOrganizerRequestHandler.php, tests/UiTPASService/Controller/GetCardSystemsFromOrganizerRequestHandlerTest.php
- Use getCardSystemsForOrganizer
---
Ticket: https://jira.uitdatabank.be/browse/III-4940
=> Use getCardSystemsForOrganizer

app/Event/EventJSONLDServiceProvider.php, app/Place/PlaceJSONLDServiceProvider.php, src/Cdb/CdbXmlPriceInfoParser.php, src/Event/Event.php, src/Offer/ReadModel/JSONLD/CdbXMLItemBaseImporter.php, tests/Event/EventTest.php, tests/Event/ReadModel/JSONLD/CdbXMLImporterTest.php, tests/Event/ReadModel/JSONLD/EventLDProjectorTest.php, tests/Event/samples/event_with_price_value_and_description.cdbxml.xml, tests/Event/samples/event_with_price_value_and_formatted_description.cdbxml.xml, tests/Place/ReadModel/JSONLD/CdbXMLImporterTest.php, tests/Place/ReadModel/JSONLD/PlaceLDProjectorTest.php
- Added new `CdbXmlPriceInfoParser` to create `PriceInfo` from CDB detail
- Stored `PriceInfo` on import from and update from UDB2
---
Ticket: https://jira.uitdatabank.be/browse/III-4898
=> III-4898 Update Event aggregate state with price info from UDB2

src/Http/ApiProblem/ApiProblem.php, src/Http/Request/RouteParameters.php, src/Http/Role/AddLabelToRoleRequestHandler.php, src/Http/Role/AddPermissionToRoleRequestHandler.php, src/Http/Role/AddRoleToUserRequestHandler.php, src/Http/Role/DeleteRoleRequestHandler.php, src/Http/Role/GetLabelIdFromRouteParameters.php, src/Http/Role/RemoveLabelFromRoleRequestHandler.php, src/Http/Role/RemovePermissionFromRoleRequestHandler.php, src/Http/Role/RemoveRoleFromUserRequestHandler.php, src/Role/Commands/AddUser.php, src/Role/Commands/RemoveUser.php, src/Role/Services/DefaultRoleEditingService.php, tests/Http/ApiProblem/ApiProblemTest.php, tests/Http/Role/AddLabelToRoleRequestHandlerTest.php, tests/Http/Role/AddPermissionToRoleRequestHandlerTest.php, tests/Http/Role/AddRoleToUserRequestHandlerTest.php, tests/Http/Role/DeleteRoleRequestHandlerTest.php, tests/Http/Role/RemoveLabelFromRoleRequestHandlerTest.php, tests/Http/Role/RemovePermissionFromRoleRequestHandlerTest.php, tests/Http/Role/RemoveRoleFromUserRequestHandlerTest.php, tests/Role/CommandHandlerTest.php, tests/Role/Commands/AddUserTest.php, tests/Role/Commands/RemoveUserTest.php
- Added new request handler `AddLabelToRoleRequestHandler`
- Added new request handler `AddPermissionToRoleRequestHandler`
- Added new request handler `AddRoleToUserRequestHandler`
- Added new request handler `DeleteRoleRequestHandler`
- Added new request handler `RemoveLabelFromRoleRequestHandler`
- Added new request handler `RemovePermissionFromRoleRequestHandler`
- Added new request handler `RemoveRoleFromUserRequestHandler`
- `AddUser` and `RemoveUser` command now expect string iso `StringLiteral` when constructing
---
Ticket: https://jira.uitdatabank.be/browse/III-4882
=> III-4882 refactor edit role rest controller (2/3)

migrations.php, migrations.yml
- replaced `migrations.yml` with `migrations.php`
-  errors while running migrations
---
Ticket: https://jira.uitdatabank.be/browse/III-4992
=> III-4992 replace migrations.yml

app/Proxy/ProxyRequestHandlerServiceProvider.php
- Fixed broken `ProxyRequestHandler` service definition (from https://jira.uitdatabank.be/browse/III-3888 / #1163)
---
Ticket: https://jira.uitdatabank.be/browse/III-3888
=> Fix broken ProxyRequestHandler service definition

app/Authentication/AuthServiceProvider.php, app/Silex/Authentication/AuthServiceProvider.php, bootstrap.php
- Refactored `AuthServiceProvider` &  to League service providers 
---
Ticket: https://jira.uitdatabank.be/browse/III-4964
=> III-4964 psr11 Authentication

app/Jobs/JobsServiceProvider.php, app/Silex/Jobs/JobsServiceProvider.php, bootstrap.php
- Make `JobsServiceProvider` PSR-11 Compliant
- Move `JobsServiceProvider` outside SilexApp Folder
---
Ticket: https://jira.uitdatabank.be/browse/III-4974
=> III-4974 psr11 jobs

app/Curators/CuratorsServiceProvider.php, app/Silex/Curators/CuratorsServiceProvider.php, bootstrap.php
- `CuratorsServiceProvider` is now shared via League container
---
Ticket: https://jira.uitdatabank.be/browse/III-4967
=> III-4967 Curators service provider

app/Export/ExportServiceProvider.php, app/Silex/Export/ExportServiceProvider.php, bootstrap.php
- `ExportServiceProvider` PSR-11 compliant
---
Ticket: https://jira.uitdatabank.be/browse/III-4972
=> III-4972 ExportServiceProvider PSR-11 compliant

tests/Http/Media/UploadMediaRequestHandlerTest.php
- Fixed typo in test name as spotted by @LucWollants  in https://github.com/cultuurnet/udb3-silex/pull/1197#discussion_r991992581
=> Fix typo in test name

readme.md
- Changed mention of `udb3-silex` name with something more informative
---
Ticket: https://jira.uitdatabank.be/browse/III-3708
=> III-3708 Remove mention of old udb3-silex name in README

app/Console/Command/ProcessDuplicatePlaces.php, src/Place/Canonical/DBALDuplicatePlaceRepository.php
- Added start cluster id option to the process cluster command
=> Add start cluster id option to the process cluster command

.github/CODEOWNERS, .gitignore, Gemfile, Gemfile.lock, Jenkinsfile, Rakefile, lib/tasks/build.rake, lib/tasks/build_artifact.rake
- Jenkinsfile
- Build tasks
- Code owners for build/deployment related files
---
Ticket: https://jira.uitdatabank.be/browse/III-5070
=> Jenkinsfile and rake tasks for new UDB3 backend pipeline

Jenkinsfile
- Jenkins agent label expressions
---
Ticket: https://jira.uitdatabank.be/browse/III-5070
=> Fix Jenkins agent label expressions

composer.json, composer.lock, src/Http/Deserializer/Offer/UpdateContactPointDenormalizer.php, src/Http/Offer/LegacyContactPointRequestBodyParser.php, src/Http/Offer/UpdateContactPointRequestHandler.php, src/Http/Request/Body/JsonSchemaLocator.php, tests/Http/Offer/UpdateContactPointRequestHandlerTest.php
- `UpdateContactPointRequestHandler` now uses JSON schema validation to validate the request.
---
Ticket: https://jira.uitdatabank.be/browse/III-4263
=> III-4263 event contact point

composer.json, composer.lock, src/Http/Deserializer/Offer/UpdateTypicalAgeRangeDenormalizer.php, src/Http/Offer/UpdateTypicalAgeRangeRequestHandler.php, src/Http/Request/Body/JsonSchemaLocator.php, src/Offer/Commands/AbstractUpdateTypicalAgeRange.php, tests/Event/Commands/UpdateTypicalAgeRangeTest.php, tests/Http/Event/ImportEventRequestHandlerTest.php, tests/Http/Offer/UpdateTypicalAgeRangeRequestHandlerTest.php, tests/Offer/Commands/AbstractUpdateTypicalAgeRangeTest.php
- `UpdateTypicalAgeRangeRequestHandler` now uses JSON schema validation.
- `AbstractUpdateTypicalAgeRange` improved typehinting
---
Ticket: https://jira.uitdatabank.be/browse/III-4269
=> III-4269 offer typical age range

docker/Makefile, docker/php/Dockerfile
- extra dependencies for docker container so platform-reqs don't have to be ignored
- use same composer version as on production
- use make install without ignoring platform-reqs
---
=> Docker improvements

composer.lock, tests/Http/Offer/GetCalendarSummaryRequestHandlerTest.php
- Updated to calendar summary 4.0.1
---
Ticket: https://jira.uitdatabank.be/browse/III-5110
=> III-5110 update to calendar summary 4.0.1

composer.json, composer.lock, tests/EventExport/CalendarSummary/CalendarSummaryWithFormatterRepositoryTest.php, tests/Http/Offer/GetCalendarSummaryRequestHandlerTest.php
- Upgraded to calendar summary 4.0
---
Ticket: https://jira.uitdatabank.be/browse/III-5107
=> III-5107 Upgrade to calendar summary 4.0

composer.json, composer.lock, src/Http/Offer/UpdateDescriptionRequestHandler.php, src/Offer/Serializers/DescriptionDenormalizer.php, tests/Http/Offer/UpdateDescriptionRequestHandlerTest.php
- It's now possible again to remove a description from an offer
---
Ticket: https://jira.uitdatabank.be/browse/III-4251
=> Fix empty offer description

src/Contributor/ContributorRepository.php, src/Contributor/DbalContributorRepository.php, src/Offer/CommandHandlers/UpdateContributorsHandler.php, src/Organizer/CommandHandler/UpdateContributorsHandler.php, tests/Contributor/ContributorRepositoryTest.php, tests/Contributor/DbalContributorRepositoryTest.php
- renamed `overwriteContributors()` to `updateContributors()`
- renamed `ContributorRepositoryTest()` to `DbalContributorRepositoryTest`
---
Ticket: https://jira.uitdatabank.be/browse/III-5334
=> III-5334 Consistent naming

Makefile, docker.md
- Added `make bash` command to open terminal inside container
- Point to location of key files
=> Improve docker setup

app/Console/Command/ReplayCommand.php
- Added confirmation question before starting a replay
=> Ask for replay confirmation

src/Place/Events/MajorInfoUpdated.php, tests/Place/Events/MajorInfoUpdatedTest.php
- Implemented `ConvertsToGranularEvents` on `MajorInfoUpdated` in the `Place` namespace (follow-up to #1270)
---
Ticket: https://jira.uitdatabank.be/browse/III-5366
=> III-5366 Split up MajorInfoUpdated (Place)

docker-compose.yml, docker.md, docker/php/Dockerfile
- Switched to Apache2 container
=> Switch to Apache2 container

docker-compose.yml, docker.md
- Setup Docker RabbitMQ container
=> Setup Docker RabbitMQ container

src/Place/ReadModel/RDF/RdfProjector.php, src/RDF/InMemoryGraphRepository.php
- Removed unused method
- Fixed slightly wrong wording in comment
---
Ticket: https://jira.uitdatabank.be/browse/III-5356
=> III-5356 Fix comment & remove unused method

app/Event/EventJSONLDServiceProvider.php, src/Event/ReadModel/JSONLD/EventLDProjector.php, src/Offer/ReadModel/JSONLD/OfferLDProjector.php
- Log error message when modified does not match expected value after updating a projection
---
Ticket: https://jira.uitdatabank.be/browse/III-5281
=> III-5281 Log error message when modified does not match

app/Event/EventJSONLDServiceProvider.php, src/Event/ReadModel/JSONLD/EventLDProjector.php, src/Offer/ReadModel/JSONLD/OfferLDProjector.php
- Revert logging modified
---
Ticket: https://jira.uitdatabank.be/browse/III-5436
=> III-5436 Revert logging modified

app/Console/Command/FindOutOfSyncProjections.php, app/Event/EventJSONLDServiceProvider.php, src/Doctrine/ReadModel/CacheDocumentRepository.php
- Added error log for out of sync Redis documents
---
Ticket: https://jira.uitdatabank.be/browse/III-5281
=> III-5281 Log out of sync redis docs

src/Place/Events/PlaceFromUDB2.php, tests/Place/Events/PlaceImportedFromUDB2Test.php, tests/Place/actor3.3.xml, tests/Place/actor_with_root_node.xml
- tests to handle various formats of `cdbXml`
-  Refactored trait `PlaceFromUDB2` to handle various formats of `cdbXml`
- It handles now both `cdbxml 3.2` & `cdbXml 3.3` with or without a `cdbXml` root Node
---
Ticket: https://jira.uitdatabank.be/browse/III-5351
=> III-5351 Convert Place*FromUDB2 to smaller events - bugfix various cdbxml Formats

app/Console/Command/ReplayCommand.php
- Added a `force`-parameter for the replay command(needed for the Jenkins-job)
---
Ticket: https://jira.uitdatabank.be/browse/III-5475
=> III-5475 Add force parameter for ReplayCommand

app/Place/PlaceRdfServiceProvider.php, app/RDF/RdfServiceProvider.php, tests/Place/ReadModel/RDF/RdfProjectorTest.php, tests/Place/ReadModel/RDF/data/address-translated.ttl, tests/Place/ReadModel/RDF/data/address-updated.ttl, tests/Place/ReadModel/RDF/data/place-created.ttl, tests/Place/ReadModel/RDF/data/title-translated.ttl, tests/Place/ReadModel/RDF/data/title-updated-and-translated.ttl, tests/Place/ReadModel/RDF/data/title-updated.ttl
- Made the base URI of places in RDF data configurable
---
Ticket: https://jira.uitdatabank.be/browse/III-5477
See https://github.com/cultuurnet/udb3-vagrant/pull/154 for the config changes for the local setup
=> III-5477 Make base URI of places in RDF data configurable

docker-compose.yml, docker.md
- Added support for fuseki through custom docker container
=> Setup fuseki with docker

src/Place/ReadModel/RDF/RdfProjector.php, src/RDF/RdfNamespaces.php, tests/Place/ReadModel/RDF/RdfProjectorTest.php, tests/Place/ReadModel/RDF/data/geo-coordinates-updated.ttl
- Added handle method for `GeoCoordinatesUpdated` inside the `RDFProjector` of places
---
Ticket: https://jira.uitdatabank.be/browse/III-5355
=> III-5355 Project `GeoCoordinatesUpdated` to RDF

tests/Place/ReadModel/RDF/data/geo-coordinates-updated.ttl
- Fixed unit tests after name changes in fuseki stores
=> Fix unit tests after name changes in fuseki stores

composer.json, composer.lock
- Reset udb3-json-schemas dependency to main branch
=> Reset udb3-json-schemas dependency to main branch

app/Event/EventJSONLDServiceProvider.php, src/Doctrine/ReadModel/CacheDocumentRepository.php
- Added retry when saving to Redis results in different data
- Config updated:
- For UDB3 Vagrant: https://github.com/cultuurnet/udb3-vagrant/pull/156
- For appconfig: https://github.com/cultuurnet/appconfig/pull/324
---
Ticket: https://jira.uitdatabank.be/browse/III-5281
=> III-5281 Add retry when saving to Redis results in different data

src/Place/ReadModel/RDF/RdfProjector.php, tests/Place/ReadModel/RDF/data/geo-coordinates-updated.ttl
- Removed coordinates in `geosparql:asWKT` format
---
Ticket: https://jira.uitdatabank.be/browse/III-5521
=> III-5521 Remove coordinates in geosparql:asWKT format

src/Place/ReadModel/RDF/RdfProjector.php, tests/Place/ReadModel/RDF/data/address-translated.ttl, tests/Place/ReadModel/RDF/data/address-updated.ttl, tests/Place/ReadModel/RDF/data/geo-coordinates-updated.ttl, tests/Place/ReadModel/RDF/data/place-created.ttl, tests/Place/ReadModel/RDF/data/title-translated.ttl, tests/Place/ReadModel/RDF/data/title-updated-and-translated.ttl, tests/Place/ReadModel/RDF/data/title-updated.ttl
- Changed `locn:geographicName` to `locn:locatorName`
---
Ticket: https://jira.uitdatabank.be/browse/III-5516
=> III-5516 Change `locn:geographicName` to `locn:locatorName`

src/Place/ReadModel/RDF/RdfProjector.php, tests/Place/ReadModel/RDF/data/place-created-with-publication-date.ttl, tests/Place/ReadModel/RDF/data/place-published.ttl
- Added `udb:availableFrom` predicate when a place is published
---
Ticket: https://jira.uitdatabank.be/browse/III-5509
Note: This branches from #1317 ⚠️ Please review that first 🙏
=> III-5509 Add `udb:availableFrom` predicate

app/Place/PlaceRdfServiceProvider.php, src/Address/CachingAddressParser.php, tests/Address/CachingAddressParserTest.php
- Added `AddressParser` decorator that caches previously parsed addresses
---
Ticket: https://jira.uitdatabank.be/browse/III-5489
=> III-5489 Cache GeoPunt API results

app/Event/EventRdfServiceProvider.php, src/Event/ReadModel/RDF/RdfProjector.php, src/RDF/RdfNamespaces.php, tests/Event/ReadModel/RDF/RdfProjectorTest.php, tests/Event/ReadModel/RDF/data/approved.ttl, tests/Event/ReadModel/RDF/data/created.ttl, tests/Event/ReadModel/RDF/data/deleted.ttl, tests/Event/ReadModel/RDF/data/description-translated.ttl, tests/Event/ReadModel/RDF/data/description-updated.ttl, tests/Event/ReadModel/RDF/data/location-updated.ttl, tests/Event/ReadModel/RDF/data/published.ttl, tests/Event/ReadModel/RDF/data/rejected.ttl, tests/Event/ReadModel/RDF/data/title-translated.ttl, tests/Event/ReadModel/RDF/data/title-updated-and-translated.ttl, tests/Event/ReadModel/RDF/data/title-updated.ttl
- Added handle method for `locationUpdated` on events
---
Ticket: https://jira.uitdatabank.be/browse/III-5362
=> III-5362 Handle `locationUpdated` on events

app/Event/EventRdfServiceProvider.php, src/Event/ReadModel/RDF/RdfProjector.php, tests/Event/ReadModel/RDF/RdfProjectorTest.php, tests/Event/ReadModel/RDF/data/approved.ttl, tests/Event/ReadModel/RDF/data/calendar-updated-multiple.ttl, tests/Event/ReadModel/RDF/data/calendar-updated-periodic.ttl, tests/Event/ReadModel/RDF/data/calendar-updated-single.ttl, tests/Event/ReadModel/RDF/data/created-with-calendar-multiple.ttl, tests/Event/ReadModel/RDF/data/created-with-calendar-periodic.ttl, tests/Event/ReadModel/RDF/data/created-with-calendar-single.ttl, tests/Event/ReadModel/RDF/data/created.ttl, tests/Event/ReadModel/RDF/data/deleted.ttl, tests/Event/ReadModel/RDF/data/description-translated.ttl, tests/Event/ReadModel/RDF/data/description-updated.ttl, tests/Event/ReadModel/RDF/data/location-updated.ttl, tests/Event/ReadModel/RDF/data/published.ttl, tests/Event/ReadModel/RDF/data/rejected.ttl, tests/Event/ReadModel/RDF/data/title-translated.ttl, tests/Event/ReadModel/RDF/data/title-updated-and-translated.ttl, tests/Event/ReadModel/RDF/data/title-updated.ttl, tests/Event/ReadModel/RDF/data/type-updated.ttl, tests/Event/ReadModel/RDF/data/various-calendar-updated.ttl
- Added handler for `TypeUpdated` on event which adds an URL pointing to the taxonomy terms on the RDF projection
---
Ticket: https://jira.uitdatabank.be/browse/III-5360
=> III-5360 Handle `TypeUpdated` on event

src/Event/ReadModel/RDF/RdfProjector.php, tests/Event/ReadModel/RDF/data/calendar-updated-multiple.ttl, tests/Event/ReadModel/RDF/data/calendar-updated-periodic.ttl, tests/Event/ReadModel/RDF/data/calendar-updated-single.ttl, tests/Event/ReadModel/RDF/data/created-with-calendar-multiple.ttl, tests/Event/ReadModel/RDF/data/created-with-calendar-periodic.ttl, tests/Event/ReadModel/RDF/data/created-with-calendar-single.ttl, tests/Event/ReadModel/RDF/data/various-calendar-updated.ttl
- Fixed cidoc URIs by using the full name instead of the id
---
Ticket: https://jira.uitdatabank.be/browse/III-5563
=> III-5563 Fix cidoc URIs

src/Event/ReadModel/RDF/InMemoryLocationIdRepository.php, src/Event/ReadModel/RDF/RdfProjector.php, src/RDF/RdfNamespaces.php, tests/Event/ReadModel/RDF/RdfProjectorTest.php, tests/Event/ReadModel/RDF/data/approved.ttl, tests/Event/ReadModel/RDF/data/calendar-updated-multiple.ttl, tests/Event/ReadModel/RDF/data/calendar-updated-periodic-without-event-created.ttl, tests/Event/ReadModel/RDF/data/calendar-updated-periodic.ttl, tests/Event/ReadModel/RDF/data/calendar-updated-permanent.ttl, tests/Event/ReadModel/RDF/data/calendar-updated-single.ttl, tests/Event/ReadModel/RDF/data/created-with-calendar-multiple.ttl, tests/Event/ReadModel/RDF/data/created-with-calendar-periodic.ttl, tests/Event/ReadModel/RDF/data/created-with-calendar-single.ttl, tests/Event/ReadModel/RDF/data/created.ttl, tests/Event/ReadModel/RDF/data/deleted.ttl, tests/Event/ReadModel/RDF/data/description-translated.ttl, tests/Event/ReadModel/RDF/data/description-updated.ttl, tests/Event/ReadModel/RDF/data/location-updated-on-calendar-single.ttl, tests/Event/ReadModel/RDF/data/location-updated.ttl, tests/Event/ReadModel/RDF/data/published.ttl, tests/Event/ReadModel/RDF/data/rejected.ttl, tests/Event/ReadModel/RDF/data/title-translated.ttl, tests/Event/ReadModel/RDF/data/title-updated-and-translated.ttl, tests/Event/ReadModel/RDF/data/title-updated.ttl, tests/Event/ReadModel/RDF/data/type-updated.ttl, tests/Event/ReadModel/RDF/data/various-calendar-updated.ttl
- Make sure `permanent` calendar has `prov:atLocation` but no `cp:ruimtetijd`
- Make sure `single`, `multiple` and `periodic` have `cp:ruimtetijd` but no `prov:atLocation`
---
Ticket: https://jira.uitdatabank.be/browse/III-5566
=> III-5566 Fix prov:atLocation

src/Place/Events/PlaceFromUDB2.php, tests/Place/Events/PlaceImportedFromUDB2Test.php, tests/Place/actor_without_address.xml
- `actor_without_address.xml`: `CdbXml`-testfile for place without `address`
- test for Places without `address`
- `PlaceFromUDB2`: Added check if `CdbXml` contains a `PhysicalAddress`
---
Ticket: https://jira.uitdatabank.be/browse/III-5351
=> III-5351 bugfix xmlplace without address

Makefile, app/Console/Command/CopyToFuseki.php, app/Console/ConsoleServiceProvider.php, app/Event/EventRdfServiceProvider.php, app/Place/PlaceRdfServiceProvider.php, src/RDF/CacheGraphRepository.php, tests/RDF/CacheGraphRepositoryTest.php, tests/RDF/event.ttl
- Added GraphStore inside Cache
- Added command to copy from Cache to Fuseki
- Added extra makefile command `make test-filter filter=<filter>` to filter on a test
---
Ticket: https://jira.uitdatabank.be/browse/III-5593
=> III-5593 Create GraphStore inside Cache

src/Event/Events/DummyLocationUpdated.php, src/Event/Events/EventFromUDB2.php, src/Event/Events/EventImportedFromUDB2.php, src/Event/Events/EventUpdatedFromUDB2.php, src/Event/ValueObjects/DummyLocation.php, tests/Event/Events/EventImportedFromUDB2Test.php, tests/Event/Events/EventUpdatedFromUDB2Test.php
- Refactored `DummyLocationUpdated` to concrete event
---
Ticket: https://jira.uitdatabank.be/browse/III-5545
=> III-5545 Refactor `DummyLocationUpdated` to concrete event

app/Migrations/Version20230526075219.php
- Add Migration to add `excluded` column to table `labels_json`.
- Add `index` to `excluded` column.
---
=> III-5613: Add migration to add `excluded` column to `Labels`

app/Event/EventJSONLDServiceProvider.php, app/Place/PlaceJSONLDServiceProvider.php
- Injected broadcasting repo into JSON projector to avoid the overhead of decorators used for polyfill. These decorators are not needed when updating JSON projections for places and events.
---
Ticket: https://jira.uitdatabank.be/browse/III-5614
=> III-5614 Inject broadcasting repo in json projector

app/Console/Command/BulkExcludeLabel.php, app/Console/Command/ExcludeLabel.php, app/Console/Command/IncludeLabel.php, app/Console/ConsoleServiceProvider.php
=> III-5613 CLI Commands Include/Exclude Labels

src/Offer/ReadModel/JSONLD/OfferLDProjector.php
- Prevent logging playhead mismatch error when the last retry fixed it
---
Ticket: https://jira.uitdatabank.be/browse/III-5614
=> III-5614 Prevent logging playhead mismatch error when the last retry fixed it

app/Event/EventRdfServiceProvider.php, app/EventBus/EventBusServiceProvider.php, src/Event/ReadModel/RDF/GranularRdfProjector.php, src/Event/ReadModel/RDF/RdfProjector.php, src/Place/ReadModel/RDF/RdfProjector.php, src/RDF/Editor/GraphEditor.php, src/RDF/Editor/WorkflowStatusEditor.php, tests/Event/ReadModel/RDF/GranularRdfProjectorTest.php, tests/Event/ReadModel/RDF/RdfProjectorTest.php, tests/Event/ReadModel/RDF/ttl/event-with-calendar-multiple.ttl, tests/Event/ReadModel/RDF/ttl/event-with-calendar-periodic.ttl, tests/Event/ReadModel/RDF/ttl/event-with-calendar-single.ttl, tests/Event/ReadModel/RDF/ttl/event-with-description.ttl, tests/Event/ReadModel/RDF/ttl/event-with-publication-date.ttl, tests/Event/ReadModel/RDF/ttl/event-with-status-approved.ttl, tests/Event/ReadModel/RDF/ttl/event-with-status-deleted.ttl, tests/Event/ReadModel/RDF/ttl/event-with-status-ready-for-validation.ttl, tests/Event/ReadModel/RDF/ttl/event-with-status-rejected.ttl, tests/Event/ReadModel/RDF/ttl/event-with-translations.ttl, tests/Event/ReadModel/RDF/ttl/event.ttl
- Renamed `RdfProjector` to `GranularRdfProjector`
---
Ticket: https://jira.uitdatabank.be/browse/III-5629
=> III-5629 Refactor event RDF projector to use JSON

src/Doctrine/ReadModel/CacheDocumentRepository.php, src/Offer/ReadModel/JSONLD/OfferLDProjector.php
- Removed noisy happy path logging which is no longer needed now that performance and out-of-sync issue are more stable
=> Removed noisy logging

app/Migrations/Version20230614094123.php, app/Migrations/Version20230614094352.php, app/Migrations/Version20230614094517.php, app/Migrations/Version20230614094817.php
- Add index on `user_id` inside the `event_permission_readmodel` table
- Add index on `user_id` inside the `place_permission_readmodel` table
- Add index on `user_id` inside the `organizer_permission_readmodel` table
- Add index on `email` inside the `contributor_relations` table
---
Ticket: https://jira.uitdatabank.be/browse/III-5662
=> III-5662 Add indexes to improve performance

bin/udb3.php, composer.json, composer.lock
- Upgrade package `http/httplug`
- Replaced `renderException` with `renderThrowable`
=> Hotfix for http/httplug

src/Label/ReadModels/JSON/Projector.php, src/Label/ReadModels/JSON/Repository/BroadcastingWriteRepositoryDecorator.php, src/Label/ReadModels/JSON/Repository/Doctrine/DBALReadRepository.php, src/Label/ReadModels/JSON/Repository/Doctrine/DBALWriteRepository.php, src/Label/ReadModels/JSON/Repository/Entity.php, src/Label/ReadModels/JSON/Repository/WriteRepositoryInterface.php, tests/Label/ReadModels/JSON/ProjectorTest.php, tests/Label/ReadModels/JSON/Repository/BroadcastingWriteRepositoryDecoratorTest.php, tests/Label/ReadModels/JSON/Repository/Doctrine/BaseDBALRepositoryTest.php, tests/Label/ReadModels/JSON/Repository/Doctrine/DBALReadRepositoryTest.php, tests/Label/ReadModels/JSON/Repository/Doctrine/DBALWriteRepositoryTest.php, tests/Label/ReadModels/JSON/Repository/EntityTest.php
- Removed count concept from `Labels`
- Ignore the last commit, this was committed on the wrong branch. It should have been committed on https://github.com/cultuurnet/udb3-backend/tree/III-5685-boyscouting
---
Ticket: https://jira.uitdatabank.be/browse/III-5685
=> III-5685 Remove count concept from Labels

features/image/create.feature, features/image/get.feature
- Added the acceptance tests for Image
---
=> III-5648 Port image features

features/Steps/ResponseSteps.php, features/production/create.feature, features/production/merge.feature, features/production/skip.feature, features/production/update.feature
- Added acceptance tests for the production features
---
=> III-5648 Port production features

features/uitpas/events.feature, features/uitpas/organizers.feature
- Added acceptance tests for UiTPAS features
---
=> III-5648 port uitpas features

src/Label/ReadModels/AbstractProjector.php
- Fixed type hint Label projector
=> Fixed type hint Label projector

features/Steps/AuthorizationSteps.php, features/Steps/CuratorSteps.php, features/Steps/EventSteps.php, features/Steps/LabelSteps.php, features/Steps/OrganizerSteps.php, features/Steps/PlaceSteps.php, features/Steps/RequestSteps.php, features/Support/HttpClient.php, features/auth/client-access-token.feature, features/auth/jwt-provider-v2.feature, features/auth/user-access-token.feature
- Added acceptance tests for the auth features
---
=> III-5648 Port auth features

features/users/permissions.feature
- Added acceptance tests for the user features
---
=> III-5648 Port users features

features/State/ResponseState.php, features/Steps/ResponseSteps.php, features/saved_searches/create.feature, features/saved_searches/get.feature
- Added acceptance tests for saved searches
---
=> III-5648 Port saved searches features

features/Bootstrap/FeatureContext.php, features/Steps/RequestSteps.php, features/Steps/ResponseSteps.php, features/Steps/RoleSteps.php, features/Steps/UtilitySteps.php, features/place/rdf.feature, features/place/workflow-status.feature, features/role/create.feature, features/role/delete.feature, features/role/get.feature, features/role/permissions.feature, features/role/update.feature, features/role/users.feature, features/saved_searches/get.feature
- Added acceptance tests for role features
---
=> III-5648 Port role features

features/Bootstrap/FeatureContext.php, features/State/RequestState.php, features/State/ResponseState.php, features/State/VariableState.php, features/Steps/AuthorizationSteps.php, features/Steps/EventSteps.php, features/Steps/RequestSteps.php, features/Steps/UtilitySteps.php, features/Support/HttpClient.php, features/search/auth.feature, features/search/contributors.feature, features/search/search-proxy.feature
- Added acceptance test for the search features
- The wait for the contributors is still hardcoded because this is not the first indexation
---
=> III-5648 port search features

features/data/events/rondleiding-citadel.json, features/data/places/citadel.json, features/data/places/hemmekes.json, features/data/places/molenhuis-updated-name.json, features/data/places/molenhuis.json, features/permission/client-permissions.feature, features/permission/permissions.feature
- Added acceptance tests for the permission features
- Some tests are still failing because the user roles are not created
---
=> III-5648 Port permission features

src/Address/GeopuntAddressParser.php, tests/Address/GeopuntAddressParserTest.php
- Old URL is now replaced by new one in both source and tests. Functional test on the new URL provides expected output
=> The URL https://loc.geopunt.be has been removed and replaced by https://geo.api.vlaanderen.be/geolocation

composer.lock, features/event/videos.feature, features/place/videos.feature, tests/Http/Event/ImportEventRequestHandlerTest.php, tests/Http/Offer/AddVideoRequestHandlerTest.php
- New e2e test to add a video to an event
- New e2e test to add youtube short and vimeo videos to a place
- Updated matching unit test for new regex
---
Ticket: https://jira.uitdatabank.be/browse/III-5624
=> added tests for new video formats

src/Model/Serializer/Offer/OfferDenormalizer.php, tests/Model/Serializer/Event/EventDenormalizerTest.php
- Added `nl` as the default main language when normalizing an offer
---
Ticket: https://jira.uitdatabank.be/browse/III-5752
=> Add default main language `nl`

.github/CODEOWNERS
- Added @grubolsch as code owner
=> Add @grubolsch as code owner

src/Model/Serializer/Offer/OfferDenormalizer.php, tests/Model/Serializer/Event/EventDenormalizerTest.php
- Handled invalid organizer references
---
Ticket: https://jira.uitdatabank.be/browse/III-5753
=> Handle invalid organizer references

app/RDF/RdfServiceProvider.php, src/Address/GeopuntAddressParser.php, tests/Address/GeopuntAddressParserTest.php
Made apiUrlV4 configurable for the GeopuntAddressParser
Twin PR of https://github.com/cultuurnet/appconfig/pull/393 (config change)
---
Ticket: https://jira.uitdatabank.be/browse/III-5748
=> Made apiUrlV4 configurable for the GeopuntAddressParser

app/Place/PlaceRdfServiceProvider.php, src/Place/ReadModel/RDF/RdfProjector.php, tests/Place/ReadModel/RDF/RdfProjectorTest.php, tests/Place/ReadModel/RDF/ttl/place-with-coordinates.ttl, tests/Place/ReadModel/RDF/ttl/place-with-publication-date.ttl, tests/Place/ReadModel/RDF/ttl/place-with-status-approved.ttl, tests/Place/ReadModel/RDF/ttl/place-with-status-deleted.ttl, tests/Place/ReadModel/RDF/ttl/place-with-status-ready-for-validation.ttl, tests/Place/ReadModel/RDF/ttl/place-with-status-rejected.ttl, tests/Place/ReadModel/RDF/ttl/place-with-translations.ttl, tests/Place/ReadModel/RDF/ttl/place.ttl
- Projected location type in RDF projector 
---
Ticket: https://jira.uitdatabank.be/browse/III-5722
=> III-5722 Project location type in RDF projector

features/data/places/rdf/place-with-required-fields.ttl
- Fixed acceptance test by adding location type to RDF projection of place
=> Fix acceptance test RDF projection of place

app/Http/PsrRouterServiceProvider.php, app/Organizer/OrganizerRequestHandlerServiceProvider.php, features/organizer/educational-description.feature, src/Http/Organizer/DeleteEducationalDescriptionRequestHandler.php, tests/Http/Organizer/DeleteEducationalDescriptionRequestHandlerTest.php
Added new endpoint for organizer to delete educational description
Related to pr https://github.com/cultuurnet/apidocs/pull/295
---
Ticket: https://jira.uitdatabank.be/browse/III-5756
=> III-5756 delete educational description

app/CommandHandling/CommandBusServiceProvider.php, app/Console/Command/ConvertDescriptionToEducationalDescriptionForCultuurkuur.php, app/Console/ConsoleServiceProvider.php, app/Organizer/OrganizerCommandHandlerProvider.php, src/Organizer/CommandHandler/ConvertDescriptionToEducationalDescriptionHandler.php, src/Organizer/Commands/ConvertDescriptionToEducationalDescription.php, src/Organizer/Organizer.php, tests/Organizer/CommandHandler/ConvertDescriptionToEducationalDescriptionHandlerTest.php
Added a script to convert descriptions to educational descriptions for a specific label (cultuurkuur).
---
Ticket: https://jira.uitdatabank.be/browse/III-5758
=> Script - Convert description to educational description

docker.md
- `docker.md`: updated the info about the acceptance tests after switch from ruby to Behat.
---
Ticket: https://jira.uitdatabank.be/browse/III-5767
=> III-5767: Update docker.md after changing the acceptance tests

src/Event/ReadModel/RDF/RdfProjector.php, src/Place/ReadModel/RDF/RdfProjector.php, src/RDF/Editor/GraphEditor.php, tests/Event/ReadModel/RDF/RdfProjectorTest.php, tests/Place/ReadModel/RDF/RdfProjectorTest.php
- Get created timestamp from JSON instead of the recorded from domain messages
---
Ticket: https://jira.uitdatabank.be/browse/III-5769
=> III-5769 Get created timestamp from JSON

app/Console/Command/ConvertDescriptionToEducationalDescriptionForCultuurkuur.php
- Added check to see if description exists (based on feedback from Luc)
- Added confirmation question
---
Ticket: https://jira.uitdatabank.be/browse/III-5758
=> III-5758 Add check to see if description exist

src/Role/ValueObjects/Permission.php, tests/Http/Role/GetPermissionsRequestHandlerTest.php, tests/Http/Role/GetUserPermissionsRequestHandlerTest.php, tests/Role/ValueObjects/PermissionTest.php
- Added permission `aanbod_historiek`
---
Ticket: https://jira.uitdatabank.be/browse/III-4892
=> III-4892 Add permission `aanbod_historiek`

features/Steps/EventSteps.php, features/data/events/event-with-multiple-calendar.json, features/data/events/rdf/event-with-all-fields.ttl, features/data/places/rdf/place-with-required-fields.ttl, features/event/rdf.feature, src/RDF/Editor/GraphEditor.php, tests/Event/ReadModel/RDF/ttl/event-with-calendar-multiple.ttl, tests/Event/ReadModel/RDF/ttl/event-with-calendar-periodic.ttl, tests/Event/ReadModel/RDF/ttl/event-with-calendar-single.ttl, tests/Event/ReadModel/RDF/ttl/event-with-description.ttl, tests/Event/ReadModel/RDF/ttl/event-with-dummy-location-and-multiple-calendar.ttl, tests/Event/ReadModel/RDF/ttl/event-with-dummy-location-and-single-calendar.ttl, tests/Event/ReadModel/RDF/ttl/event-with-dummy-location.ttl, tests/Event/ReadModel/RDF/ttl/event-with-publication-date.ttl, tests/Event/ReadModel/RDF/ttl/event-with-status-approved.ttl, tests/Event/ReadModel/RDF/ttl/event-with-status-deleted.ttl, tests/Event/ReadModel/RDF/ttl/event-with-status-ready-for-validation.ttl, tests/Event/ReadModel/RDF/ttl/event-with-status-rejected.ttl, tests/Event/ReadModel/RDF/ttl/event-with-translations.ttl, tests/Event/ReadModel/RDF/ttl/event.ttl, tests/Place/ReadModel/RDF/ttl/place-with-coordinates.ttl, tests/Place/ReadModel/RDF/ttl/place-with-publication-date.ttl, tests/Place/ReadModel/RDF/ttl/place-with-status-approved.ttl, tests/Place/ReadModel/RDF/ttl/place-with-status-deleted.ttl, tests/Place/ReadModel/RDF/ttl/place-with-status-ready-for-validation.ttl, tests/Place/ReadModel/RDF/ttl/place-with-status-rejected.ttl, tests/Place/ReadModel/RDF/ttl/place-with-translations.ttl, tests/Place/ReadModel/RDF/ttl/place.ttl
- Added structured identifier on RDF projection
---
Ticket: https://jira.uitdatabank.be/browse/III-5774
=> III-5774 Add structured identifier

features/organizer/contributors.feature, src/Organizer/Commands/UpdateContributors.php
Fix wrong permission for updating contributers
---
Ticket: https://jira.uitdatabank.be/browse/III-5530
=> III-5530 Fix wrong permission for updating contributers

features/Steps/ResponseSteps.php, features/data/events/event-with-periodic-calendar-and-opening-hours.json, features/data/events/event-with-permanent-calendar-and-opening-hours.json, features/data/events/rdf/event-with-periodic-calendar-and-opening-hours.ttl, features/data/events/rdf/event-with-permanent-calendar-and-opening-hours.ttl, features/event/rdf.feature, src/Event/ReadModel/RDF/RdfProjector.php, src/RDF/Editor/OpeningHoursEditor.php, src/RDF/RdfNamespaces.php, tests/Event/ReadModel/RDF/RdfProjectorTest.php, tests/Event/ReadModel/RDF/ttl/event-with-calendar-periodic-and-opening-hours.ttl, tests/Event/ReadModel/RDF/ttl/event-with-calendar-permanent-and-opening-hours.ttl
-  Added opening hours to RDF projection of periodic or permanent event
---
Ticket: https://jira.uitdatabank.be/browse/III-5601
=> III-5601 Add opening hours to RDF of periodic or permanent event

features/data/events/rdf/event-with-all-fields.ttl, features/data/events/rdf/event-with-periodic-calendar-and-opening-hours.ttl, src/Event/ReadModel/RDF/RdfProjector.php, tests/Event/ReadModel/RDF/RdfProjectorTest.php, tests/Event/ReadModel/RDF/ttl/event-with-calendar-multiple.ttl, tests/Event/ReadModel/RDF/ttl/event-with-calendar-periodic-and-opening-hours.ttl, tests/Event/ReadModel/RDF/ttl/event-with-calendar-periodic.ttl, tests/Event/ReadModel/RDF/ttl/event-with-calendar-permanent-and-opening-hours.ttl, tests/Event/ReadModel/RDF/ttl/event-with-calendar-single.ttl, tests/Event/ReadModel/RDF/ttl/event-with-description.ttl, tests/Event/ReadModel/RDF/ttl/event-with-dummy-location-and-multiple-calendar.ttl, tests/Event/ReadModel/RDF/ttl/event-with-dummy-location-and-single-calendar.ttl, tests/Event/ReadModel/RDF/ttl/event-with-dummy-location.ttl, tests/Event/ReadModel/RDF/ttl/event-with-publication-date.ttl, tests/Event/ReadModel/RDF/ttl/event-with-status-approved.ttl, tests/Event/ReadModel/RDF/ttl/event-with-status-deleted.ttl, tests/Event/ReadModel/RDF/ttl/event-with-status-ready-for-validation.ttl, tests/Event/ReadModel/RDF/ttl/event-with-status-rejected.ttl, tests/Event/ReadModel/RDF/ttl/event-with-translations.ttl, tests/Event/ReadModel/RDF/ttl/event.ttl
- Added `theme` to event RDF projection
---
Ticket: https://jira.uitdatabank.be/browse/III-5788
=> III-5788 Add `theme` to event RDF projection

src/RDF/RdfNamespaces.php
- Removed unused namespace `Monday`
=> Remove unused namespace `Monday`

docker/php/Dockerfile
- Made sure to report PHP notices in our Docker setup like the AWS servers
=> Report PHP notices in Docker

features/data/events/rdf/event-with-periodic-calendar-and-opening-hours.ttl, features/data/events/rdf/event-with-permanent-calendar-and-opening-hours.ttl, src/RDF/Editor/OpeningHoursEditor.php, tests/Event/ReadModel/RDF/ttl/event-with-calendar-periodic-and-opening-hours.ttl, tests/Event/ReadModel/RDF/ttl/event-with-calendar-permanent-and-opening-hours.ttl
- Fixed `Beschikbaarheid` type on RDF
---
Ticket: https://jira.uitdatabank.be/browse/III-5793
=> III-5793 Fix `Beschikbaarheid` type on RDF

features/data/events/rdf/online-event-with-multiple-calendar.json, features/data/events/rdf/online-event-with-multiple-calendar.ttl, features/data/events/rdf/online-event-with-online-url-and-multiple-calendar.json, features/data/events/rdf/online-event-with-online-url-and-multiple-calendar.ttl, features/data/events/rdf/online-event-with-online-url-and-permanent-calendar.json, features/data/events/rdf/online-event-with-online-url-and-permanent-calendar.ttl, features/event/rdf.feature, src/Event/ReadModel/RDF/RdfProjector.php, tests/Event/ReadModel/RDF/RdfProjectorTest.php, tests/Event/ReadModel/RDF/ttl/online-event-with-online-url-and-multiple-calendar.ttl, tests/Event/ReadModel/RDF/ttl/online-event-with-online-url-and-permanent-calendar.ttl, tests/Event/ReadModel/RDF/ttl/online-event-with-online-url-and-single-calendar.ttl, tests/Event/ReadModel/RDF/ttl/online-event-with-permanent-calendar.ttl, tests/Event/ReadModel/RDF/ttl/online-event-with-single-calendar.ttl
- Added virtual location to RDF projection of an event
---
Ticket: https://jira.uitdatabank.be/browse/III-5606
=> III-5606 Add virtual location to RDF projection of an event

features/data/events/rdf/online-event-with-multiple-calendar.ttl, features/data/events/rdf/online-event-with-online-url-and-multiple-calendar.ttl, features/data/events/rdf/online-event-with-online-url-and-permanent-calendar.ttl, src/Event/ReadModel/RDF/RdfProjector.php, tests/Event/ReadModel/RDF/ttl/online-event-with-online-url-and-multiple-calendar.ttl, tests/Event/ReadModel/RDF/ttl/online-event-with-online-url-and-permanent-calendar.ttl, tests/Event/ReadModel/RDF/ttl/online-event-with-online-url-and-single-calendar.ttl, tests/Event/ReadModel/RDF/ttl/online-event-with-permanent-calendar.ttl, tests/Event/ReadModel/RDF/ttl/online-event-with-single-calendar.ttl
- Moved virtual location to the root of RDF projection
---
Ticket: https://jira.uitdatabank.be/browse/III-5803
=> III-5803 Move virtual location to root of RDF projection

features/data/events/rdf/mixed-event-with-online-url-and-multiple-calendar.json, features/data/events/rdf/mixed-event-with-online-url-and-multiple-calendar.ttl, features/data/events/rdf/mixed-event-with-online-url-and-permanent-calendar.json, features/data/events/rdf/mixed-event-with-online-url-and-permanent-calendar.ttl, features/event/rdf.feature, src/Event/ReadModel/RDF/RdfProjector.php, tests/Event/ReadModel/RDF/RdfProjectorTest.php, tests/Event/ReadModel/RDF/ttl/mixed-event-with-online-url-and-multiple-calendar.ttl, tests/Event/ReadModel/RDF/ttl/mixed-event-with-online-url-and-permanent-calendar.ttl, tests/Event/ReadModel/RDF/ttl/mixed-event-with-online-url-and-single-calendar.ttl, tests/Event/ReadModel/RDF/ttl/mixed-event-with-permanent-calendar.ttl, tests/Event/ReadModel/RDF/ttl/mixed-event-with-single-calendar.ttl
- Supported virtual locations for mixed events
---
Ticket: https://jira.uitdatabank.be/browse/III-5803
=> III-5803 Add RDF projection for mixed events

features/data/organizers/rdf/organizer.ttl, src/Organizer/ReadModel/RDF/RdfProjector.php, src/RDF/RdfNamespaces.php, tests/Organizer/ReadModel/RDF/ttl/organizer.ttl
- Added organizer unique URL as homepage on RDF projection
---
Ticket: https://jira.uitdatabank.be/browse/III-5796
=> III-5796 Project organizer unique url as homepage

features/data/organizers/rdf/organizer-with-address.ttl, features/organizer/rdf.feature, src/Organizer/ReadModel/RDF/RdfProjector.php, src/Place/ReadModel/RDF/RdfProjector.php, src/RDF/Editor/GeometryEditor.php, tests/Organizer/ReadModel/RDF/RdfProjectorTest.php, tests/Organizer/ReadModel/RDF/ttl/organizer-with-address.ttl
- Added organizer geolocation to RDF projection
---
Ticket: https://jira.uitdatabank.be/browse/III-5797
=> III-5797 Add organizer geolocation to RDF projection

app/Organizer/OrganizerRdfServiceProvider.php, features/data/organizers/rdf/organizer-with-address.ttl, src/Organizer/ReadModel/RDF/RdfProjector.php, tests/Organizer/ReadModel/RDF/RdfProjectorTest.php, tests/Organizer/ReadModel/RDF/ttl/organizer-with-address.ttl
- Added organizer address to RDF projection of organizer
---
Ticket: https://jira.uitdatabank.be/browse/III-5797
=> III-5797 Add organizer address to RDF projection of organizer

app/Migrations/Version20161220092125.php, app/Migrations/Version20181217144324.php
- Changed `StringLiteral` with `string` in the migrations
---
=> III-3853 StringLiteral Migrations

app/Event/EventRdfServiceProvider.php, features/data/events/rdf/event-with-organizer.json, features/data/events/rdf/event-with-organizer.ttl, features/event/rdf.feature, src/Event/ReadModel/RDF/RdfProjector.php, src/Place/ReadModel/RDF/RdfProjector.php, tests/Event/ReadModel/RDF/RdfProjectorTest.php, tests/Event/ReadModel/RDF/ttl/event-with-organizer.ttl
- Added RDF projection for organizer on an event
---
Ticket: https://jira.uitdatabank.be/browse/III-5801
=> III-5801 Add RDF projection for organizer on an event

features/data/events/rdf/event-with-contact-point.json, features/data/events/rdf/event-with-contact-point.ttl, features/event/rdf.feature, src/Event/ReadModel/RDF/RdfProjector.php, src/Organizer/ReadModel/RDF/RdfProjector.php, src/RDF/Editor/ContactPointEditor.php, tests/Event/ReadModel/RDF/RdfProjectorTest.php, tests/Event/ReadModel/RDF/ttl/event-with-contact-point.ttl
- Added RDF projection for contact point on event
---
Ticket: https://jira.uitdatabank.be/browse/III-5810
=> III-5810 Add RDF projection contact point on event

src/Address/Street.php
III-3853 Remove stringliteral on legacy street
---
=> III-3853 Remove stringliteral on legacy street

app/RDF/RdfServiceProvider.php, app/UiTPAS/UiTPASIncomingEventServicesProvider.php, src/Broadway/AMQP/AbstractConsumer.php, src/Deserializer/DeserializerLocatorInterface.php, src/Deserializer/SimpleDeserializerLocator.php, tests/Deserializer/SimpleDeserializerLocatorTest.php
III-3853 Remove stringliteral from deserializer to primitive string
---
=> III-3853 Remove stringliteral from deserializer

src/Address/Locality.php, src/Address/LocalityAddressFormatter.php
Remove stringliteral on legacy locality
---
=> III-3853 Remove stringliteral on legacy locality

src/Address/Address.php
Removed docblocks and added typehints for the properties of the legacy address class.
=> Quick improvement to the code style of legacy address

src/Address/LocalityAddressFormatter.php, src/Address/PostalCode.php
Remove stringliteral on legacy postal code
---
=> III-3853 Remove stringliteral on legacy postal code

src/Event/Event.php, src/Event/Events/EventFromUDB2.php, src/Http/Offer/PatchOfferRequestHandler.php, src/Offer/Commands/Moderation/AbstractReject.php, src/Offer/Events/Moderation/AbstractRejected.php, src/Offer/Offer.php, src/Offer/ReadModel/History/OfferHistoryProjectorTrait.php, src/Offer/Serializers/UpdateWorkflowStatusDenormalizer.php, src/Place/Place.php, tests/Event/Events/EventImportedFromUDB2Test.php, tests/Event/ReadModel/History/HistoryProjectorTest.php, tests/Http/Offer/PatchOfferRequestHandlerTest.php, tests/Http/Offer/UpdateWorkflowStatusRequestHandlerTest.php, tests/Offer/CommandHandlers/UpdateAvailableFromHandlerTest.php, tests/Offer/Events/Moderation/AbstractRejectedTest.php, tests/Offer/Item/Item.php, tests/Offer/OfferCommandHandlerTest.php, tests/Offer/OfferTest.php, tests/Offer/ReadModel/JSONLD/OfferLDProjectorTest.php, tests/Place/ReadModel/History/HistoryProjectorTest.php
Remove StringLiteral from reject reason
---
=> III-3853 Remove StringLiteral from reject reason

src/Cdb/CdbXmlPriceInfoParser.php, src/ValueObject/MultilingualString.php, tests/BackwardsCompatiblePayloadSerializerFactoryTest.php, tests/BookingInfoTest.php, tests/Event/Commands/UpdateBookingInfoTest.php, tests/Event/EventTest.php, tests/Event/Events/BookingInfoUpdatedTest.php, tests/Http/Event/ImportEventRequestHandlerTest.php, tests/Http/Offer/UpdateBookingInfoRequestHandlerTest.php, tests/Http/Place/ImportPlaceRequestHandlerTest.php, tests/Model/Import/Offer/Udb3ModelToLegacyOfferAdapterTest.php, tests/Offer/Commands/AbstractUpdateBookingInfoTest.php, tests/Offer/Events/AbstractBookingInfoEventTest.php, tests/Offer/OfferTest.php, tests/Offer/ReadModel/JSONLD/OfferLDProjectorTest.php, tests/OfferLDProjectorTestBase.php, tests/Place/PlaceTest.php, tests/PriceInfo/PriceInfoTest.php, tests/ValueObject/MultilingualStringTest.php
Removed StringLiteral from MultilingualString
---
=> III-3853 Remove StringLiteral from MultilingualString

src/Event/ReadModel/JSONLD/Specifications/Has1Taalicoon.php, src/Event/ReadModel/JSONLD/Specifications/Has2Taaliconen.php, src/Event/ReadModel/JSONLD/Specifications/Has3Taaliconen.php, src/Event/ReadModel/JSONLD/Specifications/Has4Taaliconen.php, src/Event/ReadModel/JSONLD/Specifications/HasUiTPASBrand.php, src/Event/ReadModel/JSONLD/Specifications/Labelable.php
remove stringliteral from ReadModel/JSONLD/Specifications/Labelable
---
=> III-3853 remove stringliteral from ReadModel/JSONLD/Specifications/Labelable

src/Event/ReadModel/JSONLD/EventLDProjector.php, src/Offer/OfferFacilityResolver.php, src/Place/PlaceFacilityResolver.php, tests/Offer/AvailableToTest.php
remove stringliteral from events
---
=> III-3853 remove stringliteral from events

src/EventListener/ClassNameEventSpecification.php, src/Offer/Commands/ImportLabels.php, tests/EventListener/ClassNameEventSpecificationTest.php
=> III-3853 Removes StringLiteral

app/SwiftMailer/SwiftMailerServiceProvider.php
- Fixed subclass check
---
Ticket: https://jira.uitdatabank.be/browse/III-5827
=> III-5827 Fix subclass check

app/Migrations/Version20230927114216.php, src/Label/ReadModels/JSON/Repository/Doctrine/DBALReadRepository.php, src/Label/ReadModels/JSON/Repository/Doctrine/DBALWriteRepository.php, src/Label/ReadModels/JSON/Repository/Doctrine/SchemaConfigurator.php, tests/Label/ReadModels/JSON/Repository/Doctrine/BaseDBALRepositoryTest.php
- Removed columns `parentUuid` and `count_col`
---
Ticket: https://jira.uitdatabank.be/browse/III-5689
=> III-5689 Remove columns `parentUuid` and `count_col`

app/Event/EventRdfServiceProvider.php, src/Event/ReadModel/RDF/RdfProjector.php, src/Model/Serializer/Offer/OfferDenormalizer.php, tests/Event/ReadModel/RDF/RdfProjectorTest.php, tests/Event/ReadModel/RDF/ttl/event-with-dummy-organizer-with-contact-point.ttl, tests/Event/ReadModel/RDF/ttl/event-with-dummy-organizer.ttl
- Refactored RdfProjector for events to handle events with dummy organizers
- Project dummy organizer name
- Project dummy organizer contact point
---
Ticket: https://jira.uitdatabank.be/browse/III-5852
=> III-5852 Handle events with dummy organizers

features/data/organizers/rdf/organizer-with-address.ttl, features/data/organizers/rdf/organizer-with-contact-point.ttl, features/data/organizers/rdf/organizer.ttl, src/Model/Organizer/ImmutableOrganizer.php, src/Model/Organizer/Organizer.php, src/Model/Serializer/Organizer/OrganizerDenormalizer.php, src/Model/ValueObject/Moderation/Organizer/WorkflowStatus.php, src/Organizer/Organizer.php, src/Organizer/OrganizerLDProjector.php, src/Organizer/ReadModel/RDF/RdfProjector.php, tests/Model/Serializer/Organizer/OrganizerDenormalizerTest.php, tests/Organizer/ReadModel/RDF/RdfProjectorTest.php, tests/Organizer/ReadModel/RDF/ttl/organizer-deleted.ttl, tests/Organizer/ReadModel/RDF/ttl/organizer-with-address.ttl, tests/Organizer/ReadModel/RDF/ttl/organizer-with-contact-point.ttl, tests/Organizer/ReadModel/RDF/ttl/organizer-without-homepage.ttl, tests/Organizer/ReadModel/RDF/ttl/organizer.ttl
- Added workflow status on denormalized organizer model
- Added workflow status to RDF projection of organizer
---
Ticket: https://jira.uitdatabank.be/browse/III-5854
=> III-5854 Project workflow status on RDF of organizer

src/Event/ReadModel/RDF/RdfProjector.php, tests/Event/ReadModel/RDF/RdfProjectorTest.php
- Fixed indentation level of contact point data
---
Ticket: https://jira.uitdatabank.be/browse/III-5852
=> III-5852 Fix indentation level of contact point data

src/Model/Serializer/Offer/OfferDenormalizer.php, src/Model/Serializer/Organizer/OrganizerDenormalizer.php
- Fixed missing language by setting main language also on data parsed data
---
Ticket: https://jira.uitdatabank.be/browse/III-5892
=> III-5892 Fixed missing main language

app/Authentication/AuthServiceProvider.php, src/Http/Auth/RequestAuthenticatorMiddleware.php, src/Http/Auth/RouteRule.php, tests/Http/Auth/PublicRouteRuleTest.php
Added a configuration parameter to mark which routes are always requiring authentication, or make it toggleable dependent on a GET param.
---
Ticket: https://jira.uitdatabank.be/browse/III-5875
=> III-5875 Exclude param for public route

app/Organizer/OrganizerRdfServiceProvider.php, app/Organizer/OrganizerRequestHandlerServiceProvider.php, features/data/organizers/rdf/organizer-with-address.ttl, features/data/organizers/rdf/organizer-with-contact-point.ttl, features/data/organizers/rdf/organizer.ttl, features/organizer/rdf.feature, src/Http/Organizer/GetOrganizerRequestHandler.php, src/Http/RDF/RDFResponseFactory.php, src/Http/RDF/TurtleResponse.php, tests/Http/Organizer/GetOrganizerRequestHandlerTest.php, tests/Http/Organizer/samples/organizer.ttl
- Served organizer RDF from Redis Graph cache
---
Ticket: https://jira.uitdatabank.be/browse/III-5901
=> III-5901 Serve organizer RDF from Redis Graph cache

app/Event/EventRdfServiceProvider.php, app/Offer/OfferServiceProvider.php, app/Place/PlaceRdfServiceProvider.php, features/data/events/rdf/event-with-all-fields.ttl, features/data/events/rdf/event-with-booking-info.ttl, features/data/events/rdf/event-with-contact-point.ttl, features/data/events/rdf/event-with-organizer.ttl, features/data/events/rdf/event-with-periodic-calendar-and-opening-hours.ttl, features/data/events/rdf/event-with-permanent-calendar-and-opening-hours.ttl, features/data/events/rdf/event-with-required-fields.ttl, features/data/events/rdf/mixed-event-with-online-url-and-multiple-calendar.ttl, features/data/events/rdf/mixed-event-with-online-url-and-permanent-calendar.ttl, features/data/events/rdf/online-event-with-multiple-calendar.ttl, features/data/events/rdf/online-event-with-online-url-and-multiple-calendar.ttl, features/data/events/rdf/online-event-with-online-url-and-permanent-calendar.ttl, features/data/places/rdf/place-with-required-fields.ttl, features/event/rdf.feature, features/place/rdf.feature, src/Http/Offer/GetDetailRequestHandler.php, tests/Http/Offer/GetDetailRequestHandlerTest.php, tests/Http/Offer/samples/event.ttl, tests/Http/Offer/samples/place.ttl
- Served offers RDF from Redis cache
---
Ticket: https://jira.uitdatabank.be/browse/III-5901
=> III-5901 Serve offers RDF from Redis cache

app/Authentication/AuthServiceProvider.php, features/event/contributors.feature, features/organizer/contributors.feature, features/place/contributors.feature
Fixed broken feature tests
---
Ticket: https://jira.uitdatabank.be/browse/III-5875
=> III-5875 Fixed broken feature tests

src/Event/ReadModel/RDF/RdfProjector.php, tests/Event/ReadModel/RDF/RdfProjectorTest.php
- Fixed exception when parsing the name of a dummy organizer by implementing a fallback to translated names
---
Ticket: https://jira.uitdatabank.be/browse/III-5900
=> III-5900 Improve extracting name of a dummy organizer

features/search/contributors.feature
Added check that contributors are not leaked in sapi3 responses
---
Ticket: https://jira.uitdatabank.be/browse/III-5875
=> III-5875 Added check that contributors are not leaked in sapi3 responses

src/Event/ReadModel/RDF/RdfProjector.php, tests/Event/ReadModel/RDF/RdfProjectorTest.php
- Handled missing created date on an event and log warning
---
Ticket: https://jira.uitdatabank.be/browse/III-5921
=> III-5921 Handle missing created date on event and log warning

features/data/places/rdf/place-with-labels.json, features/data/places/rdf/place-with-labels.ttl, features/event/rdf.feature, features/place/rdf.feature, src/Event/ReadModel/RDF/EventJsonToTurtleConverter.php, src/Place/ReadModel/RDF/PlaceJsonToTurtleConverter.php, src/RDF/Editor/LabelEditor.php, tests/Place/ReadModel/RDF/PlaceJsonToTurtleConverterTest.php, tests/Place/ReadModel/RDF/ttl/place-with-labels.ttl
- Added label to place RDF projection
---
Ticket: https://jira.uitdatabank.be/browse/III-5944
=> III-5944 Add label to place RDF projection

features/data/organizers/organizer-with-labels.json, features/data/organizers/rdf/organizer-with-labels.ttl, features/organizer/rdf.feature, src/Organizer/ReadModel/RDF/OrganizerJsonToTurtleConverter.php, tests/Organizer/ReadModel/RDF/OrganizerJsonToTurtleConverterTest.php, tests/Organizer/ReadModel/RDF/ttl/organizer-with-labels.ttl
- Add labels to organizer RDF projection
---
Ticket: https://jira.uitdatabank.be/browse/III-5945
=> III-5945 Add labelas to organizer RDF projection

features/data/events/rdf/event-with-all-fields.ttl, features/data/events/rdf/event-with-price-info.json, features/data/events/rdf/event-with-price-info.ttl, features/event/rdf.feature, src/Event/ReadModel/RDF/EventJsonToTurtleConverter.php, src/RDF/RdfNamespaces.php, tests/Event/ReadModel/RDF/EventJsonToTurtleConverterTest.php, tests/Event/ReadModel/RDF/ttl/event-with-price-info.ttl, tests/Organizer/ReadModel/RDF/OrganizerJsonToTurtleConverterTest.php, tests/Place/ReadModel/RDF/PlaceJsonToTurtleConverterTest.php
- Added price info to event RDF projection
---
Ticket: https://jira.uitdatabank.be/browse/III-5903
=> III-5903 Add price info to event RDF projection

features/data/events/rdf/event-with-all-fields.ttl, features/data/events/rdf/event-with-price-info.ttl, src/Event/ReadModel/RDF/EventJsonToTurtleConverter.php, src/RDF/RdfNamespaces.php, tests/Event/ReadModel/RDF/ttl/event-with-price-info.ttl
- Fixed prijs categorie on RDF
---
Ticket: https://jira.uitdatabank.be/browse/III-5903
=> III-5903 Fix prijs categorie on RDF

tests/Http/Place/ImportPlaceRequestHandlerTest.php
- Fixed unit test with hardcoded 2024
=> Fix unit test with hardcoded 2024

features/data/places/rdf/place-with-labels.ttl, features/data/places/rdf/place-with-required-fields.ttl
- Fixed acceptance tests geo coordinates when location name is used. This results in slightly different geo coordinates for points of interest.
=> Fixed geo coordinates when using location name

features/event/booking-info.feature, features/event/contact-point.feature, features/event/contributors.feature, features/event/description.feature, features/event/images.feature, features/event/typical-age-range.feature, features/organizer/contributors.feature, features/place/address.feature, features/place/booking-info.feature, features/place/contact-point.feature, features/place/contributors.feature, features/place/description.feature, features/place/images.feature, features/place/typical-age-range.feature, features/role/create.feature, features/role/delete.feature, features/role/get.feature, features/role/permissions.feature, features/role/users.feature
- Improved scenario names
---
Ticket: https://jira.uitdatabank.be/browse/III-5609
=> III-5609 Improve scenario name

features/role/users.feature
- Fixed acceptance test with user role after a cleanup was done for the users of @LucWollants
=> Fix acceptance test with user role

composer.json, composer.lock
- Upgraded `doctrine/migrations` to 2.3.5
---
=> III-5031 Upgrade doctrine migrations

composer.json, composer.lock, tests/Http/Media/UploadMediaRequestHandlerTest.php, tests/Media/ImageUploaderServiceTest.php
- Replaced `zendframework/zend-diactoros` with `laminas/laminas-diactoros`
---
=> III-5031 Replace Zend diactoros

composer.json, composer.lock
- Upgraded `php-amqplib/php-amqplib` to version 3.6.0
---
=> III-5031 Upgrade php-amqplib

.github/workflows/ci.yml
- Changed name of the unit test step
- Upgraded checkout action to version 4
- Upgraded cache action to version 3
---
=> III-5031 Improve CI steps

config/cli-config.php
- Used correct Doctrine Migration imports to fix CLI
---
=> Use correct Doctrine Migration imports to fix CLI

src/Event/ReadModel/RDF/EventJsonToTurtleConverter.php, src/Http/ApiProblem/ApiProblem.php, src/Organizer/ReadModel/RDF/OrganizerJsonToTurtleConverter.php, src/Place/ReadModel/RDF/PlaceJsonToTurtleConverter.php, src/RDF/JsonDataCouldNotBeConverted.php, tests/Event/ReadModel/RDF/EventJsonToTurtleConverterTest.php
- Throw custom exception when JOSN to RDF conversion fails
---
Ticket: https://jira.uitdatabank.be/browse/III-5971
=> III-5971 Throw custom exception when JOSN to RDF conversion fails

app/Console/Command/ProcessDuplicatePlaces.php
- Added option to only set the canonical of all clusters
=> Add option to only set the canonical of all clusters

src/Event/ReadModel/RDF/EventJsonToTurtleConverter.php, tests/Event/ReadModel/RDF/EventJsonToTurtleConverterTest.php, tests/Event/ReadModel/RDF/ttl/event-with-dummy-location-and-single-calendar.ttl, tests/Event/ReadModel/RDF/ttl/event-with-dummy-location-name-and-multiple-calendar.ttl, tests/Event/ReadModel/RDF/ttl/event-with-dummy-location-name-and-single-calendar.ttl, tests/Event/ReadModel/RDF/ttl/event-with-dummy-location-name.ttl, tests/Event/ReadModel/RDF/ttl/event-with-dummy-location.ttl
- Fixed projection of dummy location RDF by making it a node and adding the name to it.
---
Ticket: https://jira.uitdatabank.be/browse/III-5989
=> III-5989 Fix projection of dummy location RDF

features/data/events/rdf/mixed-event-with-online-url-and-multiple-calendar.ttl, features/data/events/rdf/mixed-event-with-online-url-and-permanent-calendar.ttl, features/data/events/rdf/online-event-with-online-url-and-multiple-calendar.ttl, features/data/events/rdf/online-event-with-online-url-and-permanent-calendar.ttl, src/Event/ReadModel/RDF/EventJsonToTurtleConverter.php, tests/Event/ReadModel/RDF/ttl/mixed-event-with-online-url-and-multiple-calendar.ttl, tests/Event/ReadModel/RDF/ttl/mixed-event-with-online-url-and-permanent-calendar.ttl, tests/Event/ReadModel/RDF/ttl/mixed-event-with-online-url-and-single-calendar.ttl, tests/Event/ReadModel/RDF/ttl/online-event-with-online-url-and-multiple-calendar.ttl, tests/Event/ReadModel/RDF/ttl/online-event-with-online-url-and-permanent-calendar.ttl, tests/Event/ReadModel/RDF/ttl/online-event-with-online-url-and-single-calendar.ttl
- Changed virtualUrl type to schema:URL
---
Ticket: https://jira.uitdatabank.be/browse/III-5996
=> III-5996 Change virtualUrl type to schema:URL

features/data/events/rdf/event-with-all-fields.ttl, features/data/events/rdf/event-with-videos.json, features/data/events/rdf/event-with-videos.ttl, features/event/rdf.feature, src/Event/ReadModel/RDF/EventJsonToTurtleConverter.php, src/Model/Serializer/ValueObject/MediaObject/VideoNormalizer.php, src/Model/ValueObject/MediaObject/VideoPlatform.php, src/Model/ValueObject/MediaObject/VideoPlatformData.php, src/Model/ValueObject/MediaObject/VideoPlatformFactory.php, src/RDF/Editor/VideoEditor.php, tests/Event/ReadModel/RDF/EventJsonToTurtleConverterTest.php, tests/Event/ReadModel/RDF/ttl/event-with-videos.ttl
- Created `VideoPlatformData` class to handle different video platforms
- Created `VideoEditor` to convert video to RDF
- Added conversion from videos JSON to RDF inside `EventJsonToTurtleConverter`
---
Ticket: https://jira.uitdatabank.be/browse/III-5975
=> III-5975 Project videos to RDF

features/data/events/rdf/event-with-all-fields.json, features/data/events/rdf/event-with-all-fields.ttl, features/data/events/rdf/event-with-image-object.ttl, features/data/events/rdf/event-with-images.json, features/event/rdf.feature, src/Event/ReadModel/RDF/EventJsonToTurtleConverter.php, src/RDF/Editor/MediaObjectEditor.php, tests/Event/ReadModel/RDF/EventJsonToTurtleConverterTest.php, tests/Event/ReadModel/RDF/ttl/event-with-media-object.ttl
Added images to RDF projection
---
Ticket: https://jira.uitdatabank.be/browse/III-5976
=> III-5976/add image to rdf event projection

src/Model/Serializer/Place/PlaceReferenceDenormalizer.php, tests/Event/ReadModel/RDF/EventJsonToTurtleConverterTest.php, tests/Place/ReadModel/RDF/PlaceJsonToTurtleConverterTest.php
- Handled dummy location with missing address
---
Ticket: https://jira.uitdatabank.be/browse/III-6013
=> III-6013 Handle dummy location with missing address

src/Event/ReadModel/RDF/EventJsonToTurtleConverter.php, tests/Event/ReadModel/RDF/EventJsonToTurtleConverterTest.php
- Handled dummy location with `null` name
---
Ticket: https://jira.uitdatabank.be/browse/III-6014
=> III-6014 Handle dummy location with `null` name

src/Model/Serializer/Place/PlaceDenormalizer.php, tests/Place/ReadModel/RDF/PlaceJsonToTurtleConverterTest.php
- Handled missing address better to avoid PHP warning
---
Ticket: https://jira.uitdatabank.be/browse/III-6028
=> III-6028 Handled missing address better to avoid PHP warning

src/Model/Serializer/ValueObject/Calendar/CalendarDenormalizer.php, tests/Event/ReadModel/RDF/EventJsonToTurtleConverterTest.php
- Handled missing sub events on multiple calendars
---
Ticket: https://jira.uitdatabank.be/browse/III-6029
=> III-6029 Handle missing sub events on multiple calendar

app/Console/Command/ProcessDuplicatePlaces.php
- Fixed misconfiguration of option for command `place:process-duplicates`
=> Fix misconfiguration of option

features/place/duplicate.feature, src/Http/ApiProblem/ApiProblem.php, src/Http/Place/ImportPlaceRequestHandler.php, src/Place/ReadModel/Duplicate/LookupDuplicatePlaceWithSapi3.php, tests/Http/Place/ImportPlaceRequestHandlerTest.php
Improved error message for duplicate errors
---
Ticket: https://jira.uitdatabank.be/browse/III-4601
Related: https://github.com/cultuurnet/apidocs/pull/359
=> Improve error message

app/Event/EventJSONLDServiceProvider.php, app/Organizer/OrganizerJSONLDServiceProvider.php, app/Place/PlaceJSONLDServiceProvider.php, features/event/create.feature, features/place/create.feature, src/Completeness/Completeness.php, src/Completeness/CompletenessFromWeights.php, src/Completeness/Weight.php, src/Completeness/Weights.php, src/Event/ReadModel/JSONLD/EventLDProjector.php, src/Offer/ReadModel/JSONLD/OfferLDProjector.php, src/Organizer/OrganizerLDProjector.php, src/Place/ReadModel/JSONLD/PlaceLDProjector.php, tests/Event/ReadModel/JSONLD/EventLDProjectorTest.php, tests/Offer/ReadModel/JSONLD/OfferLDProjectorTest.php, tests/Organizer/OrganizerLDProjectorTest.php, tests/Place/ReadModel/JSONLD/PlaceLDProjectorTest.php
- Added `Weight` class with name and value
- Added `Weights` collection
- Added `Completeness` interface with concrete `CompletenessFromWeights` for better encapsulation
---
Ticket: https://jira.uitdatabank.be/browse/III-6047
=> III-6047 Introduce completeness interface for better desing

src/Event/Event.php, src/Event/Events/EventFromUDB2.php, src/Offer/Events/AbstractTitleTranslated.php, src/Offer/Offer.php, src/Offer/ReadModel/JSONLD/OfferLDProjector.php, src/Place/Events/PlaceFromUDB2.php, src/Place/Place.php, tests/Event/Events/EventImportedFromUDB2Test.php, tests/Event/Events/EventUpdatedFromUDB2Test.php, tests/Event/ReadModel/History/HistoryProjectorTest.php, tests/Offer/Events/AbstractTitleTranslatedTest.php, tests/Offer/Item/Item.php, tests/Offer/OfferTest.php, tests/Offer/ReadModel/JSONLD/OfferLDProjectorTest.php, tests/Place/Events/PlaceImportedFromUDB2Test.php, tests/Place/Events/PlaceUpdatedFromUDB2Test.php, tests/Place/ReadModel/History/HistoryProjectorTest.php
III-5912 Change AbstractTitleTranslated Title to a string
---
=> III-5912 Change AbstractTitleTranslated Title to a string

features/event/create.feature, features/place/create.feature, src/Completeness/CompletenessFromWeights.php, tests/Event/ReadModel/JSONLD/EventLDProjectorTest.php, tests/Place/ReadModel/JSONLD/PlaceLDProjectorTest.php
- Fixed type and theme calculation for completeness by improving the iteration of the different properties and map type and theme to the terms property.
---
Ticket: https://jira.uitdatabank.be/browse/III-6047
=> III-6047 Fix type and theme calculation for completeness

src/Event/Event.php, src/Event/Events/EventCreated.php, src/Event/Events/EventFromUDB2.php, src/Event/Events/MajorInfoUpdated.php, src/Offer/Events/AbstractTitleUpdated.php, src/Offer/Offer.php, src/Offer/ReadModel/JSONLD/OfferLDProjector.php, src/Place/Events/MajorInfoUpdated.php, src/Place/Events/PlaceCreated.php, src/Place/Events/PlaceFromUDB2.php, src/Place/Place.php, tests/Event/Events/EventCreatedTest.php, tests/Event/Events/EventImportedFromUDB2Test.php, tests/Event/Events/EventUpdatedFromUDB2Test.php, tests/Event/Events/MajorInfoUpdatedTest.php, tests/Event/ReadModel/History/HistoryProjectorTest.php, tests/Offer/Item/Item.php, tests/Offer/OfferTest.php, tests/Offer/ReadModel/JSONLD/OfferLDProjectorTest.php, tests/Place/Events/MajorInfoUpdatedTest.php, tests/Place/Events/PlaceCreatedTest.php, tests/Place/Events/PlaceImportedFromUDB2Test.php, tests/Place/Events/PlaceUpdatedFromUDB2Test.php, tests/Place/ReadModel/History/HistoryProjectorTest.php
AbstractTitleUpdated - changed LegacyTitle to string
---
=> III-5912 AbstractTitleUpdated - changed LegacyTitle to string

features/data/places/rdf/place-with-invalid-address.json, features/data/places/rdf/place-with-invalid-address.ttl
- Set bogus address values to force failing Google geocoding
=> Fix acceptance tests RDF place

app/Console/Command/ReplayCommand.php
- `ReplayCommand`: check if all cdbid's are valid (legacy) `UUID`s
- Input from `Users` is better validated & more error prone.
---
Ticket: https://jira.publiq.be/browse/III-6098
=> III-6098: validate all cdbids as UUID instead of only first one

composer.json, composer.lock
Added "symfony/console" and "symfony/process" as main dependencies in composer.
---
Ticket: https://jira.uitdatabank.be/browse/...
=> Added Symfony Process and Console to composer

app/Http/PsrRouterServiceProvider.php
-  Hide ownership endpoints behind config toggle
---
Ticket: https://jira.uitdatabank.be/browse/III-6103
=> III-6103 Hide ownership endpoints behind config toggle

app/Ownership/OwnershipRequestHandlerServiceProvider.php, features/Steps/OwnershipSteps.php, features/ownership/request.feature, src/Http/Ownership/RequestOwnershipRequestHandler.php, src/Ownership/CommandHandlers/RequestOwnershipHandler.php, src/Ownership/Commands/RequestOwnership.php, src/Ownership/Events/OwnershipRequested.php, src/Ownership/Ownership.php, src/Ownership/OwnershipState.php, src/Ownership/Readmodels/OwnershipLDProjector.php, src/Ownership/Serializers/RequestOwnershipDenormalizer.php, tests/Http/Ownership/RequestOwnershipRequestHandlerTest.php, tests/Ownership/CommandHandlers/RequestOwnershipHandlerTest.php, tests/Ownership/Commands/RequestOwnershipTest.php, tests/Ownership/Events/OwnershipRequestedTest.php, tests/Ownership/OwnershipTest.php, tests/Ownership/Readmodels/OwnershipLDProjectorTest.php
- Added state to ownership
- Added requester to ownership taken from current user
- Allow owner to be passed to feature step to create a new ownership request
---
Ticket: https://jira.uitdatabank.be/browse/III-6069
=> III-6069 Extend ownership with state and requester

src/Http/Ownership/RequestOwnershipRequestHandler.php, tests/Http/Ownership/RequestOwnershipRequestHandlerTest.php
- Prevent creating ownership for another owner when not a God user
---
Ticket: https://jira.uitdatabank.be/browse/III-6069
=> III-6069 Prevent another owner

app/Ownership/OwnershipRequestHandlerServiceProvider.php, features/ownership/request.feature, src/Http/Ownership/RequestOwnershipRequestHandler.php, tests/Http/Ownership/RequestOwnershipRequestHandlerTest.php
- Prevent creating an ownership when the organizer does not exist
---
Ticket: https://jira.uitdatabank.be/browse/III-6069
=> III-6069 Check organizer does exist

composer.json, composer.lock, src/Http/Ownership/RequestOwnershipRequestHandler.php, src/Http/Request/Body/JsonSchemaLocator.php, tests/Http/Ownership/RequestOwnershipRequestHandlerTest.php
- Added basic JSON schema validation
- Requires https://github.com/cultuurnet/apidocs/pull/378
---
Ticket: https://jira.uitdatabank.be/browse/III-6069
=> III-6069 Improve ownership validation

features/saved_searches/update.feature, src/Http/ApiProblem/SchemaError.php, tests/SavedSearches/UDB3SavedSearchRepositoryTest.php
Code changes related to PR feedback from @LucWollants : https://github.com/cultuurnet/udb3-backend/pull/1655
- Improved feature test for creating saved searches
- Check affected rows in Saved search repository test
- Removed dead code on ApiProblem
---
Ticket: https://jira.uitdatabank.be/browse/III-6117
=> III-6117 Improve feature test

app/Console/Command/ProcessDuplicatePlaces.php
Add force option to place:process-duplicates
---
Ticket: https://jira.uitdatabank.be/browse/III-6125
=> III-6126 - Add force option to place:process-duplicates

src/Address/Address.php, src/Offer/AbstractGeoCoordinatesCommandHandler.php, src/Offer/Commands/AbstractUpdateGeoCoordinatesFromAddress.php, src/Place/ReadModel/Duplicate/CleanPlaceName.php, tests/Address/AddressTest.php, tests/Place/ReadModel/Duplicate/CleanPlaceNameTest.php
Added cleanup of location name towards geocoordinates API call - using slide 3.
**Before I merge this - I want to check tomorrow with Frederic if everything is implemented as he intended!**
---
Ticket: https://jira.uitdatabank.be/browse/III-6120
=> III-6120/clean place names before sending api call

app/CommandHandling/CommandBusServiceProvider.php, app/Place/PlaceGeoCoordinatesServiceProvider.php, src/Place/ExtendedGeoCoordinatesCommandHandler.php, src/Place/GeoCoordinatesProcessManager.php, tests/Place/ExtendedGeoCoordinatesCommandHandlerTest.php
Logging calls to changes in coordinates or title for Place.
Currently does not do a lot but is a placeholder for fetching the geo coordinates for the new index for the data team.
---
Ticket: https://jira.uitdatabank.be/browse/III-6133
=> Log changes in coordinates or title for Place

features/saved_searches/update.feature
Add random name to feature test
=> Add random name to feature test

Makefile, features/permission/permissions.feature, features/search/auth.feature, features/search/contributors.feature, features/search/search-proxy.feature
I added a tag to all feature tests related to SAPI3, to make it easier to change code in the sapi3 code base.
I also added a new Make command to run commands with a specific tag.
=> Add tag to sapi3 feature tests

features/place/duplicate.feature
- Fixed duplicate feature test by using the correct error type
=> Fix duplicate feature test

app/Ownership/OwnershipRequestHandlerServiceProvider.php, src/Http/Ownership/ApproveOwnershipRequestHandler.php, src/Http/Ownership/OwnershipStatusGuard.php, src/Http/Ownership/RejectOwnershipRequestHandler.php, tests/Http/Ownership/ApproveOwnershipRequestHandlerTest.php, tests/Http/Ownership/RejectOwnershipRequestHandlerTest.php
- Implemented ownership status guard to validate status changes 
---
Ticket: https://jira.uitdatabank.be/browse/III-6072
=> III-6072 Implement ownership status guard

app/CommandHandling/CommandBusServiceProvider.php, app/Http/PsrRouterServiceProvider.php, app/Ownership/OwnershipCommandHandlerProvider.php, app/Ownership/OwnershipRequestHandlerServiceProvider.php, features/Steps/OwnershipSteps.php, features/ownership/delete.feature, src/Http/Ownership/DeleteOwnershipRequestHandler.php, src/Http/Ownership/OwnershipStatusGuard.php, src/Ownership/CommandHandlers/DeleteOwnershipHandler.php, src/Ownership/Commands/DeleteOwnership.php, src/Ownership/Events/OwnershipDeleted.php, src/Ownership/Ownership.php, src/Ownership/OwnershipState.php, src/Ownership/Readmodels/OwnershipLDProjector.php, tests/Http/Ownership/DeleteOwnershipRequestHandlerTest.php, tests/Ownership/CommandHandlers/ApproveOwnershipHandlerTest.php, tests/Ownership/CommandHandlers/DeleteOwnershipHandlerTest.php, tests/Ownership/Commands/DeleteOwnershipTest.php, tests/Ownership/Events/OwnershipDeletedTest.php, tests/Ownership/OwnershipTest.php, tests/Ownership/Readmodels/OwnershipLDProjectorTest.php
- Added endpoint `DELETE ownerships/{ownershipId}` to delete requested, rejected and approved ownerships.
---
Ticket: https://jira.uitdatabank.be/browse/III-6070
=> III-6070 Added delete ownership endpoint

app/Ownership/OwnershipServiceProvider.php, src/CommandHandling/AuthorizedCommandBus.php, src/CommandHandling/AuthorizedCommandBusInterface.php, src/Ownership/Readmodels/OwnershipPermissionProjector.php, tests/Ownership/Readmodels/OwnershipPermissionProjectorTest.php, tests/Ownership/Readmodels/TraceableAuthorizedCommandBus.php
- Fixed authorization for normal user by adding toggle for authorization checks
---
Ticket: https://jira.uitdatabank.be/browse/III-6075
=> III-6075 Fix authorization for normal user

app/Role/RoleServiceProvider.php
- Added missing metadata on roles events
=> Add missing meta data

app/Migrations/Version20240402125210.php
- `Migration`: to add mapping table between KinepolisID & publiq ID
---
Ticket: https://jira.uitdatabank.be/browse/III-6079
=> III-6079: add migration to map Id's

app/Console/ConsoleServiceProvider.php, src/Kinepolis/AuthenticatedKinepolisClient.php, src/Kinepolis/KinepolisClient.php, src/Kinepolis/KinepolisService.php, src/Kinepolis/ParsedMovie.php, src/Kinepolis/Parser/KinepolisParser.php, tests/Kinepolis/KinepolisServiceTest.php, tests/Kinepolis/Parser/KinepolisParserTest.php
- `KinepolisClient`: Added  `getImage()` to fetch the Image from a movie
- `ParsedMovie`: Added `$poster` as property
- `KinepolisService`: Upload Poster as Image to `UiTdatabank`, when creating a new movie.
- Movies now have an Image.
---
Ticket: https://jira.publiq.be/browse/III-6079
=> III-6079 moviefetcher image

app/Console/ConsoleServiceProvider.php, composer.json, composer.lock, src/Kinepolis/KinepolisService.php, src/Kinepolis/KinepolisTrailerRepository.php, src/Kinepolis/TrailerRepository.php, src/Kinepolis/YoutubeTrailerRepository.php, tests/Kinepolis/KinepolisServiceTest.php
- `composer`: Added `google/apiclient`
- `TrailerRepository` & `YoutubeTrailerRepository`: 
- `KinepolisService`: Add trailer is searched on `YouTube` if `enabled` in config
- `KinepolisServiceTest`: updated tests
-  https://github.com/cultuurnet/appconfig/pull/620
---
Ticket: https://jira.publiq.be/browse/III-4945
=> III-4945: Add YouTube trailer to movies

src/Kinepolis/KinepolisService.php
- bugfix: because productions cannot be created with an empty list. logic was refactored.
---
Ticket: https://jira.publis.be/browse/III-6079
=> III-6079: bugfix, you cannot create empty productions

src/Kinepolis/KinepolisService.php
- `KinepolisService`: do not directly add via a `Repository` but work with `Commands`
- `KinepolisService`: refactor `searchForProduction()` to `getLinkToProductionCommand()` & return an `AuthorizableCommand` instead of a `ProductionId`
---
Ticket: https://jira.uitdatabank.be/browse/III-6079
=> III-6079: CodeStyle

app/Console/Command/ProcessDuplicatePlaces.php
- Move `getDuplicatePlacesRemovedFromCluster` outside the cluster loop, it is now generating way too many messages on the queue.
=> move getDuplicatePlacesRemovedFromCluster outside cluster loop

Makefile, docker/config.sh
- Copied pem files from common key location
---
Ticket: https://jira.uitdatabank.be/browse/III-6216
=> III-6216 Copy pem files from common key location

features/Steps/AuthorizationSteps.php, features/search/auth.feature, src/User/Keycloak/KeycloakUserIdentityResolver.php
- Used access token for authentication with user/client pair
---
Ticket: https://jira.uitdatabank.be/browse/III-6214
=> III-6214 Use access token for authentication

app/Authentication/AuthServiceProvider.php, features/Steps/AuthorizationSteps.php, features/search/auth.feature, src/User/Keycloak/KeycloakUserIdentityResolver.php
- Bootstrap JWT V2 validator dynamically for Keycloak
- Requires config change https://github.com/cultuurnet/appconfig/pull/671
---
Ticket: https://jira.uitdatabank.be/browse/III-6212
=> III-6212 Bootstrap JWT V2 validator dynamically for Keycloak

src/User/Keycloak/KeycloakUserIdentityResolver.php
- Handle 404 when user not found in Keycloak
---
Ticket: https://jira.uitdatabank.be/browse/III-6220
=> III-6220 Handle 404 when user not found

src/User/Keycloak/KeycloakUserIdentityResolver.php
- Get nickname and id from attributes fields
---
Ticket: https://jira.uitdatabank.be/browse/III-6220
=> III-6220 Get nickname and id from attributes fields

src/User/Keycloak/KeycloakUserIdentityResolver.php, tests/User/Keycloak/KeycloakUserIdentityResolverTest.php
- Implemented the method to search on Nickname in Keycloak
---
Ticket: https://jira.uitdatabank.be/browse/III-6212
=> III-6212 Implement searching on nickname in Keycloak

src/User/Keycloak/KeycloakUserIdentityResolver.php, tests/User/Keycloak/KeycloakUserIdentityResolverTest.php
- Implemented fallback search to search on UiTiD v1
---
Ticket: https://jira.uitdatabank.be/browse/III-6212
=> III-6212 Implement fallback search to search on UiTiD v1

app/Console/Command/MoveEvents.php, app/Console/ConsoleServiceProvider.php, src/Event/Commands/UpdateLocation.php, tests/Console/Command/MoveEventsTest.php
I added a CLI script to move events to another place based on a SAPI3 query.
---
Ticket: https://jira.uitdatabank.be/browse/III-6228
=> III-6228 Create script that can move events

app/Console/Command/MoveEvents.php, tests/Console/Command/MoveEventsTest.php
Minor feedback processed.
--
Ticket: https://jira.uitdatabank.be/browse/III-6228
=> III-6228 Script that can move events

app/Console/Command/ReplayCommand.php, composer.lock, features/Steps/RoleSteps.php, src/Geocoding/Coordinate/Coordinate.php
- Upgraded `publiq/php-cs-fixer-config` to v2.1 to avoid alias functions
---
Ticket: https://jira.uitdatabank.be/browse/III-6150
=> III-6150 Avoid alias functions

tests/Broadway/CommandHandling/Validation/CompositeCommandValidatorTest.php, tests/Broadway/CommandHandling/Validation/ValidatingCommandBusDecoratorTest.php, tests/Broadway/EventHandling/ReplayFilteringEventListenerTest.php, tests/Event/Productions/ProductionEnrichedEventRepositoryTest.php, tests/Event/RelocateEventToCanonicalPlaceTest.php, tests/Http/Offer/AddVideoRequestHandlerTest.php, tests/Http/Place/ImportPlaceRequestHandlerTest.php, tests/Http/Role/AddLabelToRoleRequestHandlerTest.php, tests/Http/Role/RemoveLabelFromRoleRequestHandlerTest.php, tests/Http/Role/RolesSearchRequestHandlerTest.php, tests/Mailinglist/SubscribeUserToMailinglistRequestHandlerTest.php, tests/Media/ImageUploaderServiceTest.php, tests/Media/Serialization/MediaObjectSerializerTest.php, tests/Model/Serializer/Event/EventDenormalizerTest.php, tests/Offer/ReadModel/JSONLD/PropertyPolyfillOfferRepositoryTest.php, tests/Organizer/CommandHandler/DeleteOrganizerHandlerTest.php, tests/Place/CanonicalPlaceRepositoryTest.php
- Fixed even more `MockObject` type hints
---
Ticket: https://jira.uitdatabank.be/browse/III-3558
=> III-3558 Fix `MockObject` typing

src/DateTimeFactory.php, src/Event/Events/EventFromUDB2.php, src/Kinepolis/Parser/KinepolisDateParser.php, src/Model/Serializer/ValueObject/Calendar/CalendarDenormalizer.php, tests/Event/Events/EventCreatedTest.php, tests/Event/Events/EventImportedFromUDB2Test.php, tests/EventExport/Format/HTML/Uitpas/Promotion/EventOrganizerPromotionQueryFactoryTest.php, tests/Model/Event/ImmutableEventTest.php, tests/Model/Offer/ImmutableOfferTest.php, tests/Model/Place/ImmutablePlaceTest.php, tests/Model/ValueObject/Calendar/MultipleSubEventsCalendarTest.php, tests/Model/ValueObject/Calendar/PeriodicCalendarTest.php, tests/Model/ValueObject/Calendar/SingleSubEventCalendarTest.php, tests/Model/ValueObject/Contact/BookingAvailabilityTest.php, tests/Model/ValueObject/Contact/BookingInfoTest.php, tests/Model/ValueObject/Moderation/AvailableToTest.php, tests/Offer/CommandHandlers/UpdateStatusHandlerTest.php, tests/Place/Events/PlaceCreatedTest.php
- Changed creating date times with custom format to wrapper method to avoid type conflict
---
Ticket: https://jira.uitdatabank.be/browse/III-3558
=> III-3558 Replace datetime custom format

docker-compose.yml
- Used `bitnami/mysql` for local container
---
Ticket: https://jira.uitdatabank.be/browse/III-3516
=> III-3516 Use `bitnami/mysql` for local container

docker/config.sh
- Handled move of Docker config
- Related pull request https://github.com/cultuurnet/appconfig/pull/775
---
Ticket: https://jira.uitdatabank.be/browse/III-4932
=> III-4932 Handle move of Docker config

src/Http/Organizer/ImportOrganizerRequestHandler.php
- Removed reference in comment to `synchronous_imports`
- Removed unused local variable
---
Ticket: https://jira.uitdatabank.be/browse/III-4932
=> III-4932 Remove reference to `synchronous_imports`

src/BackwardsCompatiblePayloadSerializerFactory.php, src/Calendar/CalendarConverter.php, src/CulturefeedSlugger.php, src/Event/ReadModel/JSONLD/EventLDProjector.php, src/EventExport/PriceFormatter.php, src/Http/Auth/CorsHeadersResponseDecorator.php, src/Http/Deserializer/BookingInfo/BookingInfoJSONDeserializer.php, src/Http/Request/Body/RemoveNullPropertiesRequestBodyParser.php, src/Model/Serializer/Offer/OfferDenormalizer.php, src/Offer/ReadModel/JSONLD/CdbXmlContactInfoImporter.php, src/Offer/ReadModel/JSONLD/EmbeddingRelatedResourcesOfferRepository.php, src/Offer/ReadModel/JSONLD/OfferUpdate.php, src/Offer/ReadModel/JSONLD/PropertyPolyfillOfferRepository.php, src/Offer/ReadModel/JSONLD/TermLabelOfferRepositoryDecorator.php, src/Organizer/ReadModel/JSONLD/PropertyPolyfillRepository.php, src/Role/ReadModel/Labels/LabelRolesProjector.php, src/Role/ReadModel/Labels/RoleLabelsProjector.php, src/StringFilter/StripHtmlStringFilter.php, tests/Event/CdbXMLEventFactory.php, tests/Event/ReadModel/JSONLD/CdbXMLImporterTest.php, tests/EventExport/Format/HTML/Uitpas/DistributionKey/KansentariefForCurrentCardSystemSpecificationTest.php, tests/EventExport/Format/HTML/Uitpas/DistributionKey/KansentariefForOtherCardSystemsSpecificationTest.php, tests/Http/Request/Psr7RequestBuilder.php, tests/Organizer/OrganizerLDProjectorTest.php, tests/Place/ReadModel/JSONLD/CdbXMLImporterTest.php, tests/Place/ReadModel/JSONLD/PlaceLDProjectorTest.php, tests/Role/ReadModel/Permissions/Doctrine/UserPermissionsWriteRepositoryTest.php
- Removed unneeded local variables
---
Ticket: https://jira.uitdatabank.be/browse/III-6308
=> III-6308 Remove unneeded local variables

tests/Broadway/AMQP/AMQPPublisherTest.php, tests/Broadway/AMQP/CommandBusForwardingConsumerTest.php, tests/Cdb/CdbId/EventCdbIdExtractorTest.php, tests/Event/GeoCoordinatesCommandHandlerTest.php, tests/Geocoding/CachedGeocodingServiceTest.php, tests/Http/InvokableRequestHandlerContainerTest.php, tests/Http/Organizer/ImportOrganizerRequestHandlerTest.php, tests/Http/Place/ImportPlaceRequestHandlerTest.php, tests/Mailinglist/SubscribeUserToMailinglistRequestHandlerTest.php, tests/Offer/IriOfferIdentifierFactoryTest.php, tests/Place/GeoCoordinatesCommandHandlerTest.php, tests/Place/GeoCoordinatesProcessManagerTest.php, tests/Place/LocalPlaceServiceTest.php, tests/ReadModel/JsonDocumentLanguageEnricherTest.php, tests/Role/Commands/AbstractPermissionCommandTest.php, tests/Security/LabelCommandBusSecurityTest.php, tests/Security/PermissionVoterCommandBusSecurityTest.php
- Removed unneeded private properties
---
Ticket: https://jira.uitdatabank.be/browse/III-6308
=> III-6308 Remove unneeded private properties

src/Media/Events/MediaObjectCreated.php, src/Media/MediaObject.php, tests/Media/MediaObjectCreatedTest.php, tests/Media/MediaObjectTest.php
- Refactored `Language` on `MediaObjectCreated`
---
=> III-6310 Refactor `Language` on `MediaObjectCreated`

src/Media/MediaManager.php, src/Media/MediaManagerInterface.php
- Refactored `MediaManager` to use new `Language` class
---
=> III-6310 Refactor `MediaManager` to use new `Language` class

Makefile
- `Makefile`: always use `docker-compose`
---
Ticket: https://jira.publiq.be/browse/III-6154
=> III-6154 improve makefile

src/BackwardsCompatiblePayloadSerializerFactory.php
- Removed usage of old `Language` from backwards compatible class
---
=> III-6310 Refactor backwards compatible

src/Http/Deserializer/Event/CreateEvent.php, src/Http/Deserializer/Event/CreateEventJSONDeserializer.php, tests/Http/Deserializer/Event/CreateEventJSONDeserializerTest.php
- Refactored `CreateEvent` to use new `Language`
---
=> III-6310 Refactor `CreateEvent` to use new `Language`

src/Http/Event/ImportEventRequestHandler.php, src/Http/Offer/UpdateDescriptionRequestHandler.php, src/Http/Place/ImportPlaceRequestHandler.php, src/Kinepolis/KinepolisService.php, src/Offer/Commands/AbstractUpdateDescription.php, src/Offer/OfferCommandHandler.php, tests/Event/Commands/UpdateDescriptionTest.php, tests/Event/EventCommandHandlerTest.php, tests/Http/Event/ImportEventRequestHandlerTest.php, tests/Http/Offer/UpdateDescriptionRequestHandlerTest.php, tests/Kinepolis/KinepolisServiceTest.php, tests/Offer/Commands/AbstractUpdateDescriptionTest.php, tests/OfferCommandHandlerTestTrait.php
- Refactored `Language` in the command `UpdateDescription`
---
=> III-6310 Refactor `Language` in the command `UpdateDescription`

app/Organizer/OrganizerJSONLDServiceProvider.php, src/Organizer/ReadModel/JSONLD/CdbXMLImporter.php, tests/Organizer/OrganizerLDProjectorTest.php
- Used `CultureFeedAddressFactory` inside `CdbXMLImporter`
---
=> III-6310 Use `CultureFeedAddressFactory` inside `CdbXMLImporter`

src/Http/Auth/Jwt/JsonWebToken.php
On request of Luc I clarified the comment regarding the fix for the id tokens in Keycloak.
---
Ticket: https://jira.uitdatabank.be/browse/III-6347
=> III-6347 clarify comment

docker-compose.yml, lib/tasks/build_artifact.rake
- `docker-compose`: Replace `*.dev` to `*.local`
---
Ticket: https://jira.publiq.be/browse/III-6154
=> III-6154: replace *.dev to *.local

src/Http/Event/ImportEventRequestHandler.php, src/Http/Offer/UpdateDescriptionRequestHandler.php, src/Http/Place/ImportPlaceRequestHandler.php, src/Kinepolis/KinepolisService.php, src/Offer/Commands/AbstractUpdateDescription.php, src/Offer/OfferCommandHandler.php, tests/Event/Commands/UpdateDescriptionTest.php, tests/Event/EventCommandHandlerTest.php, tests/Http/Event/ImportEventRequestHandlerTest.php, tests/Http/Offer/UpdateDescriptionRequestHandlerTest.php, tests/Kinepolis/KinepolisServiceTest.php, tests/Offer/Commands/AbstractUpdateDescriptionTest.php, tests/OfferCommandHandlerTestTrait.php
- Refactored `AbstractUpdateDescription` to use new `Description`
---
=> III-6310 Refactor `AbstractUpdateDescription` to use new `Description`

src/Event/Event.php, src/Offer/Events/AbstractDescriptionUpdated.php, src/Offer/Offer.php, src/Place/Place.php, tests/Event/Events/DescriptionUpdatedTest.php, tests/Event/ReadModel/History/HistoryProjectorTest.php, tests/Offer/Events/AbstractDescriptionUpdatedTest.php, tests/Offer/Item/Events/ItemCreated.php, tests/Offer/Item/Item.php, tests/Offer/OfferTest.php, tests/OfferCommandHandlerTestTrait.php, tests/OfferLDProjectorTestBase.php, tests/Place/ReadModel/History/HistoryProjectorTest.php
- Refactored `AbstractDescriptionUpdated` to use new `Description`
---
=> III-6310 Refactor `AbstractDescriptionUpdated` to use new `Description`

src/Offer/Offer.php, src/Offer/OfferCommandHandler.php, tests/Offer/OfferTest.php
- Refactored `updateDescription` aggregate method
---
=> III-6310 Refactor `updateDescription` aggregate method

src/Model/Serializer/ValueObject/Contact/ContactPointDenormalizer.php
- Catched invalid URLs and emails inside `ContactPointDenormalizer` to avoid crash when editing events with invalid data
---
Ticket: https://jira.uitdatabank.be/browse/III-6368
=> III-6368 Catch invalid URLs and emails inside `ContactPointDenormalizer`

composer.json, composer.lock, features/curator/create.feature, tests/Http/Curators/CreateNewsArticleRequestHandlerTest.php, tests/Http/Curators/UpdateNewsArticleRequestHandlerTest.php
- Allow jpg as file extension
---
Ticket: https://jira.uitdatabank.be/browse/III-6312
=> III-6312 Allow jpg

Makefile
---
Ticket: https://jira.uitdatabank.be/browse/III-6154
=> Add extra make target for running acceptance tests with extra output

features/curator/create.feature, features/curator/update.feature
- Fixed acceptance tests after change to regex for jpeg
=> Use correct regex for jpeg

features/Steps/UtilitySteps.php, features/event/export.feature
- `UtilitySteps`: Added `iCountTheFiles()` & `iCheckIfOneFileHasBeenCreated()`
- `export.feature`: Check for each export if a new file has been created
- Better acceptance tests
- https://github.com/cultuurnet/appconfig/pull/846
- This PR cannot be merged before https://jira.publiq.be/browse/III-6367 has been fixed.
---
Ticket: https://jira.publiq.be/browse/III-6342
=> III-6342 count check

src/Geocoding/AbstractGeocodingService.php, src/Place/ReadModel/Duplicate/CleanPlaceName.php, tests/Place/ReadModel/Duplicate/CleanPlaceNameTest.php
- `CleanPlaceName`: Also remove `"` from `PlaceName`
- `AbstractGeocodingService`: Small Typo
- Places with `"` in their `title` will get Coordinates from the `GeocodingService`
---
Ticket: https://jira.publiq.be/browse/III-6027
=> III-6027 no geo

composer.json, composer.lock, features/event/contact-point.feature, features/place/contact-point.feature, tests/Http/Offer/UpdateContactPointRequestHandlerTest.php
- `composer`: updated `udb3-json-schemas`
- `features/event/contact-point.feature`: Add test with faulty `contactPoints`
- `features/place/contact-point.feature`: Add test with faulty `contactPoints`
- `UpdateContactPointRequestHandlerTest`: Add extra `requestBodies` in `provideInvalidRequestBodies()`
- Integrators can no longer send invalid contactPoints
- https://github.com/cultuurnet/apidocs/pull/411
---
Ticket: https://jira.publiq.be/browse/III-6368
=> III-6368 fineTune ContactPointUpdated by adding tests

features/ownership/request.feature, src/Ownership/Readmodels/OwnershipLDProjector.php, tests/Ownership/Readmodels/OwnershipLDProjectorTest.php
- Expose the requester email
---
Ticket: https://jira.uitdatabank.be/browse/III-6372
=> III-6372 Expose requester email

features/curator/update.feature
- Fixed acceptance test
---
Ticket: https://jira.uitdatabank.be/browse/III-6312
=> III-6312 Fix acceptance test

src/BackwardsCompatiblePayloadSerializerFactory.php, tests/BackwardsCompatiblePayloadSerializerFactoryTest.php
- BUGFIX description should not be empty
---
Ticket: https://jira.uitdatabank.be/browse/III-6396
=> III-6396 BUGFIX description should not be empty

features/history/metadata.feature
- `metadata.feature`:  Add acceptance test to check if we store the `clientName`
---
Ticket: https://jira.publiq.be/browse/III-6420
=> III-6420 Add acceptance test for metadata

src/Cdb/CdbXmlPriceInfoParser.php, src/Event/Event.php, src/PriceInfo/PriceInfo.php, tests/Event/EventTest.php, tests/PriceInfo/PriceInfoTest.php
- Used `Tariffs` collection inside legacy `PriceInfo`
---
=> III-6310 Use `Tariffs` collection inside legacy `PriceInfo`

src/Http/Place/ImportPlaceRequestHandler.php, src/Place/Events/PlaceCreated.php, src/Place/Place.php, src/Place/ReadModel/JSONLD/PlaceLDProjector.php, tests/DomainMessage/CompositeDomainMessageEnricherTest.php, tests/EventListener/EnrichingEventListenerDecoratorTest.php, tests/Offer/ReadModel/Metadata/OfferMetadataProjectorTest.php, tests/Place/CommandHandlerTest.php, tests/Place/Events/PlaceCreatedTest.php, tests/Place/ExtendedGeoCoordinatesCommandHandlerTest.php, tests/Place/GeoCoordinatesCommandHandlerTest.php, tests/Place/GeoCoordinatesProcessManagerTest.php, tests/Place/PlaceRepositoryTest.php, tests/Place/PlaceTest.php, tests/Place/ReadModel/History/HistoryProjectorTest.php, tests/Place/ReadModel/JSONLD/PlaceLDProjectorTest.php, tests/Place/ReadModel/Permission/ProjectorTest.php
- Refactored `Calendar` on `PlaceCreated`
---
=> III-6310 Refactor `Calendar` on `PlaceCreated`

src/Event/Commands/UpdateMajorInfo.php, src/Event/Event.php, src/Event/Events/MajorInfoUpdated.php, src/Event/ReadModel/JSONLD/EventLDProjector.php, src/Http/Deserializer/Event/CreateEvent.php, src/Http/Deserializer/Event/MajorInfo.php, src/Http/Deserializer/Event/MajorInfoJSONDeserializer.php, tests/Event/Commands/UpdateMajorInfoTest.php, tests/Event/EventCommandHandlerTest.php, tests/Event/EventTest.php, tests/Event/Events/MajorInfoUpdatedTest.php, tests/Event/ReadModel/History/EventPlaceHistoryProjectorTest.php, tests/Event/ReadModel/History/HistoryProjectorTest.php, tests/Event/ReadModel/JSONLD/EventLDProjectorTest.php, tests/Event/ReadModel/Relations/EventRelationsProjectorTest.php, tests/Http/Deserializer/Event/CreateEventJSONDeserializerTest.php, tests/Http/Deserializer/Event/MajorInfoJSONDeserializerTest.php, tests/Http/Event/UpdateMajorInfoRequestHandlerTest.php
- Refactored `Calendar` on `MajorInfo` of `Event`
---
=> III-6310 Refactor `Calendar` on `MajorInfo` of `Event`

src/Http/Deserializer/Place/CreatePlace.php, src/Http/Deserializer/Place/MajorInfo.php, src/Http/Deserializer/Place/MajorInfoJSONDeserializer.php, src/Place/Commands/UpdateMajorInfo.php, src/Place/Events/MajorInfoUpdated.php, src/Place/Place.php, src/Place/ReadModel/JSONLD/PlaceLDProjector.php, tests/Http/Deserializer/Place/CreatePlaceJSONDeserializerTest.php, tests/Http/Deserializer/Place/MajorInfoJSONDeserializerTest.php, tests/Http/Place/UpdateMajorInfoRequestHandlerTest.php, tests/Place/CommandHandlerTest.php, tests/Place/Commands/UpdateMajorInfoTest.php, tests/Place/Events/MajorInfoUpdatedTest.php, tests/Place/GeoCoordinatesProcessManagerTest.php, tests/Place/ReadModel/History/HistoryProjectorTest.php, tests/Place/ReadModel/JSONLD/PlaceLDProjectorTest.php
- Refactored `Calendar` on `MajorInfo` of `Place`
---
=> III-6310 Refactor `Calendar` on `MajorInfo` of `Place`

features/event/status.feature, src/Model/Serializer/ValueObject/Calendar/CalendarNormalizer.php
- Fixed single calendar edge case when setting with a reason that should also become the top reason
---
=> III-6310 Fix single calendar edge case with reason

src/Model/Serializer/ValueObject/Taxonomy/Category/CategoryDenormalizer.php, tests/Place/Events/PlaceCreatedTest.php
- Handled empty category label
---
Ticket: https://jira.uitdatabank.be/browse/III-6444
=> III-6444 Handle empty category label

app/Media/MediaServiceProvider.php, app/Organizer/OrganizerRdfServiceProvider.php, features/data/organizers/rdf/organizer-with-images.ttl, features/organizer/rdf.feature, src/Model/Serializer/ValueObject/MediaObject/MediaObjectReferencesDenormalizer.php, src/Model/ValueObject/MediaObject/ImagesToMediaObjectReferencesConvertor.php, src/Organizer/ReadModel/RDF/OrganizerJsonToTurtleConverter.php, tests/Model/ValueObject/MediaObject/ImagesToMediaObjectReferencesConvertorTest.php, tests/Organizer/ReadModel/RDF/OrganizerJsonToTurtleConverterTest.php, tests/Organizer/ReadModel/RDF/ttl/organizer-with-image.ttl
- Add images to organisation RDF projection
---
Ticket: https://jira.uitdatabank.be/browse/III-6448
=> III-6448 rdf organisation add images

app/Ownership/OwnershipRequestHandlerServiceProvider.php, features/ownership/search.feature, src/Http/Ownership/SearchOwnershipRequestHandler.php, tests/Http/Ownership/SearchOwnershipRequestHandlerTest.php
- Limited access to search ownerships
---
Ticket: https://jira.uitdatabank.be/browse/III-6146
=> III-6146 Limit access to search ownerships

src/Model/Serializer/ValueObject/MediaObject/MediaObjectReferencesDenormalizer.php, src/Model/ValueObject/MediaObject/MediaObject.php, tests/Model/Import/MediaObject/MediaManagerImageCollectionFactoryTest.php, tests/Model/Serializer/Event/EventDenormalizerTest.php, tests/Model/Serializer/Place/PlaceDenormalizerTest.php, tests/Model/ValueObject/MediaObject/MediaObjectReferenceTest.php, tests/Model/ValueObject/MediaObject/MediaObjectReferencesTest.php, tests/Model/ValueObject/MediaObject/MediaObjectTest.php
- Removed unused URL from `MediaObject`
---
Ticket: https://jira.uitdatabank.be/browse/III-6471
=> III-6471 Remove unused URL from `MediaObject`

features/Steps/ResponseSteps.php, features/data/events/rdf/event-with-all-fields.ttl, features/data/events/rdf/event-with-price-info.ttl, src/Event/ReadModel/RDF/EventJsonToTurtleConverter.php, src/Model/Serializer/ValueObject/Price/MoneyNormalizer.php, src/Model/Serializer/ValueObject/Price/TariffNormalizer.php, tests/Event/ReadModel/RDF/ttl/event-with-price-info.ttl, tests/Model/Serializer/ValueObject/Price/MoneyNormalizerTest.php, tests/Model/Serializer/ValueObject/Price/TariffNormalizerTest.php
- New Normalizers for Tariff / Money + unit tests
- Tariff / Money has named nodes in RDF projection
---
Ticket: https://jira.uitdatabank.be/browse/III-6484
=> III-6484 RDF - Convert blanknode for tariff

src/Model/ValueObject/Calendar/DateRange.php
- From and to are always required for this class, remove nulls
=> From and to are always required for this class, remove nulls

features/data/organizers/rdf/organizer-with-address.ttl, features/data/places/rdf/place-with-invalid-address.ttl, features/data/places/rdf/place-with-labels.ttl, features/data/places/rdf/place-with-required-fields.ttl, src/Event/ReadModel/RDF/EventJsonToTurtleConverter.php, src/Model/Serializer/ValueObject/Geography/TranslatedAddressNormalizer.php, src/Organizer/ReadModel/RDF/OrganizerJsonToTurtleConverter.php, src/Place/ReadModel/RDF/PlaceJsonToTurtleConverter.php, src/RDF/Editor/AddressEditor.php, tests/Event/ReadModel/RDF/ttl/event-with-dummy-location-and-multiple-calendar.ttl, tests/Event/ReadModel/RDF/ttl/event-with-dummy-location-and-single-calendar.ttl, tests/Event/ReadModel/RDF/ttl/event-with-dummy-location-name-and-multiple-calendar.ttl, tests/Event/ReadModel/RDF/ttl/event-with-dummy-location-name-and-single-calendar.ttl, tests/Event/ReadModel/RDF/ttl/event-with-dummy-location-name.ttl, tests/Event/ReadModel/RDF/ttl/event-with-dummy-location.ttl, tests/Model/Serializer/ValueObject/Geography/TranslatedAddressNormalizerTest.php, tests/Organizer/ReadModel/RDF/ttl/organizer-with-address.ttl, tests/Place/ReadModel/RDF/ttl/place-with-coordinates.ttl, tests/Place/ReadModel/RDF/ttl/place-with-labels.ttl, tests/Place/ReadModel/RDF/ttl/place-with-publication-date.ttl, tests/Place/ReadModel/RDF/ttl/place-with-status-approved.ttl, tests/Place/ReadModel/RDF/ttl/place-with-status-deleted.ttl, tests/Place/ReadModel/RDF/ttl/place-with-status-ready-for-validation.ttl, tests/Place/ReadModel/RDF/ttl/place-with-status-rejected.ttl, tests/Place/ReadModel/RDF/ttl/place-with-translations.ttl, tests/Place/ReadModel/RDF/ttl/place.ttl
- Added named nodes for location / address nodes.
- Added new TranslatedAddressNormalizer + test
---
Ticket: https://jira.uitdatabank.be/browse/III-6475
=> III-6475 Convert blanknode for address editor

features/data/events/rdf/event-with-all-fields.ttl, features/data/events/rdf/event-with-periodic-calendar-and-opening-hours.ttl, features/data/events/rdf/mixed-event-with-online-url-and-multiple-calendar.ttl, features/data/events/rdf/online-event-with-multiple-calendar.ttl, features/data/events/rdf/online-event-with-online-url-and-multiple-calendar.ttl, src/Event/ReadModel/RDF/EventJsonToTurtleConverter.php, tests/Event/ReadModel/RDF/EventJsonToTurtleConverterTest.php, tests/Event/ReadModel/RDF/ttl/event-with-calendar-multiple.ttl, tests/Event/ReadModel/RDF/ttl/event-with-calendar-periodic-and-opening-hours.ttl, tests/Event/ReadModel/RDF/ttl/event-with-calendar-periodic.ttl, tests/Event/ReadModel/RDF/ttl/event-with-calendar-single.ttl, tests/Event/ReadModel/RDF/ttl/event-with-dummy-location-and-multiple-calendar.ttl, tests/Event/ReadModel/RDF/ttl/event-with-dummy-location-and-single-calendar.ttl, tests/Event/ReadModel/RDF/ttl/event-with-dummy-location-name-and-multiple-calendar.ttl, tests/Event/ReadModel/RDF/ttl/event-with-dummy-location-name-and-single-calendar.ttl, tests/Event/ReadModel/RDF/ttl/mixed-event-with-online-url-and-multiple-calendar.ttl, tests/Event/ReadModel/RDF/ttl/mixed-event-with-online-url-and-single-calendar.ttl, tests/Event/ReadModel/RDF/ttl/mixed-event-with-single-calendar.ttl, tests/Event/ReadModel/RDF/ttl/online-event-with-online-url-and-multiple-calendar.ttl, tests/Event/ReadModel/RDF/ttl/online-event-with-online-url-and-single-calendar.ttl, tests/Event/ReadModel/RDF/ttl/online-event-with-single-calendar.ttl
- Convert blanknode for spacetime volume
---
Ticket: https://jira.uitdatabank.be/browse/III-6479
=> III-6479 Convert blanknode for spacetime volume

src/Label/ReadModels/JSON/Repository/Doctrine/DBALReadRepository.php
- Always specify a max number of Label results
---
Ticket: https://jira.publiq.be/browse/III-4855
=> Always specify a max number of Label results

app/Event/EventRdfServiceProvider.php, features/data/events/rdf/event-with-all-fields.ttl, features/data/events/rdf/event-with-videos.ttl, src/Event/ReadModel/RDF/EventJsonToTurtleConverter.php, src/RDF/Editor/VideoEditor.php, tests/Event/ReadModel/RDF/EventJsonToTurtleConverterTest.php, tests/Event/ReadModel/RDF/ttl/event-with-videos.ttl
- RDF Convert blanknode for video object
---
Ticket: https://jira.uitdatabank.be/browse/III-6493
=> III-6493 RDF Convert blanknode for video object

features/data/events/rdf/event-with-all-fields.ttl, features/data/events/rdf/event-with-booking-info.ttl, src/Event/ReadModel/RDF/EventJsonToTurtleConverter.php, tests/Event/ReadModel/RDF/ttl/event-with-booking-info.ttl
- Convert blanknode for boekingsinfo on event
---
Ticket: https://jira.uitdatabank.be/browse/III-6483
=> III-6483 RDF Convert blanknode for boekingsinfo on event

Makefile, docker/php/Dockerfile, features/event/export.feature
Reverts cultuurnet/udb3-backend#1833
=> III-6367: Install prince in Dockerfile

features/data/events/rdf/event-with-all-fields.ttl, features/data/events/rdf/event-with-labels.ttl, features/data/organizers/rdf/organizer-with-labels.ttl, features/data/places/rdf/place-with-invalid-address.ttl, features/data/places/rdf/place-with-labels.ttl, src/RDF/Editor/LabelEditor.php, tests/Event/ReadModel/RDF/ttl/event-with-labels.ttl, tests/Organizer/ReadModel/RDF/ttl/organizer-with-labels.ttl, tests/Place/ReadModel/RDF/ttl/place-with-labels.ttl
- Change predicate uri for labels from rdfs label to dcat keyword
---
Ticket: https://jira.uitdatabank.be/browse/III-6507
=> III-6507 RDF Change predicate uri for labels from rdfs label to dcat keyword

app/EventBus/EventBusServiceProvider.php, app/Media/MediaServiceProvider.php, src/Media/Properties/MIMEType.php, src/Media/ReadModel/ImageLDProjector.php, tests/Media/Properties/MIMETypeTest.php, tests/Media/ReadModel/ImageLDProjectorTest.php
- Add JSON-LD projector for `MediaObjectCreated`
---
Ticket: https://jira.uitdatabank.be/browse/III-6471
=> III-6471 Add JSON-LD projector for MediaObjectCreated

.github/CODEOWNERS
=> make stef codeowner

features/event/organizer.feature, features/place/organizer.feature, features/uitpas/organizers.feature
-  Fixed acceptance tests for invalid organizer after new middleware was added
=> Fix acceptance tests for invalid organizer

src/Media/Events/MediaObjectCreated.php, tests/Media/MediaObjectCreatedTest.php
- Clipped long copyright to max 250 characters
---
Ticket: https://jira.uitdatabank.be/browse/III-6529
=> III-6529 Clip long copyright to max 250 characters

app/Console/Command/KeycloakCommand.php
- Fixed KeycloakCommand constructor by changing parameter type
=> Change KeycloakCommand constructor parameter type

app/Console/ConsoleServiceProvider.php, src/Kinepolis/Trailer/YoutubeTrailerRepository.php, tests/Kinepolis/Trailer/YoutubeTrailerRepositoryTest.php
- `YoutubeTrailerRepository`: Add Logging
- `YoutubeTrailerRepositoryTest` & `ConsoleServiceProvder`: Update `constructor` of `TrailerRepository`
---
Ticket: https://jira.publiq.be/browse/III-6526
=> III-6526 add YouTube logging

lib/tasks/build_artifact.rake
---
Ticket: https://jira.uitdatabank.be/browse/III-6523
=> Don't package development setups and tests

docker.md, docker/config.sh
- `config.sh`: update shellscript to handle both `io.uitdatabank.local` & `mailpit.uitdatabank.local`
- `docker.md`: update links to `mailpit.uitdatabank.local`
---
Ticket: https://jira.publiq.be/browse/III-6545
=> III-6545 mailpit extra

src/Mailer/templates/ownership/approved.html.twig, src/Mailer/templates/ownership/approved.txt.twig, src/Mailer/templates/ownership/partials/_button.html.twig, src/Mailer/templates/ownership/partials/_footer.html.twig, src/Mailer/templates/ownership/partials/_header.html.twig, src/Mailer/templates/ownership/rejected.html.twig, src/Mailer/templates/ownership/rejected.txt.twig, src/Mailer/templates/ownership/requested.html.twig, src/Mailer/templates/ownership/requested.txt.twig
- Changed copy of the emails to [the latest version](https://docs.google.com/document/d/1LtNU-5DG6jm_PGa0t9UVyy2zyjIFodU2fN8Fk8ZJOfI/edit?usp=sharing)
- Added mail template based on the Mailjet Publiq Platform template. Code is ugly because I needed to use inline styles for emails. Tested in Outlook + Gmail.
---
Ticket: https://jira.uitdatabank.be/browse/III-6539
=> III-6539 Final copy email ownership

features/role/users.feature
- Remove personal accounts from tests
---
Ticket: https://jira.uitdatabank.be/browse/III-6300
=> III-6300 Remove personal accounts from tests

Jenkinsfile
---
Ticket: https://jira.uitdatabank.be/browse/III-6523
=> Move build and deployment of UiTdatabank entry API to Ubuntu 20.04

.github/CODEOWNERS
- `CODEOWNERS`: Offboarding Stef
---
=> offboarding Stef

features/ownership/approve.feature, features/ownership/delete.feature, features/ownership/reject.feature, src/Ownership/Readmodels/OwnershipLDProjector.php, tests/Ownership/Readmodels/OwnershipLDProjectorTest.php
- Updated the ownership JSON projections, to show user id / email / date when approved/rejected/deleted
- Update feature tests to prove working concept
---
Ticket: https://jira.uitdatabank.be/browse/III-6585
=> III-6585 Store approver by ownership change

src/Mailer/Handler/SendOwnershipMailCommandHandler.php, src/Mailer/templates/ownership/rejected.html.twig, src/Mailer/templates/ownership/requested.html.twig, tests/Mailer/Handler/SendOwnershipMailCommandHandlerTest.php
- Copy change: Change "beheers aanvraag" and "beheersaanvraag" to "beheeraanvraag"
---
Ticket: https://jira.uitdatabank.be/browse/III-6586
=> III-6586 Change "beheers aanvraag" and "beheersaanvraag" to "beheeraanvraag"

composer.json, composer.lock, src/Http/Offer/UpdateLabelsRequestHandler.php, src/Http/Request/Body/JsonSchemaLocator.php, tests/Http/Offer/UpdateLabelsRequestHandlerTest.php
- Added validation for bulk update labels endpoint
---
Ticket: https://jira.uitdatabank.be/browse/III-6634
=> III-6634 Add validation bulk update labels

src/Cultuurkuur/data/regions.json
-Some labels where duplicated, and wrong in the source spreadsheet, every label is now unique.
---
Ticket: https://jira.uitdatabank.be/browse/III-6579
=> III-6579 Updated region labels, no more duplicates

tests/Offer/OfferTest.php
- Improved test label names for import and replace
---
Ticket: https://jira.uitdatabank.be/browse/III-6634
=> III-6634 Improve test label names for import and replace

.github/CODEOWNERS
Make bert codeowner, remove Paul
=> Make bert codeowner, remove Paul

features/search/facets.feature
- `search/facets.feature`: Add acceptance tests for searching with facets.
---
Ticket: https://jira.publiq.be/browse/III-6743
=> III-6743 Add Acceptance tests for facets

src/Offer/ExtractOfferName.php, tests/Offer/ExtractOfferNameTest.php
-  name can be string, not array
- 
---
Ticket: https://jira.uitdatabank.be/browse/III-6799
=> III-6799 BUGFIX name can be string, not array

docker-compose.yml
- Fixed volume path of the MySQL Docker container
=> Fix volume path of MySQL Docker container
