cultuurnet/udb3-backend

src/Migrations/Version19700101000000.php, src/Migrations/Version19700101000001.php, src/Migrations/Version19700101000002.php, src/Migrations/Version19700101000003.php
In order to create a clean migration path from an empty database
to the latest schema version, a number of missing migrations have
been added here. This makes the database population through migrations
equivalent to the method via the DatabaseSchemaInstaller class.
Database migrations have been numbered starting from epoch (01/01/1970)
for lack of availability of a more accurate timestamp. This will
ensure they're processed first.
=> Backfill migrations to create clean migration path

web/index.php
The service is registered in bootstrap.php and was registered a second time in index.php.
=> III-331: Removed duplicate saved searches provider registration

src/Migrations/Version20170731151814.php
As discussed with @willaerk , we're going to remove the custom `install` command and setup the application using the doctrine migrations instead. However one of these crashes on an existing index when running all migrations from start to end. This PR fixes that.
=> Fix migration crashing on existing index

src/Migrations/Version20190509112328.php
This will make sure the columns becomes `longtext` on both existing and new installations since we're using migrations to setup new installations since https://bitbucket.org/cultuurnet/udb3-vagrant/pull-requests/60/install-the-silex-database-using/diff
=> III-2917 Change constraint_query column to longtext

bootstrap.php
Otherwise events that are dispatched as a result from a process manager will not be published because the process manager itself is handling an event and one event bus instance does not allow multiple events at the same time.
=> Don't share event bus instances

build.xml, migrations.yml
- Updated the path to the migration classes to `app`
- Included the `app` directory in the `phing` tasks (e.g. linting, coding standards, ...)
=> Fix issues with src -> app rename in tooling config

app/CommandHandling/CommandBusServiceProvider.php, app/ErrorHandlerProvider.php
- Permissions are now checked again when dispatching a command
- Unauthorized commands now return a `401` status code instead of a `400`
=> Fix permission check when dispatching commands

composer.json, composer.lock
- `cultuurnet/valueobjects` now uses version `^3.1`
---
This should remove warnings during the build process
=> Upgrade cultuurnet/valueobjects library

app/Export/ExportServiceProvider.php
- Fixed an incorrect path to the HTML templates for the PDF exports, which caused every export to crash (even for the other types because this code was bootstrapped regardless of the export type).
---
Ticket: https://jira.uitdatabank.be/browse/III-3002
=> III-3002 Fix exports crashing on the backend

app/UiTPAS/UiTPASIncomingEventServicesProvider.php, src/UiTPAS/Event/EventProcessManager.php, src/UiTPAS/Label/HttpUiTPASLabelsRepository.php, src/UiTPAS/Label/UiTPASLabelsRepository.php, src/UiTPAS/Label/UiTPASLabelsRepositoryInterface.php, tests/UiTPAS/Event/EventProcessManagerTest.php, tests/UiTPAS/Label/HttpUiTPASLabelsRepositoryTest.php
- UiTPAS labels are now applied to events based on the active card systems of the event, and no longer based on the UiTPAS labels on the organizer.
- Removing irrelevant UiTPAS labels is now a bit smarter, the process manager no longer removes an UiTPAS label to re-add it later again.
---
Ticket: https://jira.uitdatabank.be/browse/III-2668
---
Note that the list of labels in the [`uitpas-service` configuration](https://github.com/cultuurnet/udb3-uitpas-service/blob/master/config.dist.yml#L4-L14) will need to be updated to add the correct card system ids instead of those (currently unused) label keys. Will also mention this in the ticket.
=> Apply UiTPAS labels to events based on active card systems

src/Curators/LabelFactory.php, src/Curators/PublisherName.php, tests/Curators/LabelFactoryTest.php, tests/Curators/PublisherNameTest.php
- `PublisherName` VO now always works with lowercase so `Bruzz` will match `bruzz` in the configuration
---
Ticket: https://jira.uitdatabank.be/browse/III-3037
=> III-3037 - Publisher name should be case insensitive

src/Model/Import/Organizer/OrganizerDocumentImporter.php, tests/Model/Import/Organizer/OrganizerDocumentImporterTest.php
- Additional addresses in different languages are now correctly added when importing an organizer
---
Ticket: https://jira.uitdatabank.be/browse/III-2907
=> III-2907 - Import translated addresses for organizers

src/EventExport/Format/HTML/HTMLEventFormatter.php, src/EventExport/Format/HTML/templates/export.map.activities.html.twig, src/EventExport/Format/HTML/templates/export.tips.html.twig, tests/EventExport/Format/HTML/HTMLEventFormatterTest.php, tests/EventExport/samples/event_with_dummy_location.json
- When exporting an event with a dummy location, it will only show the location name and not the full address.
---
Ticket: https://jira.uitdatabank.be/browse/III-3012
=> Only show location name for dummy locations in PDF exports

bootstrap.php
- Bootstrapping to set a list of configured dummy ids on `LocationId` value object
---
Ticket: https://jira.uitdatabank.be/browse/III-3053
=> III-3053 - Statically set the list of dummy place ids during bootstrapping

app/UDB2IncomingEventServicesProvider.php, src/UDB2/Event/EventImporter.php
- When importing an event via cdbxml the audienceType of that event is automatically set to education if it has a dummy location meant for bookable education events.
---
Ticket: https://jira.uitdatabank.be/browse/III-3054
=> III-3054 Set audienceType to education when importing event with dummy location

app/Console/MarkPlaceAsDuplicateCommand.php, app/Event/EventEditingServiceProvider.php, app/Place/PlaceEditingServiceProvider.php, bin/udb3.php, bootstrap.php, composer.lock, tests/Http/Jobs/ReadRestControllerTest.php
- CLI command to mark place as duplicate
- Configured `MarkAsDuplicateCommandHandler` on the command bus.
- Configured `LocationMarkedAsDuplicateProcessManager` on the event bus
- Updated `cultuurnet/udb3` to latest version
- A non-existing class that was imported in a service provider
---
Ticket: https://jira.uitdatabank.be/browse/III-3045
=> III-3045 - Add CLI command to mark place as duplicate

app/Event/EventEditingServiceProvider.php, bootstrap.php, composer.lock
- Service provisioning for `RelocateEventToCanonicalPlace` process manager
- `RelocateEventToCanonicalPlace` is now configured as an event listener
- `udb3-silex` is now using the latest version of `cultuurnet/udb3`
---
Ticket: https://jira.uitdatabank.be/browse/III-3047
=> III-3047 - Wire up Process Manager to relocate events

composer.json, composer.lock
- No longer depend on a specific commit of the `udb3-api-guard` dependency
=> Use latest version for api guard dependency

app/Console/DispatchMarkedAsDuplicateEventCommand.php, bin/udb3.php
- Added CLI command to re-dispatch MarkedAsDuplicateEvent to re-trigger LocationMarkedAsDuplicate process manager for testing purposes
---
Ticket: https://jira.uitdatabank.be/browse/III-3070
=> III-3070 Add command to re-dispatch MarkedAsDuplicate event

composer.lock, src/Model/Import/Event/EventDocumentImporter.php, src/Model/Import/Taxonomy/Label/LockedLabelRepository.php, src/Model/Import/Taxonomy/Label/RelationshipModelLockedLabelRepository.php, tests/Model/Import/Event/EventDocumentImporterTest.php, tests/Model/Import/Taxonomy/Label/RelationshipModelLockedLabelRepositoryTest.php
- Uitpas labels are no longer removed from events after import. This was originally tried in https://github.com/cultuurnet/udb3-silex/pull/381 but that didn't cover everything.
---
Ticket: https://jira.uitdatabank.be/browse/III-3087
=> III-3087 BIS - Explicitly pass which labels can be removed from the offer

composer.json, composer.lock
- Updated udb3 dependency. Since composer still didn't want to update it to the latest commit after 15 minutes I had to hardcode the commit hash.
---
Ticket: https://jira.uitdatabank.be/browse/III-3080
=> Update udb3-php dependency

app/Authentication/UitidApiKeyServiceProvider.php, app/CommandHandling/CommandBusServiceProvider.php, app/CommandHandling/ContextDecoratedCommandBus.php, app/CommandHandling/ContextFactory.php, app/Impersonator.php, app/Metadata/MetadataServiceProvider.php, bootstrap.php, composer.json, composer.lock, web/index.php
- Refactored the way context / metadata is determined and set.
- The api key is now added to all events' metadata instead of only in some edge cases.
- Removed `auth_jwt` and `uitid_token_credentials` from the metadata that gets stored as they were cast to `{}` anyway and are too sensitive to store.
---
Ticket: https://jira.uitdatabank.be/browse/III-3113
=> Add api key to event metadata and history projection

app/Impersonator.php, bin/udb3.php, bootstrap.php
- Fixed console commands crashing because of a type error in the `Impersonator` class caused by invalid `uitid_token_credentials` data
---
Ticket: https://jira.uitdatabank.be/browse/III-3113
=> III-3113 Fix type error caused by uitid_token_credentials being an array

composer.json, composer.lock, src/Event/ReadModel/History/HistoryProjector.php, src/Event/ReadModel/History/Log.php, src/Offer/ReadModel/History/OfferHistoryProjector.php, tests/Event/ReadModel/History/HistoryProjectorTest.php, tests/Event/ReadModel/History/event-a0ee7b1c-a9c1-4da1-af7e-d15496014656.xml, tests/Event/ReadModel/History/event-a2d50a8d-5b83-4c8b-84e6-e9c0bacbb1a3.xml
- Added the history projectors from udb3-php
---
Ticket: https://jira.uitdatabank.be/browse/III-3141
---
Note: I had to remove the tests for `OfferHistoryProjector` because they relied on classes that are only found in the `tests` directory of `udb3-php`. However, the exact same functionality was also being tested in `HistoryProjector`, so we still have the same coverage.
=> Move the history projectors

src/Event/ReadModel/History/HistoryProjector.php, src/Event/ReadModel/History/Log.php, src/Offer/ReadModel/History/OfferHistoryProjector.php, tests/Event/ReadModel/History/HistoryProjectorTest.php
- If the event metadata contains a consumer name, it is now projected in the history projection
---
Ticket: https://jira.uitdatabank.be/browse/III-3141
=> Add consumer name to history projection

app/Organizer/OrganizerGeoCoordinatesServiceProvider.php, src/Organizer/ProcessManager/GeoCoordinatesProcessManager.php, tests/Organizer/ProcessManager/GeoCoordinatesProcessManagerTest.php, tests/Organizer/Samples/actor.xml, tests/Organizer/Samples/actor_without_contactinfo.xml, tests/Organizer/Samples/actor_without_physical_address.xml
- Added geocoding for organizer updates from cdbxml. This implementation and the tests were copied and adjusted from the [Place GeoCoordinatesProcessManager in the cultuurnet/udb3 
package](https://github.com/cultuurnet/udb3-php/blob/master/src/Place/GeoCoordinatesProcessManager.php#L75-L137)
---
Ticket: https://jira.uitdatabank.be/browse/III-3148
Note that this is pointing to another feature branch which should be merged first ideally.
=> III-3148 Geocode organizer address updates from cdbxml

src/EventExport/EventExportService.php
- Add a logger to the search results generator in the export service. This generator already has logging support but was not configured in this context (only in the mark as duplicate context)
---
Ticket: https://jira.uitdatabank.be/browse/III-3153
=> III-3153 Add logger to search results generator

app/Event/EventEditingServiceProvider.php
- LocationMarkedAsDuplicateProcessManager should no longer record new events during a replay
=> Wrap LocationMarkedAsDuplicateProcessManager in ReplayFilteringEventListener

app/Event/EventEditingServiceProvider.php
- Don't relocate events to canonical places when replaying
=> Do not relocate events to canonical place on replays

src/Organizer/ReadModel/JSONLD/CdbXMLImporter.php, tests/Organizer/OrganizerLDProjectorTest.php
- Organizer names are now projected as translatable properties when imported or updated from UDB2. Previous translations that are not found in the CDBXML will be kept (same behaviour as events and places).
---
Ticket: https://jira.uitdatabank.be/browse/III-3245
=> III-3245 Project organizer name as translatable property on udb2 imports/updates

composer.lock, src/User/Auth0UserIdentityResolver.php, tests/User/Auth0UserIdentityResolverTest.php
- emails with `+` sing would not return correct result
- urlencode emails before sending them as queries to Auth0 SDK
---
Ticket:
[Jira](https://jira.uitdatabank.be/browse/III-3243)
=> Bug: III-3243

src/User/Auth0UserIdentityResolver.php, tests/User/Auth0UserIdentityResolverTest.php
- use old uuid from Auth0 response if it is present (for migrated users)
---
Ticket:
[Jira](https://jira.uitdatabank.be/browse/III-3254)
=> Bug: III-3254

app/Migrations/Version20200526130622.php
- Removed `my_organizers` table. This was a read model that has been replaced with SAPI3. All references in the code (outside of migrations) had already been removed.
=> Drop unused my_organizers table

app/Event/ProductionControllerProvider.php, src/Http/Productions/ProductionsWriteController.php, tests/Http/Productions/ProductionsWriteControllerTest.php
- Route to remove an event from an existing production: `DELETE /{productionId}/events/{eventId}`
=> Add route to remove an event from an existing production

app/Event/EventJSONLDServiceProvider.php, src/Event/Productions/ProductionEnrichedEventRepository.php, src/Event/Productions/ProductionRepository.php, tests/Event/Productions/ProductionEnrichedEventRepositoryTest.php, tests/Event/Productions/ProductionRepositoryTest.php
- Events now have an additional `production` property in JSONLD.
---
https://confluence.uitdatabank.be/pages/viewpage.action?pageId=26192041#Backend(UDB)-5/Propertyforstoringlinkedevents
=> Enrich events with production

src/Event/Productions/EventCannotBeAddedToProduction.php, src/Event/Productions/ProductionCommandHandler.php, src/Event/Productions/RejectSuggestedEventPair.php, src/Event/Productions/SimilarEventPair.php, src/Http/Productions/ProductionsWriteController.php, tests/Event/Productions/ProductionCommandHandlerTest.php
- Renamed methods that deal with a side-effect to better clarify their reactive nature. We decided not to implement a full event+listener flow due to the lack of simple event bus in UDB3 that is not forcing the Broadway event structure.
- `RejectSuggestedEventPair` now uses the `SimilarEventPair` VO instead of relying on a potentially faulty array of strings.
- Unused method
- Trying to create a new production with an event that already belongs to a production now throws the correct domain exception instead of a unique constraint error on database level.
=> Clean up and fix production command handling

src/Offer/Commands/Moderation/AbstractPublish.php, tests/Http/Offer/PatchOfferRestControllerTest.php, tests/Offer/Commands/Moderation/AbstractPublishTest.php
- Publishing only allows a future publication date or it will default to now.
---
Ticket: https://jira.uitdatabank.be/browse/III-3362
=> Fix issue with publication date in the past breaking ETL tools

.github/workflows/ci.yml, app/Migrations/Version20200804090405.php, composer.json, composer.lock, src/Event/Productions/GroupEventsAsProduction.php, src/Event/Productions/ProductionRepository.php, src/Http/Label/ReadRestController.php, src/Http/Productions/ProductionsSearchController.php, src/Http/Response/PagedCollectionResponse.php, tests/Http/Label/ReadRestControllerTest.php, tests/Http/Productions/ProductionsSearchControllerTest.php
- Added `start` parameter to productions search endpoint
- Added `limit` parameter to productions search endpoint
- The response from the productions search endoint is now a paged collection object
- The `name` parameter is now optional, and when omitted the search endpoint will return all productions (paginated)
- Increased the length of `name` column from 32 to 255
- Added missing return type in `GroupEventsAsProduction`
---
Ticket: https://jira.uitdatabank.be/browse/III-3403
=> III-3403 Productions backend tweaks/fixes

app/Event/ProductionServiceProvider.php, src/Event/Productions/EventCannotBeAddedToProduction.php, src/Event/Productions/ProductionCommandHandler.php, src/Event/Productions/SimilaritiesClient.php, tests/Event/Productions/ProductionCommandHandlerTest.php
- Events that are being grouped as production or added to an existing production are now validated for their existence.
- Call to Google Cloud Api to permanently exclude an event pair now works correctly
---
Ticket: https://jira.uitdatabank.be/browse/III-3324
=> Validate if event exists

src/Event/Productions/EventCannotBeRemovedFromProduction.php, src/Event/Productions/ProductionCommandHandler.php, tests/Event/Productions/ProductionCommandHandlerTest.php
- To align with adding an event to a production, we now check if an event and production exist before we try to remove it. That way, endpoint responses will be consistent across the productions api.
---
Ticket: https://jira.uitdatabank.be/browse/III-3425
=> III-3425 - Check if event can be removed from production

src/Event/Productions/ProductionRepository.php
- Productions search by name now uses `LIKE` (with wildcards) instead of `MATCH` to make autocomplete/typeahead possible.
---
Ticket: https://jira.uitdatabank.be/browse/III-3451
=> III-3451 Use LIKE instead of MATCH for productions search

composer.json, composer.lock, src/Http/Deserializer/Calendar/CalendarForEventDataValidator.php, src/Http/Deserializer/Calendar/CalendarJSONDeserializer.php, tests/Event/Commands/UpdateCalendarTest.php, tests/Event/EventCommandHandlerTest.php, tests/Event/EventEditingServiceTest.php, tests/Event/EventTest.php, tests/Event/ReadModel/JSONLD/EventLDProjectorTest.php, tests/Http/Deserializer/Calendar/CalendarForEventDataValidatorTest.php, tests/Offer/AvailableToTest.php, tests/Offer/OfferTest.php, tests/Place/Commands/UpdateCalendarTest.php, tests/Place/DefaultPlaceEditingServiceTest.php, tests/Place/PlaceCommandHandlerTest.php, tests/Place/PlaceTest.php, tests/Place/ReadModel/JSONLD/PlaceLDProjectorTest.php, tests/samples/serialized_event_major_info_updated_class.json
- Removed requirement for start and end date for `single` and `multiple` calendar types.
- Fixed broken tests after `cultuurnet/udb3` update
---
Ticket: https://jira.uitdatabank.be/browse/III-3433
Related PR: https://github.com/cultuurnet/udb3-php/pull/471
=> III-3433 Remove validation for start and end date for single and multiple calendars

src/Http/Role/EditRoleRestController.php, tests/Http/Role/EditRoleRestControllerTest.php
- Fixed fatal error when trying to delete a role because of a "missing" $roleId argument. This was caused by a name change from `$id` to `$roleId` in 22b95460cd22d7b0dadf9b1f2d224550a978dc44 and 87452c49b1c29e2a1310cb5ea4ad3b35d80c72b6. This change results in a fatal error because the `RoleControllerProvider` defines the parameter name as `{id}`, not `{roleId}`. And changing it to `{roleId}` in the ControllerProvider results in CORS issues, because other HTTP methods on the same path (`get`, `patch`) use `{id}` as well so this confuses Silex it seems. We could also fix it by making all of these controller methods use `$roleId` instead of `$id` but that's a bigger change and I think in this context it should be clear that it's a role id.
---
Ticket: …
=> Fix id argument in role delete method

composer.lock
- The application now uses the latest version of `calendar-summary-v3` with new calendar formats
---
Ticket: https://jira.uitdatabank.be/browse/III-3482
=> III-3482 - Upgrade cultuurnet/calendar-summary-v3 to latest version

app/Migrations/Version20201015095142.php, app/PurgeServiceProvider.php
- Unused read model table `event_variation_search_index`
---
Ticket: https://jira.uitdatabank.be/browse/III-3502
=> Remove event variation search index table

app/Place/PlaceControllerProvider.php, src/Doctrine/ReadModel/CacheDocumentRepository.php, src/Event/Productions/ProductionEnrichedEventRepository.php, src/Event/ReadModel/DocumentGoneException.php, src/Http/Event/ReadEventRestController.php, src/Http/Place/ReadPlaceRestController.php, src/Place/DummyPlaceProjectionEnricher.php, src/ReadModel/DocumentDoesNotExist.php, src/ReadModel/DocumentDoesNotExistException.php, src/ReadModel/DocumentRepository.php, src/ReadModel/DocumentRepositoryDecorator.php, src/ReadModel/InMemoryDocumentRepository.php, tests/Event/Productions/ProductionEnrichedEventRepositoryTest.php, tests/Http/Event/ReadEventRestControllerTest.php, tests/Http/Place/ReadPlaceRestControllerTest.php, tests/Place/DummyPlaceProjectionEnricherTest.php
- Refactored place read controller to use document repository directly instead of a service in-between
- Deprecated `DocumentRepository::get()` in favor of a new `DocumentRepository::fetch()` which has more consistent error-handling
- Added `DocumentRepository::fetch()` which always throws if a document is not found, instead of either returning `null` if it's not found or throwing if it was deleted. The difference can still be deduced based on the `isNotFound()` and `isGone()` methods on the new exception type. 
---
Ticket: https://jira.uitdatabank.be/browse/III-3583
---
Note: The new `fetch()` method should also be useful for https://jira.uitdatabank.be/browse/III-3593 in which we want to remove a service that converts the `null` return value to an exception
=> III-3583 use document repository in place read controller

app/PurgeServiceProvider.php
- The table `index_readmodel` no longer exists so no purge is needed
- Added missing read models to purge
---
Ticket: https://jira.uitdatabank.be/browse/III-3500
=> Avoid purging of the index_readmodel table

app/Event/EventJSONLDServiceProvider.php, app/Place/PlaceJSONLDServiceProvider.php, src/Offer/ReadModel/JSONLD/NewPropertyPolyfillOfferRepository.php, tests/Offer/ReadModel/JSONLD/NewPropertyPolyfillOfferRepositoryTest.php
- Added an offer repository decorator that can polyfill new properties with default values.
---
Ticket: https://jira.uitdatabank.be/browse/III-3570
I went with a generic polyfilling decorator because these polyfills are only relevant until we do a new replay, so we can use this to do all the polyfills in one place and then remove them all once we do a replay. That way we also don't have to duplicate all the bootstrapping and boilerplate code.
=> III-3570 Polyfill new status property

app/Console/SQL/get_all_events.sql, app/Console/SQL/get_all_places.sql, app/Console/SQL/get_events_with_missing_or_outdated_coordinates.sql, app/Console/SQL/get_places_with_missing_or_outdated_coordinates.sql
- We now use the correct event_store table when geocoding places and events.
=> Use correct table when geocoding events and places

app/Console/GeocodeEventCommand.php, app/Console/GeocodePlaceCommand.php
- Changed the `event:geocode` and `place:geocode` commands to not geocode deleted or rejected events and places
---
Ticket: https://jira.uitdatabank.be/browse/III-3634
=> Omit deleted & rejected events/places from geocoding

app/Console/UpdateOfferStatusCommand.php
- Late refactoring to the update offer status CLI command left it in a state where some required properties were unset. This is now fixed.
=> Fix UpdateOfferStatus CLI command

src/Event/Event.php, src/Place/Place.php
- Updating the status of events and places imported from UDB2 was not possible because their calendars weren't set properly in the aggregate
---
Ticket: https://jira.uitdatabank.be/browse/III-3655
=> Fix update status of udb2 imported events

app/Console/ChangeOfferOwner.php, app/Console/ChangeOfferOwnerInBulk.php, app/Offer/OfferServiceProvider.php, bin/udb3.php, bootstrap.php, src/Event/Event.php, src/Event/Events/OwnerChanged.php, src/Event/ReadModel/JSONLD/EventLDProjector.php, src/Event/ReadModel/Permission/Projector.php, src/Offer/CommandHandlers/ChangeOwnerHandler.php, src/Offer/Commands/ChangeOwner.php, src/Offer/Events/AbstractOwnerChanged.php, src/Offer/Offer.php, src/Offer/ReadModel/Permission/Doctrine/DBALRepository.php, src/Offer/ReadModel/Permission/PermissionRepositoryInterface.php, src/Place/Events/OwnerChanged.php, src/Place/Place.php, src/Place/ReadModel/JSONLD/PlaceLDProjector.php, src/Place/ReadModel/Permission/Projector.php, tests/Event/ReadModel/JSONLD/EventLDProjectorTest.php, tests/Event/ReadModel/Permission/ProjectorTest.php, tests/Offer/CommandHandlers/ChangeOwnerHandlerTest.php, tests/Offer/Item/Events/OwnerChanged.php, tests/Offer/Item/Item.php, tests/Offer/OfferTest.php, tests/Offer/ReadModel/Permission/Doctrine/DBALRepositoryTest.php, tests/Place/ReadModel/JSONLD/PlaceLDProjectorTest.php, tests/Place/ReadModel/Permission/ProjectorTest.php
- Added two CLI commands to change the owner of events/places. Either for one event/place based on its id, or for all events/places that belong to a specific user id.
---
Ticket: https://jira.uitdatabank.be/browse/III-3691
Context is described in the ticket + comments, but a summary:
- When we integrated with Auth0, we refactored UDB3 to determine the user id as follows: If the user has a v1 id in their token, use that to make sure their roles, permissions, entered events/places etc keep working. Also create new events/places with this v1 id. So basically always use the v1 id if there is one. If there's no v1 id, use the v2 (= Auth0) id.
- At one point, there was a bug in Auth0 which caused users that were migrated from v1 and used social media to login to lose their v1 id.
- These users …
=> III-3691 Add ability to change the owner of events/places

app/ErrorHandlerProvider.php, app/UiTPASService/UiTPASServiceEventControllerProvider.php, app/UiTPASService/UiTPASServiceLabelsControllerProvider.php, app/UiTPASService/UiTPASServiceOrganizerControllerProvider.php, src/UiTPASService/Controller/EventCardSystemsController.php, src/UiTPASService/Controller/EventDetailController.php, src/UiTPASService/Controller/OrganizerCardSystemsController.php, src/UiTPASService/Controller/Response/CardSystemsJsonResponse.php, tests/UiTPASService/Controller/EventCardSystemsControllerTest.php, tests/UiTPASService/Controller/EventDetailControllerTest.php, tests/UiTPASService/Controller/OrganizerCardSystemsControllerTest.php, tests/UiTPASService/Controller/Response/CardSystemsJsonResponseTest.php, tests/UiTPASService/Controller/Response/data/cardSystems.json, web/index.php
- Added `/uitpas/events/` endpoints from udb3-uitpas-service
- Added `/uitpas/organizers/` endpoints from udb3-uitpas-service
- Added better error handling for CultureFeed exceptions, based on udb3-uitpas-service
- Added 401 status code for response when a token is missing in a request that needs one, using a custom "EntryPoint" in the firewall configuration (also based on udb3-uitpas-service and an improvement over the default redirect to `/login` which doesn't exist)
- Refactored code of existing `/uitpas/labels/` endpoint a bit for consistency
---
Ticket: https://jira.uitdatabank.be/browse/III-3733
=> III-3733 Add uitpas service endpoints

bootstrap.php, phpstan.neon
- Updated PHPStan config to also check `bootstrap.php` and `web/index.php` (these were added to `paths` instead of `bootstrapFiles` because `bootstrapFiles` is bootstrapping that needs to happen before phpstan can start its checks, not bootstrapping of the app)
- Fixed two PHPStan errors that popped up after the config changes
=> Updated PHPStan config to include bootstrap.php and web/index.php

src/Model/ValueObject/Audience/AgeRange.php, src/Offer/AgeRange.php, tests/Model/ValueObject/Audience/AgeRangeTest.php, tests/Offer/AgeRangeTest.php
- Make sure to preserve ` - ` as all ages and don't convert it to `0- `
---
Ticket: https://jira.uitdatabank.be/browse/III-3766
=> III-3766 Preserve `-` as al ages

app/Console/UpdateUniqueLabels.php, app/Console/UpdateUniqueOrganizers.php, bin/udb3.php
- Add script to update the unique websites of organizers based on the events `OrganizerCreatedWithUniqueWebsite` and `WebsiteUpdated`
Note: An extra select statement was added to verify what is already inside the unique table. This makes it possible to do an update or insert. It also makes it possible to just skip an organizer that is already correctly stored inside the unique table.
---
Ticket: https://jira.uitdatabank.be/browse/III-3653
=> III-3653 Update unique organizers

src/Offer/ReadModel/JSONLD/NewPropertyPolyfillOfferRepository.php, tests/Offer/ReadModel/JSONLD/NewPropertyPolyfillOfferRepositoryTest.php
- Places no longer accidentally get a `location` property through the polyfill logic
---
Ticket: https://jira.uitdatabank.be/browse/III-3815
=> III-3815 Do not add a location property on places through polyfill logic

app/Console/ReindexOffersWithPopularityScore.php, bin/udb3.php
- Avoid re-indexing related events when updating the popularity of a place. This was fixed by injecting the `AMQPPublisher` inside the command and directly pushing the projected events to the queue.
---
Ticket: https://jira.uitdatabank.be/browse/III-3813
=> III-3813 Avoid "cascading" replay

src/Event/Productions/ProductionRepository.php
- Using `GROUP_CONCAT` can lead to clipping when the result is bigger than the column size. This was removed and an iteration is used to create the productions which their events.
---
Ticket: https://jira.uitdatabank.be/browse/III-3677
=> III-3677 Prevent truncated production search

app/Console/ConcludeCommand.php
- The query to get concluded events still used the SAPI2 syntax and properties instead of the SAPI3 syntax. This was fixed so the conclude command finds again events to conclude.
---
Ticket: https://jira.uitdatabank.be/browse/III-3340
=> III-3340 Fix conclude query

app/Migrations/Version20210302114100.php
- Removed primary key in `labels_import` table. This would prevent multiple rows from being added for the same id, while we do want to allow that to make it possible to add multiple labels to a single event/place through auto-classification by the data team in the future.
---
Ticket: https://jira.uitdatabank.be/browse/III-3608
=> III-3608 Drop primary key in labels_import table

.github/workflows/ci.yml
- Only require the bcmath and tidy extensions for the test step
=> Remove all PHP extensions from GitHub Actions steps

app/Console/UpdateOfferStatusCommand.php
- Catch exceptions when updating the status of events instead of bailing out. These exceptions will be dumped when the command finishes
- Stop the command when no offers were found
- Default answer for update is false.
---
Ticket: https://jira.uitdatabank.be/browse/III-3838
=> III-3838 Keep setting status on offers in case of exceptions

app/CommandHandling/ContextFactory.php
- Use `toString` to convert an API key to a string
=> Use `toString` to convert api key to a string

src/EventSourcing/DBAL/DBALEventStoreException.php
- Fix crash because the message is type string and not null. Can be reproduced by adding an existing label.
=> Fix crash because message is type string and not null

app/Console/ConsumeCommand.php
- Avoid non-blocking `wait` statement to improve performance. The wait used to be called in non-blocking mode and with a timeout. But when the mode is set to non-blocking the timeout is discarded.
---
This is the line that causes the discard in `php-amqplib`: https://github.com/php-amqplib/php-amqplib/blob/master/PhpAmqpLib/Channel/AbstractChannel.php#L345
This is the PR that changed it in `php-amqplib`: https://github.com/php-amqplib/php-amqplib/commit/242db8072cb46f3da79e76300140a6e152d04d37
This is the PR that changed it inside `udb3-silex`: https://github.com/cultuurnet/udb3-silex/commit/7a12ad601f60b5bee928feee80c268d6f3e53b7f
=> Avoid non-blocking wait statement to improve performance

src/EventExport/Format/TabularData/TabularDataEventFormatter.php, tests/EventExport/Format/TabularData/TabularDataEventFormatterTest.php
- Event status field can now be exported in ooxml with this mapping
ooxml value | status type in jsonld
-- | --
Gaat door | Available
Uitgesteld | TemporarilyUnavailable
Geannuleerd | Unavailable
---
Ticket: https://jira.uitdatabank.be/browse/III-3860
=> Export status field in OOXML format

src/Event/ReadModel/JSONLD/CdbXMLImporter.php, src/Offer/ReadModel/JSONLD/NewPropertyPolyfillOfferRepository.php, tests/Event/ReadModel/JSONLD/CdbXMLImporterTest.php, tests/Offer/ReadModel/JSONLD/NewPropertyPolyfillOfferRepositoryTest.php
- Removed `calendarSummary` from new event projections/replays from XML imports
- Removed `calendarSummary` from existing projections (on the fly), until we do a full replay again
---
Ticket: https://jira.uitdatabank.be/browse/III-3864
=> III-3864 Remove old leftover calendarSummary property from JSON-LD

src/Http/Label/ReadRestController.php, tests/Http/Label/ReadRestControllerTest.php
- Return empty collection and HTTP status code 200 when no labels are found
---
Ticket: https://jira.uitdatabank.be/browse/III-3890
=> III-3890 Fix for empty search result for labels

app/Migrations/Version20210325170924.php, app/Offer/OfferServiceProvider.php, app/PurgeServiceProvider.php, bootstrap.php, src/Offer/ReadModel/Metadata/OfferMetadata.php, src/Offer/ReadModel/Metadata/OfferMetadataProjector.php, src/Offer/ReadModel/Metadata/OfferMetadataRepository.php, tests/Offer/ReadModel/Metadata/Doctrine/OfferMetadataSchemaConfigurator.php, tests/Offer/ReadModel/Metadata/OfferMetadataProjectorTest.php, tests/Offer/ReadModel/Metadata/OfferMetadataRepositoryTest.php
- Table, Projector and Repository for `OfferMetadata` read model
---
Ticket: https://jira.uitdatabank.be/browse/III-3819
---
Next up: adding a polyfill to add this metadata to the JsonLD read model when necessary, similar to the popularity score
=> III-3819 - Projector and repository for OfferMetadata

app/Event/EventJSONLDServiceProvider.php, app/Place/PlaceJSONLDServiceProvider.php, src/Offer/ReadModel/Metadata/OfferMetadataEnrichedOfferRepository.php, src/Offer/ReadModel/Metadata/OfferMetadataProjector.php, tests/Offer/ReadModel/Metadata/OfferMetadataEnrichedOfferRepositoryTest.php
- When requesting places or events with metadata, the `createdByApiConsumer` property will now be embedded. If that information is not available (due to a not yet available read model or the offer being a very old event), we will default to `unknown`.
---
Ticket: https://jira.uitdatabank.be/browse/III-3819
=> III-3819 - Add decoration layer that embeds the offer metadata

src/Offer/ReadModel/Metadata/OfferMetadataProjector.php, src/Offer/ReadModel/Metadata/OfferMetadataRepository.php, tests/Offer/ReadModel/Metadata/OfferMetadataProjectorTest.php, tests/Offer/ReadModel/Metadata/OfferMetadataRepositoryTest.php
- This reverts the changes introduced by an unnecessary cleanup in https://github.com/cultuurnet/udb3-silex/pull/635#issuecomment-809337347, making the read model projection idempotent again
---
Ticket: https://jira.uitdatabank.be/browse/III-3819
=> III-3819 - Revert unnecessary cleanup

app/Error/ErrorLogger.php, app/Error/WebErrorHandlerProvider.php
- Added more bad request exceptions to filter out of logs/Sentry
- Bad request filtering now happens on the logger level, so if they occur async through supervisor/resque workers they do not get logged/sent to Sentry anymore either
---
Ticket: https://jira.uitdatabank.be/browse/III-3661
=> III-3661 Filter out irrelevant Sentry messages

app/CommandHandling/CommandBusServiceProvider.php, app/CommandHandling/RetryingCommandBus.php, tests/Broadway/CommandHandling/RetryingCommandBusTest.php
- Introduced a retrying command bus as a form of optimistic locking for race conditions in an aggregate that was loaded through concurrent requests.
---
Ticket: https://jira.uitdatabank.be/browse/III-3919
=> Introduce RetryingCommandBus for optimistic locking

bin/udb3.php
- Fixed the console app returning status 0 when it crashed, for example during a replay.
---
Ticket: https://jira.uitdatabank.be/browse/III-3928
=> III-3928 Fix console app exiting with incorrect status on error

.gitignore, app/Event/EventJSONLDServiceProvider.php, app/Place/PlaceJSONLDServiceProvider.php, app/Term/TermServiceProvider.php, bootstrap.php, src/Category.php, src/Offer/ReadModel/JSONLD/TermLabelOfferRepositoryDecorator.php, src/Term/TermNotFoundException.php, src/Term/TermRepository.php, tests/Offer/ReadModel/JSONLD/TermLabelOfferRepositoryDecoratorTest.php, tests/Term/TermRepositoryTest.php
- Added decorator around event/place JSON-LD repositories to update/add term labels on-the-fly from config
---
Ticket: https://jira.uitdatabank.be/browse/III-4010
Related config PRs:
- https://github.com/cultuurnet/appconfig/pull/70
- https://github.com/cultuurnet/udb3-vagrant/pull/63
Note that this config still needs to be double checked to make sure the label names are correct
=> III-4010 Term label decorator

src/ReadModel/ConfigurableJsonDocumentLanguageAnalyzer.php
- Return early when type is not object inside language analyzer
---
Ticket: https://jira.uitdatabank.be/browse/III-3991
=> III-3991 Return early when type is not object

web/index.php
- Removed `email` from required claims in Auth0 tokens
- Removed `nick` and `email` from required claims in old UDB3 self-signed tokens (long-lived or integrations using the old JWT provider)
---
Ticket: https://jira.uitdatabank.be/browse/III-4052
Note: This just removes the requirement for these claims from the token validation. It shouldn't break existing tokens that have these claims, they will just be ignored.
=> III-4052 Remove unused claims from required claims

app/Authentication/UitidApiKeyServiceProvider.php, app/CommandHandling/ContextFactory.php, app/Error/SentryHandlerScopeDecorator.php, bootstrap.php, config.yml.dist, src/HttpFoundation/Response/ForbiddenResponse.php, src/HttpFoundation/Response/UnauthorizedResponse.php, src/Jwt/JwtParserException.php, src/Jwt/Silex/JwtServiceProvider.php, src/Jwt/Symfony/Authentication/JwtAuthenticationEntryPoint.php, src/Jwt/Symfony/Authentication/JwtAuthenticationProvider.php, src/Jwt/Symfony/Firewall/JwtListener.php, src/Jwt/Udb3Token.php, tests/Jwt/Symfony/Authentication/JwtAuthenticationEntryPointTest.php, tests/Jwt/Symfony/Authentication/JwtAuthenticationProviderTest.php, tests/Jwt/Symfony/Firewall/JwtListenerTest.php, tests/Jwt/Udb3TokenTest.php
- Added check that id tokens can only be used if they are provided by the JWT provider (for backward compatibility)
- Client id from access tokens in Sentry errors
- Client id from access tokens in event store metadata
- Removed API key requirement for access tokens (that have an `azp` claim)
---
Ticket: https://jira.uitdatabank.be/browse/III-4061
=> III-4061 Remove api key requirement for access tokens

src/Offer/ReadModel/Metadata/OfferMetadataProjector.php, tests/Offer/ReadModel/Metadata/OfferMetadataProjectorTest.php
- Support auth_api_client_id metadata for consumer
---
Ticket: https://jira.uitdatabank.be/browse/III-4067
Note: the mapping config still needs to be updated in the appconfig repo and the udb3-vagrant repo and needs to represent the new id for the user interface
=> III-4067 Support auth_api_client_id metadata for consumer

src/Http/Productions/ProductionsWriteController.php, tests/Http/Productions/ProductionsWriteControllerTest.php
- Extend the response of the production create endpoint with a production id
---
Ticket: https://jira.uitdatabank.be/browse/III-4103
=> III-4103 Extend the production create endpoint with a production id

src/Event/Productions/AddEventToProduction.php, src/Event/Productions/GroupEventsAsProduction.php, src/Event/Productions/MergeProductions.php, src/Event/Productions/RejectSuggestedEventPair.php, src/Event/Productions/RemoveEventFromProduction.php, src/Label/Commands/AbstractCommand.php, src/Media/Commands/UploadImage.php, src/Offer/Commands/AbstractCommand.php, src/Offer/Commands/AbstractUpdateFacilities.php, src/Offer/Commands/AuthorizableCommandInterface.php, src/Offer/Commands/ImportLabels.php, src/Offer/Commands/Moderation/AbstractModerationCommand.php, src/Offer/Commands/PreflightCommand.php, src/Organizer/Commands/AbstractLabelCommand.php, src/Organizer/Commands/AbstractOrganizerCommand.php, src/Organizer/Commands/AbstractUpdateOrganizerCommand.php, src/Organizer/Commands/DeleteOrganizer.php, src/Organizer/Commands/ImportLabels.php, src/Place/Commands/MarkAsDuplicate.php, src/Role/Commands/AbstractCommand.php, src/Role/Commands/AbstractLabelCommand.php, src/Role/Commands/AbstractPermissionCommand.php, src/Role/Commands/AbstractUserCommand.php, src/Role/Commands/AddConstraint.php, src/Role/Commands/CreateRole.php, src/Role/Commands/RemoveConstraint.php, src/Security/LabelSecurityInterface.php, tests/Security/DummyCommand.php
- Cleanup the type hinting of commands
Note: not essential for III-3494 but always better to create new code with return types
---
Ticket: https://jira.uitdatabank.be/browse/III-3494
=> III-3494 Cleanup the type hinting of commands

src/Jwt/Symfony/Authentication/JsonWebToken.php
- Hotfix to prevent crash when token was not parsed
=> Hotfix to prevent crash when token was not parsed

app/SavedSearches/SavedSearchesServiceProvider.php, src/Http/User/UserIdentityController.php, src/Jwt/Symfony/Authentication/JsonWebToken.php, src/SavedSearches/Sapi3FixedSavedSearchRepository.php, tests/CultuurNet/UDB3/SavedSearches/Sapi3FixedSavedSearchRepositoryTest.php, tests/Http/User/UserIdentityControllerTest.php, tests/Jwt/Symfony/Authentication/JsonWebTokenTest.php
- Fixed 400 response on `/user` for v1 tokens
- Fixed email not being included in "door mij ingevoerd" saved search on `/saved-searches` for v1 tokens
---
Ticket: https://jira.uitdatabank.be/browse/III-4133
=> III-4133 Fix /user and /saved-searches for v1 tokens

app/CommandHandling/ContextFactory.php, src/Jwt/Symfony/Authentication/JsonWebToken.php, tests/CultuurNet/UDB3/Silex/CommandHandling/ContextFactoryTest.php
- Fix serialising a JWT inside the metadata context for queued command
- Remove validation for possible null value of token which should no longer happen
Note: I noticed to late there was already an open PR https://github.com/cultuurnet/udb3-silex/pull/689 but that PR had no reference to the ticket so I missed it.
---
Ticket: https://jira.uitdatabank.be/browse/III-4134
=> Fix serialising a JWT inside the metadata context for queued command

app/Auth0/Auth0ServiceProvider.php, src/User/Auth0ManagementTokenGenerator.php, src/User/Auth0ManagementTokenProvider.php, src/User/Auth0ManagementTokenRepository.php, src/User/Auth0Token.php, src/User/CacheRepository.php, src/User/InMemoryRepository.php, src/User/UserIdentityDetails.php, tests/User/Auth0ManagementTokenProviderTest.php
- Added new `Auth0Token`
- Use `Auth0Token` inside `Auth0ManagementTokenRepository` and `Auth0ManagementTokenGenerator`
- Use expired value inside `Auth0ManagementTokenProvider` to determine a token that is about to expire
---
Ticket: https://jira.uitdatabank.be/browse/III-4070
=> III-4070 Improved token cache

app/Event/EventControllerProvider.php, app/Offer/OfferControllerProvider.php, app/Place/PlaceControllerProvider.php, src/Http/Event/UpdateSubEventsRequestHandler.php, src/Http/Offer/UpdateBookingAvailabilityRequestHandler.php, src/Http/Offer/UpdateStatusRequestHandler.php, src/Http/Request/Body/JsonSchemaLocator.php, src/Http/Request/RequestHandler.php, src/Http/Request/RouteParameters.php, tests/Http/Event/UpdateSubEventsRequestHandlerTest.php, tests/Http/Offer/UpdateBookingAvailabilityRequestHandlerTest.php, tests/Http/Offer/UpdateStatusRequestHandlerTest.php, tests/Http/Request/Psr7RequestBuilder.php, tests/Http/Request/RouteParametersTest.php
- `RequestHandler` interface
- `RouteParameters` class to get route parameters from `ServerRequestInterface` instead of `handle()` method arguments
- Implemented `RequestHandler` on `UpdateStatusRequestHandler`
- Implemented `RequestHandler` on `UpdateBookingAvailabilityRequestHandler`
- Implemented `RequestHandler` on `UpdateSubEventsRequestHandler`
- Used JSON schema validation in `UpdateStatusRequestHandler`
- Moved registration of shared offer routes from Event- and PlaceControllerProvider to OfferControllerProvider
---
Ticket: https://jira.uitdatabank.be/browse/III-4168 (as preparation for new request handler for calendar endpoint)
=> III-4168 Add RequestHandler interface

src/Http/Request/Body/JsonSchemaLocator.php, src/Http/Request/Body/JsonSchemaValidatingRequestBodyParser.php, tests/Http/Request/Body/JsonSchemaLocatorTest.php
- Load JSON schemas via URI, by configuring a resolver on the `Validator`
- Resolving of `$ref` in JSON schema validation
---
Ticket: https://jira.uitdatabank.be/browse/III-4168
I noticed this while working with `$ref` in the changes to make the calendar endpoint work with JSON schema validation. So the next PR will better cover this with tests, when I add tests for the JSON schema validation of that endpoint.
=> III-4168 fix $ref in schemas

src/Http/Event/UpdateSubEventsRequestHandler.php, src/Http/Offer/UpdateBookingAvailabilityRequestHandler.php, src/Http/Offer/UpdateStatusRequestHandler.php, src/Http/Request/Body/AssociativeArrayRequestBodyParser.php, src/Http/Request/Body/RequestBodyParserFactory.php
- Parsed body is now associative arrays instead of objects (after validation), so we can use the existing denormalization/deserialization/etc logic to convert the JSON to value objects
---
Ticket: https://jira.uitdatabank.be/browse/III-4168
=> III-4168 Use associative arrays in request handlers

app/Export/ExportServiceProvider.php, src/Search/Sapi3SearchService.php
- Added logger to search service used for exports. It already got one via `ResultsGenerator`, but too late in the flow to debug the issue with the count that happens before the actual export.
=> Add export count query logging

app/CommandHandling/ContextFactory.php, src/History/Log.php, src/Jwt/Symfony/Authentication/JsonWebToken.php, tests/Event/ReadModel/History/HistoryProjectorTest.php, tests/Jwt/Symfony/Authentication/JsonWebTokenTest.php
- Added `auth0ClientName` to history log projections for tokens that support it (all client & user access tokens since UID-762 has been deployed)
---
Ticket: https://jira.uitdatabank.be/browse/III-4087
=> III-4087 Add client name to history projection

bootstrap.php, config.yml.dist
- Any CORS origin is now allowed (if we don't specify any allowed origins, the package we use allows every origin)
- OPTIONS responses no longer have a `Access-Control-Allow-Credentials: true` header (which would allow the browser to send cookies via CORS requests which we don't use nor want)
---
Ticket: https://jira.uitdatabank.be/browse/III-4099
=> III-4099 Allow any CORS origin

app/LegacyRoutesServiceProvider.php, web/index.php
- [internal] Moved catch-all route to `ServiceProviderInterface::boot()`. This way it gets registered after the dynamic `OPTIONS` routes that get registered by `CorsServiceProvider::boot()`
- Broken CORS requests
---
Ticket: https://jira.uitdatabank.be/browse/III-4243
=> III-4243 Move catch-all route to ServiceProviderInterface::boot()

app/Event/EventControllerProvider.php, app/Event/ProductionControllerProvider.php, app/Export/ExportControllerProvider.php, app/Import/ImportControllerProvider.php, app/JSONLD/ContextControllerProvider.php, app/Jobs/JobsControllerProvider.php, app/Labels/LabelsControllerProvider.php, app/LegacyRoutesServiceProvider.php, app/Media/MediaControllerProvider.php, app/Offer/BulkLabelOfferControllerProvider.php, app/Offer/OfferControllerProvider.php, app/Organizer/OrganizerControllerProvider.php, app/Place/PlaceControllerProvider.php, app/Role/RoleControllerProvider.php, app/SavedSearches/SavedSearchesControllerProvider.php, app/UiTPASService/UiTPASServiceEventControllerProvider.php, app/User/UserControllerProvider.php, web/index.php
- Routes can now be accessed with our without trailing slash, but they MUST be registered with a trailing slash for this to work! If you register a route without a trailing slash it will work without the trailing slash, but it won't work with a trailing slash.
---
Ticket: https://jira.uitdatabank.be/browse/III-4148
Note: For this to be possible the internal routes have to be registered in a consistent manner, so either all with or all without trailing slash. I had to pick trailing slash, because if you do for example `$app->mount('/places', new PlaceControllerProvider())` and then `$app->post('/', function () { ... });` in that mounted controller provider, the `POST` is registered as `POST /places/` (so with trailing slash). And there is now way to do something like `$app->post('', …
=> III-4148 ignore trailing slashes

app/Organizer/OrganizerCommandHandlerProvider.php, app/Organizer/OrganizerControllerProvider.php, bootstrap.php, composer.json, composer.lock, src/Http/Organizer/EditOrganizerRestController.php, src/Http/Organizer/UpdateUrlRequestHandler.php, src/Http/Request/Body/JsonSchemaLocator.php, src/Model/Import/Organizer/OrganizerDocumentImporter.php, src/Organizer/CommandHandler/UpdateWebsiteHandler.php, src/Organizer/Commands/UpdateWebsite.php, src/Organizer/DefaultOrganizerEditingService.php, src/Organizer/Organizer.php, src/Organizer/OrganizerCommandHandler.php, src/Organizer/OrganizerEditingServiceInterface.php, src/Organizer/Serializers/UpdateWebsiteDenormalizer.php, tests/Http/Organizer/EditOrganizerRestControllerTest.php, tests/Http/Organizer/UpdateUrlRequestHandlerTest.php, tests/Model/Import/Organizer/OrganizerDocumentImporterTest.php, tests/Organizer/CommandHandler/UpdateWebsiteHandlerTest.php, tests/Organizer/Commands/UpdateWebsiteTest.php, tests/Organizer/DefaultOrganizerEditingServiceTest.php, tests/Organizer/OrganizerCommandHandlerTest.php, tests/Organizer/OrganizerTest.php
- Added new `UpdateWebsite` command handler
- Added new `UpdateWebsite` request handler
- Refactor UpdateWebsite command to work with `Url` from Model namespace
- Refactor Organizer::updateWebsite method to work with `Url` from Model namespace
- Removed obsolete code for handling updateWebsite
---
Ticket: https://jira.uitdatabank.be/browse/III-4287
=> III-4287 Refactor the update organizer url

app/Http/RequestHandlerControllerResolver.php
- Fixed warning that `$controller` is not a `string` or `int` when checking if the controller is a class name of a `RequestHandlerInterface` implementation (for example when the `$controller` is actually a closure)
=> Fix warning that $controller is not a string or int

src/Http/Event/UpdateSubEventsRequestHandler.php
- Catch end date before start date when updating a sub event and throw as an invalid body ApiProblem
---
Ticket: https://jira.uitdatabank.be/browse/III-4229
=> III-4229 Catch end date before start date and throw as ApiProblem

src/Event/ReadModel/History/HistoryProjector.php, src/Offer/ReadModel/History/OfferHistoryProjectorTrait.php, src/Place/ReadModel/History/HistoryProjector.php, tests/Event/ReadModel/History/HistoryProjectorTest.php, tests/Place/ReadModel/History/HistoryProjectorTest.php
- Project `VideoAdded` inside the history of a **place** or **event**
- Project `VideoDeleted` inside the history of a **place** or **event**
- Project `VideoUpdated` inside the history of a **place** or **event**
- Project `AvailableFromUpdated` inside the history of a **place** or **event**
- Project `ThemeRemoved` inside the history of an **event**
---
Ticket: https://jira.uitdatabank.be/browse/III-4380
=> III-4380 Add extra history events

app/Event/EventJSONLDServiceProvider.php, app/Media/MediaControllerProvider.php, app/Media/MediaServiceProvider.php, app/Place/PlaceJSONLDServiceProvider.php, src/Http/Media/ReadMediaRestController.php, src/Media/MediaUrlMapping.php, src/Offer/ReadModel/JSONLD/MediaUrlOfferRepositoryDecorator.php, tests/Http/Media/ReadMediaRestControllerTest.php, tests/Offer/ReadModel/JSONLD/MediaUrlOfferRepositoryDecoratorTest.php
- Rename `MediaUrlRepository` to `MediaUrlMapping`
- Map the contentUrl and thumbnailUrl from `mediaObject`
---
Ticket: https://jira.uitdatabank.be/browse/III-4384
=> III-4384 Replace urls for media object

app/Media/MediaControllerProvider.php
- Use correct key `media_url_mapping` instead of `media_mapping_mapping`
---
Ticket: https://jira.uitdatabank.be/browse/III-4384
=> III-4384 Use correct key media_url_mapping

src/Organizer/Events/TitleTranslated.php, src/Organizer/Organizer.php, tests/Organizer/CommandHandler/UpdateTitleHandlerTest.php, tests/Organizer/Events/TitleTranslatedTest.php, tests/Organizer/OrganizerLDProjectorTest.php, tests/Organizer/OrganizerTest.php
- Changed `CultuurNet\UDB3\Organizer\Events\TitleTranslated` to use scalar types in constructor and internally
---
Ticket: https://jira.uitdatabank.be/browse/III-4392
=> III-4392 Refactor organizer TitleTranslated value objects in constructor

src/Organizer/Events/TitleUpdated.php, src/Organizer/Organizer.php, tests/Organizer/CommandHandler/UpdateTitleHandlerTest.php, tests/Organizer/Events/TitleUpdatedTest.php, tests/Organizer/OrganizerLDProjectorTest.php, tests/Organizer/OrganizerTest.php
- Refactor `TitleTranslated` constructor to use primitive types
---
Ticket: https://jira.uitdatabank.be/browse/III-4393
=> III-4393 Refactor TitleTranslated constructor to use primitive types

src/Organizer/Events/AddressTranslated.php, src/Organizer/Events/AddressUpdated.php, src/Organizer/Organizer.php, tests/Organizer/CommandHandler/RemoveAddressHandlerTest.php, tests/Organizer/CommandHandler/UpdateAddressHandlerTest.php, tests/Organizer/DefaultOrganizerEditingServiceTest.php, tests/Organizer/Events/AddressTranslatedTest.php, tests/Organizer/Events/AddressUpdatedTest.php, tests/Organizer/OrganizerLDProjectorTest.php, tests/Organizer/OrganizerTest.php, tests/Organizer/ProcessManager/GeoCoordinatesProcessManagerTest.php
- Refactor `AddressUpdated` and `AddressTranslated` to use primitives.
---
Ticket: https://jira.uitdatabank.be/browse/III-4400
=> III-4400 refactor address updated

src/Organizer/Events/ContactPointUpdated.php, src/Organizer/Organizer.php, tests/Organizer/CommandHandler/UpdateContactPointHandlerTest.php, tests/Organizer/Events/ContactPointUpdatedTest.php, tests/Organizer/OrganizerTest.php
- refactored `ContactPointUpdated ` to use primitives
---
Ticket: https://jira.uitdatabank.be/browse/III-4397
=> III-4397 refactor ContactPointUpdated

app/Organizer/OrganizerJSONLDServiceProvider.php, src/Organizer/Events/AbstractLabelEvent.php, src/Organizer/Events/WebsiteUpdated.php, src/Organizer/Organizer.php, src/Organizer/OrganizerLDProjector.php, src/Organizer/WebsiteUniqueConstraintService.php, tests/Organizer/OrganizerLDProjectorTest.php
- Refactored `getWebsite` from `WebsiteUpdated` to return a `string`
- Various boy scouting changes (property type hints, return types, removed unused parameter)
---
=> III-4414 Refactor getWebsite from WebsiteUpdated

src/Organizer/Events/TitleTranslated.php, src/Organizer/Organizer.php, src/Organizer/OrganizerLDProjector.php
- Remove `TitleTranslated` to return primitive types
---
=> III-4144 refactor organizer getters TitleTranslated

src/Organizer/Organizer.php
- Make $website back a VO instead of a primitive in Organizer Class.
---
=> III-4414 Undo primitive type $website in Organizer class

app/Curators/CuratorsControllerProvider.php, src/Curators/Serializer/NewsArticleDenormalizer.php, src/Http/Curators/CreateNewsArticleRequestHandler.php, src/Http/Curators/UpdateNewsArticleRequestHandler.php, tests/Http/Curators/UpdateNewsArticleRequestHandlerTest.php, web/index.php
- Added new handler `UpdateNewsArticleRequestHandler` to update a news article
- Refactor `NewsArticleDenormalizer` to work with `UUID` instead of `UuidGeneratorInterface`. By changing this the denormalizer works for both update and create.
---
=> III-4410 news article put request

tests/Http/Curators/UpdateNewsArticleRequestHandlerTest.php
- Fix test warning because getById was not mocked
=> Fix test warning because getById was not mocked

src/Organizer/Events/AddressTranslated.php, src/Organizer/Events/AddressUpdated.php, src/Organizer/Events/ContactPointUpdated.php
- Add `contactPoint` root property again to stay backwards compatible
- Add `address` root property again to stay backwards compatible
=> Hot fix organizer events serialisation

app/SavedSearches/SavedSearchesServiceProvider.php, src/SavedSearches/Sapi3FixedSavedSearchRepository.php, src/SavedSearches/ValueObject/CreatedByQueryMode.php, tests/SavedSearches/Sapi3FixedSavedSearchRepositoryTest.php
- Refactor `CreatedByQueryMode` to derive from `Enum` from `Model` namespace
---
=> III-4187 Refactor CreatedByQueryMode

src/Http/Label/CommandType.php, src/Http/Label/EditRestController.php, tests/Http/Label/CommandTypeTest.php
- Refactor `CommandType` to use `Enum` from Model namespace.
---
=> III-4187 refactor command type

app/Organizer/OrganizerCommandHandlerProvider.php, app/Organizer/OrganizerControllerProvider.php, app/Organizer/OrganizerJSONLDServiceProvider.php, bootstrap.php, composer.json, composer.lock, src/Http/ApiProblem/ApiProblem.php, src/Http/Organizer/AddImageRequestHandler.php, src/Http/Request/Body/JsonSchemaLocator.php, src/Model/Serializer/ValueObject/MediaObject/ImageNormalizer.php, src/Model/ValueObject/MediaObject/Image.php, src/Model/ValueObject/MediaObject/Images.php, src/Organizer/CommandHandler/AddImageHandler.php, src/Organizer/Commands/AddImage.php, src/Organizer/Events/ImageAdded.php, src/Organizer/Organizer.php, src/Organizer/OrganizerLDProjector.php, src/Organizer/Serializers/AddImageDenormalizer.php, tests/Http/Organizer/AddImageRequestHandlerTest.php, tests/Model/ValueObject/MediaObject/ImageTest.php, tests/Organizer/CommandHandler/AddImageHandlerTest.php, tests/Organizer/Commands/AddImageTest.php, tests/Organizer/Events/ImageAddedTest.php, tests/Organizer/OrganizerLDProjectorTest.php, tests/Organizer/OrganizerTest.php, tests/Organizer/Samples/organizer_with_image.json, tests/Organizer/Samples/organizer_with_two_images.json
- Added `Image` value object
- Added `Images` collection
- Added `ImageAdded` event
- Added `AddImage` command
- Added method `addImage` on `Organizer` aggregate
- Added method to handle `ImageAdded` inside the `OrganizerLDProjector`
- Added normalizer `ImageNormalizer` which can get the URLs from a media object (unfortunate the media object does not have a projection so the aggregate is used to get the URLs)
- Added `AddImageHandler` to handle `AddImage` command
- Added `AddImageDenormalizer` to create `AddImage` command from request bodies
- Added `AddImageRequestHandler` to handle POST image requests
---
Ticket: https://jira.uitdatabank.be/browse/III-4426
=> III-4426 Add endpoint to add an image to an organizer

app/Organizer/OrganizerCommandHandlerProvider.php, app/Organizer/OrganizerControllerProvider.php, bootstrap.php, composer.json, composer.lock, src/Http/Organizer/DeleteImageRequestHandler.php, src/Organizer/CommandHandler/RemoveImageHandler.php, src/Organizer/Commands/RemoveImage.php, src/Organizer/Events/ImageRemoved.php, src/Organizer/Organizer.php, src/Organizer/OrganizerLDProjector.php, tests/Http/Organizer/DeleteImageRequestHandlerTest.php, tests/Organizer/CommandHandler/RemoveImageHandlerTest.php, tests/Organizer/Commands/RemoveImageTest.php, tests/Organizer/Events/ImageRemovedTest.php, tests/Organizer/OrganizerLDProjectorTest.php, tests/Organizer/OrganizerTest.php, tests/Organizer/Samples/organizer_with_all_images_removed.json
- Added `ImageRemoved` event
- Added `RemoveImage` command
- Implement `removeImage` on `Organizer` aggregate
- Implement `ImageRemoved` inside `OrganizerLDProjector`
- Added `RemoveImageHandler` to handle the `RemoveImage` command
- Added `DeleteImageRequestHandler` to handle the `DELETE` image request
---
Ticket: https://jira.uitdatabank.be/browse/III-4428
=> III-4428 Add endpoint to delete image from organizer

app/LegacyRoutesServiceProvider.php, src/Curators/Serializer/NewsArticleNormalizer.php, tests/Http/Curators/GetNewsArticleRequestHandlerTest.php, tests/Http/Curators/GetNewsArticlesRequestHandlerTest.php, tests/Http/Curators/UpdateNewsArticleRequestHandlerTest.php, web/index.php
- `news_articles` routes are now registered as `news-articles`, but `news_articles` also still works
---
Ticket: https://jira.uitdatabank.be/browse/III-4507
(Note: This ticket also still requires some documentation changes and acceptance test changes)
=> III-4507 Use hyphens in news articles paths

composer.json, composer.lock, src/Http/Organizer/AddImageRequestHandler.php, src/Http/Organizer/AddMediaObjectPropertiesRequestBodyParser.php, tests/Http/Organizer/AddImageRequestHandlerTest.php
- Made properties when adding an image on an organizer optional
---
Note: I left the `composer.json` conflict so I can set it do dev-unreleased when reviewed.
Ticket: https://jira.uitdatabank.be/browse/III-4426
=> III-4426 Make properties when adding an image on an organizer optional

src/Http/Curators/CreateNewsArticleRequestHandler.php, tests/Http/Curators/CreateNewsArticleRequestHandlerTest.php
- Added check that no news article(s) already exist with the same `url` and `about` when creating a new news article
---
Ticket: https://jira.uitdatabank.be/browse/III-4509
=> III-4509 Block new news article with existing url and about

src/Model/Serializer/ValueObject/MediaObject/ImageNormalizer.php, tests/Organizer/Samples/organizer_with_image.json, tests/Organizer/Samples/organizer_with_two_images.json, tests/Organizer/Samples/organizer_with_two_images_and_updated_main_image.json, tests/Organizer/Samples/organizer_with_updated_image.json
- Added `id` to the images projection of an organizer.
---
Ticket: https://jira.uitdatabank.be/browse/III-4511
=> III-4511 Add id to organizer images

app/Organizer/OrganizerCommandHandlerProvider.php, app/Organizer/OrganizerControllerProvider.php, bootstrap.php, src/Http/Organizer/DeleteDescriptionRequestHandler.php, src/Organizer/CommandHandler/DeleteDescriptionHandler.php, src/Organizer/Commands/DeleteDescription.php, src/Organizer/Events/DescriptionDeleted.php, src/Organizer/Organizer.php, src/Organizer/OrganizerLDProjector.php, tests/Http/Organizer/AddImageRequestHandlerTest.php, tests/Http/Organizer/DeleteDescriptionRequestHandlerTest.php, tests/Http/Organizer/DeleteImageRequestHandlerTest.php, tests/Http/Organizer/UpdateDescriptionRequestHandlerTest.php, tests/Http/Organizer/UpdateImagesRequestHandlerTest.php, tests/Http/Organizer/UpdateMainImageRequestHandlerTest.php, tests/Organizer/CommandHandler/DeleteDescriptionHandlerTest.php, tests/Organizer/Commands/DeleteDescriptionTest.php, tests/Organizer/Events/DescriptionDeletedTest.php, tests/Organizer/OrganizerLDProjectorTest.php, tests/Organizer/OrganizerTest.php, tests/Organizer/Samples/organizer_without_description.json
- Added `DeleteDescription` command
- Added `DeleteDescriptionHandler` command handler
- Added `DescriptionDeleted` event
- Added method `deleteDescription` on the `Organizer` aggregate
- Handled `DescriptionDeleted` inside the organizer JSON-LD projector
- Added `DeleteDescriptionRequestHandler` HTTP handler
- Removed some unused properties inside the Organizer HTTP tests.
---
Note: when doing the commits I mixed up the tests for the `DeleteDescriptionHandler` and `DeleteDescriptionRequestHandler`
Ticket: https://jira.uitdatabank.be/browse/III-4500
=> III-4500 Add endpoint to delete organizer description

app/Event/EventCommandHandlerProvider.php, src/Event/CommandHandlers/CopyEventHandler.php, tests/Event/CommandHandlers/CopyEventHandlerTest.php
- `CopyEventHandler` now copies the production of the original event to the new event.
---
Ticket: https://jira.uitdatabank.be/browse/III-4516
=> III-4516 Add copied event to same production as original event

src/Event/Event.php
- Fixed calendar update issues with copied events by updating the copied event's internal calendar state to the new calendar in the copy event message.
---
Ticket: https://jira.uitdatabank.be/browse/III-4526
Note: Test added in https://github.com/cultuurnet/udb3-acceptance-tests/pull/59
=> III-4526 Update calendar in internal Event state after copy

app/Console/AbstractGeocodeCommand.php, app/Console/GeocodeOrganizerCommand.php, app/Search/Sapi3SearchServiceProvider.php, bin/udb3.php, src/EventExport/EventExportService.php, src/Model/ValueObject/Identity/ItemIdentifier.php, src/Model/ValueObject/Identity/ItemIdentifierFactory.php, src/Model/ValueObject/Identity/ItemIdentifiers.php, src/Model/ValueObject/Identity/ItemType.php, src/Search/Results.php, src/Search/ResultsGenerator.php, src/Search/Sapi3SearchService.php, src/Search/SearchServiceInterface.php, tests/EventExport/EventExportServiceTest.php, tests/Model/ValueObject/Identity/ItemIdentifierFactoryTest.php, tests/Model/ValueObject/Identity/ItemIdentifierTest.php, tests/Model/ValueObject/Identity/ItemIdentifiersTest.php, tests/Search/ResultsGeneratorTest.php, tests/Search/ResultsTest.php, tests/Search/Sapi3SearchServiceTest.php
- Added `ItemIdentifier` and `ItemType` to identify either an event, place or organizer
- Added `ItemIdentifierFactory` to easily create a `ItemIdentifier` from a `Url
- Added `ItemIdentifiers` which stores a list of `ItemIdentifier`
- Added `GeocodeOrganizerCommand` to trigger geocode commands for organizers
- `Sapi3SearchService` now works with `ItemIdentifiers` to make it possible to also search for organizers
- Boy scouting on `Sapi3Search` related classes
- Boy scouting on `EventExportService`
- Remove dependency on `ValueObjects` for `Sapi3Search` related classes
---
Ticket: https://jira.uitdatabank.be/browse/III-4438
=> III-4438 Add CLI command to geocode organizers

src/BookingInfo.php, src/DateTimeFactory.php, src/DateTimeInvalid.php, src/Http/Deserializer/BookingInfo/BookingInfoDataValidator.php, src/Http/Deserializer/BookingInfo/BookingInfoJSONDeserializer.php, src/Http/Offer/DateRangeValidator.php, src/Model/Serializer/Offer/OfferDenormalizer.php, src/Model/Serializer/ValueObject/Calendar/CalendarDenormalizer.php, src/Model/Serializer/ValueObject/Contact/BookingInfoDenormalizer.php, tests/DateTimeFactoryTest.php, tests/Http/Deserializer/BookingInfo/BookingInfoDataValidatorTest.php
- Classes that validate / decode incoming JSON now parse datetimes in multiple possible ISO-8601 / RFC-3339 datetime formats. For example without second fractions, with milliseconds, and with microseconds. This fixes compatibility with older integrations that send use datetimes with milli/microseconds even though we never officially supported it, but because it happened to work by accident in the past.
---
Ticket: https://jira.uitdatabank.be/browse/III-4528
Note: There are more usages of `DateTime::createFromFormat()` and `DateTimeImmutable::createFromFormat()` then the ones I replaced in this PR, but I tried to change all those that handle datetime strings from "incoming" JSON. Classes/methods that decode datetime strings from e.g. the event store did not need to be replaced since we …
=> III-4528 Be more flexible in ISO-8601 date formats

src/Event/LocationMarkedAsDuplicateProcessManager.php, src/Offer/BulkLabelCommandHandler.php, tests/Event/LocationMarkedAsDuplicateProcessManagerTest.php, tests/Offer/BulkLabelCommandHandlerTest.php
- Fixed `LocationMarkedAsDuplicateProcessManager` to work with `ItemIdentifier`
- Fixed `BulkLabelCommandHandler` to work partly with `ItemIdentifier`
Note: this is a temporary fix, the `BulkLabelCommandHandler` should also handle `AddLabelToMultiple` with `ItemIdentifier` but that command is still created with `IriOfferIdentifier`
---
Ticket: https://jira.uitdatabank.be/browse/III-4577
=> III-4577 search result item identifier

src/Model/Organizer/OrganizerReference.php, src/Model/Serializer/Offer/OfferDenormalizer.php, src/Model/Serializer/Organizer/OrganizerReferenceDenormalizer.php, tests/Model/Organizer/OrganizerReferenceTest.php
- Fixed PHP notice when importing an event with an organizer, and the organizer contains more properties than just `@id`. (https://sentry.io/organizations/publiq-vzw/issues/3003000437/?project=5435528)
---
Ticket: https://jira.uitdatabank.be/browse/III-4578
=> III-4578 Fix PHP notice in event import with organizer

app/Error/LoggerName.php, app/Event/EventJSONLDServiceProvider.php, src/Offer/ReadModel/JSONLD/CuratorEnrichedOfferRepository.php, tests/Offer/ReadModel/JSONLD/CuratorEnrichedOfferRepositoryTest.php
- Fixed `null` being added as a `hiddenLabel` when an event has a news article with a publisher that is not in the config list of publisher and their labels. If this happens an error will be logged in Sentry, but the code will continue without unintended side-effects.
---
Ticket: https://jira.uitdatabank.be/browse/III-4570
=> III-4570 Fix hidden labels null value

src/Organizer/Organizer.php, tests/Organizer/OrganizerTest.php
- Changed the aggregate `Organizer` to store the ContactPoint as `StringArray`
- Fixed the comparison of `ContactPoint` when an old `ContactPoint` was broken, so that `ContactPoint` can be updated.
---
Ticket: https://jira.uitdatabank.be/browse/III-4594
=> III-4594 Broken contactpoints problems

app/Event/EventImportServiceProvider.php, app/Offer/OfferServiceProvider.php, app/Place/PlaceControllerProvider.php, src/Http/Place/ImportPlaceRequestHandler.php, src/Model/Import/Event/EventDocumentImporter.php, src/Model/Import/Validation/Event/EventImportValidator.php, src/Offer/CommandHandlers/ImportLabelsHandler.php, src/Offer/Commands/ImportLabels.php, src/Offer/Offer.php, tests/Http/Place/ImportPlaceRequestHandlerTest.php, tests/Model/Import/Event/EventDocumentImporterTest.php, tests/Model/Import/Validation/Event/EventImportValidatorTest.php, tests/Offer/CommandHandlers/ImportLabelsHandlerTest.php, tests/Offer/OfferTest.php
- Refactored `ImportLabelsHandler` to take into account label visibility and privacy and the labels already present on the place or event
- Changed the `Offer::importLabels` method to handle a simple but correct list of labels
- Refactored the import of places to no longer use `ImportLabelVisibilityRequestBodyParser`
- Refactored the import of events to also work with the refactored `ImportLabelsHandler`
Note: In a follow-up PR it would even be possible to change the import label code from organizers to match the code from places and events closer. Once this is done `ImportLabelVisibilityRequestBodyParser` can be removed.
---
Ticket: https://jira.uitdatabank.be/browse/III-4567
=> III-4567 Refactor place labels importing

app/Authentication/UitidApiKeyServiceProvider.php, app/CommandHandling/ContextFactory.php, app/Offer/OfferServiceProvider.php, bootstrap.php, composer.json, composer.lock, src/Http/Event/EditEventRestController.php, src/Http/Place/ImportPlaceRequestHandler.php, src/Model/Import/DocumentImporterInterface.php, src/Model/Import/Event/EventDocumentImporter.php, src/Model/Import/PreProcessing/LabelPreProcessingDocumentImporter.php, src/Model/Import/PreProcessing/TermPreProcessingDocumentImporter.php, src/Offer/ProcessManagers/AutoApproveForUiTIDv1ApiKeysProcessManager.php, tests/Http/Event/EditEventRestControllerTest.php, tests/Http/Place/EditPlaceRestControllerTest.php, tests/Http/Place/ImportPlaceRequestHandlerTest.php, tests/Model/Import/Event/EventDocumentImporterTest.php, tests/Offer/ProcessManagers/AutoApproveForUiTIDv1ApiKeysProcessManagerTest.php
- Added support for `workflowStatus` property to explicitly set the desired workflow status when creating or updating a place
- Auto-approval of places now happens via a process manager. This will also work for events, but events also still have auto-approval logic inside `EditEventRestController` and `EventDocumentImporter` for now.
---
Ticket: https://jira.uitdatabank.be/browse/III-4609
=> III-4609 Manual workflowStatus when creating/updating a place

src/Http/Offer/LegacyCalendarRequestBodyParser.php, tests/Http/Event/ImportEventRequestHandlerTest.php
- Ignored empty `timeSpans` array to avoid creating an empty `subEvent` array
---
Ticket: https://jira.uitdatabank.be/browse/III-4640
=> III-4640 Ignore empty time spans

src/Http/Event/LegacyEventRequestBodyParser.php, tests/Http/Event/ImportEventRequestHandlerTest.php
- Allowed location as plain string inside event
Note: I did not add this to the docs because it was never documented and it seems that only the angular UI passes it as a plain string.
---
Ticket: https://jira.uitdatabank.be/browse/III-4641
=> III-4641 Allow location as plain string inside event

src/Http/Event/AgeRangeValidatingRequestBodyParser.php, src/Http/Event/ImportEventRequestHandler.php, src/Model/Serializer/ValueObject/Audience/AgeRangeDenormalizer.php, tests/Http/Event/ImportEventRequestHandlerTest.php
- Validated age range to make sure from is before to
Note: follow-up ticket [III-4647](https://jira.uitdatabank.be/browse/III-4647) to convert `InvalidArgumentException` to Internal server error
---
Ticket: https://jira.uitdatabank.be/browse/III-4638
=> III-4638 Validate age range from before to

app/Media/MediaControllerProvider.php, app/Organizer/OrganizerJSONLDServiceProvider.php, composer.json, composer.lock, src/Http/Media/EditMediaRestController.php, src/Media/Serialization/MediaObjectSerializer.php, src/Model/Serializer/ValueObject/MediaObject/ImageNormalizer.php, src/Offer/ReadModel/JSONLD/NewPropertyPolyfillOfferRepository.php, src/Organizer/ReadModel/JSONLD/PropertyPolyfillRepository.php, tests/Http/Event/ImportEventRequestHandlerTest.php, tests/Http/Media/EditMediaRestControllerTest.php, tests/Http/Media/ReadMediaRestControllerTest.php, tests/Http/Organizer/ImportOrganizerRequestHandlerTest.php, tests/Http/Place/ImportPlaceRequestHandlerTest.php, tests/Media/Serialization/MediaObjectSerializerTest.php, tests/Offer/ReadModel/JSONLD/NewPropertyPolyfillOfferRepositoryTest.php, tests/Offer/ReadModel/JSONLD/OfferLDProjectorTest.php, tests/OfferLDProjectorTestBase.php, tests/Organizer/ReadModel/JSONLD/PropertyPolyfillRepositoryTest.php, tests/Organizer/Samples/organizer_with_image.json, tests/Organizer/Samples/organizer_with_two_images.json, tests/Organizer/Samples/organizer_with_two_images_and_updated_main_image.json, tests/Organizer/Samples/organizer_with_updated_image.json
- Added `@id` in response of `POST /images`
- Added `id` to items inside `mediaObject` (on events/places) and in `GET /images/{imageId}`
- Added `@type` to items inside `images` (organizers)
- Renamed `language` in items inside `images` (organizers) to `inLanguage`
---
Goal of this PR was to make `mediaObject` and `images` use exactly the same schema for items inside them, to make the import logic easier.
Ticket: https://jira.uitdatabank.be/browse/III-4503 (actual importing logic will be added in a next PR)
=> III-4503 Align mediaObject / images JSON schema

src/Http/Offer/LegacyCalendarRequestBodyParser.php, src/Http/Offer/LegacyTimeSpansParser.php, tests/Http/Event/CopyEventRequestHandlerTest.php
- Handled empty time spans also on event copy
---
Ticket: https://jira.uitdatabank.be/browse/III-4572
=> III-4572 Handle empty time spans on event copy

app/Event/EventControllerProvider.php, app/Organizer/OrganizerCommandHandlerProvider.php, app/Organizer/OrganizerControllerProvider.php, app/Place/PlaceControllerProvider.php, bootstrap.php, composer.json, composer.lock, src/Event/Event.php, src/Http/ApiProblem/ApiProblem.php, src/Http/Organizer/ImportOrganizerRequestHandler.php, src/Http/Request/Body/ImagesPropertyPolyfillRequestBodyParser.php, src/Model/Organizer/ImmutableOrganizer.php, src/Model/Organizer/Organizer.php, src/Model/Serializer/Organizer/OrganizerDenormalizer.php, src/Model/Serializer/ValueObject/MediaObject/ImageDenormalizer.php, src/Model/Serializer/ValueObject/MediaObject/ImagesDenormalizer.php, src/Offer/Events/Image/AbstractImageUpdated.php, src/Offer/Offer.php, src/Offer/ReadModel/JSONLD/OfferLDProjector.php, src/Organizer/CommandHandler/ImportImagesHandler.php, src/Organizer/Commands/ImportImages.php, src/Organizer/Organizer.php, src/Place/Place.php, tests/Http/Event/ImportEventRequestHandlerTest.php, tests/Http/Organizer/ImportOrganizerRequestHandlerTest.php, tests/Http/Place/ImportPlaceRequestHandlerTest.php, tests/Offer/Item/Item.php, tests/OfferCommandHandlerTestTrait.php, tests/Organizer/CommandHandler/ImportImagesHandlerTest.php
- Image "import" functionality for organizers
- `description`, `copyrightHolder`, `inLanguage` are now optional in mediaObject when "importing" events and places
---
Ticket: https://jira.uitdatabank.be/browse/III-4503
=> III-4503 Organizer images imports

src/Http/Offer/LegacyCalendarRequestBodyParser.php, tests/Http/Event/ImportEventRequestHandlerTest.php, tests/Http/Place/ImportPlaceRequestHandlerTest.php
- Fixed importing events/places with incomplete calendar by converting them with a best guess to permanent, periodic, single or multiple.
Note: The unit tests don't verify the calendar from the create aggregate method, this is covered with acceptance tests, see https://github.com/cultuurnet/udb3-acceptance-tests/pull/103
---
Ticket: https://jira.uitdatabank.be/browse/III-4670
=> III-4670 Allow importing events/places with missing calendar

app/Event/EventControllerProvider.php, app/Organizer/OrganizerControllerProvider.php, app/Place/PlaceControllerProvider.php, src/Http/Import/RemoveEmptyArraysRequestBodyParser.php, src/Http/Request/Body/RemoveNullPropertiesRequestBodyParser.php, src/Http/Request/Body/RequestBodyParserFactory.php, tests/Http/Event/ImportEventRequestHandlerTest.php, tests/Http/Organizer/ImportOrganizerRequestHandlerTest.php, tests/Http/Place/ImportPlaceRequestHandlerTest.php
- Fixed validation error when `labels` or `hiddenLabels` or another array is empty while it should technically have at least one item according to the schema (by simply removing the property)
- Fixed validation error when an (optional) property is set to `null` by recursively removing all `null` values from the JSON
---
Ticket: https://jira.uitdatabank.be/browse/III-4669
=> III-4669 Fix errors on nullable properties

app/Migrations/Version20220406090353.php
- Added migration to delete `is_canonical` column from `duplicate_places` table
---
Ticket: https://jira.uitdatabank.be/browse/III-4664
=> III-4664 Add migration to delete `is_canonical` column

composer.json, composer.lock, tests/Http/Event/ImportEventRequestHandlerTest.php, tests/Http/Place/ImportPlaceRequestHandlerTest.php, tests/Http/Request/Body/JsonSchemaLocatorTest.php, tests/bootstrap.php, web/index.php
- Changed usage of `publiq/stoplight-docs-uitdatabank` to `publiq/udb3-json-schemas`, which is a read-only repository (https://github.com/cultuurnet/udb3-json-schemas/) that is split off automatically from https://github.com/cultuurnet/apidocs for every push to a branch
---
Ticket: https://jira.uitdatabank.be/browse/API-63
=> API-63 Use new publiq/udb3-json-schemas package

app/Event/EventCommandHandlerProvider.php, bootstrap.php, composer.json, composer.lock, src/Event/CommandHandlers/UpdateAttendanceModeHandler.php, src/Event/Commands/UpdateAttendanceMode.php, src/Event/Event.php, src/Event/Events/AttendanceModeUpdated.php, src/Event/ReadModel/JSONLD/EventLDProjector.php, src/Http/Event/ImportEventRequestHandler.php, src/Model/Event/Event.php, src/Model/Event/ImmutableEvent.php, src/Model/Serializer/Event/EventDenormalizer.php, src/Model/ValueObject/Virtual/AttendanceMode.php, tests/Event/CommandHandlers/UpdateAttendanceModeHandlerTest.php, tests/Event/EventTest.php, tests/Event/Events/AttendanceModeUpdatedTest.php, tests/Event/ReadModel/JSONLD/EventLDProjectorTest.php, tests/Event/ReadModel/JSONLD/copied_event.json, tests/Event/ReadModel/JSONLD/copied_event_with_place_type.json, tests/Event/ReadModel/JSONLD/copied_event_without_working_hours.json, tests/Http/Event/ImportEventRequestHandlerTest.php, tests/Model/Event/ImmutableEventTest.php, tests/Model/Serializer/Event/EventDenormalizerTest.php
- Added VO `AttendanceMode`
- Added command `UpdateAttendanceMode`
- Added event `AttendanceModeUpdated`
- Added handler `UpdateAttendanceModeHandler`
- Extend aggregate `Event` to support updating attendance mode
- Extend `ImportEventRequestHandler` to handle attendance mode and test validation of the provided attendance mode property inside the past JSON body
- Extend `EventLDProjector` to handle `AttendanceModeUpdated`
Note:
- Handling the validation of the provided location will be done in a follow-up pull request
- Creating a dedicated endpoint to only update the attendance mode will be done in ticket https://jira.uitdatabank.be/browse/III-4677
---
Ticket: https://jira.uitdatabank.be/browse/III-4667
=> III-4667 Support creating/importing attendance mode

src/Offer/ReadModel/JSONLD/NewPropertyPolyfillOfferRepository.php, tests/Offer/ReadModel/JSONLD/NewPropertyPolyfillOfferRepositoryTest.php
- Use only the `cdbid` in `sameAs` instead of the `io.uitdatabank.be` link to generate the UiTinVlaanderen link.
---
Ticket: https://jira.uitdatabank.be/browse/III-4661
=> III-4661 bugfix for polyfill sameAs

src/Offer/ReadModel/JSONLD/PropertyPolyfillOfferRepository.php, src/Organizer/ReadModel/JSONLD/PropertyPolyfillRepository.php, tests/Offer/ReadModel/JSONLD/PropertyPolyfillOfferRepositoryTest.php, tests/Organizer/ReadModel/JSONLD/PropertyPolyfillRepositoryTest.php
- Fixed bug that causes `labels` and/or `hiddenLabels` to become an object, by calling `array_values()` on the filtered array so the array becomes sequential instead of associative again.
---
Ticket: https://jira.uitdatabank.be/browse/III-4697
=> III-4697 Fix bug that causes `labels` and/or `hiddenLabels` to become an object

src/Http/Event/LegacyEventRequestBodyParser.php, tests/Http/Event/ImportEventRequestHandlerTest.php
- Fixed "undefined index $id" error when creating/updating an event without `location.@id` and `location.id`
---
Ticket: https://jira.uitdatabank.be/browse/III-4701
=> III-4701 Fix "undefined index $id" error when creating/updating an event without location.@id and location.id

app/Event/EventCommandHandlerProvider.php, app/Event/EventControllerProvider.php, bootstrap.php, src/Event/CommandHandlers/DeleteOnlineUrlHandler.php, src/Event/Commands/DeleteOnlineUrl.php, src/Event/Event.php, src/Event/Events/OnlineUrlDeleted.php, src/Event/ReadModel/JSONLD/EventLDProjector.php, src/Http/Event/DeleteOnlineUrlRequestHandler.php, src/Http/Event/ImportEventRequestHandler.php, tests/Event/CommandHandlers/DeleteOnlineUrlHandlerTest.php, tests/Event/CommandHandlers/UpdateAttendanceModeHandlerTest.php, tests/Event/Commands/DeleteOnlineUrlTest.php, tests/Event/EventTest.php, tests/Event/Events/OnlineUrlDeletedTest.php, tests/Event/ReadModel/JSONLD/EventLDProjectorTest.php, tests/Http/Event/DeleteOnlineUrlRequestHandlerTest.php, tests/Http/Event/ImportEventRequestHandlerTest.php
- Added `DeleteOnlineUrl` command
- Added `OnlineUrlDeleted` event
- Added `DeleteOnlineUrlHandler` to handle `DeleteOnlineUrl` command
- Added HTTP handler `DeleteOnlineUrlRequestHandler`
- Extended `EventLDProjector` with apply method for `OnlineUrlDeleted`
- Extended `Event` aggregate with `deleteOnlineUrl` method
- Handled empty onlineUrl on import as a delete
- Delete `onlineUrl` when setting `attendanceMode` to `offline`
---
Ticket: https://jira.uitdatabank.be/browse/III-4693
=> III-4693 Support deleting an onlineUrl

app/Event/EventJSONLDServiceProvider.php, app/Place/PlaceJSONLDServiceProvider.php, src/Event/ReadModel/JSONLD/CdbXMLImporter.php, src/Event/ReadModel/JSONLD/EventLDProjector.php, src/Offer/ReadModel/JSONLD/OfferLDProjector.php, src/Offer/ReadModel/JSONLD/PropertyPolyfillOfferRepository.php, src/Place/ReadModel/JSONLD/CdbXMLImporter.php, tests/Event/ReadModel/JSONLD/CdbXMLImporterTest.php, tests/Event/ReadModel/JSONLD/EventLDProjectorTest.php, tests/Event/ReadModel/JSONLD/copied_event.json, tests/Event/ReadModel/JSONLD/copied_event_with_place_type.json, tests/Event/ReadModel/JSONLD/copied_event_without_working_hours.json, tests/Offer/ReadModel/JSONLD/PropertyPolyfillOfferRepositoryTest.php, tests/OfferLDProjectorTestBase.php, tests/Place/ReadModel/JSONLD/CdbXMLImporterTest.php
- Polyfill `typicalAgeRange` on events and places
- Always project `typicalAgeRange` so when executing a replay the polyfill can be removed
- Extend `PropertyPolyfillOfferRepository` with `OfferType`
- Change `XMLImporter` to set all ages by default
- Only polyfill `attendanceMode` on events
---
Ticket: https://jira.uitdatabank.be/browse/III-4648
=> III-4648 Polyfill typicalAgeRange for events

app/Error/ErrorLogger.php
- `ConvertsToApiProblem` exceptions do not get logged to Sentry anymore, except if the status code of their ApiProblem is not 4XX.
- `ApiProblem` exceptions still do not get logged to Sentry (like before), except if their status code is not 4XX.
---
Ticket: https://jira.uitdatabank.be/browse/III-4709
=> III-4709 Make sure ConvertsToApiProblem exceptions do not get logged in Sentry

app/Console/ChangeOrganizerOwner.php, app/Console/ChangeOrganizerOwnerInBulk.php, app/Organizer/OrganizerCommandHandlerProvider.php, bin/udb3.php, bootstrap.php, src/Organizer/CommandHandler/ChangeOwnerHandler.php, src/Organizer/Commands/ChangeOwner.php, src/Organizer/Events/OwnerChanged.php, src/Organizer/Organizer.php, src/Organizer/OrganizerLDProjector.php, src/Organizer/ReadModel/Permission/Projector.php, tests/Organizer/CommandHandler/ChangeOwnerHandlerTest.php, tests/Organizer/Commands/ChangeOwnerTest.php, tests/Organizer/Events/OwnerChangedTest.php, tests/Organizer/OrganizerLDProjectorTest.php, tests/Organizer/OrganizerTest.php, tests/Organizer/ReadModel/Permission/ProjectorTest.php, tests/Organizer/Samples/organizer_with_changed_owner.json
- Created `ChangeOwner` command
- Created `OwnerChanged` event
- Added method `changeOwner` on `Organizer` aggregate
- Added `ChangeOwnerHandler` to handle the `ChangeOwner` command
- Added `ChangeOrganizerOwner` command to change owner of a single organizer
- Added `ChangeOrganizerOwnerInBulk` command to change the owner of all organizers belonging to a certain owner
- Extended `OrganizerLDProjector` to handle `OwnerChanged`
- Extended Resource owner projector to handle `OwnerChanged` event
---
Ticket: https://jira.uitdatabank.be/browse/III-4642
=> III-4642 Create `ChangeOwner` command

.github/CODEOWNERS
- Added a `CODEOWNERS` file. This way PR reviewers will be assigned automatically.
=> Configure CODEOWNERS file

src/Geocoding/CachedGeocodingService.php, src/Geocoding/DefaultGeocodingService.php, src/Geocoding/GeocodingService.php, tests/Geocoding/DefaultGeocodingServiceTest.php
- Changed log level to `warning` instead of `error` when no address is available, this will prevent this from being logged in Sentry.
---
Ticket: https://jira.uitdatabank.be/browse/III-4715
=> III-4715 Change log level to warning when no address available

src/Http/Label/Query/QueryFactory.php, src/Label/ReadModels/JSON/Repository/Doctrine/DBALReadRepository.php, src/Label/ReadModels/JSON/Repository/Entity.php, src/Label/ReadModels/JSON/Repository/Query.php, tests/Http/Label/Query/QueryFactoryTest.php, tests/Label/ReadModels/JSON/Repository/Doctrine/BaseDBALRepositoryTest.php, tests/Label/ReadModels/JSON/Repository/Doctrine/DBALReadRepositoryTest.php, tests/Label/ReadModels/JSON/Repository/QueryTest.php
- Filtered labels when suggestion mode is active
- Extended `Query` with optional `suggestion` parameter
- Extended `QueryFactory` to read suggestion from URL query
---
Ticket: https://jira.uitdatabank.be/browse/III-4734
=> III-4734 Implement label searching based on suggestion

app/Error/ErrorLogger.php, src/Http/ApiProblem/ApiProblem.php, src/Http/Media/EditMediaRestController.php, src/Media/Exceptions/ImageSizeError.php, src/Media/Exceptions/ImageUploadError.php, src/Media/Exceptions/InvalidFileSize.php, src/Media/Exceptions/InvalidFileType.php, src/Media/ImageUploaderService.php, tests/Http/Media/EditMediaRestControllerTest.php, tests/Media/ImageUploaderServiceTest.php
- Converted `ImageSizeError` to `ApiProblem::fileInvalidSize`
- Converted `ImageUploadError` to `ApiProblem::fileInvalidType`
---
Ticket: https://jira.uitdatabank.be/browse/III-3925
=> III-3925 Convert file errors to ApiProblem

src/Event/Event.php, src/Offer/Events/AbstractEvent.php, src/Offer/Events/Image/AbstractImageUpdated.php, src/Offer/Offer.php, src/Offer/ReadModel/History/OfferHistoryProjectorTrait.php, src/Offer/ReadModel/JSONLD/OfferLDProjector.php, src/Place/Place.php, tests/Event/Events/ImageUpdatedTest.php, tests/Event/ReadModel/History/HistoryProjectorTest.php, tests/Offer/Item/Events/ImageUpdated.php, tests/Offer/Item/Item.php, tests/Offer/OfferTest.php, tests/OfferCommandHandlerTestTrait.php, tests/OfferLDProjectorTestBase.php, tests/Place/ReadModel/History/HistoryProjectorTest.php
- Converted `CopyrightHolder` property to a native `string` to allow empty values when serializing `ImageUpdated` from the event store
- Modified `description` property to a native `string`
---
Ticket: https://jira.uitdatabank.be/browse/III-4751
=> III-4751 Allow copyright property to be empty when serializing ImageUpdated

composer.json, composer.lock
- Made `priceCurrency` optional again by updating the JSON schema to a version without the required field. The `PriceInfoDenormalizer` (used both in the `price-info` endpoint and the imports) always sets it to `EUR` anyway so no other changes are needed. This property is not actually parsed at the moment. (See https://github.com/cultuurnet/udb3-silex/blob/6f629a3bbfa4f6caec085b8642d2a58ff05de522/src/Model/Serializer/ValueObject/Price/PriceInfoDenormalizer.php#L95)
---
Ticket: https://jira.uitdatabank.be/browse/III-4769
=> III-4769 Make priceCurrency optional for priceInfo updates

app/Console/MarkPlacesAsDuplicateFromTableCommand.php, app/Console/ProcessDuplicatePlaces.php, app/Migrations/Version20220608094122.php, app/Migrations/Version20220608095217.php, app/Migrations/Version20220609104420.php, bin/udb3.php, src/Place/Canonical/CanonicalService.php, src/Place/Canonical/DBALDuplicatePlaceRepository.php, src/Place/Canonical/DuplicatePlaceRepository.php, tests/Place/Canonical/DBALDuplicatePlaceRepositoryTest.php
- Added migration to create simple `duplicate_places_removed_from_cluster` table
- Added method `setCanonicalOnCluster` on `DuplicatePlaceRepository`
- Added method `getCanonicalOfPlace` on `DuplicatePlaceRepository`
- Added method `getDuplicatesOfPlace` on `DuplicatePlaceRepository`
- Added CLI command `ProcessDuplicatePlaces` to
- Fill the `canonical` column of `duplicate_places`
- Trigger SAPI3 reindex for duplicate places and for places that are no longer duplicates by dispatching a `PlaceProjectedToJSONLD`
- Fire an `UpdateLocation` for all events of duplicate places
- Created migration to add `canonical` column to `duplicate_places` table
- Created migration to add index on `place_uuid` column of `duplicate_places` table
- Renamed `getCluster` to `getPlacesInCluster`
---
Ticket: …
=> III-4776 Create script to maintain duplicate places

app/Place/PlaceJSONLDServiceProvider.php, src/Place/Canonical/DuplicatePlacesEnrichedPlaceRepository.php, tests/Place/Canonical/DuplicatePlacesEnrichedPlaceRepositoryTest.php
- Added `DuplicatePlacesEnrichedPlaceRepository` which will enrich places with duplicate information. This will only happen when the feature is enabled. It has 3 behaviors:
- Remove `duplicateOf` and `duplicatedBy` from a regular place
- Add `duplicateOf` and remove `duplicatedBy` from a duplicate place
- Add `duplicatedBy` and remove `duplicateOf` from a canonical place
---
Ticket: https://jira.uitdatabank.be/browse/III-4777
=> III-4777 polyfil duplicates

app/Console/ProcessDuplicatePlaces.php
- Fixed crashed for canonical places: prevent looping when there are no duplicates places
---
Ticket: https://jira.uitdatabank.be/browse/III-4775
=> III-4775 Fix crashed for canonical places

app/Console/RemoveFacilitiesFromPlace.php, bin/udb3.php, src/Offer/Offer.php, tests/Offer/OfferTest.php
- Added CLI command `RemoveFacilitiesFromPlace` to remove the facilities from a single place or a list of places matching the query `terms.id:3.`
- Prevent updating the facilities with an empty list if the offer has no facilities. This will prevent a redundant and empty `FacilitiesUpdated` inside the event store
---
Ticket: https://jira.uitdatabank.be/browse/III-4613
=> III-4613 Add script to remove facilities from places

app/Console/RemoveFacilitiesFromPlace.php, src/Offer/Offer.php, tests/Offer/OfferTest.php
- Took into account that the generator returns `ItemIdentifier` objects inside the `RemoveFacilitiesFromPlace` CLI
- Changed initial internal facilities state to `null` to better handle UDB2 imports which don't set facilities. But once an update is done either filled or empty no extra updates with the same values will be recorded.
---
Ticket: https://jira.uitdatabank.be/browse/III-4613
=> III-4613 Finetune the update facilities command

app/Console/ImportOfferAutoClassificationLabels.php, src/Curators/LabelFactory.php, src/Http/Offer/EditOfferRestController.php, src/Label/LabelServiceInterface.php, src/LabelJSONDeserializer.php, src/Offer/BulkLabelCommandHandler.php, src/Offer/CommandHandlers/AddLabelHandler.php, src/Offer/Commands/AbstractLabelCommand.php, src/Offer/Commands/AddLabelToMultiple.php, src/Offer/Commands/AddLabelToMultipleJSONDeserializer.php, src/Offer/Commands/AddLabelToQuery.php, src/Offer/Commands/AddLabelToQueryJSONDeserializer.php, src/UiTPAS/Event/EventProcessManager.php, src/UiTPAS/Label/InMemoryUiTPASLabelsRepository.php, src/UiTPAS/Label/UiTPASLabelsRepository.php, tests/Curators/LabelFactoryTest.php, tests/Curators/NewsArticleProcessManagerTest.php, tests/Http/Offer/EditOfferRestControllerTest.php, tests/LabelJSONDeserializerTest.php, tests/Offer/BulkLabelCommandHandlerTest.php, tests/Offer/CommandHandlers/AddLabelHandlerTest.php, tests/Offer/Commands/AbstractLabelCommandTest.php, tests/Offer/Commands/AddLabelToMultipleJSONDeserializerTest.php, tests/Offer/Commands/AddLabelToMultipleTest.php, tests/Offer/Commands/AddLabelToQueryJSONDeserializerTest.php, tests/Offer/Commands/AddLabelToQueryTest.php, tests/Security/LabelCommandBusSecurityTest.php, tests/UiTPAS/Event/EventProcessManagerTest.php, tests/UiTPAS/Label/InMemoryUiTPASLabelsRepositoryTest.php
- Make `AddLabel` use the new VO `Label` instead the legacy one.
- Make `app/Console/ImportOfferAutoClassificationLabels`, `Curators/LabelFactory`, `Http/Offer/EditOfferRestController`, `LabelJSONDeserializer`, `Offer/BulkLabelCommandHandler`,`Offer/Commands/AddLabelToMultiple`, `Offer/Commands/AddLabelToMultipleJSONDeserializer`, `Offer/Commands/AddLabelToQuery`, `Offer/Commands/AddLabelToQueryJSONDeserializer`, `UiTPAS/Event/EventProcessManager`, `UiTPAS/Label/InMemoryUiTPASLabelsRepository`  use the  new VO `Label` instead the legacy one.
- Updated tests after refactoring
---
Ticket: https://jira.uitdatabank.be/browse/III-4786
=> III-4786 refactor add label use new vo

src/Label/CommandHandler.php, src/Label/Commands/Create.php, src/Label/Commands/CreateCopy.php, src/Label/Services/WriteService.php, tests/Label/CommandHandlerTest.php, tests/Label/Commands/CreateCopyTest.php, tests/Label/Commands/CreateTest.php, tests/Label/Services/WriteServiceTest.php
- Changed the legacy `LabelName` in the Commands of the `Label` aggregate
---
Ticket: https://jira.uitdatabank.be/browse/III-47896
=> III-4786 get rid legacy label in aggregate Commands

src/Event/ReadModel/JSONLD/EventLDProjector.php, src/Offer/AvailableTo.php, tests/Event/ReadModel/JSONLD/EventLDProjectorTest.php
- Made sure to Keep `availableTo` on the start date for lessenreeks
---
Ticket: https://jira.uitdatabank.be/browse/III-4790
=> III-4790 Keep `availableTo` on start date for lessenreeks

composer.json
- Added `allow-plugins` section in `composer.json
- Added `kylekatarnls/update-helper`, `icanhazstring/composer-unused` to `allow-plugins`
---
Ticket: https://getcomposer.org/doc/06-config.md#allow-plugins
=> Add allow plugins on composer

bootstrap.php
- Fix DeleteOrganizerHandler from Offer namespace not being subscribed to the command bus. Both Organizer and Offer namespaces have a DeleteOrganizerHandler, and only the one for Organizer was imported and subscribed twice. So the one for Offer was not subscribed.
---
Ticket: https://jira.uitdatabank.be/browse/III-4840
=> III-4840 Fix DeleteOrganizerHandler from Offer namespace not being subscribed

src/Model/ValueObject/Taxonomy/Label/LabelName.php, tests/Model/ValueObject/Taxonomy/Label/LabelNameTest.php
- Rollback of the Regex change of III-4783 so newlines are again blocked in new `LabelName`
- updated tests for newlines in `LabelName` to comply with 
---
Ticket: https://jira.uitdatabank.be/browse/III-4796
=> III-4796 reactive regex to block newlines

src/Http/Place/EditPlaceRestController.php
- Update constructor of `EditPlaceRestController` to use DefaultOfferEditingService so the endpoint `events` still works
---
Ticket: https://jira.uitdatabank.be/browse/III-4866
=> update contructor parameter

app/Error/ErrorLogger.php
- Do not log League Router errors. They are both 4xx errors and converted correctly to an ApiProblem, so not exceptions that we should fix.
---
Ticket: https://jira.uitdatabank.be/browse/III-4896
=> III-4896 Do not log League Router errors

src/Doctrine/ReadModel/CacheDocumentRepository.php
- Throw when saving in Redis Cache fails
---
Ticket: https://jira.uitdatabank.be/browse/III-4893
=> III-4893 Throw when saving in Redis Cache fails

app/Authentication/AuthServiceProvider.php
Examples that should be public:
- /events/{eventId}/permission/{userId}
- /places/{placeId}/permission/{userId}
- /organizers/{placeId}/permission/{userId}
- /events/{eventId}/permissions/{userId}
- /places/{placeId}/permissions/{userId}
- /organizers/{placeId}/permissions/{userId}
(and also singular event / place)
Examples that should NOT be public:
- /events/{eventId}/permission/
- /places/{placeId}/permission/
- /organizers/{placeId}/permission/
- /events/{eventId}/permissions/
- /places/{placeId}/permissions/
- /organizers/{placeId}/permissions/
(and also singular event / place, and without trailing slash)
-> These are to check the permission for the user based on the Authorization header
I accidentally removed the `.+` that was originally in the Symfony firewall config for these …
=> III-4901 Fix some permission routes that are accidentally public

bootstrap.php
- Registered `UiTPASServiceLabelsControllerProvider` to prevent crash when getting UiTPAS labels
=> Register `UiTPASServiceLabelsControllerProvider`

bootstrap.php, src/Http/Media/UploadMediaRequestHandler.php, src/Media/ImageUploaderInterface.php, src/Media/ImageUploaderService.php, tests/Http/Media/UploadMediaRequestHandlerTest.php, tests/Media/ImageUploaderServiceTest.php
- Refactor image uploader to use `UploadedFileInterface`
---
Ticket: https://jira.uitdatabank.be/browse/III-4891
=> III-4891 Refactor image uploader to use `UploadedFileInterface`

app/Console/ReindexOffersWithPopularityScore.php
- Intercept event projected events when the popularity score of a place is updated. This should prevent updates to the related events.
---
Ticket: https://jira.uitdatabank.be/browse/III-4941
=> III-4941 Intercept event projected events when place is projected

app/Error/WebErrorHandler.php, app/Error/WebErrorHandlerProvider.php, app/Http/CustomLeagueRouterStrategy.php, app/Http/PsrRouterServiceProvider.php, src/Offer/ReadModel/JSONLD/OfferJsonDocumentReadRepository.php, tests/Http/Offer/GetCalendarSummaryRequestHandlerTest.php, tests/Http/Offer/GetDetailRequestHandlerTest.php, web/index.php
- Fixed missing route parameters in error handling caused by the exceptions occurring in the new router being handled by Silex, which does not know about the route parameters of the routes handled by the new router. Fixed by letting the new router handle throwables itself.
- Moved some of the web error handling logic to a more framework-agnostic class so we wouldn't tie the new router to Silex-specific classes like a ServiceProvider
- `OfferJsonDocumentReadRepository` no longer throws `ApiProblem`, but `DocumentDoesNotExist` instead. This makes it easier to test this since the only route registered in the new router uses this class. And `OfferJsonDocumentReadRepository` is not in the HTTP layer so it should not throw HTTP-specific exceptions (= ApiProblem)
---
Ticket: …
=> III-4949 Fix missing route parameters in error handling

src/UiTPASService/Controller/SetCardSystemsOnEventRequestHandler.php, tests/UiTPASService/Controller/SetCardSystemsOnEventRequestHandlerTest.php
- When updating an event's UiTPAS card systems, an empty list of card systems is allowed (again)
---
Ticket: https://jira.uitdatabank.be/browse/III-4950
=> III-4950 Allow an empty list of card system ids for events

src/EventExport/Format/TabularData/TabularDataEventFormatter.php, tests/EventExport/Format/TabularData/TabularDataEventFormatterTest.php, tests/EventExport/samples/event_with_dates.json
- Tabular data exports no longer look for a non-existent `calendarSummary` property on the event JSON-LD if the calendar summary cannot be generated
- The related unit test now actually tests that the calendar summary is generated, instead of testing the fallback
---
Ticket: https://jira.uitdatabank.be/browse/III-4913
=> III-4913 Remove calendarSummary property fallback in Excel exports

.github/CODEOWNERS
- Added `steftrenson` to CODEOWNERS so he also gets automatically assigned to new PRs
=> Add steftrenson to CODEOWNERS

src/Http/Proxy/ProxyRequestHandler.php, tests/Http/Proxy/ProxyRequestHandlerTest.php
- Fixed the proxy endpoints for `/events`, `/places`, `/offers` and `/organizers` on acc where they were broken because the incoming request was e.g. `http://io-acc.uitdatabank.be:80/events` (due to the load balancer handling SSL and then forwarding the request using plain HTTP), and the proxy endpoints rewrote that to `https://search-acc.uitdatabank.be:80/events` which does not work since port 80 is not the right port for SSL (on our servers)
=> Make sure to use HTTPS and no explicit port when proxying a request

app/Error/CliErrorHandlerProvider.php, app/Error/ContextExceptionConverterProcessor.php, app/Error/LoggerFactory.php, app/Error/SentryHandlerScopeDecorator.php, app/Error/SentryServiceProvider.php, app/Error/WebErrorHandler.php, app/Silex/Error/CliErrorHandlerProvider.php, app/Silex/Error/SentryServiceProvider.php, bin/udb3.php, bootstrap.php
- Converted service providers from `CultuurNet\UDB3\Silex\Error` namespace to service providers for the new PSR-11 container.
- Moved all classes from this `CultuurNet\UDB3\Silex\Error` to `CultuurNet\UDB3\Error` as they are not related to Silex anymore.
---
Ticket: https://jira.uitdatabank.be/browse/III-4968
=> III-4968 PSR-11 Error service providers

worker_bootstrap.php
- The `worker_bootstrap.php` file (used by the Resque worker scripts) now fetches all required services from the PSR-11 container
---
Ticket: https://jira.uitdatabank.be/browse/III-4991
=> III-4991 Refactor worker_bootstrap.php to use PSR-11 container

migrations.php
- Fixed migrations namespace by removing `Silex`
=> Fix migrations namespace

bin/udb3.php, bootstrap.php, config/cli-config.php, web/index.php, worker_bootstrap.php
- `bootstrap.php` now returns the `$container` variable with the new League container instead of the Silex application `$app` variable
- `config/cli-config.php`, used by the Doctrine Migrations, has been updated to fetch the necessary service (the DB connection) from the PSR-11 container
- All places where `bootstrap.php` are included now use the returned container directly instead of assuming that the return value is the Silex application and getting it from that. (All those files only used the `$container` already after refactorings in other PRs)
---
Ticket: https://jira.uitdatabank.be/browse/III-4997
=> III-4997 Return `$container` instead of `$app` from `bootstrap.php`

app/Console/Command/AbstractFireProjectedToJSONLDCommand.php, app/Console/Command/ConsumeCommand.php, app/Console/Command/ImportOfferAutoClassificationLabels.php, app/Console/Command/PurgeModelCommand.php, app/Console/Command/ReindexEventsWithRecommendations.php, app/Console/Command/ReindexOffersWithPopularityScore.php, composer.json, composer.lock
- All console commands now directly extend `Symfony\Component\Console\Command\Command`, instead of the sub-class `Knp\Command\Command` (most already did)
- Removed unused `knplabs/console-service-provider` dependency (after cleanup above)
---
Ticket: https://jira.uitdatabank.be/browse/III-4998
=> III-4998 Remove `knplabs/console-service-provider` dependency

app/ApiName.php
- Removed two unused `ApiName` constants (unused since #1166)
---
Just noticed these by coincidence
=> Remove unused CDBXML and CURATORS_LISTENER ApiName constants

bootstrap.php
- Warnings related to invalid XML being passed to `new SimpleXmlElement()` are now surpressed. An exception will still be thrown (as would be expected).
---
Ticket: https://jira.uitdatabank.be/browse/III-4837
Note: I primarily tested this in a PHP sandbox: https://onlinephp.io/c/754a2 (change the `true` to `false`, or remove the `libxml_use_internal_errors(true);` completely, to test the default behavior and see the warning it originally generated)
=> III-4837 Surpress invalid XML warnings

app/Error/ErrorLogger.php, src/Http/ApiProblem/ApiProblem.php, src/Http/ApiProblem/ApiProblemFactory.php
- Some specific `CultureFeed_HttpException` errors are converted to 502 Bad Gateway responses, and those are now excluded from logs and Sentry (since we cannot fix them on our end, and we have different monitoring to keep an eye on UiTPAS)
---
Ticket: https://jira.uitdatabank.be/browse/III-4719
I tested this manually by temporary making a request handler throw the exception as it was logged in Sentry (locally). We cannot cover this with acceptance tests sadly.
=> III-4719 Convert (some) `CultureFeed_HttpException` errors to 502 Bad Gateway

src/Http/ApiProblem/ApiProblem.php, src/Http/ApiProblem/ApiProblemFactory.php
- `ApiProblem::eventHasUitpasTicketSales()` - see https://github.com/cultuurnet/apidocs/pull/73 for the documentation update
- `CultureFeed_Exception` is converted to `ApiProblem::eventHasUitpasTicketSales()` if the message contains "event already has ticketsales"
---
Ticket: https://jira.uitdatabank.be/browse/III-4758
=> III-4758 Convert `Culturefeed_Exception` with "event already has ticket sales" to correct ApiProblem

app/Media/ImageStorageProvider.php, app/Media/MediaImportServiceProvider.php, app/Media/MediaServiceProvider.php, app/Silex/Media/ImageStorageProvider.php, app/Silex/Media/MediaImportServiceProvider.php, app/Silex/Media/MediaServiceProvider.php, bootstrap.php
- `ImageStorageProvider`, `MediaImportServiceProvider` & `MediaServiceProvider` are now shared via the Container instead of the Silex App.
- `ImageStorageProvider`, `MediaImportServiceProvider` & `MediaServiceProvider` were moved outside the Silex folder.
---
Ticket: https://jira.uitdatabank.be/browse/III-4976
=> III-4976 make Media PSR-11 Comliant

src/Http/Media/UploadMediaRequestHandler.php, src/Media/ImageUploaderService.php, tests/Http/Media/UploadMediaRequestHandlerTest.php, tests/Media/ImageUploaderServiceTest.php
- If there is one uploaded file but its form data name is not `file`, we no longer get a type error but return an appropriate ApiProblem
- If the size of the uploaded file is `0` we return an ApiProblem instead of throwing a RuntimeException. If the size is `null` we still throw a `RuntimeException` because it could be a server issue (we'll need to see if it happens again or not after this is deployed)
---
Ticket: https://jira.uitdatabank.be/browse/III-5005
=> III-5005 Improve file upload errors

src/Http/Media/UploadMediaRequestHandler.php, src/Media/ImageUploaderService.php, tests/Http/Media/UploadMediaRequestHandlerTest.php, tests/Media/ImageUploaderServiceTest.php
- When the `copyrightHolder` field is invalid according to the `CopyrightHolder` VO a `body/invalid-data` ApiProblem is returned
- When the `language` field is invalid according to the `Language` VO a `body/invalid-data` ApiProblem is returned
- When a field is missing a `body/invalid-data` ApiProblem is returned
---
Ticket: https://jira.uitdatabank.be/browse/III-5010
=> III-5010 Improve file field errors

app/Error/ErrorLogger.php
- AMQP exceptions that commonly pop up in Sentry are no longer sent to Sentry to avoid noise of exceptions that we cannot fix in code. Usually these are caused by CloudAMQP having issues, which we cannot fix on our end
---
Ticket: https://jira.uitdatabank.be/browse/III-4818
=> III-4818 Do not log AMQP exceptions or send them to Sentry

src/Http/Media/GetMediaRequestHandler.php
- `GET /media/{id}` now returns a 404 when the media object (image) is not found, and also when the uuid is invalid (= means that we won't find a media object for the given invalid id anyway)
---
Ticket: https://jira.uitdatabank.be/browse/III-5012
=> III-5012 Fix `GET /media/{id}` not found error responses

app/EventBus/EventBusServiceProvider.php, app/Place/PlaceEditingServiceProvider.php, app/Place/PlaceGeoCoordinatesServiceProvider.php, app/Place/PlaceHistoryServiceProvider.php, app/Place/PlaceJSONLDServiceProvider.php, app/Place/PlacePermissionServiceProvider.php, app/Place/PlaceReadServiceProvider.php, app/Place/PlaceRequestHandlerServiceProvider.php, app/Silex/Place/PlaceEditingServiceProvider.php, app/Silex/Place/PlaceGeoCoordinatesServiceProvider.php, app/Silex/Place/PlaceHistoryServiceProvider.php, app/Silex/Place/PlaceJSONLDServiceProvider.php, app/Silex/Place/PlacePermissionServiceProvider.php, app/Silex/Place/PlaceReadServiceProvider.php, app/Silex/Place/PlaceRequestHandlerServiceProvider.php, bootstrap.php
- `PlaceEditingServiceProvider`, `PlaceGeoCoordinatesServiceProvider`, `PlaceHistoryServiceProvider`, `PlaceJSONLDServiceProvider`, `PlacePermissionServiceProvider`, `PlaceReadServiceProvider` & `PlaceRequestHandlerServiceProvider` are now shared via the Container instead of the Silex App.
- `PlaceEditingServiceProvider`, `PlaceGeoCoordinatesServiceProvider`, `PlaceHistoryServiceProvider`, `PlaceJSONLDServiceProvider`, `PlacePermissionServiceProvider`, `PlaceReadServiceProvider` & `PlaceRequestHandlerServiceProvider`  were moved outside the Silex folder.
- 'place_main_language_query' because it is nowhere used
---
Ticket: https://jira.uitdatabank.be/browse/III-4980
=> III-4980 psr11 place

app/Export/ExportServiceProvider.php, app/Search/Sapi3SearchServiceProvider.php, app/Silex/Offer/BulkLabelOfferServiceProvider.php, app/Silex/Search/Sapi3SearchServiceProvider.php, bootstrap.php
- `Sapi3SearchServiceProvider` is now shared via the Container instead of the Silex App.
- `Sapi3SearchServiceProvider` was moved outside the Silex folder.
---
Ticket: https://jira.uitdatabank.be/browse/III-4983
=> III-4983 psr11 Search

app/Geocoding/GeocodingServiceProvider.php, app/Silex/GeocodingServiceProvider.php, app/Silex/UDB2EventServicesProvider.php, app/UDB2/UDB2EventServicesProvider.php, bootstrap.php
- `GeocodingServiceProvider` is now PSR-11 compliant
- `UDB2EventServicesProvider` is now PSR-11 compliant
- `udb2_place_external_id_mapping_service`, `udb2_organizer_external_id_mapping_service`, `udb2_external_id_mapping_service_factory` service definitions as they were unused by other services and it made more sense to construct them inline.
---
Ticket: https://jira.uitdatabank.be/browse/III-4988
=> III-4988 Remaining providers in Silex folder

app/Silex/User/UserServiceProvider.php, app/User/UserServiceProvider.php, bootstrap.php, tests/User/Auth0ManagementTokenProviderTest.php, tests/User/Auth0UserIdentityResolverTest.php
- `UserServiceProvider` is now shared via the Container instead of the Silex App.
- `UserServiceProvider` was moved outside the Silex folder.
---
Ticket: https://jira.uitdatabank.be/browse/III-5018
=> III-5018 PSR-11 User

app/SwiftMailer/SwiftMailerServiceProvider.php, bootstrap.php
- The `mailer` service definition (a `Swift_Mailer` class instance) is now registered using a custom service provider on the new League container instead of a ServiceProvider provided by `silex/silex`
---
Ticket: https://jira.uitdatabank.be/browse/III-5020
Since this is hard to test with an acceptance test or unit test, I tested it manually by reloading the supervisor commands (so the `udb3-event-export-worker` was restarted and loaded the new code), and then doing an export of some events via the UI. I then verified that there was a new email in the local mailcatcher:
=> III-5020 Internalize SwiftmailerServiceProvider

bootstrap.php
- When `bootstrap.php` is required/included twice in the same file, as in `worker_bootstrap.php` (which I'm not sure we can change to only require/include it once because it needs the returned container in both places), the `ROLE_SEARCH_V3_REPOSITORY_TABLE_NAME` is no longer re-defined which would otherwise result in a notice that gets converted to an ErrorException
---
Ticket: https://jira.uitdatabank.be/browse/III-5028
=> III-5028 Make sure `ROLE_SEARCH_V3_REPOSITORY_TABLE_NAME` is only defined once

app/Authentication/AuthServiceProvider.php
- Fixed `PHP Fatal error:  Uncaught League\Container\Exception\NotFoundException: Alias (impersonator) is not being managed by the container or delegates in /var/www/udb-silex/vendor/league/container/src/Container.php:194`
---
Ticket: https://jira.uitdatabank.be/browse/III-5042
=> III-5042 Fix impersonator service name in getProvidedServiceNames()

readme.md
- Removed documentation about obsolete logs from README
=> Remove obsolete logs from readme

composer.json, composer.lock, src/Http/Offer/UpdateImageRequestHandler.php, src/Http/Request/Body/JsonSchemaLocator.php, src/Offer/Commands/Image/AbstractUpdateImage.php, src/Offer/OfferCommandHandler.php, src/Offer/Serializers/UpdateImageDenormalizer.php, tests/Http/Offer/UpdateImageRequestHandlerTest.php, tests/Http/Organizer/AddImageRequestHandlerTest.php, tests/OfferCommandHandlerTestTrait.php
- A request to `UpdateImageRequestHandler` is now validated with JSON schema.
- `UpdateImage` command expects string iso `StringLiteral` for a description in its constructor. It returns a string now as well.
- An `ApiProblem` is thrown when mediaId is not a valid UUID iso throwing an exception.
---
Ticket: https://jira.uitdatabank.be/browse/III-4258
=> III-4258 update offer image

Jenkinsfile
- Application environment indicator for publishing aptly snapshots should be fetched from stage environment
---
Ticket: https://jira.uitdatabank.be/browse/III-5070
=> Use application environment from stage environment variable when publishing an aptly snapshot

app/Http/PsrRouterServiceProvider.php, app/Offer/OfferServiceProvider.php, composer.json, composer.lock, src/Http/Offer/PatchOfferRequestHandler.php, src/Http/Offer/UpdateWorkflowStatusRequestHandler.php, src/Http/Request/Body/JsonSchemaLocator.php, src/Offer/Serializers/UpdateWorkflowStatusDenormalizer.php, tests/Http/Offer/UpdateWorkflowStatusRequestHandlerTest.php
- Added a new route & request handler to update the `workflowStatus` of an event or place, to replace the quirky PATCH endpoint that uses custom content-types to determine the intended state transition.
---
Ticket: https://jira.uitdatabank.be/browse/III-4272
I will add some acceptance tests as well, but in the meantime this can already be reviewed if someone has the time (as well as the schema in https://github.com/cultuurnet/apidocs/pull/115)
Edit: Done, see https://github.com/cultuurnet/udb3-acceptance-tests/pull/169
I'll also fix the merge conflict in `composer.lock` once the schema is merged, because I'll have to update the `publiq/udb3-json-schemas` dependency then again anyway
Edit: Done
=> III-4272 Endpoint to update `workflowStatus`

tests/Broadway/AMQP/EventBusForwardingConsumerTest.php, tests/EventExport/Format/HTML/HTMLFileWriterTest.php, tests/Label/ReadModels/Relations/ProjectorTest.php, tests/Offer/BulkLabelCommandHandlerTest.php, tests/Offer/CommandHandlers/AddLabelHandlerTest.php, tests/Offer/CommandHandlers/ImportLabelsHandlerTest.php, tests/Organizer/CommandHandler/ImportLabelsHandlerTest.php, tests/Place/CanonicalPlaceRepositoryTest.php
- replaced deprecated `assertFileNotExists()` with `assertFileDoesNotExist()`
- replaced deprecated `at()` depending on how it was used.
- Code cleanup of edited files
---
Ticket: https://jira.uitdatabank.be/browse/III-5111
=> III-5111 Refactor Unit to avoid deprecated methods

app/Http/PsrRouterServiceProvider.php, src/Http/Auth/CorsHeadersResponseDecorator.php, tests/Http/Auth/CorsHeadersResponseDecoratorTest.php, web/index.php
- Every error response now also gets CORS headers added, to prevent 401, 403, 404 etc errors in the frontend from being inaccessible to the JS code due to missing CORS headers.
---
Ticket: https://jira.uitdatabank.be/browse/III-5125
=> III-5125 Fix missing CORS headers from error responses

composer.lock, tests/EventExport/CalendarSummary/CalendarSummaryWithFormatterRepositoryTest.php, tests/Http/Offer/GetCalendarSummaryRequestHandlerTest.php
- updated calendar-summary to v4.0.3
- Replaced `CarbonImmutable::setTestNow()` with abstraction in calendar-summary
---
Ticket: https://jira.uitdatabank.be/browse/...
=> Abstraction Layer setTestNow()

composer.lock, src/Cdb/CdbXmlPriceInfoParser.php, src/Model/Serializer/ValueObject/Price/PriceInfoDenormalizer.php, src/MoneyFactory.php, src/PriceInfo/BasePrice.php, src/PriceInfo/Tariff.php, src/UiTPAS/Event/Event/PricesUpdatedDeserializer.php, tests/EventExport/CalendarSummary/CalendarSummaryWithFormatterRepositoryTest.php, tests/Http/Offer/GetCalendarSummaryRequestHandlerTest.php, tests/Http/Offer/UpdatePriceInfoRequestHandlerTest.php, tests/MoneyFactoryTest.php
- `MoneyFactory` to better handle the conversions from `int`, `float` & `string` to `Money` 
- € 2.3 is no longer changed to € 2.29
- Temp Fix for `setTestNow()`
---
Ticket: https://jira.uitdatabank.be/browse/III-5159
=> III-5159 Rounding Error eg. € 2.30

app/Authentication/AuthServiceProvider.php, app/Security/OfferSecurityServiceProvider.php, app/Security/OrganizerSecurityServiceProvider.php, app/User/UserServiceProvider.php, src/Http/Auth/Jwt/JsonWebToken.php, src/Http/Auth/RequestAuthenticatorMiddleware.php, src/Security/InMemoryUserEmailAddressRepository.php, src/Security/Permission/ContributorVoter.php, src/Security/UserEmailAddressRepository.php, tests/Http/Auth/Jwt/JsonWebTokenTest.php, tests/Security/InMemoryUserEmailAddressRepositoryTest.php, tests/Security/Permission/ContributorVoterTest.php
- `ContributorVoter` to  give Contributors `edit` rights.
- `UserEmailAddressRepository` to retrieve `email` from `userId`
- `InMemoryUserEmailAddressRepository` as implementation of `UserEmailAddressRepository`
- Added `ContributorVoter` to `OfferSecurityServiceProvider` & `OrganizerSecurityServiceProvider`
- `getEmailAddress()` on `JsonWebToken`
---
Ticket: https://jira.uitdatabank.be/browse/III-5214
=> III-5214 Give contributors edit rights

app/AMQP/AMQPPublisherServiceProvider.php, app/Contributor/ContributorServiceProvider.php, src/Contributor/BroadcastingContributorRepository.php, src/Contributor/ContributorsUpdated.php, src/Contributor/ContributorsUpdatedFactory.php, src/Event/EventContributorsUpdated.php, src/Organizer/OrganizerContributorsUpdated.php, src/Place/PlaceContributorsUpdated.php, tests/Contributor/BroadcastingContributorRepositoryTest.php
- `BroadcastingContributorRepository` as `Decorator` to publish messages
- Abstract `ContributorsUpdated` And childClasses `EventContributorsUpdated`, `PlaceContributorsUpdated` & `OrganizerContributorsUpdated` for Messages
- `ContributorsUpdatedFactory` to create message depending on `ItemType`
- Use `BroadcastingContributorRepository` instead of `DbalContributorRepository` in `ServiceProvider`
---
Ticket: https://jira.uitdatabank.be/browse/III-5334
=> III-5334 messaging contributors

src/Security/InMemoryUserEmailAddressRepository.php
- make `JsonWebToken` nullabel in constructor of `InMemoryUserEmailAddressRepository` since a `CurrentUser` does not always exist.
---
Ticket: https://jira.uitdatabank.be/browse/III-5214
=> III-5214 Hotfix: make token nullable

app/Console/Command/FindOutOfSyncProjections.php, app/Console/ConsoleServiceProvider.php
- Added script to find out-of-sync projections based on a first and last row id
- This script is very basic, it needs to be finetuned but can be used to get a feeling of the amount of data to process and how well it fits the expected format.
=> Add script to find out of sync projections

.github/CODEOWNERS
- Added @simon-debruijn to the `CODEOWNERS` file so his approvals are actually valid to merge a PR
---
Simon will mostly review OSLO-related PRs at first
=> Make Simon CODEOWNER so he can also approve PRs

src/Event/Events/MajorInfoUpdated.php, src/EventSourcing/ConvertsToGranularEvents.php, tests/Event/Events/MajorInfoUpdatedTest.php
- Added a way to split up `MajorInfoUpdated` events from `Event` namespace, in preparation of the RDF/OSLO projector in UDB3
---
Ticket: https://jira.uitdatabank.be/browse/III-5350
=> III-5350 split up major info (Event)

src/Event/Events/EventCreated.php, src/EventSourcing/ConvertsToGranularEvents.php, tests/Event/Events/EventCreatedTest.php
- Added a method to convert `EventCreated` into smaller events, in preparation for the RDF/OSLO projector
---
Ticket: https://jira.uitdatabank.be/browse/III-5364
=> III-5364 Split up EventCreated

src/Place/Events/PlaceCreated.php, tests/Place/Events/PlaceCreatedTest.php
- Implemented `ConvertsToGranularEvents` on `PlaceCreated` in preparation for the new RDF/OSLO projector
---
Ticket: https://jira.uitdatabank.be/browse/III-5365
=> III-5365 Split up PlaceCreated in smaller events

src/Event/Productions/ProductionEnrichedEventRepository.php, tests/Event/Productions/ProductionEnrichedEventRepositoryTest.php
- Don't save dynamic field `production` in `JsonDocument`
---
Ticket: https://jira.uitdatabank.be/browse/III-5334
=> III-5334 dont save dynamic field `production` in `JsonDocument`

app/Migrations/Version20230215144540.php
- Fixed migration file name by removing extra digit
=> Fix migration file name by removing extra digit

src/Event/Events/EventCreated.php, src/Event/Events/EventImportedFromUDB2.php, src/EventSourcing/MainLanguageDefined.php, src/Place/Events/PlaceCreated.php, src/Place/Events/PlaceImportedFromUDB2.php, tests/Event/Events/EventCreatedTest.php, tests/Event/Events/EventImportedFromUDB2Test.php, tests/Place/Events/PlaceCreatedTest.php, tests/Place/Events/PlaceImportedFromUDB2Test.php
- Added `MainLanguageDefined` interface, implemented on events that create new events|places. This was initially added in #1278 but I split it off to keep the PRs focused on a small scope.
---
Ticket: https://jira.uitdatabank.be/browse/III-5389
=> III-5389 Add MainLanguageDefined interface

composer.json, composer.lock
- Update `udb3-json-schemas` to allow `[]` in `contributors` endpoint, needed to delete all `contributors`
---
Ticket: https://jira.uitdatabank.be/browse/IIII-5214
=> IIII-5214 Update udb3-json-schemas to allow empty array in contributors endPoint

src/Place/ReadModel/RDF/RdfProjector.php, src/RDF/RdfNamespaces.php, tests/Place/ReadModel/RDF/RdfProjectorTest.php, tests/Place/ReadModel/RDF/data/place-created.ttl, tests/Place/ReadModel/RDF/data/title-translated.ttl, tests/Place/ReadModel/RDF/data/title-updated-and-translated.ttl, tests/Place/ReadModel/RDF/data/title-updated.ttl
- Projection of `rdf:type` property
- Projection of `dcterms:created` property ("aangemaaktOp" in OSLO generiek)
- Projection of `dcterms:modified` property ("laatstAangepast" in OSLO generiek)
- Projection of `adms:identifier` resource with:
- `skos:notation`
- `dcterms:creator`
- `generiek:naamruimte` (from OSLO generiek)
- `generiek:lokaleIdentificator` (from OSLO generiek)
- `generiek:versieIdentificator` (from OSLO generiek)
---
Ticket: https://jira.uitdatabank.be/browse/III-5392
Notes:
- The correct URI for the `dcterms:creator` property inside `adms:Identifier` is not decided yet, needs to be replaced later (hence the "fixme.com" URL so it's clear that this is not final)
- We will also need to add a "bron" attribute to the `adms:Identifier`, but the URI for that property is not …
=> III-5392 Project common place properties

docker-compose.yml, docker.md
- Used custom RabbitMQ image with preconfigured exchange and queues equal to Vagrant setup
=> Use custom RabbitMQ image

src/Place/ReadModel/RDF/RdfProjector.php, tests/Place/ReadModel/RDF/data/place-created.ttl, tests/Place/ReadModel/RDF/data/title-translated.ttl, tests/Place/ReadModel/RDF/data/title-updated-and-translated.ttl, tests/Place/ReadModel/RDF/data/title-updated.ttl
- Added missing timezones to `xsd:dateTime` datatype properties
- Changed `generiek:versieIdentificator` from datatype `xsd:dateTime` to `xsd:string` for correct compatibility with OSLO generiek
---
Ticket: https://jira.uitdatabank.be/browse/III-5417
=> III-5417 Fix datetime properties

app/Migrations/Version20230309140014.php, composer.json, composer.lock, src/Curators/DBALNewsArticleRepository.php, src/Curators/NewsArticle.php, src/Curators/NewsArticleImage.php, src/Curators/NewsArticleSchemaConfigurator.php, src/Curators/Serializer/NewsArticleDenormalizer.php, src/Curators/Serializer/NewsArticleNormalizer.php, tests/Curators/DBALNewsArticleRepositoryTest.php, tests/Http/Curators/CreateNewsArticleRequestHandlerTest.php, tests/Http/Curators/GetNewsArticleRequestHandlerTest.php, tests/Http/Curators/UpdateNewsArticleRequestHandlerTest.php
- Migration to add `image_url` & `copyright_holder` to `news_article` table
- class `NewsArticleImage`
- updated `publiq/udb3-json-schemas` in `composer`
- `NewsArticle`: added optional `NewsArticleImage`
- `DBALNewsArticleRepository`: added support for CRUD-options on `NewsArticle` with `Images`
- `NewsArticleDenormalizer`: added support for `Images`
- `NewsArticleNormalizer`: added support for `Images`
- `*NewsArticleRequestHandlers`: added tests for `NewsArticle` with `image`
- `DBALNewsArticleRepositoryTest`: added tests for `NewsArticle` with `image`
---
Ticket: https://jira.uitdatabank.be/browse/III-5166
=> III-5166 add `image` to `NewsArticle`

bootstrap.php
- Fixed the non-default RDF prefixes not working correctly. We also have to register them globally in the regular app. Until now it was only done in tests/bootstrap.php, which is why they worked in the tests but were missing in the actual Fuseki data.
---
Ticket: https://jira.uitdatabank.be/browse/III-5424
=> III-5424 Fixed the non-default RDF prefixes not working correctly

app/Event/EventGeoCoordinatesServiceProvider.php, app/Organizer/OrganizerGeoCoordinatesServiceProvider.php, app/Place/PlaceGeoCoordinatesServiceProvider.php, app/Place/PlaceRdfServiceProvider.php, src/Address/AddressFormatter.php, src/Address/AddressParser.php, src/Address/DefaultAddressFormatter.php, src/Address/FullAddressFormatter.php, src/Address/GeopuntAddressParser.php, src/Address/LocalityAddressFormatter.php, src/Address/ParsedAddress.php, src/Offer/AbstractGeoCoordinatesCommandHandler.php, src/Organizer/CommandHandler/UpdateGeoCoordinatesFromAddressCommandHandler.php, src/Place/ReadModel/RDF/RdfProjector.php, tests/Address/DefaultAddressFormatterTest.php, tests/Address/GeopuntAddressParserTest.php, tests/Event/GeoCoordinatesCommandHandlerTest.php, tests/Organizer/CommandHandler/UpdateGeoCoordinatesCommandHandlerTest.php, tests/Place/GeoCoordinatesCommandHandlerTest.php, tests/Place/ReadModel/RDF/RdfProjectorTest.php, tests/Place/ReadModel/RDF/data/address-translated.ttl, tests/Place/ReadModel/RDF/data/address-updated.ttl, tests/Place/ReadModel/RDF/data/place-created.ttl, tests/Place/ReadModel/RDF/data/title-translated.ttl, tests/Place/ReadModel/RDF/data/title-updated-and-translated.ttl, tests/Place/ReadModel/RDF/data/title-updated.ttl, tests/TestLogger.php
- Projection of `locn:address` predicate on places with `locn:Address` node with `locn:fullAddress`, `locn:thoroughfare`, `locn:locatorDesignator`, `locn:postcode`, `locn:postName`, `locn:adminUnitL1`
- `GeopuntAddressParser` to look up the thoroughfare and house number of an address given a formatted address, so that we can convert the "streetAddress" in the UDB3 data to a separate street (thoroughfare) & house number
- Removed `Interface` suffix from `AddressFormatter(Interface)`
- Renamed `DefaultAddressFormatter` to `FullAddressFormatter`
---
Ticket: https://jira.uitdatabank.be/browse/III-5357
=> III-5357 RDF address projection

app/Console/Command/ChangePlaceTypeOnEvents.php, app/Console/ConsoleServiceProvider.php
- Command `ChangePlaceTypeOnEvents` to give `events` with an incorrect `placeType` a correct `eventType` and set their  `availableFrom` far in the future.
- Register `ChangePlaceTypeOnEvents` in `ServiceProvider`
---
Ticket: https://jira.uitdatabank.be/browse/III-5422
=> III-5422 Fix events with incorrect PlaceType 

src/Event/Events/DummyLocation.php, src/Event/Events/DummyLocationUpdated.php, src/Event/Events/EventFromUDB2.php, src/Event/Events/EventImportedFromUDB2.php, src/Event/Events/EventUpdatedFromUDB2.php, src/Event/Events/ExternalIdLocationUpdated.php, tests/Event/Events/EventImportedFromUDB2Test.php, tests/Event/Events/EventUpdatedFromUDB2Test.php, tests/Event/samples/event_with_externalid_location.cdbxml.xml
- `DummyLocation`- class to store `Title` & `Address` of a DummyLocation from `UDB2`
- interface `DummyLocationUpdated` to get `DummyLocation` from `EventImportedFromUDB2` & `EventUpdatedFromUDB2 `
- interface `ExternalIdLocationUpdated ` to get `externalId` from `EventImportedFromUDB2` & `EventUpdatedFromUDB2 `
- implemented `DummyLocationUpdated` & `ExternalIdLocationUpdated` in trait `EventFromUDB2`
- Added tests for `getDummyLocation()` & `getExternalId()`
---
Ticket: https://jira.uitdatabank.be/browse/III-5352
=> III-5352 events from udb2 to granular events dummy locations

composer.json, composer.lock, src/Model/Serializer/ValueObject/MediaObject/VideoNormalizer.php, src/Model/ValueObject/MediaObject/Video.php, tests/Http/Event/ImportEventRequestHandlerTest.php, tests/Http/Offer/AddVideoRequestHandlerTest.php, tests/Model/Serializer/ValueObject/MediaObject/VideoNormalizerTest.php
- Test for adding embedded YouTube urls.
- Updated `publiq/udb3-json-schemas` in `composer` to allow embedded YouTube urls.
- Updated Regex in ValueObject `Video` to allow embedded YouTube urls.
- Updated tests with new Video-url regex.
- Update `VideoNormalizer` to handle embedded YouTube urls.
- Update test for `VideoNormalizer`
---
Ticket: https://jira.uitdatabank.be/browse/III-5428
=> III-5428 embed youtube url

src/Place/ReadModel/RDF/RdfProjector.php, tests/Place/ReadModel/RDF/data/address-translated.ttl, tests/Place/ReadModel/RDF/data/address-updated.ttl, tests/Place/ReadModel/RDF/data/geo-coordinates-updated.ttl, tests/Place/ReadModel/RDF/data/place-created.ttl, tests/Place/ReadModel/RDF/data/title-translated.ttl, tests/Place/ReadModel/RDF/data/title-updated-and-translated.ttl, tests/Place/ReadModel/RDF/data/title-updated.ttl
- `dcterms:creator` value is now a resource link, so it's wrapped in `<...>` instead of `"..."` in the Turtle data and it is a link instead of a literal string
---
Ticket: https://jira.uitdatabank.be/browse/III-5520
=> III-5520 Mark dcterms:creator value as a Resource

src/Place/ReadModel/RDF/RdfProjector.php, tests/Place/ReadModel/RDF/data/address-translated.ttl, tests/Place/ReadModel/RDF/data/address-updated.ttl, tests/Place/ReadModel/RDF/data/geo-coordinates-updated.ttl, tests/Place/ReadModel/RDF/data/place-created.ttl, tests/Place/ReadModel/RDF/data/title-translated.ttl, tests/Place/ReadModel/RDF/data/title-updated-and-translated.ttl, tests/Place/ReadModel/RDF/data/title-updated.ttl
- Added `xsd:anyUri` datatype to `skos:notation` predicate value
---
Ticket: https://jira.uitdatabank.be/browse/III-5522
=> III-5522 Add xsd:anyUri datatype to skos:notation predicate value

src/Place/Events/PlaceCreated.php, src/Place/ReadModel/RDF/RdfProjector.php, src/RDF/InMemoryGraphRepository.php, src/RDF/RdfNamespaces.php, tests/Place/Events/PlaceCreatedTest.php, tests/Place/ReadModel/RDF/RdfProjectorTest.php, tests/Place/ReadModel/RDF/data/address-translated.ttl, tests/Place/ReadModel/RDF/data/address-updated.ttl, tests/Place/ReadModel/RDF/data/geo-coordinates-updated.ttl, tests/Place/ReadModel/RDF/data/place-approved.ttl, tests/Place/ReadModel/RDF/data/place-created-with-publication-date.ttl, tests/Place/ReadModel/RDF/data/place-created.ttl, tests/Place/ReadModel/RDF/data/place-deleted.ttl, tests/Place/ReadModel/RDF/data/place-published.ttl, tests/Place/ReadModel/RDF/data/place-rejected.ttl, tests/Place/ReadModel/RDF/data/title-translated.ttl, tests/Place/ReadModel/RDF/data/title-updated-and-translated.ttl, tests/Place/ReadModel/RDF/data/title-updated.ttl
- Added `udb:workflowStatus` predicate based on `PlaceCreated`, `PlaceDeleted`, `Published`, `Approved`, `Rejected`, `FlaggedAsDuplicate` and `FlaggedAsInappropriate` events (based on how the `workflowStatus` property is set in the JSON projector)
---
Ticket: https://jira.uitdatabank.be/browse/III-5508
=> III-5508 add workflow status predicate

src/Offer/ReadModel/JSONLD/OfferLDProjector.php, tests/Offer/ReadModel/JSONLD/OfferLDProjectorTest.php
-  `OfferLDProjectorTest`: added test to check if `ImagedRemoved` with `http`-link unsets the same MainImage with `https`
- `OfferLDProjector`: make comparison with `mainImageUrl` protocol-agnostic, when an `ImageRemoved` is applied.
- `OfferLDProjector`: always unset `mainImageUrl` if no `MainObjects` remain
- `ImageRemoved` with `http` can now unset the `mainImageUrl` if it is the same but url with `https`
---
Ticket: https://jira.uitdatabank.be/browse/III-4684
=> III-4684 Offers with MainImage and no MediaObject

src/Offer/ReadModel/JSONLD/PropertyPolyfillOfferRepository.php, tests/Offer/ReadModel/JSONLD/PropertyPolyfillOfferRepositoryTest.php
- Polyfill to remove `image` from `json` if no `mediaObjects` are present
- tests for new Polyfill
- This does not handle the edge case where an a legacy `mainImage` is removed but the `json` still contains other images.
---
Ticket: https://jira.uitdatabank.be/browse/III-5544
=> III-5544 polyfill mainimage

src/Event/ReadModel/RDF/RdfProjector.php, src/Place/ReadModel/RDF/RdfProjector.php, src/RDF/Editor/GraphEditor.php, tests/Event/ReadModel/RDF/data/approved.ttl, tests/Event/ReadModel/RDF/data/deleted.ttl, tests/Event/ReadModel/RDF/data/published.ttl, tests/Event/ReadModel/RDF/data/rejected.ttl, tests/Event/ReadModel/RDF/data/title-translated.ttl, tests/Event/ReadModel/RDF/data/title-updated-and-translated.ttl, tests/Event/ReadModel/RDF/data/title-updated.ttl, tests/Place/ReadModel/RDF/data/address-translated.ttl, tests/Place/ReadModel/RDF/data/address-updated.ttl, tests/Place/ReadModel/RDF/data/geo-coordinates-updated.ttl, tests/Place/ReadModel/RDF/data/place-approved.ttl, tests/Place/ReadModel/RDF/data/place-created.ttl, tests/Place/ReadModel/RDF/data/place-deleted.ttl, tests/Place/ReadModel/RDF/data/place-published.ttl, tests/Place/ReadModel/RDF/data/place-rejected.ttl, tests/Place/ReadModel/RDF/data/title-translated.ttl, tests/Place/ReadModel/RDF/data/title-updated-and-translated.ttl, tests/Place/ReadModel/RDF/data/title-updated.ttl
- Removed `generiek` part of identificator
---
Ticket: https://jira.uitdatabank.be/browse/III-5425
=> III-5425 Remove `generiek` part of identificator

app/Event/EventRdfServiceProvider.php, src/Event/ReadModel/RDF/CacheLocationIdRepository.php, src/Event/ReadModel/RDF/InMemoryLocationIdRepository.php, src/Event/ReadModel/RDF/LocationIdRepository.php, src/Event/ReadModel/RDF/RdfProjector.php, src/RDF/RdfNamespaces.php, tests/Event/ReadModel/RDF/RdfProjectorTest.php, tests/Event/ReadModel/RDF/data/calendar-updated-multiple.ttl, tests/Event/ReadModel/RDF/data/calendar-updated-periodic.ttl, tests/Event/ReadModel/RDF/data/calendar-updated-single.ttl, tests/Event/ReadModel/RDF/data/created-with-calendar-multiple.ttl, tests/Event/ReadModel/RDF/data/created-with-calendar-periodic.ttl, tests/Event/ReadModel/RDF/data/created-with-calendar-single.ttl, tests/Event/ReadModel/RDF/data/various-calendar-updated.ttl
- Added handler for `CalendarUpdated` on event for single calendar type.
- Added repo to store the `LocationId` when `LocationUpdated` is handled so it can be used when `CalendarUpdated` is handled.
- For the `periodic` calendar the opening hours are ignored.
---
Ticket: https://jira.uitdatabank.be/browse/III-5363
=> III-5363 Handle `calendarUpdated` on event (single/multiple/periodic)

app/Event/EventJSONLDServiceProvider.php, src/Doctrine/ReadModel/CacheDocumentRepository.php, src/Offer/ReadModel/JSONLD/OfferLDProjector.php
- Added log for `applyPublished` method of `EventLDProjector`
- Added log for `save` method of `CacheDocumentRepository`
---
Ticket: https://jira.uitdatabank.be/browse/III-5281
=> III-5281 Add extra logging to monitor published

src/Address/FullAddressFormatter.php, tests/Address/DefaultAddressFormatterTest.php
- Remove `street` if it is empty in `FullAddressFormatter`
- test for `FullAddressFormatter` with empty `street` 
- Avoid a leading comma when a formatting a legacy Place from `CdbXml` without a `streetAdress`
---
Ticket: https://jira.uitdatabank.be/browse/III-5351
=> III-5351 FullAddressFormatter for Empty street

src/Address/FullAddressFormatter.php, src/Place/Events/PlaceFromUDB2.php, tests/Address/DefaultAddressFormatterTest.php, tests/Place/Events/PlaceImportedFromUDB2Test.php, tests/Place/Events/PlaceUpdatedFromUDB2Test.php, tests/Place/actor_without_housnr.xml, tests/Place/actor_without_street.xml
- `getStreet()` to return streetAddress regardless if it is missing in `CdbXml` in `PlaceFromUDB2`
- test-`CdbXml` with places without `street` and `housenr`
- test for `PlaceImportedFromUDB2` with `CdbXml` without missing `street` & `housenr`
- test for `PlaceUpdatedFromUDB2` with `CdbXml` without missing `street` & `housenr`
- `TypeError` during replay
---
Ticket: https://jira.uitdatabank.be/browse/III-5351
=> III-5351 Bugfix for legacy Places without street and/or housenr

composer.json, composer.lock, tests/Http/Event/ImportEventRequestHandlerTest.php, tests/Http/Event/UpdateOnlineUrlRequestHandlerTest.php, tests/Http/Offer/UpdateBookingInfoRequestHandlerTest.php, tests/Http/Organizer/UpdateContactPointRequestHandlerTest.php
- Test in `UpdateBookingInfoRequestHandlerTest` for invalid `Url` with triple slashes.
- Updated `publiq/udb3-json-schemas` in `composer`
- `ImportEventRequestHandlerTest`, `UpdateOnlineUrlRequestHandlerTest` & `UpdateContactPointRequestHandlerTest`: use new regex in test
- A correct Error Response is now generated when a triple slashed `Url` (e.g., https:///publiq.be) is used.
---
Ticket: https://jira.uitdatabank.be/browse/III-5581
=> III-5581 Invalid ErrorResponse for Urls with triple slashes

src/Address/GeopuntAddressParser.php, src/Address/ParsedAddress.php, src/Place/ReadModel/RDF/RdfProjector.php, tests/Address/GeopuntAddressParserTest.php
- `GeopuntAddressParser`: test for empty `Zipcode`
- `GeopuntAddressParser`: test for empty `Thoroughfarename`
- `GeopuntAddressParser`: changed `jsonSchema`, make `Zipcode` & `Thoroughfarename`  nullable
- `GeopuntAddressParser`: expected result in test for incorrect property values
- `ParsedAddress`: make `thoroughfare` & `postalCode` nullable
- `RdfProjector`: add check if `thoroughfare` is not null.
---
Ticket: https://jira.uitdatabank.be/browse/III-5548
=> III-5548 geopunt zipcode null

src/Offer/ReadModel/JSONLD/OfferLDProjector.php, tests/Event/ReadModel/JSONLD/EventLDProjectorTest.php, tests/Event/ReadModel/JSONLD/copied_event.json, tests/Event/ReadModel/JSONLD/copied_event_without_working_hours.json, tests/Offer/ReadModel/JSONLD/OfferLDProjectorTest.php, tests/OfferLDProjectorTestBase.php, tests/Place/ReadModel/JSONLD/PlaceLDProjectorTest.php
- Store playhead inside JSON projection
- Log error when current playhead is not one more than the previous one
- Before building the retry based on the playhead we will first monitor the logging
---
Ticket: https://jira.uitdatabank.be/browse/III-5528
=> III-5528 Store playhead inside JSON projection

src/Event/ReadModel/JSONLD/EventLDProjector.php, src/Offer/Events/AbstractLabelsImported.php, src/Offer/ReadModel/JSONLD/OfferLDProjector.php, src/Place/ReadModel/JSONLD/PlaceLDProjector.php, tests/Offer/Item/ReadModel/JSONLD/ItemLDProjector.php, tests/Offer/ReadModel/JSONLD/OfferLDProjectorTest.php
- Handle `LabelsImported` to make sure playhead gets increased.
---
Ticket: https://jira.uitdatabank.be/browse/III-5614
=> III-5614 Increment playhead on `LabelsImported`

src/Event/Events/EventFromUDB2.php, tests/Event/Events/EventUpdatedFromUDB2Test.php, tests/Event/samples/event_with_calendar_timestamps.cdbxml.xml, tests/Event/samples/event_with_dummy_location.cdbxml.xml, tests/Event/samples/event_with_dummy_location_without_number.cdbxml.xml, tests/Event/samples/event_with_dummy_location_without_street.cdbxml.xml, tests/Event/samples/event_with_dummy_location_without_street_and_number.cdbxml.xml, tests/Event/samples/event_with_photo.cdbxml.xml
- Handled missing street and/or number on dummy location by converting it to `-`. This simple workaround avoids if statements when `Street` on `Address` would have been made `nullable` for this exceptional case on dummy locations.
---
Ticket: https://jira.uitdatabank.be/browse/III-5545
=> III-5545 Handle missing street and/or number on dummy location

src/Event/Events/EventFromUDB2.php, src/Event/Events/EventImportedFromUDB2.php, src/Event/Events/EventUpdatedFromUDB2.php, src/Event/Events/ExternalIdLocationUpdated.php, tests/Event/Events/EventImportedFromUDB2Test.php, tests/Event/Events/EventUpdatedFromUDB2Test.php
- Converted `ExternalIdLocationUpdated` to a concrete event so it can be used inside a handle method of the `RdfProjector`
---
Ticket: https://jira.uitdatabank.be/browse/III-5546
=> III-5546 Convert `ExternalIdLocationUpdated` to concrete event

app/Event/EventRdfServiceProvider.php, app/UDB2/UDB2EventServicesProvider.php, src/Cdb/ExternalId/ArrayMappingService.php, src/Cdb/ExternalId/MappingServiceInterface.php, src/Event/ReadModel/RDF/RdfProjector.php, tests/Cdb/ExternalId/ArrayMappingServiceTest.php, tests/Event/ReadModel/RDF/RdfProjectorTest.php, tests/Event/ReadModel/RDF/data/external-id-location-updated.ttl
- Handled `ExternalIdLocationUpdated` inside `RdfProjector` by converting to a normal `LocationUpdated` when the mapping from an external id to an internal id was successful.
---
Ticket: https://jira.uitdatabank.be/browse/III-5546
=> III-5546 Handle `ExternalIdLocationUpdated` inside `RdfProjector`

app/Event/EventJSONLDServiceProvider.php, app/Place/PlaceJSONLDServiceProvider.php, src/Offer/ReadModel/JSONLD/OfferLDProjector.php
- Added configurable for retry count and time between retries
- https://github.com/cultuurnet/appconfig/pull/349
- https://github.com/cultuurnet/udb3-vagrant/pull/163
- A replay will still work without warnings/errors because a `PlaceCreated` and `EventCreated` will trigger the creation of a new JSON document.
---
Ticket: https://jira.uitdatabank.be/browse/III-5614
=> III-5614 Sleep 500 milliseconds before new fetch

app/CommandHandling/CommandBusServiceProvider.php, app/Jobs/JobsServiceProvider.php, src/CommandHandling/ResqueCommandBus.php, src/Http/Jobs/ResqueJobStatusFactory.php, tests/CommandHandling/ResqueCommandBusTest.php
- Required Redis host and port for the `ResqueJobStatusFactory`
- Required Redis host and port for the `ResqueCommandBus`
---
Ticket: https://jira.uitdatabank.be/browse/III-5636
=> III-5636 Require Redis for resque from config

src/Label/ReadModels/JSON/Repository/Doctrine/DBALWriteRepository.php
-  Save 'excluded' as `0` instead of `false` when creating new labels.
---
=> III-5613: Hotfix save bool as 0

src/Http/Label/CommandType.php, src/Http/Label/PatchLabelRequestHandler.php, tests/Http/Label/CommandTypeTest.php, tests/Http/Label/PatchLabelRequestHandlerTest.php
- `CommandType`: Added `Include` & `Exclude` to Enum
- `PatchLabelRequestHandler`: Added support to `Include` & `Exclude` Labels.
- Updated tests
---
=> III-5613 endpoint label exclusion

app/Console/Command/ExcludeLabelsFromConfig.php, app/Console/ConsoleServiceProvider.php
- Renamed  `BulkExcludeLabel ` to `ExcludeLabelsFromConfig`
- Changed commandName from `label:bulk-exclude` to `label:exclude-from-config`
---
=> III-5613 rename bulkexcludelabel

app/UiTPAS/UiTPASIncomingEventServicesProvider.php, src/Broadway/AMQP/AbstractConsumer.php, src/Broadway/AMQP/CommandBusForwardingConsumer.php, src/Broadway/AMQP/EventBusForwardingConsumer.php, src/Broadway/AMQP/EventBusForwardingConsumerFactory.php, tests/Broadway/AMQP/CommandBusForwardingConsumerTest.php, tests/Broadway/AMQP/EventBusForwardingConsumerTest.php
- Replaced usages of `StringLiteral` with `string`
- Used local variables where possible
- Removed unused local variables
- There is only one big commit but the review should be straightforward file by file
---
Ticket: https://jira.uitdatabank.be/browse/III-5630
=> Cleanup AMQP registration code

src/Http/Productions/SearchProductionsRequestHandler.php, tests/Http/Productions/SearchProductionsRequestHandlerTest.php
- Added a property `productionId` in camelCase in `SearchProductionsRequestHandler`
- Added a warning comment to the legacy snake_case `production_id` in `SearchProductionsRequestHandler`
- Updated test for `SearchProductionsRequestHandler`
---
Ticket: https://jira.uitdatabank.be/browse/III-5556
=> III-5556 productionId property in camelCase

app/Console/ConsoleServiceProvider.php
- Unregistered previous removed cli-commands(`event:copy-to-fuseki` & `place:copy-to-fuseki`) from `ConsoleServiceProvider`
---
=> HOTFIX: remove unregistered commands

app/Console/Command/ExcludeInvalidLabels.php, src/Label/ReadModels/JSON/Repository/Doctrine/DBALReadRepository.php, src/Model/ValueObject/Taxonomy/Label/LabelName.php, tests/Model/ValueObject/Taxonomy/Label/LabelNameTest.php
- `LabelName`: Added new `REGEX` to improve uniformity.
- `LabelName`: introduced new  `SUGGESTIONS_REGEX`
- `ExcludeInvalidLabels`: Use new `SUGGESTIONS_REGEX` from `LabelName` instead of a seperate one
- `DBALReadRepository`: Use new `SUGGESTIONS_REGEX`  from `LabelName` when querying database
- `LabelNameTest`: Added new scenario's for validating with existing `REGEX` & new `SUGGESTIONS_REGEX`
- Do not exclude `Labels` with whitespaces from the database search.
- Code Cleanup in `LabelName`
---
Ticket: https://jira.uitdatabank.be/browse/III-5670
=> III-5670 regex with whitespace

src/Label/ReadModels/JSON/Repository/Doctrine/DBALReadRepository.php
- Go back to old Regex in `DBALReadRepository` because older MySQL version is not compatible.
---
Ticket: https://jira.uitdatabank.be/browse/III-5670
=> use old regex cause mysql isn't compatible

app/Labels/LabelServiceProvider.php, src/Event/Productions/DBALProductionRepository.php, src/Event/Productions/SimilarEventsRepository.php, src/Event/Productions/SkippedSimilarEventsRepository.php, src/Label/ReadModels/Doctrine/AbstractDBALRepository.php, src/Label/ReadModels/JSON/Repository/Doctrine/DBALReadRepository.php, src/Label/ReadModels/JSON/Repository/Doctrine/DBALWriteRepository.php, src/Label/ReadModels/Relations/Repository/Doctrine/DBALReadRepository.php, src/Offer/ReadModel/Metadata/OfferMetadataRepository.php, tests/Event/Productions/SkippedSimilarEventsRepositoryTest.php, tests/Label/ReadModels/Relations/Repository/Doctrine/DBALReadRepositoryTest.php, tests/Label/ReadModels/Relations/Repository/Doctrine/DBALWriteRepositoryTest.php, tests/Place/Canonical/CanonicalServiceTest.php
- Refactored `AbstractDBALRepository` to use `string` 
- The abstract class `AbstractDBALRepository` is also used in other namespaces so the PR crosses the boundaries of the `Label` namespace
---
Ticket: https://jira.uitdatabank.be/browse/III-5685
=> III-5685 Refactored `AbstractDBALRepository` to use `string`

app/Place/PlaceServiceProvider.php
- `PlaceServiceProvider`: Still used a `StringLiteral` in a constructor of `DBALReadRepository`
---
=> HOTFIX: overlooked StringLiteral in PlaceServiceProvider

src/Label/ReadModels/JSON/Repository/Doctrine/DBALReadRepository.php, tests/Label/ReadModels/JSON/Repository/Doctrine/DBALReadRepositoryTest.php
- `Label\DBALReadRepository`: filter `Labels` if `excluded` is true in `database`
- `DBALReadRepositoryTest`: Added test to check if `excluded` `Labels` are shown if `suggestions` is set to false (note: an opposite test is not possible until `regexp` is removed, because the UnitTests use `sqlite`).
---
Ticket: https://jira.uitdatabank.be/browse/III-5670
=> III-5670 add excluded to db query

features/Bootstrap/FeatureContext.php, features/Steps/AuthorizationSteps.php, features/Steps/CuratorSteps.php, features/Steps/RequestSteps.php, features/curator/create.feature, features/curator/delete.feature, features/curator/get.feature, features/curator/update.feature, features/data/events/legacy/event-with-referenced-location.json
- Added acceptance tests for Curator
- Two tests are failing that check the encoding of a URL. I was not able to fix them in a short timeframe but I also did not exclude them with `@wip`
---
=> III-5648 Port curator features

src/Label/ReadModels/JSON/Repository/AppConfigReadRepositoryDecorator.php, tests/Label/ReadModels/JSON/Repository/AppConfigReadRepositoryDecoratorTest.php
- `AppConfigReadRepositoryDecorator`: make `canUseLabel()` case-insensitive
---
Ticket: https://jira.uitdatabank.be/browse/IIII-5683
=> III-5683 case insensitive label check

composer.json, composer.lock, features/event/attendance-mode.feature, features/event/booking-info.feature, features/organizer/url.feature, tests/Http/Event/ImportEventRequestHandlerTest.php, tests/Http/Event/UpdateOnlineUrlRequestHandlerTest.php, tests/Http/Offer/UpdateBookingInfoRequestHandlerTest.php, tests/Http/Organizer/UpdateContactPointRequestHandlerTest.php
- `UpdateBookingInfoRequestHandlerTest`: added test for url's with a `#`
- `composer`: updated to latest version of `dev-main`
- `ImportEventRequestHandlerTest`, `UpdateOnlineUrlRequestHandlerTest`, `UpdateBookingInfoRequestHandlerTest` & `UpdateContactPointRequestHandlerTest`: Use new regex for url in tests.
- `features`: `event/attendance-mode`, `event/booking-info` & `organizer/url` Use new regex for url in behat acceptance tests.
- Url's with 1 `#` can now be added
---
Ticket: https://jira.uitdatabank.be/browse/III-5712
=> III-5712 update uri regex for hashtag

composer.json, composer.lock, features/event/attendance-mode.feature, features/event/booking-info.feature, features/organizer/url.feature, tests/Http/Event/ImportEventRequestHandlerTest.php, tests/Http/Event/UpdateOnlineUrlRequestHandlerTest.php, tests/Http/Offer/UpdateBookingInfoRequestHandlerTest.php, tests/Http/Organizer/UpdateContactPointRequestHandlerTest.php
- Updated `apidocs` in `composer` to latest version
- reverted regex for `uri` back to old one in unit tests
- reverted regex for `uri` back to old one in behat tests
- Avoid problems with new regex We will have to look for a better solution for III-5712 in the future
related PR for Ruby acceptance tests: https://github.com/cultuurnet/udb3-acceptance-tests/pull/194
---
=> Hotfix:revert regex

docker/config.sh
Because there is a dir called features/ in the config/ dir the old config.sh script was broken, it needed the -R flag.
=> Bugfix - Fix broken config.sh script

features/Steps/LabelSteps.php, features/label/get.feature, features/label/update.feature
- Added Labels Data setup on `LabelSteps`
- Added `getLabel()` on `LabelSteps`
- Add step  `When I patch the label with :id and :command` on `LabelSteps`
- Make sure LabelData is created when running tests for `labels/get`
Related PR: https://github.com/cultuurnet/udb3-acceptance-tests/pull/193
---
Ticket: https://jira.uitdatabank.be/browse/III-5749
=> III-5749 Add labels data to behat tests and fix failing test

src/Model/Serializer/Organizer/OrganizerDenormalizer.php, src/Model/Serializer/Organizer/OrganizerReferenceDenormalizer.php, tests/Model/Serializer/Event/EventDenormalizerTest.php, tests/Model/Serializer/Organizer/OrganizerDenormalizerTest.php, tests/Model/Serializer/Place/PlaceDenormalizerTest.php
- Handle organizers with missing id when denormalizing. This was still causing an uncaught exception because the missing value `data['@id']` was converted to `null` which was passed to the `Url` constructor which expects a `string`
---
Ticket: https://jira.uitdatabank.be/browse/III-5753
=> III-5753 Handle organizer with missing id

features/data/events/event-with-bookinginfo.json, features/event/booking-info.feature, features/place/booking-info.feature, src/Offer/ReadModel/JSONLD/OfferLDProjector.php, src/Offer/ReadModel/JSONLD/PropertyPolyfillOfferRepository.php, tests/Event/Events/BookingInfoUpdatedTest.php, tests/Offer/ReadModel/JSONLD/OfferLDProjectorTest.php, tests/Offer/ReadModel/JSONLD/PropertyPolyfillOfferRepositoryTest.php
When one created an offer without bookingInfo, it does not contain a bookingInfo Node in the Json.
But when you would remove it (empty put) it stayed as an empty array.
Changed so the array is removed when empty from the projector.
---
Ticket: https://jira.uitdatabank.be/browse/III-5763
=> III-5763 remove bookinginfo when given empty values

app/Event/EventRdfServiceProvider.php, app/Place/PlaceRdfServiceProvider.php, src/Event/ReadModel/RDF/RdfProjector.php, src/Model/Serializer/Offer/OfferDenormalizer.php, src/Place/ReadModel/RDF/RdfProjector.php, tests/Event/ReadModel/RDF/RdfProjectorTest.php, tests/Model/Serializer/Event/EventDenormalizerTest.php, tests/Model/Serializer/Place/PlaceDenormalizerTest.php, tests/Place/ReadModel/RDF/RdfProjectorTest.php
- Added logging when JSON parsing fails during RDF creation. This approach is much more robust and handles all possible parsing exceptions. These exceptions should not occur because place and event imports have a strict JSON schema for validation, but now they occurred during an import of all events and places, which includes incorrect historical data
- Rollback catching parsing exceptions
---
Ticket: https://jira.uitdatabank.be/browse/III-5781
=> III-5781 Handle invalid JSON during RDF creation

composer.json, composer.lock, features/event/calendar-summary.feature, features/place/calendar-summary.feature, tests/EventExport/CalendarSummary/CalendarSummaryWithFormatterRepositoryTest.php
- Upgrade `cultuurnet/calendar-summary-v3` to support small format with day of week
- See https://github.com/cultuurnet/calendar-summary-v3/pull/75 for the calendar summary changes
---
Ticket: https://jira.uitdatabank.be/browse/III-5703
=> III-5703 Calendar summary sm with day

src/Event/ReadModel/RDF/RdfProjector.php, src/Place/ReadModel/RDF/RdfProjector.php, tests/Event/ReadModel/RDF/RdfProjectorTest.php, tests/Place/ReadModel/RDF/RdfProjectorTest.php
- Replaced `error` method `warning` method
- Catch every throwable and not only exceptions
- The error logger also posts an error to Sentry, this is not needed for failing JOSN transformations in the RDF projector
=> Prevent sentry logging

app/Event/EventRdfServiceProvider.php, app/Place/PlaceRdfServiceProvider.php, app/RDF/RdfServiceProvider.php, src/RDF/GraphStoreRepository.php
- Refactored `save` from GraphStore to use `delete` and `insert`
- Requires https://github.com/cultuurnet/appconfig/pull/413 to become active
---
Ticket: https://jira.uitdatabank.be/browse/III-5792
=> III-5792 Use `delete` and `insert` instead of `replace` in Fuseki

app/Organizer/OrganizerRdfServiceProvider.php, app/RDF/RdfServiceProvider.php, bootstrap.php, features/Steps/OrganizerSteps.php, features/data/organizers/rdf/organizer.ttl, features/organizer/rdf.feature, src/Organizer/ReadModel/RDF/RdfProjector.php, tests/Organizer/ReadModel/RDF/RdfProjectorTest.php, tests/Organizer/ReadModel/RDF/ttl/organizer.ttl
- Added RDF projector for organizers which projects the identifier, created and modified
- Subscribed to `OrganizerProjectedToJSONLD`
- Related config changes https://github.com/cultuurnet/appconfig/pull/425
---
Ticket: https://jira.uitdatabank.be/browse/III-5800
=> III-5800 Add RDF projection for organizer

src/Description.php, tests/DescriptionTest.php, tests/OfferLDProjectorTestBase.php
Unit tests for the new legacy street class methods
III-3853 Remove stringliteral from description
---
=> III-3853 Remove stringliteral from description and add unittests

src/Event/Event.php, src/Http/Media/UploadMediaRequestHandler.php, src/Media/Commands/UploadImage.php, src/Media/Events/MediaObjectCreated.php, src/Media/Image.php, src/Media/ImageUploaderInterface.php, src/Media/ImageUploaderService.php, src/Media/MediaManager.php, src/Media/MediaManagerInterface.php, src/Media/MediaObject.php, src/Media/Properties/Description.php, src/Media/Serialization/MediaObjectSerializer.php, src/Offer/Offer.php, src/Offer/OfferCommandHandler.php, src/Place/Place.php, tests/Event/EventCommandHandlerTest.php, tests/Http/Media/GetMediaRequestHandlerTest.php, tests/Http/Offer/AddImageRequestHandlerTest.php, tests/Http/Organizer/AddImageRequestHandlerTest.php, tests/Http/Organizer/ImportOrganizerRequestHandlerTest.php, tests/Media/Commands/UploadImageTest.php, tests/Media/ImageUploaderServiceTest.php, tests/Media/MediaManagerTest.php, tests/Media/MediaObjectCreatedTest.php, tests/Media/MediaObjectTest.php, tests/Offer/Item/Item.php, tests/Offer/OfferCommandHandlerTest.php, tests/OfferLDProjectorTestBase.php, tests/Organizer/OrganizerLDProjectorTest.php, tests/Place/CommandHandlerTest.php
- Do not use `StringLiteral` in `Media\Description`
- Do not mix `StringLiteral` & `Media\Description`, use `Media\Description` consistently 
- Code Style update
---
=> III-3853 StringLiteral Media/Description

src/Media/Commands/UploadImage.php, src/Media/ImageUploaderService.php, src/Media/MediaManager.php, src/Media/PathGeneratorInterface.php, src/Media/SimplePathGenerator.php, tests/Media/Commands/UploadImageTest.php, tests/Media/MediaManagerTest.php, tests/Media/SimplePathGeneratorTest.php
- `PathGenerator` use `string` instead of `StringLiteral` as parameter in `path()`
- `UploadImage` use `string` instead of `StringLiteral` for `$filePath`
- Updated code style
---
=> III-3853 Remove StringLiteral from Media/Path

src/UiTPAS/CardSystem/CardSystem.php, src/UiTPAS/Event/Event/EventCardSystemsUpdatedDeserializer.php, src/UiTPAS/ValueObject/Id.php, tests/UiTPAS/Event/Event/EventCardSystemsUpdatedDeserializerTest.php, tests/UiTPAS/Event/EventProcessManagerTest.php
- Removed `StringLiteral` from `UiTPAS\Id`
- Change type of property of `CardSystem->name` from `StringLiteral` to `string` 
- Removed `StringLiteral` from Domain `UiTPAS`
- Code Style update
---
=> III-3853 StringLiteral UiTPAS

src/Event/EventThemeResolver.php, src/Event/EventTypeResolver.php, src/Event/ReadModel/JSONLD/EventLDProjector.php, src/Http/Deserializer/Place/FacilitiesJSONDeserializer.php, src/Model/Import/Taxonomy/Category/LegacyBridgeCategoryResolver.php, src/Offer/OfferFacilityResolver.php, src/Offer/OfferFacilityResolverInterface.php, src/Offer/ThemeResolverInterface.php, src/Offer/TypeResolverInterface.php, src/Place/PlaceTypeResolver.php, tests/Event/EventFacilityResolverTest.php, tests/Event/EventThemeResolverTest.php, tests/Offer/AvailableToTest.php, tests/Place/PlaceFacilityResolverTest.php
- Removed `StringLiteral` from the `FacilityResolver`, `ThemeResolver` & `TypeResolver`
- Updated CodeStyle
---
=> III-3853 StringLiteral categoryResolver

src/Http/Deserializer/TitleJSONDeserializer.php, src/Http/SavedSearches/CreateSavedSearchRequestHandler.php, src/SavedSearches/Command/SubscribeToSavedSearchJSONDeserializer.php, tests/Http/Deserializer/TitleJSONDeserializerTest.php, tests/SavedSearches/Command/SubscribeToSavedSearchJSONDeserializerTest.php
- Removed `StringLiteral` from constructor of `SubscribeToSavedSearchJSONDeserializer`
- Removed `StringLiteral` from constructor of `TitleJSONDeserializer`
-  Code Style
---
=> III-3853 StringLiteral in Http Domain

src/Organizer/Commands/ImportLabels.php, tests/Organizer/Commands/ImportLabelsTest.php
- Unused `getLabelNames()` from `Organizer\ImportLabels` thereby removing `StringLiteral` from Domain `Organizer`
---
=> III-3583 Remove unused function getLabelNames() from ImportLabels

src/Offer/ReadModel/JSONLD/OfferLDProjector.php, tests/Offer/Item/ReadModel/JSONLD/ItemLDProjector.php, tests/Offer/ReadModel/JSONLD/OfferLDProjectorTest.php
- `OfferLDProjector`: Added a Listener for the event `Concluded`
- `testsItemLDProjector`: Added `getConcludedClassName()` for tests.
- `unit test` for updating `playhead` when Offers are `Concluded`
- The `playhead` is correctly updated if an `Offer` has Concluded in the `event_store`
---
Ticket: https://jira.uitdatabank.be/browse/III-5820
=> III-5820 Concluded Listener

features/permission/permissions.feature
- Wait until the event is indexed before checking the permissions
=> Wait until the event is indexed before checking the permissions

src/Security/ResourceOwner/Doctrine/DBALResourceOwnerRepository.php, tests/Security/ResourceOwner/Doctrine/DBALResourceOwnerRepositoryTest.php
- `DBALResourceOwnerRepository`: Add check to see if the `resourceId` is present in `event_permission_readmodel`, if it is not present preform an `INSERT` instead of an `UPDATE`. If it already exists, the code remains an `UPDATE`
- When changing the `owner` of an `Offer` with an unknown `creator`(e.g., legacy Offers, with creators who could not be mapped to an `UiTID`), the new `owner` will have edit rights.
---
Ticket: https://jira.uitdatabank.be/browse/III-5818
=> III-5818 event_permission_readmodel check for UPDATE/INSERT

src/Organizer/ReadModel/RDF/RdfProjector.php, tests/Organizer/ReadModel/RDF/RdfProjectorTest.php
- Used `modified` in case of missing `created` on organizer RDF projection
---
Ticket: https://jira.uitdatabank.be/browse/III-5829
=> III-5829 Fix missing created on organizer

src/Organizer/ReadModel/RDF/RdfProjector.php, tests/Organizer/ReadModel/RDF/RdfProjectorTest.php, tests/Organizer/ReadModel/RDF/ttl/organizer-without-homepage.ttl
- Handled organizers without URL (homepage in RDF)
---
Ticket: https://jira.uitdatabank.be/browse/III-5853
=> III-5853 Handle organizers without url

app/Event/EventRdfServiceProvider.php, app/Organizer/OrganizerRdfServiceProvider.php, app/Place/PlaceRdfServiceProvider.php, src/RDF/CacheGraphRepository.php, src/RDF/GraphNotFound.php, src/RDF/GraphRepository.php, src/RDF/GraphStoreRepository.php, src/RDF/InMemoryGraphRepository.php, tests/RDF/CacheGraphRepositoryTest.php, tests/RDF/event.ttl
- Implemented `CacheGraphRepository` to store RDF projection inside Redis
- In a follow-up pull requests the RDF will be served from Redis
---
Ticket: https://jira.uitdatabank.be/browse/III-5901
=> III-5901 Store RDF projections inside Redis

app/Organizer/OrganizerRdfServiceProvider.php, app/Organizer/OrganizerRequestHandlerServiceProvider.php, app/RDF/RdfServiceProvider.php, src/Http/Organizer/GetOrganizerRequestHandler.php, src/Http/RDF/JsonToTurtleConverter.php, src/Http/RDF/TurtleResponseFactory.php, src/Organizer/ReadModel/RDF/OrganizerJsonToTurtleConverter.php, tests/Http/Organizer/GetOrganizerRequestHandlerTest.php, tests/Organizer/ReadModel/RDF/OrganizerJsonToTurtleConverterTest.php
- Create `OrganizerJsonToTurtleConverter` to replace `RdfProjector`
- Create `TurtleResponseFactory`
- Use `TurtleResponseFactory` inside `GetOrganizerRequestHandler`
- Removed `OrganizerRdfProjector` as a subscriber
- Removing the old Fuseki and AMQP code will be done in the context of https://jira.publiq.be/browse/III-5909 and once a full reload has been done
---
Ticket: https://jira.uitdatabank.be/browse/III-5916
=> III-5916 Create organizer turtle on the fly

composer.lock, tests/Event/ReadModel/JSONLD/CdbXMLImporterTest.php, tests/Event/ReadModel/JSONLD/EventLDProjectorTest.php, tests/Event/ReadModel/RDF/EventJsonToTurtleConverterTest.php, tests/Offer/ReadModel/JSONLD/OfferLDProjectorTest.php, tests/Place/ReadModel/JSONLD/PlaceLDProjectorTest.php, tests/Place/ReadModel/RDF/PlaceJsonToTurtleConverterTest.php
- Replaced the PHPUnit assert object methods
- Replaced `exceptError` with `set_error_handler`
- Upgraded PHPUnit to 9.6.11
- These changes are done as preparation for the switch to PHP 8.x
---
=> III-5031 Replace assert object methods

docker/php/Dockerfile
- Upgraded composer for Docker
- Use `docker-compose up php --build --detach` to get the latest composer
---
=> III-5031 Upgrade composer for Docker

.github/workflows/ci.yml, tests/Event/ReadModel/RDF/EventJsonToTurtleConverterTest.php, tests/Place/ReadModel/RDF/PlaceJsonToTurtleConverterTest.php
- Run GitHub actions also on PHP 8.0
- Running GitHub Actions on PHP 8.1 is not yet possible because of issues with the `easyrdf/easyrdf` and deprecation of `PHP-CS-Fixer`
---
=> III-5031 Run CI also on PHP 8.0

app/Security/OfferSecurityServiceProvider.php, app/Security/OrganizerSecurityServiceProvider.php
- `OfferSecurityServiceProvider` & `OrganizerSecurityServiceProvider`: Removed check on `performance.resource_owner_cache` which is true on every environment.
- https://github.com/cultuurnet/appconfig/pull/549 
---
Ticket: https://jira.publiq.be/browse/III-4955
=> III-4955 Remove performance.resource_owner_cache check

composer.json
- `composer.json`: disable timeout, when running the acceptance tests.
- One can run the acceptance tests again, with the updated `2.6` version of `composer` without running into a timeout.
---
=> Bugfix: disable Timeout when running the acceptance tests

features/data/events/rdf/event-with-all-fields.ttl, features/data/events/rdf/event-with-price-info.ttl, src/RDF/RdfNamespaces.php, tests/Event/ReadModel/RDF/ttl/event-with-price-info.ttl
- Fix typo in PrijsInfo RDF namespace
---
Ticket: https://jira.uitdatabank.be/browse/III-5995
=> III-5995 Fix typo in PrijsInfo RDF namespace

features/data/events/rdf/event-with-videos.ttl
- Fixed failing RDF acceptance tests by setting `schema:URL` to correct property
=> Fix failing RDF test

src/Http/CheckTypeOfOfferMiddleware.php
- Allow nill location in `CheckTypeOfOfferMiddleware` to prevent a 404 instead of 200
---
Ticket: https://jira.publiq.be/browse/III-5999
=> Fix failure on nil location

features/Steps/PlaceSteps.php, features/place/duplicate.feature, src/Http/ApiProblem/ApiProblem.php, src/Http/Place/ImportPlaceRequestHandler.php, src/Place/ReadModel/Duplicate/MultipleDuplicatePlacesFound.php, tests/Http/Place/ImportPlaceRequestHandlerTest.php
I Made format error message RFC7807 compliant for duplicate places
I now throw ApiProblem for this new format.
Minor bonus: changed all the status codes in ApiProblem to use constants.
Related: https://github.com/cultuurnet/apidocs/pull/359
---
Ticket: https://jira.uitdatabank.be/browse/III-4601
=> III-4601 Made format error message RFC7807 compliant for duplicate places

src/Event/EventTypeResolver.php, tests/Event/ReadModel/JSONLD/EventLDProjectorTest.php
- `EventTypeResolver`: make `isOnlyAvailableUntilStartDate()` compatible with multiple terms and add `0.57.0.0.0` `Kamp of vakantie` 
-  `EventLDProjectorTest`: refactor Unit Test the test multiple terms with new DataProvider `typesThatAreAvailableTillStart`
---
Ticket: https://jira.publiq.be/browse/III-4918
=> III-4918 kamp vakantie available to

app/Place/PlaceJSONLDServiceProvider.php
- Removed `polyfill_duplicate_places` and always enrich with duplicate info.
- Also see https://github.com/cultuurnet/appconfig/pull/554 which can be merged once this is deployed on production
---
Ticket: https://jira.uitdatabank.be/browse/III-4954
=> III-4954 Remove `polyfill_duplicate_places`

src/Address/Parser/GoogleMapsAddressParser.php, tests/Address/Parser/GoogleMapsAddressParserTest.php
- Limited the amount of Google Maps API calls by storing parsed addresses from Google Maps even when the house number is missing
---
Ticket: https://jira.uitdatabank.be/browse/III-6035
=> III-6035 Limit Google Maps API calls

src/Place/ReadModel/Duplicate/LookupDuplicatePlaceWithSapi3.php, tests/Place/ReadModel/Duplicate/LookupDuplicatePlaceWithSapi3Test.php
After we get multiple places back the first fetch from sapi3, we will request them again, same params, but also with isDuplicate=false. This should return less places, and with some luck just one.
Also provided a unittest for this.
Feedback requested: 
I am not sure this is the most useful Unittest I could have written. Good suggestions are welcome.
---
Ticket: https://jira.uitdatabank.be/browse/III-4601
=> III-4601 Make a second lookup to sapi3 for duplicate places

src/Place/Events/PlaceCreated.php, src/Place/Place.php, tests/DomainMessage/CompositeDomainMessageEnricherTest.php, tests/EventListener/EnrichingEventListenerDecoratorTest.php, tests/Offer/ReadModel/Metadata/OfferMetadataProjectorTest.php, tests/Place/CommandHandlerTest.php, tests/Place/Events/PlaceCreatedTest.php, tests/Place/GeoCoordinatesCommandHandlerTest.php, tests/Place/GeoCoordinatesProcessManagerTest.php, tests/Place/PlaceRepositoryTest.php, tests/Place/PlaceTest.php, tests/Place/ReadModel/History/HistoryProjectorTest.php, tests/Place/ReadModel/JSONLD/PlaceLDProjectorTest.php, tests/Place/ReadModel/Permission/ProjectorTest.php
III-5912 Make Title a string in PlaceCreated
This is to prepare for the title length limit in the commands later.
---
=> III-5912 Place created make title string

src/Place/Events/MajorInfoUpdated.php, src/Place/Place.php, tests/Place/CommandHandlerTest.php, tests/Place/Events/MajorInfoUpdatedTest.php, tests/Place/GeoCoordinatesProcessManagerTest.php, tests/Place/ReadModel/History/HistoryProjectorTest.php, tests/Place/ReadModel/JSONLD/PlaceLDProjectorTest.php
III-5912 Make title a string in MajorInfoUpdated for Places
This is to prepare for the title length limit in the commands later.
---
=> III-5912 Place majorInfoUpdated, change title to string to prepare for length limitation

src/Address/Parser/GeopuntAddressParser.php, src/Address/Parser/ParsedAddress.php, tests/Address/Parser/GeopuntAddressParserTest.php
- `ParsedAddress`:  Make `municipality` nullable
- `GeopuntAddressParser`: add type nullable to `municipality`
- `GeopuntAddressParserTest`: add test for nullable Municipality
- No more errors for events with a `null` municipality
---
Ticket: https://jira.publiq.be/browse/III-6051
=> III-6051 Make 4th argument nullable in ParsedAddress

src/Place/ReadModel/Duplicate/LookupDuplicatePlaceWithSapi3.php
The situation I thought "could never happen", happened a lot, which caused the code around duplicate places to throw a fatal error.
Solved this in a more elegant way.
=> III-6067 Bugfix - Duplicate places throws fatal error

src/Offer/Offer.php, tests/Offer/OfferTest.php
- `Offer`: `importImages()`: check if `mainImage` has been updated & check if `Images` have been changed.
- `OfferTest`: added Unit Test
A full update on the `events|places` endpoint no longer add multiple `ImageUpdated|MainImageSelected` Events, when nothing in the `Media` has changed.
---
Ticket: https://jira.publiq.be/browse/III-6092
=> III-6092 full update image events

src/Event/Event.php, src/Offer/Offer.php, src/Organizer/Organizer.php, src/Place/Place.php
Removed the typed Title from all apply() methods, instead working with string.
- Created an org/place/event with a very long title. (disabled length check)
- Enable length check
- Try to update org/place/event -> success!
---
=> III-5912 Remove Title from Apply methods

app/Console/Command/ReplayCommand.php
- `ReplayCommand`: Add purge for `events`, `places` & `organizers` when replaying a item.
- `Offers` & `Organizers` can now be replayed without throwing an `UniqueConstraintException`
I have also checked `app/Console/Command/PurgeModelCommand.php`, but that still seems up-to-date.
---
Ticket: https://jira.publiq.be/browse/III-6098
=> III-6098 Add purge command for `*permission_readmodel`

app/Console/Command/ReplayCommand.php
-  `ReplayCommand`: Check if inputted `string` is really a (legacy) `UUID`
- Improved security to really avoid `SQL-injection`
---
Ticket: https://jira.publiq.be/browse/III-6098
=> III-6098: Add UUID check to input

features/event/update.feature, src/Event/ReadModel/JSONLD/EventLDProjector.php, tests/Event/ReadModel/JSONLD/EventLDProjectorTest.php
- `EventLDProjector`: Add logic to change `availableTo` to `endDate` when `TypeUpdated` happens from a `Kamp of Vakantie` or `Lessenreeks` to a Type that's available till the endDate.
- Unit Test for this bug
- Feature test for this bug
- Correct `availableTo`, when changing from a type that's available till start
---
Ticket: https://jira.publiq.be/browse/III-6034
=> III-6034 bugfix set availableTo to endDate on most TypeUpdated

composer.lock
- Updated library `calendar-summary-v3` to latest release
---
Ticket: https://jira.publiq.be/browse/III-5869
=> III-5869: update calendar-summary-v3

app/Console/Command/ExecuteCommandFromCsv.php, app/Console/ConsoleServiceProvider.php
I made a batchscript that accepts a csv, loops over it and then runs a different shell command for each row in the file.
It is possible to pass columns as arguments by using a placeholder %1, %2, ...
Example:   bin/udb3.php execute-command-from-csv input.csv "place:delete %1 %2"
Idea is for duplicate places to take the CSV from Frederic and delete all places in clusters (except the canonical), and we are going to do this one at a time. So other command "place:delete".
I did write this so it can be reused for different commands.
---
Ticket: https://jira.uitdatabank.be/browse/III-6109
=> III-6109 Make batchscript to loop over other script

app/SavedSearches/SavedSearchesServiceProvider.php, features/saved_searches/create.feature, src/Http/SavedSearches/CreateSavedSearchRequestHandler.php, src/SavedSearches/Command/SubscribeToSavedSearch.php, src/SavedSearches/Command/SubscribeToSavedSearchJSONDeserializer.php, src/SavedSearches/UDB3SavedSearchRepository.php, src/SavedSearches/UDB3SavedSearchesCommandHandler.php, src/SavedSearches/WriteModel/SavedSearchRepositoryInterface.php, tests/Http/SavedSearches/CreateSavedSearchRequestHandlerTest.php, tests/SavedSearches/Command/SubscribeToSavedSearchJSONDeserializerTest.php, tests/SavedSearches/Command/SubscribeToSavedSearchTest.php, tests/SavedSearches/UDB3SavedSearchRepositoryTest.php, tests/SavedSearches/UDB3SavedSearchesCommandHandlerTest.php
I changed the output of the Saved Searches endpoint.
It used to return a NULL, which I found very confusing and not consistent with most of our create statements.
(I thought that the script just failed the first time I called it.)
I refactored the endpoint to now return the id of the created saved search.
I also need this for a feature test for the next feature I am creating, a PUT command for Saved Searches.
---
Ticket: https://jira.uitdatabank.be/browse/III-6117
=> III-6117 Add id to response create saved searches

app/Console/Command/GeocodePlaceCommand.php
There is a minor bug with the geocoding event, some places do not have an address and the script throws an ugly error about this.
I now catch this in a more elegant solution.
=> Fix geocoding command when place has no address

app/SavedSearches/SavedSearchesServiceProvider.php, features/saved_searches/update.feature, src/Http/ApiProblem/ApiProblem.php, src/Http/SavedSearches/ReadSavedSearchesRequestHandler.php, src/Http/SavedSearches/UpdateSavedSearchRequestHandler.php, src/SavedSearches/CombinedSavedSearchRepository.php, src/SavedSearches/ReadModel/SavedSearch.php, src/SavedSearches/ReadModel/SavedSearchReadRepository.php, src/SavedSearches/ReadModel/SavedSearchesOwnedByCurrentUser.php, src/SavedSearches/Sapi3FixedSavedSearchRepository.php, src/SavedSearches/UDB3SavedSearchRepository.php, src/SavedSearches/UDB3SavedSearchesCommandHandler.php, src/SavedSearches/WriteModel/SavedSearchRepositoryInterface.php, tests/Http/SavedSearches/ReadSavedSearchesRequestHandlerTest.php, tests/Http/SavedSearches/UpdateSavedSearchRequestHandlerTest.php, tests/SavedSearches/CombinedSavedSearchRepositoryTest.php, tests/SavedSearches/UDB3SavedSearchRepositoryTest.php, tests/SavedSearches/UDB3SavedSearchesCommandHandlerTest.php
Fixed a bug with the PUT of saved searches.
If you saved a saved search without modifying any value, it would throw an `ApiProblem::savedSearchNotFound()`.
This is because I listened to the "affected rows", which will return 0 if the update does not have to change anything in the db.
I now use a proper select query.
I provided an extra feature test to prove the bug is fixed.
---
Ticket: https://jira.uitdatabank.be/browse/III-6117
=> III-6117 BUGFIX put saved search gave error when saving twice

app/Console/Command/ProcessDuplicatePlaces.php
To debug the problems with missing canonicals, I added an option to only update 1 cluster.
I didn't need it in the end, but might be useful in the future.
Added an option to only update 1 cluster.
---
Ticket: https://jira.publiq.be/browse/III-6122
=> Add option to only process 1 cluster

app/CommandHandling/CommandBusServiceProvider.php, app/Http/PsrRouterServiceProvider.php, app/Ownership/OwnershipCommandHandlerProvider.php, app/Ownership/OwnershipRequestHandlerServiceProvider.php, features/Steps/OwnershipSteps.php, features/Support/HttpClient.php, features/ownership/reject.feature, src/Http/Ownership/ApproveOwnershipRequestHandler.php, src/Http/Ownership/RejectOwnershipRequestHandler.php, src/Ownership/CommandHandlers/ApproveOwnershipHandler.php, src/Ownership/CommandHandlers/RejectOwnershipHandler.php, src/Ownership/Commands/ApproveOwnership.php, src/Ownership/Commands/RejectOwnership.php, src/Ownership/Events/OwnershipApproved.php, src/Ownership/Events/OwnershipRejected.php, src/Ownership/Ownership.php, src/Ownership/Readmodels/OwnershipLDProjector.php, tests/Http/Ownership/ApproveOwnershipRequestHandlerTest.php, tests/Http/Ownership/RejectOwnershipRequestHandlerTest.php, tests/Ownership/CommandHandlers/ApproveOwnershipHandlerTest.php, tests/Ownership/CommandHandlers/RejectOwnershipHandlerTest.php, tests/Ownership/Commands/ApproveOwnershipTest.php, tests/Ownership/Commands/RejectOwnershipTest.php, tests/Ownership/Events/OwnershipApprovedTest.php, tests/Ownership/Events/OwnershipRejectedTest.php, tests/Ownership/OwnershipTest.php, tests/Ownership/Readmodels/OwnershipLDProjectorTest.php
- Added endpoint `POST /ownerships/{ownershipId}/reject` to reject an ownership
- There is some overlapping code in the request handler, I will change that in a follow-up pull request
---
Ticket: https://jira.uitdatabank.be/browse/III-6072
=> III-6072 Add endpoint to reject ownership

app/Http/PsrRouterServiceProvider.php, app/Ownership/OwnershipRequestHandlerServiceProvider.php, features/ownership/search.feature, src/Http/ApiProblem/ApiProblem.php, src/Http/Ownership/SearchOwnershipRequestHandler.php, tests/Http/Ownership/SearchOwnershipRequestHandlerTest.php
- Implemented endpoint `GET /ownerships/?itemId={itemId}` to search ownerships based on the item id
---
Ticket: https://jira.uitdatabank.be/browse/III-6071
=> III-6071 Add endpoint to search ownerships on item id

app/EventBus/EventBusServiceProvider.php, app/Ownership/OwnershipServiceProvider.php, features/ownership/permission.feature, src/Ownership/Readmodels/OwnershipPermissionProjector.php, tests/Ownership/Readmodels/OwnershipPermissionProjectorTest.php
- Added a projector that handles ownership approval and deletion. When an ownership is approved a role to update the organizers is created. When the ownership is deleted the associated role is also deleted.
---
Ticket: https://jira.uitdatabank.be/browse/III-6074
=> III-6074 Create organizer role based on ownership

features/ownership/permission.feature, src/Ownership/Readmodels/OwnershipPermissionProjector.php, tests/Ownership/Readmodels/OwnershipPermissionProjectorTest.php
- Updated the ownership permission projector to also create a role that allows updating events from the organizer.
- There is still an issue when a normal user approves an ownership because creating roles is not allowed by a normal user, this can only be done by a user with the permission `gebruikersBeheren`
---
Ticket: https://jira.uitdatabank.be/browse/III-6075
=> III-6075 Create role with permission to update event

features/ownership/permission.feature, src/Ownership/Readmodels/OwnershipPermissionProjector.php, tests/Ownership/Readmodels/OwnershipPermissionProjectorTest.php
- Avoid permission on places associated with an organizer with approved ownership by adding the `_type:event` advanced query
---
Ticket: https://jira.uitdatabank.be/browse/III-6075
=> III-6075 Avoid permission on places

app/Migrations/Version20240402125210.php
- `Migrations/kinepolis_movie_mapping`: Removed unneeded `index` on column `movie_id`, that I overlooked in a previous PR.
---
Ticket: https://jira.uitdatabank.be/browse/III-6079
=> III-6079 Remove unneeded index.

features/saved_searches/get.feature, src/SavedSearches/Properties/QueryString.php, src/SavedSearches/ReadModel/SavedSearch.php, tests/SavedSearches/Properties/QueryStringTest.php, tests/SavedSearches/ReadModel/SavedSearchTest.php
It was possible to enter faulty saved queries, that the system could not read.
This code cleans them up.
It does NOT change anything in the database, it just makes sure the GET request returns correctly formatted queries.
Includes unit tests and a feature test.
---
Ticket: https://jira.uitdatabank.be/browse/III-6131
=> III-6131 Normalize saved searches

src/Http/ApiProblem/ApiProblem.php, src/RDF/JsonDataCouldNotBeConverted.php
I changed the ApiProblem::invalidJsonData method name to more clearly reflect this does not contain generic invalid json errors, but is specific for the RDF creation.
=> Make the ApiProblem for Rdf Creation more clear

app/Console/Command/ImportMovieIdsFromCsv.php, app/Console/ConsoleServiceProvider.php
- `ImportMovieIdsFromCsv`: `Command` to import movieIds from the legacy application via a `csv`.
- `ConsoleServiceProvider`: Register new Command `ImportMovieIdsFromCsv`
---
Ticket: https://jira.publiq.be/browse/III-6175
=> III-6175 migrate moviedata

src/Kinepolis/KinepolisService.php, tests/Kinepolis/KinepolisServiceTest.php
- `KinpelosService`:  Dispatch a `Publish`, when creating a new `Movie`
- New movies are no longer in `DRAFT`
---
Ticket: https://jira.publiq.be/browse/III-6079
=> III-6079 BUGFIX: moviefetcher publish

app/Console/ConsoleServiceProvider.php, src/Kinepolis/KinepolisService.php, tests/Kinepolis/KinepolisServiceTest.php
-  `KinepolisService`: newly created movies are linked to a `production`, if no matching `production` is found, a new one is created for the movie.
- Movies are no correctly linked to a production.
---
Ticket: https://jira.publiq.be/browse/III-6079
=> III-6079 BUGFIX: link movie to production

src/Kinepolis/KinepolisService.php, tests/Kinepolis/KinepolisServiceTest.php
- `KinepolisService`: `TrailerRepository` is now only called once per movieTitle instead of once per movieScreening, this should limit the total amount of calls.
- `KinepolisServiceTests`: Updated tests after tackling rate limiting.
- `YouTube`-api should give fewer/no `exceeded quota`-errors.
---
Ticket: https://jira.publiq.be/browse/III-6079
=> III-6079 BUGFIX: moviefetcher tackle Rate Limiting YouTubeAPI

app/Console/ConsoleServiceProvider.php, src/Kinepolis/KinepolisService.php, src/Kinepolis/Parser/KinepolisMovieParser.php, src/Kinepolis/Parser/MovieParser.php, src/Kinepolis/ValueObject/ParsedMovie.php, tests/Kinepolis/KinepolisServiceTest.php, tests/Kinepolis/Parser/KinepolisMovieParserTest.php, tests/Kinepolis/samples/KinepolisMovieDetailResponseWithEmptyDescription.json
- Refactoring: Renamed `Parser` to `MovieParser` to better differentiate between the different Parsers.
- `ParsedMovie`: Make `Description` nullable
- `KinepolisMovieParser`: handle Empty Description
- `KinepolisService`: do not dispatch a `UpdateDescription` when `Description` is `null`
- `KinepolisMovieParserTest`:  Added test for `ParsedMovie` with empty Description
- `KinepolisServiceTest`: Added test for `ParsedMovie` with empty Description
- The `KinepolisService` now handles movies with an empty description
---
Ticket: https://jira.publiq.be/browse/III-6181
=> III-6181 Movies with empty description

src/Event/Event.php, src/Event/ReadModel/JSONLD/EventLDProjector.php, tests/Event/EventTest.php, tests/Event/ReadModel/JSONLD/EventLDProjectorTest.php
- When handling `MajorInfoUpdated` make sure to update the attendance mode:
- From offline to online when `MajorInfoUpdated` contains the nil location
- From online to mixed when `MajorInfoUpdated` contains a real location and the event has an online URL
- From online to offline when `MajorInfoUpdated` contains a real location
---
Ticket: https://jira.uitdatabank.be/browse/PPF-6200
=> PPF-6200 Update attendance mode on MajorInfoUpdated

composer.json, composer.lock
- Updated `calendar-summary-v3` to 4.0.7
---
Ticket: https://jira.publiq.be/browse/III-6186
=> III-6186: update calendar-summary-v3 to 4.0.7

src/Http/Auth/Jwt/JsonWebToken.php
- Handle `azp` to get client id from a Keycloak client token and add the suffix `@clients`
---
Ticket: https://jira.uitdatabank.be/browse/III-6220
=> III-6220 Handle azp

composer.json, composer.lock
`Composer.json`: updated `calendar-summary-v3` to `4.0.8` 
---
Ticket: https://jira.uitdatabank.be/browse/III-6186
=> III-6186 calsum update to 4.0.8

app/Console/Command/DeletePlace.php, app/Console/ConsoleServiceProvider.php
- `Console/Command/DeletePlace`: Added a `PlaceDocumentRepository` to the `constructor`
- `Console/Command/DeletePlace`: Check if `placeUuid` & `canonicalUuid` are indeed Places
- `Events` should no longer be deleted by the `DeletePlace` CLI-Command.
---
Ticket: https://jira.publiq.be/browse/III-6226
=> III-6226 events deleted by SystemUser

app/Console/Command/BulkRemoveFromProduction.php, app/Console/ConsoleServiceProvider.php, app/Event/EventCommandHandlerProvider.php, src/Event/CommandHandlers/CopyEventHandler.php, src/Event/Productions/BroadcastingProductionRepository.php, src/Event/Productions/DBALProductionRepository.php, src/Event/Productions/ProductionCommandHandler.php, src/Event/Productions/ProductionRepository.php, src/Event/Productions/RemoveEventsFromProduction.php, tests/Event/CommandHandlers/CopyEventHandlerTest.php, tests/Event/Productions/BroadcastingProductionRepositoryTest.php, tests/Event/Productions/DBALProductionRepositoryTest.php, tests/Event/Productions/ProductionCommandHandlerTest.php
- `BulkRemoveFromProduction`: CLI-Command, to bulk remove Events from a production, without overloading the queues.
- `RemoveEventsFromProduction`: Command to remove multiple Events from a production.
- `ConsoleServiceProvider`: Registered `BulkRemoveFromProduction`
- `CopyEventHandler`: Make it optional to add a copied event to the same production as the original.
- `EventCommandHandlerProvider`: `Updated constructor` of `CopyEventHandler`
- `ProductionCommandHandler`: added handle for `RemoveEventsFromProduction`
- `ProductionRepository` & implementations `DBALProductionRepository` & `BroadcastingProductionRepository` added `removeEvents()`
- When a production has many incorrect events, we can now bulk remove those events without overloading the queues.
Also to see if it investigate if …
=> III-5990 incorrect events in Production

app/Console/Command/ProcessDuplicatePlaces.php, app/Console/ConsoleServiceProvider.php, app/Migrations/Version20240718143512.php, src/Place/Canonical/CanonicalService.php, src/Place/Canonical/DBALDuplicatePlaceRepository.php, src/Place/Canonical/DuplicatePlaceRepository.php, src/Place/Canonical/Exception/MuseumPassNotUniqueInCluster.php, tests/Place/Canonical/CanonicalServiceTest.php, tests/Place/Canonical/DBALDuplicatePlaceRepositoryTest.php
In preparation for the data teams changes to duplicate places:
- Added a date field "created_date" to the duplicate_places table. The data team will fill this up.
- Added a boolean field "processed"  to the duplicate_places table.
- Make sure the duplicate places CLI script only processes new records with the new field processed = false
- Bonus feature: Added logging when a dispatch UpdateLocation fails and made sure it doesn't crash the entire script.
- Added extra test case related to "processed" flag.
- Changed the "cluster_id" field to handle hashes in the duplicate_places table.
---
Ticket: https://jira.uitdatabank.be/browse/III-6236
=> III-6236 Change structure table duplicate places

app/Event/EventCommandHandlerProvider.php
- Changed the name of `copy_production` to `add_copied_event_to_parent_production` to improve readability
- https://github.com/cultuurnet/appconfig/pull/733
---
Ticket: https://jira.publiq.be/browse/III-5990
=> III-5990 change name for readability

src/Place/Canonical/CanonicalService.php
I was in this class for another ticket and saw some performance opportunities.
We currently first loop trough all places for both `getPlacesWithMostEvents()`  and `getOldestPlace()`, and then sort the arrays based on some field. 
By directly comparing event counts, we avoid the need to sort the array, reducing complexity, and also lowering the RAM usage because we don't build a tmp array to sort and then throw away..
Because sorting in PHP uses quicksort, which is O(n log n). 
This means this change reduces the complexity to a linear O(n)
=> [performance] Improve performance of canonical sorting methods

features/event/price-info.feature, features/place/price-info.feature, src/Http/Offer/PriceInfoDuplicateNameValidatingRequestBodyParser.php, tests/Http/Offer/PriceInfoDuplicateNameValidatingRequestBodyParserTest.php
- `PriceInfoDuplicateNameValidatingRequestBodyParser`: Improved check on duplicate `TariffName`, to take spacing into account.
- `PriceInfoDuplicateNameValidatingRequestBodyParserTest`: refactor to avoid endless casting to `object`
via new private function `arrayAsObject()` + new test for trimming 
---
Ticket: https://jira.publiq.be/browse/III-6239
=> III-6239 tariff name trimmed

src/Calendar/CalendarFactory.php, src/Calendar/OpeningTime.php, src/Organizer/OrganizerLDProjector.php, src/Ownership/Readmodels/OwnershipLDProjector.php, src/Place/ReadModel/JSONLD/PlaceLDProjector.php, src/RecordedOn.php, tests/Calendar/OpeningTimeTest.php, tests/Log/SocketIOEmitterHandlerTest.php
- Replaced `DateTime::createFromFormat` with `DateTimeFactory::fromFormat`
- There are still some occurrences left that use `DateTime` which is normal in the case when the result is validated for either being `false` or a real `DateTime` value.
- There is also a `DateTimeFactory` inside the `Cdb` namespace, it is out of the scope of this change to merge them. For that I created https://jira.publiq.be/browse/III-6246
---
Ticket: https://jira.uitdatabank.be/browse/III-3558
=> III-3558 Replace `DateTime::createFromFormat` with `DateTimeFactory::fromFormat`

app/Console/ConsoleServiceProvider.php, src/Kinepolis/Trailer/YoutubeTrailerRepository.php, tests/Kinepolis/Trailer/YoutubeTrailerRepositoryTest.php
- `YoutubeTrailerRepository`: removed feature-flag to enable/disable trailers on `mvoviefetcher`
- `YoutubeTrailerRepositoryTest`: removed no longer needed test & moved property inline
- Since the  trailers added by the `movie-fetcher` are OK, a feature-flag to quickly disable it, is no longer needed. Henceforth all movies imported by the movie-fetcher will automatically get a trailer(if one is available on Youtube).
- https://github.com/cultuurnet/appconfig/pull/753
---
Ticket: https://jira.publiq.be/browse/III-6184
=> III-6184 remove feature flag

features/search/default-queries-uitid.feature
- `default-queries-uitid.feature`: An acceptance test for default queries from `UiTID`
- https://github.com/cultuurnet/appconfig/pull/755
---
Ticket: https://jira.publiq.be/browse/III-6264
=> III-6264 acceptance test default filter from UiTID

features/search/default-queries-config-file.feature
- `default-queries-config-file.feature`: An acceptance test for default queries from the config file `default_queries`
- https://github.com/cultuurnet/appconfig/pull/756
---
Ticket: https://jira.publiq.be/browse/III-6264
=> III-6264 acceptance test default filter in Config File

features/event/booking-info.feature, src/Model/ValueObject/Web/InvalidUrl.php, src/Model/ValueObject/Web/Url.php, tests/Model/Serializer/Event/EventDenormalizerTest.php, tests/Model/Serializer/Place/PlaceDenormalizerTest.php, tests/Model/ValueObject/Web/UrlTest.php
- `InvalidUrl`: New exception to throw when `Url` is malformed
- `Url`: throw `InvalidUrl` instead of `InvalidArgumentException`
- `EventDenormalizerTest`, `PlaceDenormalizerTest` & `UrlTest`: update tests
- `event/booking-info.feature`: Add acceptance test.
---
Ticket: https://jira.publiq.be/browse/III-6273
=> III-6273 improve invalid url

app/Migrations/Version20150817113039.php, src/CommandHandling/Udb3CommandHandler.php, src/Event/EventFacilityResolver.php, src/History/Log.php, src/Http/Deserializer/Event/CreateEventDataValidator.php, src/Http/Deserializer/Place/CreatePlaceDataValidator.php, src/Http/Response/JsonLdResponse.php, src/Label/ReadModels/JSON/Repository/Entity.php, src/Log/ContextEnrichingLogger.php, src/Log/SocketIOEmitterHandler.php, src/Model/Event/ImmutableEvent.php, src/Model/Place/ImmutablePlace.php, src/Model/Serializer/ValueObject/Audience/AgeRangeDenormalizer.php, src/Model/ValueObject/Calendar/CalendarType.php, src/Model/ValueObject/Calendar/OpeningHours/Day.php, src/Model/ValueObject/Calendar/StatusType.php, src/Offer/OfferCommandHandler.php, src/Offer/ReadModel/JSONLD/CdbXmlContactInfoImporter.php, src/Role/Events/AbstractEvent.php, src/SavedSearches/UDB3SavedSearchRepository.php, tests/EventExport/Format/HTML/HTMLFileWriterTest.php, tests/Label/CommandHandlerTest.php, tests/Model/Offer/MockImmutableOffer.php, tests/StringFilter/StringFilterTest.php, tests/StringFilter/StripSourceStringFilterTest.php, tests/StringFilter/TidyStringFilterTest.php
- Removed unneeded inheritdoc comments
- The functions with a `static` return type are not changed/removed, this is only meaningful when running on PHP 8
---
Ticket: https://jira.uitdatabank.be/browse/III-6308
=> III-6308 Remove unneeded inheritdoc comments

features/event/contact-point.feature, features/organizer/contact-point.feature, features/place/contact-point.feature, src/ContactPoint.php, src/Event/Event.php, src/Http/Deserializer/Offer/UpdateContactPointDenormalizer.php, src/Http/Event/ImportEventRequestHandler.php, src/Http/Offer/UpdateContactPointRequestHandler.php, src/Http/Place/ImportPlaceRequestHandler.php, src/Offer/Commands/AbstractUpdateContactPoint.php, src/Offer/Offer.php, src/Place/Place.php, tests/Event/Commands/UpdateContactPointTest.php, tests/Event/EventTest.php, tests/Http/Event/ImportEventRequestHandlerTest.php, tests/Http/Offer/UpdateContactPointRequestHandlerTest.php, tests/Http/Place/ImportPlaceRequestHandlerTest.php, tests/Offer/Commands/AbstractUpdateContactPointTest.php, tests/Offer/Item/Item.php, tests/Offer/OfferTest.php, tests/OfferCommandHandlerTestTrait.php, tests/Place/PlaceTest.php
- Added feature test to update an organizer with an empty contact point values which results in removal of the contactPoint property
- Added method to convert the legacy contact point to a new contact point
- Changed the `UpdateContactPoint` command to work with the new `ContactPoint`
---
=> III-6310 Refactor `UpdateContactPoint` to new `ContactPoint`

src/Event/Event.php, src/Event/Events/EventCreated.php, src/Event/Events/EventImportedFromUDB2.php, src/EventSourcing/MainLanguageDefined.php, src/Place/Events/PlaceCreated.php, src/Place/Events/PlaceImportedFromUDB2.php, src/Place/Place.php, tests/BackwardsCompatiblePayloadSerializerFactoryTest.php, tests/Event/Events/EventCreatedTest.php, tests/Event/Events/EventImportedFromUDB2Test.php, tests/Place/Events/PlaceCreatedTest.php, tests/Place/Events/PlaceImportedFromUDB2Test.php
-  Refactored `Language` on `MainLanguageDefined` interface
---
=> III-6310 Refactor `Language` on `MainLanguageDefined` interface

src/Offer/AbstractGeoCoordinatesCommandHandler.php
- `AbstractGeoCoordinatesCommandHandler`: log final fail as `error` instead of `debug`
---
Ticket: https://jira.publiq.be/browse/III-6329
=> III-6329 log as error

features/Bootstrap/FeatureContext.php, features/Steps/UtilitySteps.php, features/place/duplicate.feature
- `UtilitySteps`: Remove `I prevent duplicate place creation` & `I restore the duplicate configuration` to make this part of the tests more robust.
- FeatureContext`: Added `BeforeScenario` & `BeforeScenario` as a replacement of the previous removed UtilitySteps.
---
Ticket: https://jira.publiq.be/browse/III-6514
=> III-6154 make place duplication more robust

phpstan.neon, src/EventExport/Format/HTML/TransformingIteratorIterator.php
- `TransformingIteratorIterator`: remove returnType from `current()`
- `phpstan.neon` : ignore TransformingIteratorIterator for the moment, because we can not get phpstan to check it for both PHP 7.4 & PHP 8.1
- PDF exports should work again.
- https://jira.publiq.be/browse/III-6342
---
Ticket: https://jira.publiq.be/browse/III-6339
=> III-6339: bugfix PDF export

src/Http/Auth/Jwt/JsonWebToken.php, src/Http/Auth/Jwt/UitIdV2JwtValidator.php, tests/Http/Auth/Jwt/JsonWebTokenTest.php
Keycloak tokens always have an AZP field, auth0 does not.
This tripped up our code to identify if it is a provider token (a token with an api key).
We added an extra check to typ, a field that only exists in Keycloak.
---
Ticket: https://jira.uitdatabank.be/browse/III-6347
=> III-6347 BUGFIX Keycloak id token was wrongly classified as access token

docker/config.sh
- `config.sh`: Updated the `config.sh` to edit `/etc/hosts` based on an `environment variable`. In a later PR `host.docker.internal`
- Developers on `MacOs` can still edit `/etc/hosts`, without affecting the Jenkins-user.
---
Ticket: https://jira.publiq.be/browse/III-6154
=> III-6154 Update config script

src/Http/Offer/UpdateDescriptionRequestHandler.php, src/Model/ValueObject/Text/Description.php, src/Model/ValueObject/Text/DescriptionShouldNotBeEmpty.php, src/Offer/Serializers/DescriptionDenormalizer.php, tests/Http/Offer/UpdateDescriptionRequestHandlerTest.php, tests/Model/ValueObject/Text/DescriptionTest.php
- Added new exception `DescriptionShouldNotBeEmpty`
- Handle an empty description and dispatch a `DeleteDescription` for this
---
=> III-6310 Handle update with empty description

app/Migrations/Version20241015103145.php, app/Ownership/OwnershipServiceProvider.php, src/Ownership/Readmodels/OwnershipPermissionProjector.php, src/Ownership/Repositories/OwnershipItem.php, src/Ownership/Repositories/Search/DBALOwnershipSearchRepository.php, src/Ownership/Repositories/Search/OwnershipSearchRepository.php, tests/Ownership/Readmodels/OwnershipPermissionProjectorTest.php, tests/Ownership/Repositories/Search/DBALOwnershipSearchRepositoryTest.php
- Added `role_id` to table `ownership_search`
- Added method `updateRoleId` to set the link between an ownership and a role
- When approving an ownership check for an existing role for the organizer, if this exists add the user to this role
- When deleting an ownership delete the user from the linked role
---
Ticket: https://jira.uitdatabank.be/browse/III-6345
=> III-6345 Reuse existing role

app/Ownership/OwnershipServiceProvider.php, features/ownership/approve.feature, features/ownership/delete.feature, features/ownership/reject.feature, features/ownership/request.feature, src/Ownership/Readmodels/OwnershipLDProjector.php, tests/Ownership/Readmodels/OwnershipLDProjectorTest.php
- Exposed email address of owner inside the JSON projector
---
Ticket: https://jira.uitdatabank.be/browse/III-6370
=> III-6370 Expose email in ownership

app/Ownership/OwnershipServiceProvider.php, src/Ownership/Readmodels/Name/DocumentItemNameResolver.php, src/Ownership/Readmodels/Name/ItemNameResolver.php, src/Ownership/Readmodels/OwnershipPermissionProjector.php, tests/Ownership/Readmodels/Name/DocumentItemNameResolverTest.php, tests/Ownership/Readmodels/OwnershipPermissionProjectorTest.php
- Used organizer name for role name. Currently, this only works for organizers, but it can be easily extended for places and events.
---
Ticket: https://jira.uitdatabank.be/browse/III-6346
=> III-6346 Use organizer name for role name

features/ownership/search.feature, src/Http/Ownership/Search/SearchParameter.php, src/Ownership/Repositories/Search/DBALOwnershipSearchRepository.php, tests/Http/Ownership/SearchOwnershipRequestHandlerTest.php, tests/Ownership/Repositories/Search/DBALOwnershipSearchRepositoryTest.php
- Added `ownerId` as a valid query parameter when searching ownerships
---
Ticket: https://jira.uitdatabank.be/browse/III-6373
=> III-6373 Allow searching ownerships on ownerId

src/BackwardsCompatiblePayloadSerializerFactory.php, tests/BackwardsCompatiblePayloadSerializerFactoryTest.php, tests/samples/serialized_event_contact_point_updated_class_with_spaces.json
- `BackwardsCompatiblePayloadSerializerFactory`: Handle `email` & `urls` with leading & trailing spaces.
- `BackwardsCompatiblePayloadSerializerFactoryTest`: Add unit test to check for trimming `ContactPoints`.
- `serialized_event_contact_point_updated_class_with_spaces.json`: Sample file for Unit Test
- `Urls` & `emails` with leading & trailing spaces can be taken from the event_store without issue.
---
Ticket: https://jira.publiq.be/browse/III-6368
=> III-6368 finetune ContactPointUpdated: BackwardsCompatiblePayloadSerializerFactory

app/Ownership/OwnershipRequestHandlerServiceProvider.php, features/ownership/request.feature, src/Http/Ownership/OwnershipStatusGuard.php, src/Http/Ownership/RequestOwnershipRequestHandler.php, tests/Http/Ownership/RequestOwnershipRequestHandlerTest.php
- Improved the Ownership request permission checks by using the organizer permission voter which handles:
- A god user can always request for someone else
- A creator can always request for someone else
- Someone with permission "organisatie bewerken" can request
- Always possible to request for yourself
---
Ticket: https://jira.uitdatabank.be/browse/III-6372
=> III-6372 Improve ownership permission checks

features/ownership/request.feature
- `features/ownership/request.feature`: Use correct id of requester(`dev+udbtestinvoerder@publiq.be`) instead of userId of `tools@cultuurnet.be`
- All acceptance test should be green
---
=> Fix broken acceptance test

app/Migrations/Version20241031084923.php, app/Migrations/Version20241031085217.php, app/Migrations/Version20241031085647.php
- Remove table `duplicate_places_removed_from_cluster_import`
- Remove column `cluster_id` from `duplicate_places_removed_from_cluster`
- Remove column `canonical` from `duplicate_places_import`
---
Ticket: https://jira.uitdatabank.be/browse/III-6382
=> III-6382 Cleanup duplicate places table

composer.json, composer.lock, features/curator/create.feature, tests/Http/Curators/CreateNewsArticleRequestHandlerTest.php, tests/Http/Curators/UpdateNewsArticleRequestHandlerTest.php
- Allowed encoded space for the image URL of a news article. Only an encoded space is allowed to not interfere with the `Url` value object validation in `udb3-backed`
- Related pull request https://github.com/cultuurnet/apidocs/pull/412
---
Ticket: https://jira.uitdatabank.be/browse/III-6312
=> III-6312 Allow encoded space

features/ownership/search.feature
- `ownership/search.feature`: Just check if `ownershipId1` & `ownershipId2`, regardless of order.
- `Scenario: Searching ownership of an organizer by ownerId`: should now always be `green` instead of random `green|red`
---
=> Fixe broken acceptance testen for Ownsership Search

src/Calendar/Calendar.php, src/Calendar/Timestamp.php, src/Event/Event.php, src/Http/Deserializer/Calendar/CalendarJSONParser.php, src/Model/Serializer/ValueObject/Calendar/StatusNormalizer.php, src/Offer/Offer.php, tests/Calendar/CalendarTest.php, tests/Calendar/TimestampTest.php, tests/Event/CommandHandlers/UpdateSubEventsHandlerTest.php, tests/Http/Deserializer/Calendar/CalendarJSONDeserializerTest.php, tests/Http/Deserializer/Calendar/CalendarJSONParserTest.php, tests/Http/Offer/UpdateCalendarRequestHandlerTest.php, tests/Offer/CommandHandlers/UpdateStatusHandlerTest.php
- Refactored legacy `Timestamp` to use the new `Status` model
---
=> III-6310 remove legacy status from timestamp

src/Cdb/CdbXmlPriceInfoParser.php, src/ValueObject/MultilingualString.php, tests/BackwardsCompatiblePayloadSerializerFactoryTest.php, tests/BookingInfoTest.php, tests/Event/Commands/UpdateBookingInfoTest.php, tests/Event/EventTest.php, tests/Event/Events/BookingInfoUpdatedTest.php, tests/Http/Event/ImportEventRequestHandlerTest.php, tests/Http/Offer/UpdateBookingInfoRequestHandlerTest.php, tests/Http/Place/ImportPlaceRequestHandlerTest.php, tests/Model/Import/Offer/Udb3ModelToLegacyOfferAdapterTest.php, tests/Offer/Commands/AbstractUpdateBookingInfoTest.php, tests/Offer/Events/AbstractBookingInfoEventTest.php, tests/Offer/OfferTest.php, tests/Offer/ReadModel/JSONLD/OfferLDProjectorTest.php, tests/OfferLDProjectorTestBase.php, tests/Place/PlaceTest.php, tests/PriceInfo/PriceInfoTest.php, tests/ValueObject/MultilingualStringTest.php
- Removed legacy `Language` from `MultilingualString`
---
=> III-6310 Remove legacy `Language` from `MultilingualString`

Gemfile.lock
This reverts commit cba65dd458cc075b116539e2b78c0b6875a86a96.
=> Revert "Bump rexml from 3.2.5 to 3.3.9"

features/data/organizers/rdf/organizer-with-address.ttl, features/data/places/rdf/place-with-invalid-address.ttl, features/data/places/rdf/place-with-labels.ttl, features/data/places/rdf/place-with-required-fields.ttl, src/RDF/Editor/AddressEditor.php, tests/Event/ReadModel/RDF/ttl/event-with-dummy-location-and-multiple-calendar.ttl, tests/Event/ReadModel/RDF/ttl/event-with-dummy-location-and-single-calendar.ttl, tests/Event/ReadModel/RDF/ttl/event-with-dummy-location-name-and-multiple-calendar.ttl, tests/Event/ReadModel/RDF/ttl/event-with-dummy-location-name-and-single-calendar.ttl, tests/Event/ReadModel/RDF/ttl/event-with-dummy-location-name.ttl, tests/Event/ReadModel/RDF/ttl/event-with-dummy-location.ttl, tests/Organizer/ReadModel/RDF/ttl/organizer-with-address.ttl, tests/Place/ReadModel/RDF/ttl/place-with-coordinates.ttl, tests/Place/ReadModel/RDF/ttl/place-with-labels.ttl, tests/Place/ReadModel/RDF/ttl/place-with-publication-date.ttl, tests/Place/ReadModel/RDF/ttl/place-with-status-approved.ttl, tests/Place/ReadModel/RDF/ttl/place-with-status-deleted.ttl, tests/Place/ReadModel/RDF/ttl/place-with-status-ready-for-validation.ttl, tests/Place/ReadModel/RDF/ttl/place-with-status-rejected.ttl, tests/Place/ReadModel/RDF/ttl/place-with-translations.ttl, tests/Place/ReadModel/RDF/ttl/place.ttl
- The current predicate uri `locn:postcode` should be replaced with `locn:postCode`
---
Ticket: https://jira.publiq.be/browse/III-6399
=> III-6399 Fix typo in postCode predicate URI in AddressEditor

src/Cdb/CdbXmlPriceInfoParser.php, src/Model/Serializer/ValueObject/Price/TranslatedTariffNameNormalizer.php, src/Model/Serializer/ValueObject/Translation/TranslatedValueObjectNormalizer.php, src/Offer/ReadModel/JSONLD/CdbXMLItemBaseImporter.php, src/Offer/ReadModel/JSONLD/OfferLDProjector.php, src/PriceInfo/Tariff.php, tests/BackwardsCompatiblePayloadSerializerFactoryTest.php, tests/Event/EventTest.php, tests/Model/Import/Offer/Udb3ModelToLegacyOfferAdapterTest.php, tests/Offer/ReadModel/JSONLD/OfferLDProjectorTest.php, tests/PriceInfo/PriceInfoTest.php
- Refactor `Tariff` to use `TranslatedTariffName` instead of `MultilingualString`
---
=> III-6310 Refactor legacy `Tariff` to use `TranslatedTariffName`

features/label/bulk.feature
- Wait for the place to be indexed before using it in the label query. This is an attempt to make the feature to bulk label more stable. It is a feature test that sometimes fails on Jenkins.
=> Try to make bulk label with SAPI3 query feature more stable

features/ownership/search.feature, src/Http/Ownership/Search/SearchQuery.php, src/Http/Ownership/SearchOwnershipRequestHandler.php, src/Ownership/Repositories/Search/DBALOwnershipSearchRepository.php, tests/Http/Ownership/Search/SearchQueryTest.php, tests/Http/Ownership/SearchOwnershipRequestHandlerTest.php, tests/Ownership/Repositories/Search/DBALOwnershipSearchRepositoryTest.php
- Changed ownership pagination parameter to be start instead of offset
---
Since the issue of which term to use is complicated since both have merits, I've elected to only change the ownership parameter to match the API Guidelines document, as it wasn't clear whether unifying the term in the code itself too would be clearer (since we sometimes refer to MySQL offsets explicitely).
Ticket: https://jira.publiq.be/browse/III-6077
=> Changed ownership pagination parameter to be start instead of offset

src/Event/ReadModel/History/EventPlaceHistoryProjector.php
- Handled dummy locations without an `id` inside the event & place history projector by catching an argument exception
---
Ticket: https://jira.uitdatabank.be/browse/III-6446
=> III-6446 Handle dummy locations without an `id` by catching an argument exception

src/Model/Serializer/ValueObject/Contact/BookingInfoDenormalizer.php
- Avoid crash on legacy booking info when start date is after end date
---
Ticket: https://jira.uitdatabank.be/browse/III-6447
=> III-6447 Avoid crash on legacy booking info when start date is after end date

src/Event/ReadModel/History/EventPlaceHistoryProjector.php, src/Event/ReadModel/History/Exception/CannotDeterminePlaceIdForDummyPlace.php, tests/Event/ReadModel/History/EventPlaceHistoryProjectorTest.php
When updating / cloning an old location with a dummy location (= no location id), the new history projector would crash.
This handles the crashes for copy locations, update locations and major info events.
Comes with unit tests to prove the solution works.
---
Ticket: https://jira.uitdatabank.be/browse/III-6458
=> III-6458 Handle dummy locations with EventPlaceHistoryProjector

app/Console/Command/AddMatchingTrailer.php, app/Console/Command/FindMatchingTrailersOnYouTube.php, app/Console/ConsoleServiceProvider.php
- `FindMatchingTrailersOnYouTube`: CLI-script to add matching trailers from YouTube to Kinepolis movies.
- `ConsoleServiceProvider`: Register `FindMatchingTrailersOnYouTube`
- In a follow-up PR the trailerSearch within the KinepolisService will be removed, to have a clear separation of responsibilities.
---
Ticket: https://jira.publiq.be/browse/III-6456
=> III-6456 cli search trailer

features/search/default-queries-config-file-apikey.feature, features/search/default-queries-config-file-clientid.feature
- `features/search/default-queries-config-file.feature`: Renamed to `features/search/default-queries-config-file-apikey.feature` and add clarification that's is only for `apiKeys`. 
- `default-queries-config-file-clientid.feature`: Acceptance tests for searching with a clientId that has a `defaultQuery`.
- https://github.com/cultuurnet/udb3-search-service/pull/330
- https://github.com/cultuurnet/appconfig/pull/924
---
Ticket: https://jira.publiq.be/browse/III-6465
=> III-6465 defaultQuery when using a ClientId

.github/workflows/ci.yml
- Only check unused dependencies on current PHP
---
Just to avoid the overkill of spinning three containers to do a simple check
From discussion around https://github.com/cultuurnet/udb3-search-service/pull/331
=> Only check unused dependencies on current PHP

app/Ownership/OwnershipRequestHandlerServiceProvider.php, features/ownership/get.feature, src/Http/Ownership/GetOwnershipRequestHandler.php, src/Http/Ownership/OwnershipStatusGuard.php, tests/Http/Ownership/GetOwnershipRequestHandlerTest.php
-  Limited access to ownership `GET` endpoint
- Allowed as admin
- Allowed as owner
- Allowed with correct permission
- Allowed as requester (has permission)
---
Ticket: https://jira.uitdatabank.be/browse/III-6146
=> III-6146 Limit access to ownership `GET` endpoint

features/data/events/rdf/mixed-event-with-online-url-and-multiple-calendar.ttl, features/data/events/rdf/mixed-event-with-online-url-and-permanent-calendar.ttl, features/data/events/rdf/online-event-with-multiple-calendar.ttl, features/data/events/rdf/online-event-with-online-url-and-multiple-calendar.ttl, features/data/events/rdf/online-event-with-online-url-and-permanent-calendar.ttl, src/Event/ReadModel/RDF/EventJsonToTurtleConverter.php, src/RDF/NodeUri/NodeUriGenerator.php, tests/Event/ReadModel/RDF/ttl/mixed-event-with-online-url-and-multiple-calendar.ttl, tests/Event/ReadModel/RDF/ttl/mixed-event-with-online-url-and-permanent-calendar.ttl, tests/Event/ReadModel/RDF/ttl/mixed-event-with-online-url-and-single-calendar.ttl, tests/Event/ReadModel/RDF/ttl/mixed-event-with-permanent-calendar.ttl, tests/Event/ReadModel/RDF/ttl/mixed-event-with-single-calendar.ttl, tests/Event/ReadModel/RDF/ttl/online-event-with-online-url-and-multiple-calendar.ttl, tests/Event/ReadModel/RDF/ttl/online-event-with-online-url-and-permanent-calendar.ttl, tests/Event/ReadModel/RDF/ttl/online-event-with-online-url-and-single-calendar.ttl, tests/Event/ReadModel/RDF/ttl/online-event-with-permanent-calendar.ttl, tests/Event/ReadModel/RDF/ttl/online-event-with-single-calendar.ttl
Details you find in the comment of https://jira.publiq.be/browse/III-6496, feedback from Stan.
- Change class of Virtual location.
Before:
<http://data.uitdatabank.local:80/events/%{eventId}#virtueleLocatie-61d7772d>
a platform:virtueleLocatie ;
schema:url "https://www.publiq.be/livestream"^^schema:URL .
Now:
<http://data.uitdatabank.local:80/events/%{eventId}#virtualLocation-61d7772d>
a schema:VirtualLocation ;
schema:url "https://www.publiq.be/livestream"^^schema:URL .
---
Ticket: https://jira.uitdatabank.be/browse/III-6482
Related: https://jira.publiq.be/browse/III-6496
=> III-6482 RDF Wrong class for virtual location

app/Console/ConsoleServiceProvider.php, app/Http/MiddlewareServiceProvider.php, app/Http/PsrRouterServiceProvider.php, app/Organizer/OrganizerJSONLDServiceProvider.php, features/organizer/update.feature, src/Http/CheckOrganizerMiddleware.php
- Fixed updating non existing organizers throwing 404 and not 403
---
Uses the same middleware approach as how it was fixed for offers and places
Ticket: https://jira.publiq.be/browse/III-5324
=> Fixed updating non existing organizers throwing 404 and not 403

tests/Media/Properties/MIMETypeTest.php
-  `MIMETypeTest`: Add missing `test`-blocks
- No more warning about risky tests
---
=> Bugfix: add missing testblocks

app/Cache/CacheServiceProvider.php, app/Console/ConsoleServiceProvider.php, app/Keycloak/KeycloakServiceProvider.php, app/User/UserServiceProvider.php, composer.json, composer.lock, src/Cache/CacheFactory.php, src/User/Keycloak/CachedUserIdentityResolver.php, tests/User/Keycloak/CachedUserIdentityResolverTest.php
- `CacheFactory`: Factory for Caches
- `CachedUserIdentityResolver`: Added `UserIdentityResolver` with caching
- `CachedUserIdentityResolverTest`: Unit tests
- `composer.json`: Added `symfony/cache`
- `CacheServiceProvider`: Added new CacheInterface next legacy `Predis\Cache`
- `UserServiceProvider` & `ConsoleServiceProvider`: Use `CachedUserIdentityResolver` instead of `KeycloakUserIdentityResolver`
- `KeycloakServiceProvider`: Add `CachedServiceProvider`
---
Ticket: https://jira.publiq.be/browse/III-6511
=> III-6511 add symfony cache

docker-compose.yml, docker.md, readme.md
- Url in documentation is updated to `io.uitdatabank.local`.
- Change the ordering in `docker.md` so the project is set up as the first step.
- Link to installation instructions from `readme.md`
- The mount volumes were not pointing to the correct mysql directory. On `make down` and `make up` your db would be wiped.
=> Improve setup documentation

app/Authentication/AuthServiceProvider.php, src/Cache/CachedApiKeyAuthenticator.php, tests/Cache/CachedApiKeyAuthenticatorTest.php
- `CachedApiKeyAuthenticator`: `ApiKeyAuthenticator` with Caching
- `CachedApiKeyAuthenticatorTest`: Unit tests
- `AuthServiceProvider`: Use `CachedApiKeyAuthenticator` instead of `CultureFeedApiKeyAuthenticator `
- Authenticated `apiKeys` are now cached.
---
Ticket: https://jira.publiq.be/browse/III-6511
=> III-6511 authenticate api key

src/Event/ReadModel/JSONLD/EventLDProjector.php, src/Place/ReadModel/JSONLD/PlaceLDProjector.php
- Cast `terms` object to array
- This was broken a long time ago but update major info commands are no longer dispatched, so only when doing a replay was this noticed
---
Ticket: https://jira.uitdatabank.be/browse/III-6531
=> III-6531 Cast `terms` object to array

app/Authentication/AuthServiceProvider.php, src/Cache/CachedConsumerReadRepository.php, src/Cache/SerializableConsumer.php, tests/Cache/CachedConsumerReadRepositoryTest.php
- `CachedConsumerReadRepository`: `ConsumerReadRepository` with caching
- `CachedConsumerReadRepositoryTest`: Unit tests
- `SerializableConsumer`: New implementation of `Consumer`
- `AuthServiceProvider`: Use `CachedConsumerReadRepository` instead of `InMemoryConsumerReadRepository`
---
Ticket: https://jira.publiq.be/browse/III-6511
=> III-6511 cache api key consumer read repository

features/label/get.feature, src/Http/Label/Query/QueryFactory.php, src/Label/ReadModels/JSON/Repository/Doctrine/DBALReadRepository.php, tests/Http/Label/Query/QueryFactoryTest.php, tests/Http/Label/SearchLabelsRequestHandlerTest.php
- Calling the `/labels` endpoint without start and limit will now use sensible defaults.
- Calling the `/labels` endpoint with a high limit will reduce this to 30 so that DOS attacks are less likely.
---
Ticket: https://jira.publiq.be/browse/III-4855
=> Bugfix/III-4855 Enforce max limit on /labels endpoint

app/Migrations/Version20250212071939.php, src/Mailer/DBALMailsSentRepository.php, src/Mailer/MailsSentRepository.php, tests/Mailer/DBALMailsSentRepositoryTest.php
To prepare to sending ownership mails, we want to remember if a mail has been sent already or not.
For this I added an extra database table.
- I tried to make it generic named (hence identifier instead of organiserId) for reuse for other mails later
- I also note down the email / date of the mail, while not technically required this will make it very practical if we ever need to lookup if a specific mail was sent.
- Mail sent migration + repo + test
---
Ticket: https://jira.uitdatabank.be/browse/III-6366
=> III-6366 Set up ownership mailings

composer.json, composer.lock, src/Mailer/Mailer.php, src/Mailer/SmtpMailer.php, src/Mailer/templates/approved.html.twig, src/Mailer/templates/approved.txt.twig, src/Mailer/templates/ownershipRequested.html.twig, src/Mailer/templates/ownershipRequested.txt.twig, src/Mailer/templates/rejected.txt.twig, tests/Mailer/SmtpMailerTest.php
- Installed Symfony mailer package
- Provide a mailer class to sent mails by SMTP
- Add the twig templates that will be used in the feature for the mails
- Providing an option to only sent mails to certain domains for testing purposes
---
Ticket: https://jira.uitdatabank.be/browse/III-6366
Related to: https://github.com/cultuurnet/appconfig/pull/956
=> III-6366 Mailer smtp class

src/User/Keycloak/CachedUserIdentityResolver.php, tests/User/Keycloak/CachedUserIdentityResolverTest.php
- `CachedUserIdentityResolver`: prevent caching `Null` by throwing an catching an `InvalidArgumentException` & refactor to improve readability.
- `CachedUserIdentityResolverTest`: Add unit tests to check `Null` isn't stored in the cache.
- `Null` is no longer cached.
---
Ticket: https://jira.publiq.be/browse/III-6541
=> III-6541 bugfix nulls

features/Steps/MailSteps.php
- `MailSteps`: add `removeCarriageReturn()` to handle the formatting quirks between `MacOs` used by devlopers & Jenkins/Linux on the CI-pipeline.
- The check for emailContent, should now work both on `MacOS` & `Jenkins` 
---
Ticket: https://jira.publiq.be/browse/III-6550
=> III-6550 Formatting issue between MacOS & Jenkins

features/organizer/get-creator.feature, features/ownership/approve.feature, features/ownership/delete.feature, features/ownership/get.feature, features/ownership/permission.feature, features/ownership/reject.feature
- Renamed `dev_e2e_test` to `udbtestinvoerder_ownerships` to make it more clear this user is used for ownerships only
---
Ticket: https://jira.uitdatabank.be/browse/III-6300
=> III-6300 Improve name ownership user

features/organizer/get-creator.feature, features/ownership/approve.feature, features/ownership/delete.feature, features/ownership/get.feature, features/ownership/permission.feature, features/ownership/reject.feature
- Renamed `udbtestinvoerder_ownerships` to `invoerder_ownerships`
- For the appconfig changes `udbtestinvoerder_1` and `udbtestinvoerder_2` should also be changed, but for now they are not directly used like `invoerder`
---
Ticket: https://jira.uitdatabank.be/browse/III-6300
=> III-6300 Renamed `udbtestinvoerder_ownerships` to `invoerder_ownerships`

features/ownership/request.feature, src/Ownership/Serializers/RequestOwnershipDenormalizer.php, tests/Http/Ownership/RequestOwnershipRequestHandlerTest.php
- `RequestOwnershipDenormalizer`: Add check to see if the `ownerId` is known in our system.
- `Ownership/RequestOwnershipRequestHandlerTest`: Refactor existing tests & add 2 new tests for non-existing `email|userId`.
- `features/ownership/request.feature`: Add 2 acceptance tests to check non-existing `email|userId`
- A request can no longer be made with an non existing userId.
- We could improve this code with a refactor to dedepulicate the validation => https://jira.publiq.be/browse/III-6633
---
Ticket: https://jira.publiq.be/browse/III-6622
=> III-6622 Improve ownership Validation for non existing userId's

docker.md, features/data/organizers/rdf/organizer-with-address.ttl, features/ownership/search.feature
- `search.feature`: Replace non-existing `userIds`
- `docker.md`: Add table with dummyUsers.
- `organizer-with-address.ttl`: Updating RDF checksums & coordinates.
- Acceptance tests should work again.
---
Ticket: https://jira.publiq.be/browse/III-6622
=> III-6622 Replace non-existing users

app/Console/Command/AddOwnershipCommand.php, app/Console/Command/OwnershipCommand.php, app/Console/ConsoleServiceProvider.php, app/EventBus/EventBusServiceProvider.php, app/Mailer/MailerServiceProvider.php, src/Broadway/Domain/DomainMessageHasMailsDisabled.php, src/EventBus/Middleware/DisableMailsMiddleware.php, src/Mailer/Handler/SendMailsForOwnershipEventHandler.php, tests/EventBus/Middleware/DisableMailsMiddlewareTest.php, tests/Mailer/Handler/SendMailsForOwnershipEventHandlerTest.php
- `AddOwnershipCommand`: CLI Command to add `ownerships`.
- `DomainMessageHasMailsDisabled`: Add new `DomainMessageSpecificationInterface`
- `DisableMailsMiddleware`: MiddleWare to disable sending mails, when changing `Ownership`
- `DisableMailsMiddlewareTest`: Unit test for `DisableMailsMiddleware`
- `ConsoleServiceProvider`: Register new Command `AddOwnershipCommand`.
- `EventBusServiceProvider`: register new MiddleWare `DisableMailsMiddleware`
- `SendMailsForOwnershipEventHandler`: Check if mails are disabled in MiddleWare.
- `SendMailsForOwnershipEventHandlerTest`: Add unit test to see if mails disabled in MiddleWare work
- `MailerServiceProvider`: Updated `constructor` of `SendMailsForOwnershipEventHandler`
---
Ticket: https://jira.publiq.be/browse/III-6618
=> III-6618 ownership cli

app/Http/PsrRouterServiceProvider.php, app/Offer/OfferServiceProvider.php, features/event/labels.feature, src/Http/Offer/UpdateLabelsRequestHandler.php, tests/Http/Offer/UpdateLabelsRequestHandlerTest.php
- Added new endpoint `PUT '/{offerType:events|places}/{offerId}/labels/'` to update all labels on an event or place
- For now the API docs and the JSON schema validation is still missing
---
Ticket: https://jira.uitdatabank.be/browse/III-6634
=> III-6634 bulk update labels

src/Cultuurkuur/data/education-levels.json, src/Cultuurkuur/data/regions.json, tests/Cultuurkuur/GetEducationLevelsRequestHandlerTest.php
- Make sure the right municipalities are shown in the regions (now som regions have the same municipalities ex: Antwerpen)
- Add the province label for the municipalities, on province level. So this is the second province label in the excel
- Remove region label (ex. ‘reg-brussel’) because it is never used
- Remove ‘+ deelgemeenten’ on all labels
- For educationlevels: lowest level labels (level 3) are changed. Check if this is the case (see excelscheet with changes).
---
Ticket: https://jira.uitdatabank.be/browse/III-6579
=> III-6579 Updated cultuurkuur endpoints

features/Steps/AuthorizationSteps.php, features/search/auth.feature, src/Http/Auth/Jwt/JsonWebToken.php, src/Http/Auth/RequestAuthenticatorMiddleware.php, tests/Http/Auth/Jwt/JsonWebTokenTest.php, tests/Http/Auth/Jwt/UitIdV2JwtValidatorTest.php
- `AuthorizationSteps`: use `id_token` instead of `access_token` in `iAmAuthorizedAsJwtProviderV2User()`
- `auth.feature`:  Remove faulty test.
- `RequestAuthenticatorMiddleware`: Add check for `typ` of `token` when deciding to `authenticateApiKey()`
- `JsonWebToken`: Remove check for `auth0`-tokens without `azp`
- `JsonWebTokenTest` & `UitIdV2JwtValidatorTest`: Remove tests for `auth0`-tokens without `azp`
- `DomainMessages` should now contain an `apiKey`, when using a `JWT Provider v2-token`.
---
Ticket: https://jira.publiq.be/browse/III-6772
=> III-6772 fix for v2 JWT Provider tokens in DomainMessage

app/SavedSearches/SavedSearchesServiceProvider.php, features/saved_searches/ownerships.feature, src/SavedSearches/OwnershipSavedSearchRepository.php, tests/SavedSearches/OwnershipSavedSearchRepositoryTest.php
- `OwnershipSavedSearchRepository`: Add Search Repo for `APPROVED` Ownerships.
- `OwnershipSavedSearchRepositoryTest`: Unit test for `OwnershipSavedSearchRepository`
- `ownerships.feature`: Acceptance test
- `SavedSearchesServiceProvider`: register `OwnershipSavedSearchRepository`
---
Ticket: https://jira.publiq.be/browse/III-6726
=> III-6726 decorate saved queries

app/Place/PlaceServiceProvider.php, src/Label/ReadModels/Relations/Repository/Doctrine/DBALReadRepository.php, src/Label/ReadModels/Relations/Repository/ReadRepositoryInterface.php, src/Place/Canonical/CanonicalService.php, src/Place/Canonical/Exception/MuseumPassAndUiTPassInSameCluster.php, src/Place/Canonical/Exception/UiTPassNotUniqueInCluster.php, tests/Label/ReadModels/Relations/Repository/Doctrine/DBALReadRepositoryTest.php, tests/Place/Canonical/CanonicalServiceTest.php
Change the canonical place algoritme in the following way:
Check if there is an UiTPAS location, in which case, pick it as the canonical place.
If there are more then 1 UiTPAS location, throw an error (like we already do for Museumpass)
If there is an UiTPAS location AND an Museumpass location (and they are not the same place), also throw an error.
---
Ticket: https://jira.uitdatabank.be/browse/III-6777
=> III-6777 Change calculation canonical place protect uitpas place

app/Console/ConsoleServiceProvider.php, app/Event/EventPermissionServiceProvider.php, app/EventBus/EventBusServiceProvider.php, app/Offer/OfferServiceProvider.php, app/Security/OfferSecurityServiceProvider.php, features/data/events/event-minimal-permanent-with-organizer-updated.json, features/event/implicit-ownership.feature, src/Security/ResourceOwner/Doctrine/DBALResourceRelatedOwnerRepository.php, tests/Security/ResourceOwner/Doctrine/DBALResourceRelatedOwnerRepositoryTest.php
- `DBALResourceRelatedOwnerRepository`: new `Repository` to find events that have an `Organizer` with a certain `creator`
- `DBALResourceRelatedOwnerRepositoryTest`: `UnitTest` for new `Repository`
- `event-minimal-permanent-with-organizer-updated.json`: new data file for use in `acceptance tests`
- `event/implicit-ownership.feature`: Add acceptance test for new implicit `Ownership`.
- `EventPermissionServiceProvider`: Register new `Repository`
- `OfferSecurityServiceProvider`: Add new `Repository` to `CombinedResourceOwnerQuery`
- `Creators` of an `Organizer` now have implicit `Ownership` of the `events` that are organized by the `Organizer`
---
Ticket: https://jira.publiq.be/browse/III-6730
=> III-6730 Add implicit Ownership for the creator of an Organizer
